### PR TITLE
fix suggestion on `[map_flatten]` being cropped causing possible information loss

### LINKED ISSUE #8506: `clippy::map_flatten` multiline suggestion is missing closing tokens
### Summary

Suggestion is incorrect Rust code.

### Reproducer

I tried this code:

```rust
Some(5)
    .map(|some_long_variable_name| {
        if some_long_variable_name <= 5 {
            Some(some_long_variable_name)
        } else {
            None
        }
    })
    .flatten();
```

I expected to see this happen:
```
warning: called `map(..).flatten()` on an `Option`
  --> picky-signtool/src/main.rs:14:12
   |
14 |       Some(5)
   |  ____________^
15 | |         .map(|some_long_variable_name| {
16 | |             if some_long_variable_name <= 5 {
17 | |                 Some(some_long_variable_name)
...  |
21 | |         })
22 | |         .flatten();
   | |__________________^
   |
   = note: `#[warn(clippy::map_flatten)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_flatten
help: try using `and_then` instead
   |
14 ~     Some(5).and_then(|some_long_variable_name| {
15 +             if some_long_variable_name <= 5 {
16 +                 Some(some_long_variable_name)
17 +             } else {
18 +                 None
19 +             }
20 +     });
 ...
```

Instead, this happened:

```
warning: called `map(..).flatten()` on an `Option`
  --> picky-signtool/src/main.rs:14:12
   |
14 |       Some(5)
   |  ____________^
15 | |         .map(|some_long_variable_name| {
16 | |             if some_long_variable_name <= 5 {
17 | |                 Some(some_long_variable_name)
...  |
21 | |         })
22 | |         .flatten();
   | |__________________^
   |
   = note: `#[warn(clippy::map_flatten)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_flatten
help: try using `and_then` instead
   |
14 ~     Some(5).and_then(|some_long_variable_name| {
15 +             if some_long_variable_name <= 5 {
16 +                 Some(some_long_variable_name)
17 +             } else {
18 +                 None
19 +             }
 ...
```

### Version

```text
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-unknown-linux-gnu
release: 1.59.0
LLVM version: 13.0.0
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by J-ZhengLi**
fixes #8506 

Multi-line suggestion given by the lint is missing its bottom part, which could potentially contains useful information about the fix.

---

changelog: [`map_flatten`]: Long suggestions will now be splitup into two help messages

### CODE REVIEW

**Comment by J-ZhengLi** [comment]
@xFrednet Hi, I wasn't sure if I understand your suggestion throughly, so I did what I could and get stuck in how to modify Span as well to reflect the modified suggestion string 😆 was I even in the right direction?

File: clippy_lints/src/methods/map_flatten.rs [hunk 1]
```diff
@@ -68,16 +70,46 @@ pub(super) fn check<'tcx>(
...
+            span_lint_and_sugg(cx, lint, sp, msg, help, sugg, applicability);
+        }
+    } else {
+        if help_msgs.len() == 2 {
+            let lines = sugg.split("\n").collect::<Vec<_>>();
+            let top_part = lines[..MAX_LINES / 2].join("\n");
+            let bottom_part = lines[lines_count - MAX_LINES / 2..].join("\n");
+            //println!("top: {}\nbottom: {}", top_part, bottom_part);
+            span_lint_and_then(cx, lint, sp, msg, |diag| {
+                // Error: "Cannot replace slice of data that was already replaced" (caused by overlapping Span I think?)
```
Comment (xFrednet) [inline clippy_lints/src/methods/map_flatten.rs:109]: rustfix doesn't work for multipart suggestions like this one. In these suggestions we usually split up the tests into a `_fixable` and a normal test

File: clippy_lints/src/methods/map_flatten.rs [hunk 2]
```diff
@@ -68,16 +70,46 @@ pub(super) fn check<'tcx>(
...
+                diag.span_suggestion(sp, &help_msgs[0], top_part, applicability);
+                diag.span_suggestion(sp, &help_msgs[1], bottom_part, applicability);
```
Comment (xFrednet) [inline clippy_lints/src/methods/map_flatten.rs:111]: Here you're suggesting to use the three lines in `top_part` and `bottom_part` for the entire span. That's a bit problematic, the span should also be adjusted to only span over the higher and lower three lines. The question is now how this can be done.

What you can do is first take the span and call [`Span::shrink_to_lo`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/span_encoding/struct.Span.html#method.shrink_to_lo) and [`Span::shrink_to_hi`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/span_encoding/struct.Span.html#method.shrink_to_hi) respectively and then use [`clippy_lints::`line_span](https://doc.rust-lang.org/nightly/nightly-rustc/clippy_utils/fn.line_span.html#) to get the entire line. The difficult part is now to expand this single line span to include the following and previous lines. You can either leave it at that or try to work with span expansion (See [`Span`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/span_encoding/struct.Span.html#) and [`SourceMap`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/source_map/struct.SourceMap.html#)). 

I hope this explanation is clear, if now please ask :upside_down_face:

**Review by xFrednet — COMMENTED** [review]
> @xFrednet Hi, I wasn't sure if I understand your suggestion throughly, so I did what I could and get stuck with not knowing how to modify Span as well to reflect the modified suggestion string laughing was I even in the right direction?

The direction is good, I underestimated the effort it can take to span over the first and last three lines. I suggested a solution and added some sources where you can search, if you want to create that suggestion :upside_down_face:

**Comment by J-ZhengLi** [comment]
> > @xFrednet Hi, I wasn't sure if I understand your suggestion throughly, so I did what I could and get stuck with not knowing how to modify Span as well to reflect the modified suggestion string laughing was I even in the right direction?
> 
> The direction is good, I underestimated the effort it can take to span over the first and last three lines. I suggested a solution and added some sources where you can search, if you want to create that suggestion 🙃

Thank you~

File: clippy_lints/src/methods/map_flatten.rs [hunk 3]
```diff
@@ -39,7 +41,8 @@ pub(super) fn check<'tcx>(
             // `(...).map(...)` has type `impl Iterator<Item=impl Iterator<...>>
             "flat_map"
         };
-        let func_snippet = snippet(cx, map_arg.span, "..");
+        let mut applicability = Applicability::MachineApplicable;
+        let func_snippet = snippet_with_applicability(cx, map_arg.span, "..", &mut applicability);
         let hint = format!(".{0}({1})", method_to_use, func_snippet);
         span_lint_and_sugg(
```
Comment (xFrednet) [inline clippy_lints/src/methods/map_flatten.rs:47]: This lint emission of `MAP_FLATTEN` should also be affected by your changes. It would probably be good to have a function that selects the message style and emits the lint, so it can be used for iterators and `Result`/`Option` types.

From your comment, it looks like this is still on the TODO list, this is therefore just a reminder for me :upside_down_face: 

BTW nice usage of `snippet_with_applicability` :+1:

File: clippy_lints/src/methods/map_flatten.rs [hunk 4]
```diff
@@ -68,16 +71,44 @@ pub(super) fn check<'tcx>(
...
-        MAP_FLATTEN,
-        expr.span.with_lo(recv.span.hi()),
-        &lint_info,
-        "try using `and_then` instead",
-        hint,
-        Applicability::MachineApplicable,
-    );
+    let help_msgs = [
+        "try replacing `map` with `and_then` instead",
+        "and remove the final `.flatten()`",
```
Comment (xFrednet) [inline clippy_lints/src/methods/map_flatten.rs:79]: I think here we should remove the *final* to not be confusing for longer changes that have multiple `flatten()` and other magic. (I know that I suggested a message like this, but that came to mind afterwards :) )

File: clippy_lints/src/methods/map_flatten.rs [hunk 5]
```diff
@@ -68,16 +71,44 @@ pub(super) fn check<'tcx>(
...
+        );
+    } else {
+        // modify hint string
+        let mid_idx = MAX_SUGGESTION_HIGHLIGHT_LINES / 2;
+        let lines = hint.split('\n').collect::<Vec<_>>();
+        let top_part = lines[..mid_idx].join("\n");
+        let bottom_part = lines[lines_count - mid_idx..].join("\n");
+        // modify span
+        let sm = cx.sess().source_map();
+        let top_line = sm.lookup_line(map_span.lo()).unwrap();
```
Comment (xFrednet) [inline clippy_lints/src/methods/map_flatten.rs:102]: This `unwrap()` should be avoided in the final version, as it can cause ICEs (Internal Compiler Errors). It's good for prototyping :+1: You can either ignore cases where these errors occur or, maybe better, fall back on the normal suggestion :)

**Review by xFrednet — COMMENTED** [review]
You found a very nice solution to span over the surrounding lines. I learned something from this review :+1:. I left some comments which should be addressed, but the current version is already a good step, thank you for the work :upside_down_face:

File: clippy_lints/src/methods/map_flatten.rs (hunk 3 above)
Comment (J-ZhengLi) [reply clippy_lints/src/methods/map_flatten.rs]: It's finished now 😃, feel free to give any kind of feedback when you got time~

**Comment by J-ZhengLi** [comment]
Low key wanna try fixing #8528 

After I figure out how to get the full span of the whole `.map()` call 🤔

**Comment by J-ZhengLi** [comment]
working on #8528

File: clippy_lints/src/methods/map_flatten.rs [hunk 6]
```diff
@@ -1,83 +1,119 @@
...
 
-    // lint if caller of `.map().flatten()` is an Option or Result
-    let caller_type = match cx.typeck_results().expr_ty(recv).kind() {
-        ty::Adt(adt, _) => {
+fn try_get_caller_ty_name_and_method_name(
+    cx: &LateContext<'_>,
+    expr: &Expr<'_>,
+    caller_expr: &Expr<'_>,
+    map_arg: &Expr<'_>,
+) -> Option<(String, String)> {
```
Comment (xFrednet) [inline clippy_lints/src/methods/map_flatten.rs:46]: NIT: Here you can return `Option<(&'static str, &'static str)>` to avoid the `.to_string()` calls and save on some performance.

I like this refactoring, it makes the implementation more readable :upside_down_face:

File: clippy_lints/src/methods/map_flatten.rs [hunk 7]
```diff
@@ -1,83 +1,119 @@
...
+        span_lint_and_splitted_sugg(
             cx,
-            MAP_FLATTEN,
-            expr.span.with_lo(recv.span.hi()),
-            "called `map(..).flatten()` on an `Iterator`",
-            &format!("try using `{}` instead", method_to_use),
-            hint,
-            Applicability::MachineApplicable,
+            expr.span.with_lo(map_span.lo()),
+            &format!("called `map(..).flatten()` on an `{}`", caller_ty_name),
```
Comment (xFrednet) [inline clippy_lints/src/methods/map_flatten.rs:33]:
```suggestion
            &format!("called `map(..).flatten()` on `{}`", caller_ty_name),
```

Here, I would remove the `an` as "on an `Result`" doesn't quite work, but "called `map(..).flatten()` on `<Type>`" should work for all :upside_down_face:

File: clippy_lints/src/methods/map_flatten.rs [hunk 8]
```diff
@@ -1,83 +1,119 @@
...
+
+            span_lint_and_then(cx, MAP_FLATTEN, sp, msg, |diag| {
+                diag.span_suggestion(span_upper, help[0], sugg_upper, applicability);
+                diag.span_suggestion(span_bottom, help[1], sugg_bottom, applicability);
+            });
+            return;
+        }
+    }
+    let combined_help = help.join(", ");
+    span_lint_and_sugg(cx, MAP_FLATTEN, sp, msg, &combined_help, sugg, applicability);
```
Comment (xFrednet) [inline clippy_lints/src/methods/map_flatten.rs:118]: This help message can get quite log when the two messages are joined together. I think it might be better to add another message just for this case or use `span_lint_and_then` to call [`span_suggestion_with_style`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.DiagnosticBuilder.html#method.span_suggestion_with_style) to set the suggestion display style to [`ShowAlways`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/enum.SuggestionStyle.html#variant.ShowAlways). Then the suggestion would always be shown in a help "window" like this:

```rs
= help: <first_msg>, <second_msg>
   |
LL + vec![5_i8; 6].into_iter().filter_map(|x| x.checked_add(1)).collect();
   | 
```

File: clippy_lints/src/methods/map_flatten.rs [hunk 9]
```diff
@@ -1,83 +1,119 @@
...
-        hint,
-        Applicability::MachineApplicable,
-    );
+/// Split code suggestion into upper and bottom parts if its number of lines exceeds
+/// `MAX_SUGGESTION_HIGHLIGHT_LINES`, otherwise this function will just call `span_lint_and_sugg`
+/// with a combined `help` message.
+///
+/// This is useful when a suggested code snippet has multiple line thus causing possible useful
+/// information being chopped off at the end.
+fn span_lint_and_splitted_sugg(
```
[the remark this answers is not in the document]
Comment (xFrednet) [reply clippy_lints/src/methods/map_flatten.rs:88]: It would be good if you could move this to `clippy_utils::diagnostic` as @dswij suggested, with a note that only changes at the edge are shown and can be applied. Maybe `span_lint_and_help_for_edges` would be a better name that describes the goal of this function.

**Review by xFrednet — COMMENTED** [review]
Excellent work. I added some smaller notes that should be easy to fix, and then it's ready to be merged! :upside_down_face:

File: clippy_lints/src/methods/map_flatten.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (J-ZhengLi) [reply clippy_lints/src/methods/map_flatten.rs:88]: should I name it as the one you suggested or `span_lint_and_sugg_for_edges`? It does fall back to `span_lint_and_sugg` after all

[the remark this answers is not in the document]
Comment (J-ZhengLi) [reply clippy_lints/src/methods/map_flatten.rs:88]: Wait a minute, could a `span_lint_and_note` be used in this type of situation? 😆

File: clippy_utils/src/diagnostics.rs [hunk 10]
```diff
@@ -213,6 +213,82 @@ pub fn span_lint_and_sugg<'a, T: LintContext>(
...
+///    |
+/// help: and remove the `.flatten()`
+///    |
+/// LL +                 None
+/// LL +             }
+/// LL ~         });
+///    |
+/// ```
+pub fn span_lint_and_sugg_for_edges(
+    cx: &LateContext<'_>,
```
Comment (J-ZhengLi) [inline clippy_utils/src/diagnostics.rs:255]: Is this alright? the function name, description, content, etc. I'm terrible at phrasing🤣 so if the comment needs improvement you can help propose some changes and I'll directly patch them~

Thank you again~

**Review by xFrednet — COMMENTED** [review]
This is almost ready to be merged. I'm very pleased with the output, it looks excellent.

Besides the comment, there is one more thing. Clippy follows rustc's [ no merge-commit policy](https://rustc-dev-guide.rust-lang.org/contributing.html#opening-a-pr). The merge commit should be removed before this can be merged into our master. You can do this by dropping the commit and rebasing. You're welcome to ask if you need help with that.

Another small optional NIT. I would change the changelog entry to:
```
changelog: [`map_flatten`]: Long suggestions will now be splitup into two help messages
```

File: clippy_utils/src/diagnostics.rs [hunk 11]
```diff
@@ -213,6 +213,82 @@ pub fn span_lint_and_sugg<'a, T: LintContext>(
...
 
+/// Like `span_lint_and_sugg` but with either span or multispan suggestion depending on the number
+/// of its lines.
+///
+/// If the given `sugg` string has more number of lines than
+/// `rustc_errors::emitter::MAX_SUGGESTION_HIGHLIGHT_LINES`, this function will "separate" the
+/// suggestion and span for both top and bottom edge of the code, which CANNOT be auto-fixed,
+/// otherwise this will act like `span_lint_and_sugg` with a combined help message.
+///
+/// # Example
```
[the remark this answers is not in the document]
Comment (J-ZhengLi) [reply clippy_utils/src/diagnostics.rs]: Oh god, what have I done!

**Review by xFrednet — APPROVED** [review]

**Comment by xFrednet** [comment]
Looks good to me, thank you for the work! I hope you also had fun while working on this. :upside_down_face: 

@bors r+
