### PR TITLE
Fix FN in `needless_return`

### LINKED ISSUE #10051: needless_return doesn't trigger properly with `anyhow!` macro
### Summary

needless_return fails to trigger on `return Err(anyhow::anyhow!("failed to do things"));`

This leads to weird situations where clippy will clean up one needless return but not another, for example https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b196ba185e8485558293b61fce4f7d7c . I saw this a fair bit when running `clippy --fix` across the fuchsia codebase, http://fxrev.dev/c/fuchsia/+/773265/2..3 shows me manually fixing up those cases.

### Lint Name

needless_return

### Reproducer

I tried this code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0952e8cbe8416c99f9a5b1e7c44c1c56

```rust
pub fn example() -> Result<(), anyhow::Error> {
    return Err(anyhow::anyhow!("failed to do things"));
}
```

I expected to see this happen:

```
warning: unneeded `return` statement
 --> src/lib.rs:2:5
  |
2 |     return Err("failed to do things");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
  = note: `#[warn(clippy::needless_return)]` on by default
  = help: remove `return`
```

Instead, this happened (no errors):

```
    Checking playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
```

### Version

```text
rustc 1.67.0-nightly (822f8c22f 2022-11-02)
binary: rustc
commit-hash: 822f8c22f540b12f296d844ad5bf39aaa47bfeb4
commit-date: 2022-11-02
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### PR DESCRIPTION
**Pull request by Niki4tap**
Fixes #10051

changelog: Enhancement: [`needless_return`]: Now detects more cases for returns of owned values
[#10110](https://github.com/rust-lang/rust-clippy/pull/10110)

### CODE REVIEW

**Comment by xFrednet** [comment]
Hey @Niki4tap, I wasn't sure what you meant with the changelog entry. My guess is, that this changes makes sure that not borrowed values are now detected properly? I've updated the changelog entry accordingly. Did I get it right? :upside_down_face:

**Comment by Niki4tap** [comment]
Yeah, that's probably it, sorry, not sure what I've meant there myself to be completely honest. I was thinking of something along the lines of "improving the `last_statement_borrows` function", but more concise, and wrote something that makes no sense apparently :sweat_smile:

**Comment by xFrednet** [comment]
No problem at all, I'm happy that you took the time to think about it and you also responded super quick! :)

**Comment by Niki4tap** [comment]
Oh, and, thanks for the correction ;)

File: clippy_lints/src/returns.rs [hunk 1]
```diff
@@ -292,7 +295,7 @@ fn last_statement_borrows<'tcx>(cx: &LateContext<'tcx>, expr: &'tcx Expr<'tcx>)
         {
             ControlFlow::Break(())
         } else {
-            ControlFlow::Continue(Descend::from(!expr.span.from_expansion()))
+            ControlFlow::Continue(Descend::from(!e.span.from_expansion()))
```
Comment (Alexendoo) [inline clippy_lints/src/returns.rs:298]: I missed this part and spent far too long wondering how the changes above this fixed the issue 😅

**Review by Alexendoo — APPROVED** [review]

**Comment by Alexendoo** [comment]
Thanks @Niki4tap!

@bors r+

File: clippy_lints/src/returns.rs (hunk 1 above)
Comment (Niki4tap) [reply clippy_lints/src/returns.rs:298]: Awwww, I made commits separate specifically for this :v

Comment (Alexendoo) [reply clippy_lints/src/returns.rs:298]: Yeah thanks for that, I ended up spotting it because I did a `git log` and saw the separate fix commit
