### PR TITLE
Look at adjusted types instead of fn signature types in `ptr_arg`

### LINKED ISSUE #10612: `ptr_arg` false positive on `ToOwned::clone_into()`
### Summary

`ptr_arg` does not recognize `ToOwned::clone_into()` as a call that requires `&mut String` or `&mut Vec<T>`, and incorrectly suggests changing to `&mut str` or `&mut [T]`.

### Lint Name

ptr_arg

### Reproducer

I tried this code:

```rust
pub fn t1(mut_string: &mut String, ref_str: &str) {
    ref_str.clone_into(mut_string);
}
pub fn t2(mut_vec: &mut Vec<u8>, ref_slice: &[u8]) {
    ref_slice.clone_into(mut_vec);
}
```

I saw this happen:

```
warning: writing `&mut String` instead of `&mut str` involves a new object where a slice will do
 --> src/lib.rs:1:23
  |
1 | pub fn t1(mut_string: &mut String, ref_str: &str) {
  |                       ^^^^^^^^^^^ help: change this to: `&mut str`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
  = note: `#[warn(clippy::ptr_arg)]` on by default

warning: writing `&mut Vec` instead of `&mut [_]` involves a new object where a slice will do
 --> src/lib.rs:4:20
  |
4 | pub fn t2(mut_vec: &mut Vec<u8>, ref_slice: &[u8]) {
  |                    ^^^^^^^^^^^^ help: change this to: `&mut [u8]`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
```

The suggestions do not compile.

I expected to see this happen: No warnings, since `clone_into` requires a mutable reference to the owned and resizable type.

### Version

```text
Happens with 0.1.70 (2023-04-02 3a8a131) and also latest git 9818ad21678e5e71dcdfd3e3be5a348195e172e0
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### LINKED ISSUE #13308: ptr_arg triggers on &mut String despite clone_into
### Summary

If a `&mut String` argument is only used as the input to `clone_into`, then `ptr_arg` triggers erroneously.

### Lint Name

ptr_arg

### Reproducer

I tried this code:

```rust
fn foo(source: &str, destination: &mut String)  {
    source.clone_into(destination)
}

fn main() {
    foo("bar", &mut String::new());
}
```

I saw this happen:

```
warning: writing `&mut String` instead of `&mut str` involves a new object where a slice will do
 --> src/main.rs:1:35
  |
1 | fn foo(source: &str, destination: &mut String)  {
  |                                   ^^^^^^^^^^^ help: change this to: `&mut str`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
  = note: `#[warn(clippy::ptr_arg)]` on by default
```

I expected to see this happen:

Nothing

### Version

```text
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
binary: rustc
commit-hash: 3f5fd8dd41153bc5fdca9427e9e05be2c767ba23
commit-date: 2024-08-06
host: x86_64-unknown-linux-gnu
release: 1.80.1
LLVM version: 18.1.7
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by y21**
This simplifies the implementation of the `ptr_arg` lint a bit and:
Fixes #13308
Fixes #10612

Currently, the lint checks if e.g. a `&String` parameter is only used in contexts where a `&str` could work. Part of it worked by looking for path exprs to that parameter in function call position specifically, looking at the callee signature and checking if that parameter type without refs is `String` (or one of a bunch of other special cases).

This simplified version removes the special casing of function calls and looking at the parameter type and instead just looks at the **adjusted type**, regardless of the expression it's in. This naturally also covers what the previous version was doing (if the expression is in a function call argument position expecting a `&str`, then it will have that adjustment. If it requires a `&String` then it won't have that adjustment and we won't lint).

The linked issue was a FP that happened because the previous implementation simply didn't consider projection types in the signature type, but with this simplification we don't really need to consider that (because we aren't looking at function signatures at all anymore -- the `&mut Self::Owned` parameter type of `clone_into` is the already-instantiated and normalized type `&mut String`).

changelog: none

### CODE REVIEW

File: clippy_lints/src/ptr.rs [hunk 1]
```diff
@@ -591,6 +587,7 @@ fn check_ptr_arg_usage<'tcx>(cx: &LateContext<'tcx>, body: &Body<'tcx>, args: &[
             };
             let args = &self.args[args_idx];
             let result = &mut self.results[args_idx];
+            let deref_ty = LazyCell::new(|| args.deref_ty.ty(self.cx));
```
Comment (Centri3) [inline clippy_lints/src/ptr.rs:590]: Do we need to use `LazyCell` here? I don't see why we can't just move this assignment down to where it's used considering there's only one path it's used

**Review by Centri3 — APPROVED** [review]
Looks perfect, just one thing!

File: clippy_lints/src/ptr.rs (hunk 1 above)
Comment (y21) [reply clippy_lints/src/ptr.rs:590]: Good point. The changes I made went through a bunch of iterations where this made more sense before I created the PR, but now it doesn't anymore, so removing

**Comment by Centri3** [comment]
Thanks! @bors r+
