### PR TITLE
Fixes issue 5095

### LINKED ISSUE #5095: Internal lint: check if `span_lint_and_then` and `span_*` are collapsable
When `span_lint_and_then` and `span_*` have the same span, we can replace them with `span_lint_and_*` in most cases. It'd be nice that we have an internal lint for this.
It's a follow-up for [this comment](https://github.com/rust-lang/rust-clippy/pull/5084#discussion_r370936810).

### PR DESCRIPTION
**Pull request by xiongmao86**
fixes #5095.

- [x] Followed [lint naming conventions][lint_naming]
- [x] Added passing UI tests (including committed `.stderr` file)
- [x] `cargo test` passes locally
- [x] Executed `cargo dev update_lints`
- [x] Added lint documentation
- [x] Run `cargo dev fmt`

[lint_naming]: https://rust-lang.github.io/rfcs/0344-conventions-galore.html#lints

changelog: (internal) warn about collapsible `span_lint_and_then` calls.

### CODE REVIEW

File: tests/ui/collapsible_span_lint_calls.rs [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+ extern crate rustc_errors;
+ extern crate rustc_lint;
+ extern crate syntax;
+ extern crate clippy_lints;
+
+use rustc_session::{declare_tool_lint, declare_lint_pass};
+use rustc_errors::Applicability;
+use rustc_lint::{EarlyContext, EarlyLintPass};
+use syntax::ast::Expr;
+use clippy_lints::utils::span_lint_and_then;
```
Comment (xiongmao86) [inline tests/ui/collapsible_span_lint_calls.rs]: How to import span_lint_and_then. This failed because `clippy_lints::utils` is private mod.

Comment (flip1995) [reply tests/ui/collapsible_span_lint_calls.rs]: I guess, this isn't possible. Can you just redefine this function here?

**Comment by xiongmao86** [comment]
@flip1995, Can I use author lint on internal lints, I have tried the playground tricks, but it is not working because of extern crate declaration.

**Comment by flip1995** [comment]
Yes you can. You could make the `utils` module public during developing the lint and then use `clippy::author` in the test file. And then just run the test and the author lint should print to stdout.

File: clippy_lints/src/utils/internal_lints.rs [hunk 2]
```diff
@@ -395,3 +401,111 @@ fn is_trigger_fn(fn_kind: FnKind<'_>) -> bool {
...
     }
 }
+
+declare_lint_pass!(CollapsibleCalls => [COLLAPSIBLE_SPAN_LINT_CALLS]);
+
+impl  EarlyLintPass for CollapsibleCalls {
+    fn check_expr(&mut self, cx: &EarlyContext<'_>, expr: &ast::Expr) {
+        use ast::ExprKind;
+
+        if_chain! {
```
Comment (xiongmao86) [inline clippy_lints/src/utils/internal_lints.rs]: There are errors saying no rule expected this token. How can I debug the macro?

File: tests/ui/collapsible_span_lint_calls.rs [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+        span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |db| {
+            db.span_suggestion(expr.span, help_msg, sugg.to_string(), Applicability::MachineApplicable);
+        });
+        span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |db| {
+            db.span_help(expr.span, help_msg);
+        });
+        span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |db| {
+            db.span_note(expr.span, note_msg);
+        });
```
Comment (flip1995) [inline tests/ui/collapsible_span_lint_calls.rs]: Can you add a test where the spans are different? (Should not lint) Also a test, where something else is done in the closure would be good.

File: clippy_lints/src/utils/internal_lints.rs [hunk 4]
```diff
@@ -395,3 +401,111 @@ fn is_trigger_fn(fn_kind: FnKind<'_>) -> bool {
...
+                    _  => (),
+                }
+            }
+        }
+    }
+}
+
+fn snippet(cx: &EarlyContext<'_>, span: Span) -> String {
+    snippet_opt(cx, span).expect("should be able to retrive span.")
+}
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs]: Please use `snippet_with_applicability`, or just `snippet`, since it is an internal lint and we don't have to be too careful with the applicability.

File: clippy_lints/src/utils/internal_lints.rs [hunk 5]
```diff
@@ -395,3 +401,111 @@ fn is_trigger_fn(fn_kind: FnKind<'_>) -> bool {
...
+declare_lint_pass!(CollapsibleCalls => [COLLAPSIBLE_SPAN_LINT_CALLS]);
+
+impl  EarlyLintPass for CollapsibleCalls {
+    fn check_expr(&mut self, cx: &EarlyContext<'_>, expr: &ast::Expr) {
+        use ast::ExprKind;
+
+        if_chain! {
+            if let ExprKind::Call(ref func, ref and_then_args) = expr.kind;
+            if let ExprKind::Path(None, ref path) = func.kind;
+            if let match_path_ast(path, &["span_lint_and_then"]);
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs]: Brute force: Remove lines until the error disappears :man_shrugging: 

```suggestion
            if match_path_ast(path, &["span_lint_and_then"]);
```

File: clippy_lints/src/utils/internal_lints.rs [hunk 6]
```diff
@@ -395,3 +401,111 @@ fn is_trigger_fn(fn_kind: FnKind<'_>) -> bool {
...
+            if and_then_args.len() == 5;
+            if let ExprKind::Closure(_, _, _, _, block) = and_then_args[4].kind;
+            if let ExprKind::Block(block, _) = block.kind;
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs]: Rather use `utils::remove_blocks` here.

Comment (flip1995) [reply clippy_lints/src/utils/internal_lints.rs]: Wait `remove_blocks` doesn't resolve `{ x; }`->`x;` So we need to check for all three cases:

```rust
|db| { db._ }

|db| { db._; }

|db| db._
```

File: clippy_lints/src/utils/internal_lints.rs [hunk 7]
```diff
@@ -395,3 +402,181 @@ fn is_trigger_fn(fn_kind: FnKind<'_>) -> bool {
...
     }
 }
+
+declare_lint_pass!(CollapsibleCalls => [COLLAPSIBLE_SPAN_LINT_CALLS]);
+
+impl  EarlyLintPass for CollapsibleCalls {
+    fn check_expr(&mut self, cx: &EarlyContext<'_>, expr: &AstExpr) {
+        use ast::{StmtKind, ExprKind};
+
+        span_lint_and_help(cx, COLLAPSIBLE_SPAN_LINT_CALLS, expr.span, "lint message", "help message");
```
Comment (xiongmao86) [inline clippy_lints/src/utils/internal_lints.rs]: I am trying to address the issues, when I come amost close, I found the span_lint_and_help doesn't even emit in stdout. I have try `utils/dev update_lints` but nothing changed?

File: tests/ui/collapsible_span_lint_calls.rs (hunk 3 above)
Comment (xiongmao86) [reply tests/ui/collapsible_span_lint_calls.rs]: How can I make up a different Span?

File: clippy_lints/src/utils/internal_lints.rs (hunk 7 above)
Comment (flip1995) [reply clippy_lints/src/utils/internal_lints.rs]: Have you registered the lint pass?

File: tests/ui/collapsible_span_lint_calls.rs (hunk 3 above)
Comment (flip1995) [reply tests/ui/collapsible_span_lint_calls.rs]: `if let ExprKind::Unop(e) = expr.kind { e.span }`  pseudocode obviously

Comment (xiongmao86) [reply tests/ui/collapsible_span_lint_calls.rs]: Oh, suddenly realize rust won't emit warning on this snippet.

File: clippy_lints/src/utils/internal_lints.rs (hunk 7 above)
Comment (xiongmao86) [reply clippy_lints/src/utils/internal_lints.rs]: I have tried to search other internal lints like `PRODUCE_ICE` on the repo, and do the same thing for internal lint I am writing, but it didn't work. 

Perhaps because I didn't search `ProduceIce` either. I'll tried that out.

File: tests/ui/collapsible_span_lint_calls.rs (hunk 3 above)
Comment (flip1995) [reply tests/ui/collapsible_span_lint_calls.rs]: With a different span, it should only warn on `and_then`+`span_note`/`and_then`+`note`

File: clippy_lints/src/utils/internal_lints.rs (hunk 7 above)
Comment (flip1995) [reply clippy_lints/src/utils/internal_lints.rs]: `update_lints` currently doesn't update internal lints. See #5156

In addition to that, you have to add `store.register_early_pass(..)` to the lib file by hand. See https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md#lint-declaration

File: clippy_lints/src/utils/internal_lints.rs (hunk 6 above)
Comment (xiongmao86) [reply clippy_lints/src/utils/internal_lints.rs]:
```rust
|db| { db._ }
|db| db._
```
The last two forms emits error.

File: tests/ui/collapsible_span_lint_calls.stderr [hunk 8]
```diff
@@ -0,0 +1,17 @@
...
+LL |             db.span_help(expr.span, help_msg)
+   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^- help: try adding a semicolon: `;`
+   |             |
+   |             expected `()`, found `&mut rustc_errors::DiagnosticBuilder<'_>`
+
+error[E0308]: mismatched types
+  --> $DIR/collapsible_span_lint_calls.rs:47:13
+   |
+LL |             db.span_note(expr.span, note_msg)
+   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `()`, found `&mut rustc_errors::DiagnosticBuilder<'_>`
```
Comment (xiongmao86) [inline tests/ui/collapsible_span_lint_calls.stderr]: These two forms emit error.

File: clippy_lints/src/utils/internal_lints.rs (hunk 6 above)
Comment (flip1995) [reply clippy_lints/src/utils/internal_lints.rs]: `|db| { db._; }` should also produce an error.

File: tests/ui/collapsible_span_lint_calls.stderr (hunk 8 above)
Comment (flip1995) [reply tests/ui/collapsible_span_lint_calls.stderr]: Oh yeah. In that case `{ db._; }` is enough. Sorry for the confusion.

Comment (xiongmao86) [reply tests/ui/collapsible_span_lint_calls.stderr]: The only case we should test should be `|db| { db._; }` only.

**Comment by xiongmao86** [comment]
As a self reminder, have not done `db.note()` and `db.help()`.

**Comment by xiongmao86** [comment]
Oh, no. My dear old laptop have blackout. Some work have lost.

**Comment by flip1995** [comment]
After rebase, `update_lints` will also update the internal lints.

**Comment by xiongmao86** [comment]
Copy, thanks for the update.

**Comment by xiongmao86** [comment]
Still downloading toolchain, network has been slow.

**Comment by xiongmao86** [comment]
Oh, there are so many problem to set up a proper environment for development. I can't use my bluetooth keyboard in ubuntu, I don't have a proper connection to successfully download rustup. I think I should buy a new laptop that is compatible with linux like my broken laptop. But there are the nCov out there and I think I couldn't get a new laptop in recent time. 

So, I am wondering should I just close this pr, @flip1995?

**Comment by flip1995** [comment]
No problem, internal lints are nothing urgent, so you can get back to this, whenever your ready.

> So, I am wondering should I just close this pr, @flip1995?

Sure, you can open it again, if you want to continue working on this. I marked it as `S-inactive-closed` in the meantime.

**Comment by xiongmao86** [comment]
Ho, ho I am back.

File: clippy_lints/src/utils/internal_lints.rs [hunk 9]
```diff
@@ -391,3 +402,188 @@ fn is_trigger_fn(fn_kind: FnKind<'_>) -> bool {
...
+    SuggestionArgs {
+        span: span_snippet_of_span_call,
+        help: help_snippet,
+        sugg: sugg_snippet,
+        applicability: applicability_snippet,
+    }
+}
+
+fn suggest_span_suggestion(cx: &EarlyContext<'_>, expr: &AstExpr, and_then_args: AndThenArgs<'_>, suggestion_args: SuggestionArgs<'_>) {
+    if and_then_args.span == suggestion_args.span {
```
Comment (xiongmao86) [inline clippy_lints/src/utils/internal_lints.rs]: Why is this condition test out to be false? I read the docs, they are both Cow<'a, str>, they should be equal.

Comment (xiongmao86) [reply clippy_lints/src/utils/internal_lints.rs]: I tested out with adding and else branch and the else branch was run.

Comment (flip1995) [reply clippy_lints/src/utils/internal_lints.rs]: You shouldn't determine if two things are the same, by comparing there snippets, but rather use `utils::hir_utils::SpanlessEq` to compare expressions. That should also simplify your code.

File: clippy_lints/src/utils/internal_lints.rs [hunk 10]
```diff
@@ -142,6 +145,64 @@ declare_clippy_lint! {
...
 
+declare_clippy_lint! {
+    /// **What it does:** When `span_lint_and_then` function call and its
+    /// closure have one statment that is a method call of `span_suggestion`,
+    /// `span_help`, or `span_note` are using the same span argument,
+    /// or when closure have one statment that is a function call of `note` or
+    /// `help`, they should be replaced with one of three function calls which is
+    /// `span_lint_and_sugg`, span_lint_and_help` or `span_lint_and_note`.
+    ///
+    /// **Why is this bad?**
```
Comment (xiongmao86) [inline clippy_lints/src/utils/internal_lints.rs]: I am not very clear why this is bad.

Comment (flip1995) [reply clippy_lints/src/utils/internal_lints.rs]: We have wrapper functions for this, so we should use them wherever possible.

Comment (xiongmao86) [reply clippy_lints/src/utils/internal_lints.rs]: Using wrapper functions mades intention more clear?

Comment (xiongmao86) [reply clippy_lints/src/utils/internal_lints.rs]: I have thought about my question, and In fact what I want to ask should be phrased is why we want to make a wrapping function. What is the benefit to make it? I have read some refactor book before, and I am often confuse why coding in that special way improves the code.

Comment (flip1995) [reply clippy_lints/src/utils/internal_lints.rs]: Ah ok, I'll split my answer to your question:

1. Why is this bad in the sense of the lint?

The lint message and the help/suggestion message have the same span most of the time. So Clippy has (wrapper) functions for this case. These wrappers make it easier to produce a lint+help message, since no closure is required, but you just have to pass some strings.

2. Why should you use wrapper functions at all?

The answer is convenience (and readability). Let's look at a simple (imaginary) case:

```rust
fn do_something(x: u32) -> Result<u32, Error> { ... }
```

If that is a function, that you use really often in your code, where the `x` argument is `0` (but sometimes is something else), you may want to define a function

```rust
fn do_something_zero() -> Result<u32, Error> { do_something(0) }
```

so that you don't have to type out the `0` argument.

If we transfer this to our `span_lint_and_then` function, the `|db| { ... }` argument is most of the time the same:

```rust
|db| {
    db.span_suggestion(span, msg, sugg, appl)
}
```

So we have a wrapper function, so you only have to pass `msg` and `sugg` and the wrapper function takes care of calling `span_lint_and_then` with the correct closure. -> More convenient, more readable, more error resistent (you don't have to write a closure, but just strings)

**Comment by flip1995** [comment]
If you think this is ready for another round of review, let me know. I kind of lost track of the progress of this. (You can just press request review at the top of the PR)

File: clippy_lints/src/utils/internal_lints.rs (hunk 10 above)
Comment (xiongmao86) [reply clippy_lints/src/utils/internal_lints.rs]: Thank you, now I see the matter clearer.

**Comment by xiongmao86** [comment]
It is almost closed. When I `cargo test`, this lint emits a lot of warning in `dogfood_clippy` test, and `cargo fix` didn't fix the code. What do you suggest me do?

After fixing the code, if no other problem emerge, then I'll request review.

**Comment by flip1995** [comment]
cargo fix doesn't work with Clippy currently. See #5358. So you would have to fix these warnings by hand.

**Comment by xiongmao86** [comment]
`RUSTC_WORKSPACE_WRAPPER=clippy-driver cargo fix -Zunsable-options` doesn't seem to work, do you literally mean by changing file after file?

**Comment by flip1995** [comment]
Yeah, that probably won't work for a while now. We have to figure out, how to deploy this. 

> do you mean by changing file after file?

Yeah. If you don't want to do this, we can put this PR on ice, until fix works again with Clippy.

**Comment by xiongmao86** [comment]
Oh, it is not very large, I'll try it by hand.

File: clippy_lints/src/utils/diagnostics.rs [hunk 11]
```diff
@@ -163,6 +163,7 @@ pub fn span_lint_hir_and_then(
 ///     |
 ///     = note: `-D fold-any` implied by `-D warnings`
 /// ```
+#[allow(clippy::collapsible_span_lint_calls)]
```
Comment (xiongmao86) [inline clippy_lints/src/utils/diagnostics.rs:166]: Adding this does not work. The terminal emits an unknown lint error. I can't figure out why.

**Comment by xiongmao86** [comment]
And there are a false positive situation 
```rust
span_lint_and_then(cx,
    USELESS_LET_IF_SEQ,
    span,
    "`if _ { .. } else { .. }` is an expression",
    |db| {
        db.span_suggestion(
             span,
             "it is more idiomatic to write",
             sug,
             Applicability::HasPlaceholders,
         );
        if !mutability.is_empty() {
            db.note("you might not need `mut` at all");
        }
    });
```
How to rule out cases like this? The `if` at last doesn't count as a stmt?

**Comment by flip1995** [comment]
`if block.expr.is_some()`

File: clippy_lints/src/utils/diagnostics.rs (hunk 11 above)
Comment (flip1995) [reply clippy_lints/src/utils/diagnostics.rs:166]: `update_lints` is broken for internal lints. I'm working on a fix

**Comment by xiongmao86** [comment]
Updating toolchain...

File: clippy_lints/src/eta_reduction.rs [hunk 12]
```diff
@@ -131,14 +132,10 @@ fn check_closure(cx: &LateContext<'_, '_>, expr: &Expr<'_>) {
...
-                        expr.span,
-                        "remove closure as shown",
-                        format!("{}::{}", name, path.ident.name),
-                        Applicability::MachineApplicable,
-                    );
-                });
+                span_lint_and_sugg(cx, REDUNDANT_CLOSURE_FOR_METHOD_CALLS, expr.span, "redundant closure found",
+                "remove closure as shown",
+                format!("{}::{}", name, path.ident.name),
+                Applicability::MachineApplicable,);
```
Comment (flip1995) [inline clippy_lints/src/eta_reduction.rs:138]: formatting
```suggestion
                span_lint_and_sugg(
                    cx,
                    REDUNDANT_CLOSURE_FOR_METHOD_CALLS,
                    expr.span,
                    "redundant closure found",
                    "remove closure as shown",
                    Applicability::MachineApplicable,
                );
```

File: clippy_lints/src/loops.rs [hunk 13]
```diff
@@ -2471,25 +2471,19 @@ fn check_needless_collect<'a, 'tcx>(expr: &'tcx Expr<'_>, cx: &LateContext<'a, '
...
                 if method.ident.name == sym!(len) {
                     let span = shorten_needless_collect_span(expr);
-                    span_lint_and_then(cx, NEEDLESS_COLLECT, span, NEEDLESS_COLLECT_MSG, |db| {
-                        db.span_suggestion(
-                            span,
+                    span_lint_and_sugg(cx, NEEDLESS_COLLECT, span, NEEDLESS_COLLECT_MSG,
                             "replace with",
                             ".count()".to_string(),
                             Applicability::MachineApplicable,
                         );
```
Comment (flip1995) [inline clippy_lints/src/loops.rs:2478]: Formatting

File: clippy_lints/src/loops.rs [hunk 14]
```diff
@@ -2471,25 +2471,19 @@ fn check_needless_collect<'a, 'tcx>(expr: &'tcx Expr<'_>, cx: &LateContext<'a, '
...
-                    span_lint_and_then(cx, NEEDLESS_COLLECT, span, NEEDLESS_COLLECT_MSG, |db| {
-                        db.span_suggestion(
-                            span,
+                    span_lint_and_sugg(cx, NEEDLESS_COLLECT, span, NEEDLESS_COLLECT_MSG,
                             "replace with",
                             ".next().is_none()".to_string(),
                             Applicability::MachineApplicable,
                         );
-                    });
                 }
```
Comment (flip1995) [inline clippy_lints/src/loops.rs:2487]: formatting

File: clippy_lints/src/ptr.rs [hunk 15]
```diff
@@ -234,20 +234,15 @@ fn check_fn(cx: &LateContext<'_, '_>, decl: &FnDecl<'_>, fn_id: HirId, opt_body_
...
                                 PTR_ARG,
                                 arg.span,
                                 "using a reference to `Cow` is not recommended.",
-                                |db| {
-                                    db.span_suggestion(
-                                        arg.span,
                                         "change this to",
                                         "&".to_owned() + &r,
                                         Applicability::Unspecified,
                                     );
```
Comment (flip1995) [inline clippy_lints/src/ptr.rs:245]: Formatting
```suggestion
                                "change this to",
                                "&".to_owned() + &r,
                                Applicability::Unspecified,
                            );
```

File: clippy_lints/src/returns.rs [hunk 16]
```diff
@@ -259,14 +261,11 @@ impl EarlyLintPass for Return {
...
                     (ty.span, Applicability::MaybeIncorrect)
                 };
-                span_lint_and_then(cx, UNUSED_UNIT, rspan, "unneeded unit return type", |db| {
-                    db.span_suggestion(
-                        rspan,
+                span_lint_and_sugg(cx, UNUSED_UNIT, rspan, "unneeded unit return type",
                         "remove the `-> ()`",
                         String::new(),
                         appl,
                     );
```
Comment (flip1995) [inline clippy_lints/src/returns.rs:268]: Formatting

File: clippy_lints/src/returns.rs [hunk 17]
```diff
@@ -279,14 +278,12 @@ impl EarlyLintPass for Return {
...
             then {
                 let sp = expr.span;
-                span_lint_and_then(cx, UNUSED_UNIT, sp, "unneeded unit expression", |db| {
-                    db.span_suggestion(
-                        sp,
+                span_lint_and_sugg(cx, UNUSED_UNIT, sp, "unneeded unit expression",
                         "remove the final `()`",
                         String::new(),
                         Applicability::MachineApplicable,
                     );
```
Comment (flip1995) [inline clippy_lints/src/returns.rs:285]: Formatting

File: clippy_lints/src/transmute.rs [hunk 18]
```diff
@@ -441,14 +442,11 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for Transmute {
...
                                     cx,
                                     TRANSMUTE_BYTES_TO_STR,
                                     e.span,
                                     &format!("transmute from a `{}` to a `{}`", from_ty, to_ty),
-                                    |db| {
-                                        db.span_suggestion(
-                                            e.span,
                                             "consider using",
                                             format!(
                                                 "std::str::from_utf8{}({}).unwrap()",
```
Comment (flip1995) [inline clippy_lints/src/transmute.rs:452]: Formatting

File: tests/ui/collapsible_span_lint_calls.rs [hunk 19]
```diff
@@ -0,0 +1,93 @@
...
+        let help_msg = "help message";
+        let note_msg = "note message";
+        let sugg = "new_call()";
+        let predicate = true;
+
+        span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |db| {
+            db.span_suggestion(expr.span, help_msg, sugg.to_string(), Applicability::MachineApplicable);
+        });
+        span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |db| {
+            db.span_help(expr.span, help_msg);
```
Comment (flip1995) [inline tests/ui/collapsible_span_lint_calls.rs:71]: This should not get linted, looking at how the wrapper functions are implemented. But since it makes sense to lint this, I would suggest to adapt the wrapper functions, instead of the lint.

Currently the wrapper functions `span_lint_and_note` and `span_lint_and_help` are inconsitent, since `note` takes an additional span, while `help` doesn't. I'd suggest to make following two changes:

1. Turn the `note_span` argument in `span_lint_and_note` to an `Option<Span>` to make it more idomatic
2. Add a `help_span: Option<Span>` to `span_lint_and_help` and adapt the implementation to the one of `span_lint_and_note`

File: clippy_lints/src/utils/internal_lints.rs [hunk 20]
```diff
@@ -391,3 +453,159 @@ fn is_trigger_fn(fn_kind: FnKind<'_>) -> bool {
...
+
+impl<'a, 'tcx> LateLintPass<'a, 'tcx> for CollapsibleCalls {
+    fn check_expr(&mut self, cx: &LateContext<'a, 'tcx>, expr: &'tcx hir::Expr<'_>) {
+        if_chain! {
+            if let ExprKind::Call(ref func, ref and_then_args) = expr.kind;
+            if let ExprKind::Path(ref path) = func.kind;
+            if match_qpath(path, &["span_lint_and_then"]);
+            if and_then_args.len() == 5;
+            if let ExprKind::Closure(_, _, body_id, _, _) = &and_then_args[4].kind;
+            if let body = cx.tcx.hir().body(*body_id);
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs:467]:
```suggestion
            let body = cx.tcx.hir().body(*body_id);
```

File: clippy_lints/src/utils/internal_lints.rs [hunk 21]
```diff
@@ -391,3 +453,159 @@ fn is_trigger_fn(fn_kind: FnKind<'_>) -> bool {
...
+            and_then_snippets.span,
+            note
+        ),
+        Applicability::MachineApplicable,
+    );
+}
+
+fn snippet<'a>(cx: &LateContext<'_, '_>, span: Span) -> Cow<'a, str> {
+    other_snippet(cx, span, "Should not be this snippet")
+}
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs:611]: Please don't reimplement this function. Especially for `cx_snippet` and `span_snippet` you can provide better defaults (`"cx"` and `"span"`). For the messages you should use the defaults `r#""...""#`.

File: clippy_lints/src/utils/internal_lints.rs [hunk 22]
```diff
@@ -142,6 +145,65 @@ declare_clippy_lint! {
     "found 'default lint description' in a lint declaration"
 }
 
+declare_clippy_lint! {
+    /// **What it does:** When `span_lint_and_then` function call and its
+    /// closure have one statment that is a method call of `span_suggestion`,
+    /// `span_help`, or `span_note` are using the same span argument,
+    /// or when closure have one statment that is a function call of `note` or
+    /// `help`, they should be replaced with one of three function calls which is
+    /// `span_lint_and_sugg`, span_lint_and_help` or `span_lint_and_note`.
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs:154]: Reworded:
```suggestion
    /// **What it does:** Lints `span_lint_and_then` function calls, where the
    /// closure argument has only one statement and that statement is a method 
    /// call to `span_suggestion`, `span_help`, `span_note` (using the same 
    /// span), `help` or `note`. 
    ///
    /// These usages of `span_lint_and_then` should be replaced with one of the 
    /// wrapper functions `span_lint_and_sugg`, span_lint_and_help`, or 
    /// `span_lint_and_note`.
```

File: clippy_lints/src/utils/internal_lints.rs [hunk 23]
```diff
@@ -142,6 +145,65 @@ declare_clippy_lint! {
...
+    ///
+    /// **Why is this bad?** There are wrapper `span_lint_and_*` functions, it is
+    /// convenient, more readable and more error resistant to use wrapper functions.
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs:157]:
```suggestion
    /// **Why is this bad?** Using the wrapper `span_lint_and_*` functions, is more
    /// convenient, readable and less error prone.
```

File: tests/ui/collapsible_span_lint_calls.rs (hunk 19 above)
Comment (xiongmao86) [reply tests/ui/collapsible_span_lint_calls.rs:71]: @flip1995 Do you mean change the `help_span` argument in the ways that point 1 describe when you are saying 'adapt the implementation to the one of span_lint_and_note'?

Comment (flip1995) [reply tests/ui/collapsible_span_lint_calls.rs:71]: Yes, this will kind of conflict with my explanation above, for what to use wrapper functions, since every call to the wrapper will have the same `None` argument. But this is more clean, since help messages can have different spans from the error message and we should respect that in the future, like we do with `span_lint_and_note`.

After this PR, _someone_ can look over every `span_lint_and_help` call and determine, if providing another span would be helpful.

Comment (flip1995) [reply tests/ui/collapsible_span_lint_calls.rs:71]: @xiongmao86 Sorry if this is more work, than you might have expected. But implementing internal lints usually uncovers flaws in the code base, which should be fixed directly. Thanks for putting all this work in!

Comment (xiongmao86) [reply tests/ui/collapsible_span_lint_calls.rs:71]: Just wondering there is opportunity to reduce work. If there is tricks to do, it's good. If there is no tricks, I am still glad that I can help.

Comment (flip1995) [reply tests/ui/collapsible_span_lint_calls.rs:71]: There's not really a trick on how to fix the fallout from this change. In vim, I would record a macro, that adds the argument and then just `rg` for `span_help_and_lint` and jump between all occurrences.

Comment (xiongmao86) [reply tests/ui/collapsible_span_lint_calls.rs:71]: I have finish span_lint_and_help last night, I have to say it not so much work than I feel at the beginning. I'll add this tip to my note, thanks for the tip.

Comment (xiongmao86) [reply tests/ui/collapsible_span_lint_calls.rs:71]: Is `rg` a plug-in? `vim-rg`?

Comment (xiongmao86) [reply tests/ui/collapsible_span_lint_calls.rs:71]: Macro is not very fit solution, does rust plan to have refactoring tool?

Comment (flip1995) [reply tests/ui/collapsible_span_lint_calls.rs:71]: > does rust plan to have refactoring tool?

Rust has rustfix. But this doesn't really work for missing arguments, since automatically add a random argument will almost always be the wrong suggestion. I don't know how well rustfix is integrated with vscode yet.

Comment (xiongmao86) [reply tests/ui/collapsible_span_lint_calls.rs:71]: Thanks for the tips. I have adapted the `span_lint_and_note` invocation. Waiting for toolchain updating.

**Comment by xiongmao86** [comment]
I don't know why this build failed, do I need another rustup?

File: clippy_lints/src/empty_enum.rs [hunk 24]
```diff
@@ -45,13 +45,15 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for EmptyEnum {
...
-                        "consider using the uninhabited type `!` (never type) or a wrapper \
-                         around it to introduce a type which can't be instantiated",
-                    );
-                });
+                span_lint_and_help(
+                    cx,
+                    EMPTY_ENUM,
+                    item.span,
+                    "enum with no variants",
+                    Some(item.span),
```
Comment (flip1995) [inline clippy_lints/src/empty_enum.rs:53]:
```suggestion
                    None,
```

same span

File: clippy_lints/src/loops.rs [hunk 25]
```diff
@@ -2471,45 +2473,50 @@ fn check_needless_collect<'a, 'tcx>(expr: &'tcx Expr<'_>, cx: &LateContext<'a, '
...
-                        diag.span_suggestion(
-                            span,
+                    span_lint_and_sugg(cx,
+                        NEEDLESS_COLLECT,
+                        span,
+                        NEEDLESS_COLLECT_MSG,
                             "replace with",
                             ".count()".to_string(),
                             Applicability::MachineApplicable,
                         );
```
Comment (flip1995) [inline clippy_lints/src/loops.rs:2483]:
```suggestion  
                        "replace with",
                        ".count()".to_string(),
                        Applicability::MachineApplicable,
                    );
```

File: clippy_lints/src/loops.rs [hunk 26]
```diff
@@ -2471,45 +2473,50 @@ fn check_needless_collect<'a, 'tcx>(expr: &'tcx Expr<'_>, cx: &LateContext<'a, '
                 match_type(cx, ty, &paths::HASHMAP) {
                 if method.ident.name == sym!(len) {
                     let span = shorten_needless_collect_span(expr);
-                    span_lint_and_then(cx, NEEDLESS_COLLECT, span, NEEDLESS_COLLECT_MSG, |diag| {
-                        diag.span_suggestion(
-                            span,
+                    span_lint_and_sugg(cx,
```
Comment (flip1995) [inline clippy_lints/src/loops.rs:2476]:
```suggestion
                    span_lint_and_sugg(
                        cx,
```

File: clippy_lints/src/loops.rs [hunk 27]
```diff
@@ -2471,45 +2473,50 @@ fn check_needless_collect<'a, 'tcx>(expr: &'tcx Expr<'_>, cx: &LateContext<'a, '
...
-                            ".next().is_none()".to_string(),
-                            Applicability::MachineApplicable,
+                    span_lint_and_sugg(cx,
+                        NEEDLESS_COLLECT,
+                        span,
+                        NEEDLESS_COLLECT_MSG,
+                        "replace with",
+                        ".next().is_none()".to_string(),
+                        Applicability::MachineApplicable,
                         );
```
Comment (flip1995) [inline clippy_lints/src/loops.rs:2494]:
```suggestion
                    span_lint_and_sugg(
                        cx,
                        NEEDLESS_COLLECT,
                        span,
                        NEEDLESS_COLLECT_MSG,
                        "replace with",
                        ".next().is_none()".to_string(),
                        Applicability::MachineApplicable,
                    );
```

File: clippy_lints/src/loops.rs [hunk 28]
```diff
@@ -2471,45 +2473,50 @@ fn check_needless_collect<'a, 'tcx>(expr: &'tcx Expr<'_>, cx: &LateContext<'a, '
...
+                                span,
+                                "replace with",
+                                format!(
+                                    ".any(|{}| x == {})",
+                                    arg, pred
+                                ),
+                                Applicability::MachineApplicable,
+                            );
+                        }
+                    );
```
Comment (flip1995) [inline clippy_lints/src/loops.rs:2519]:
```suggestion
                    span_lint_and_then(
                        cx,
                        NEEDLESS_COLLECT,
                        span,
                        NEEDLESS_COLLECT_MSG,
                        |db| {
                            let (arg, pred) = if contains_arg.starts_with('&') {
                                ("x", &contains_arg[1..])
                            } else {
                                ("&x", &*contains_arg)
                            };
                            db.span_suggestion(
                                span,
                                "replace with",
                                format!(
                                    ".any(|{}| x == {})",
                                    arg, pred
                                ),
                                Applicability::MachineApplicable,
                            );
                        }
                    );
```

File: clippy_lints/src/returns.rs [hunk 29]
```diff
@@ -279,14 +282,16 @@ impl EarlyLintPass for Return {
...
+                span_lint_and_sugg(
+                    cx,
+                    UNUSED_UNIT,
+                    sp,
+                    "unneeded unit expression",
+                    "remove the final `()`",
+                    String::new(),
+                    Applicability::MachineApplicable,
+                );
+
```
Comment (flip1995) [inline clippy_lints/src/returns.rs:294]:
```suggestion
```

File: clippy_lints/src/utils/diagnostics.rs [hunk 30]
```diff
@@ -62,12 +62,23 @@ pub fn span_lint<T: LintContext>(cx: &T, lint: &'static Lint, sp: impl Into<Mult
...
+) {
+    cx.struct_span_lint(lint, span, |ldb| {
+        let mut db = ldb.build(msg);
+        if let Some(help_span) = help_span {
+            db.span_help(help_span, help);
+        } else {
+            db.help(help);
+        }
+        docs_link(&mut db, lint);
+        db.emit();
```
Comment (flip1995) [inline clippy_lints/src/utils/diagnostics.rs:81]:
```suggestion
    cx.struct_span_lint(lint, span, |diag| {
        let mut diag = diag.build(msg);
        if let Some(help_span) = help_span {
            diag.span_help(help_span, help);
        } else {
            diag.help(help);
        }
        docs_link(&mut diag, lint);
        diag.emit();
```

File: clippy_lints/src/utils/diagnostics.rs [hunk 31]
```diff
@@ -97,15 +108,15 @@ pub fn span_lint_and_note<'a, T: LintContext>(
...
     note: &str,
 ) {
-    cx.struct_span_lint(lint, span, |diag| {
-        let mut diag = diag.build(msg);
-        if note_span == span {
-            diag.note(note);
+    cx.struct_span_lint(lint, span, |ldb| {
+        let mut db = ldb.build(msg);
+        if let Some(note_span) = note_span {
+            db.span_note(note_span, note);
```
Comment (flip1995) [inline clippy_lints/src/utils/diagnostics.rs:117]:
```suggestion
    cx.struct_span_lint(lint, span, |diag| {
        let mut diag = diag.build(msg);
        if let Some(note_span) = note_span {
            diag.span_note(note_span, note);
```

File: clippy_lints/src/utils/diagnostics.rs [hunk 32]
```diff
@@ -97,15 +108,15 @@ pub fn span_lint_and_note<'a, T: LintContext>(
...
         } else {
-            diag.span_note(note_span, note);
+            db.note(note);
```
Comment (flip1995) [inline clippy_lints/src/utils/diagnostics.rs:119]:
```suggestion
            diag.note(note);
```

File: clippy_lints/src/utils/internal_lints.rs [hunk 33]
```diff
@@ -142,6 +145,67 @@ declare_clippy_lint! {
...
+    ///     db.span_help(expr.span, help_msg);
+    /// });
+    /// span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |db| {
+    ///     db.help(help_msg);
+    /// });
+    /// span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |db| {
+    ///     db.span_note(expr.span, note_msg);
+    /// });
+    /// span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |db| {
+    ///     db.note(note_msg);
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs:184]:
```suggestion
    /// span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |diag| {
    ///     diag.span_suggestion(
    ///         expr.span,
    ///         help_msg,
    ///         sugg.to_string(),
    ///         Applicability::MachineApplicable,
    ///     );
    /// });
    /// span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |diag| {
    ///     diag.span_help(expr.span, help_msg);
    /// });
    /// span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |diag| {
    ///     diag.help(help_msg);
    /// });
    /// span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |diag| {
    ///     diag.span_note(expr.span, note_msg);
    /// });
    /// span_lint_and_then(cx, TEST_LINT, expr.span, lint_msg, |diag| {
    ///     diag.note(note_msg);
```

File: clippy_lints/src/utils/internal_lints.rs [hunk 34]
```diff
@@ -195,8 +259,8 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for LintWithoutLintPass {
                     if let ExprKind::AddrOf(_, _, ref inner_exp) = expr.kind;
                     if let ExprKind::Struct(_, ref fields, _) = inner_exp.kind;
                     let field = fields.iter()
-                                      .find(|f| f.ident.as_str() == "desc")
-                                      .expect("lints must have a description field");
+                    .find(|f| f.ident.as_str() == "desc")
+                    .expect("lints must have a description field");
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs:263]:
```suggestion
                        .find(|f| f.ident.as_str() == "desc")
                        .expect("lints must have a description field");
```

File: clippy_lints/src/utils/internal_lints.rs [hunk 35]
```diff
@@ -195,8 +259,8 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for LintWithoutLintPass {
                     if let ExprKind::AddrOf(_, _, ref inner_exp) = expr.kind;
                     if let ExprKind::Struct(_, ref fields, _) = inner_exp.kind;
                     let field = fields.iter()
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs:261]:
```suggestion
                    let field = fields
                        .iter()
```

File: clippy_lints/src/utils/internal_lints.rs [hunk 36]
```diff
@@ -332,13 +396,14 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for CompilerLintFunctions {
             if let Some(sugg) = self.map.get(&*fn_name.as_str());
             let ty = walk_ptrs_ty(cx.tables.expr_ty(&args[0]));
             if match_type(cx, ty, &paths::EARLY_CONTEXT)
-                || match_type(cx, ty, &paths::LATE_CONTEXT);
+            || match_type(cx, ty, &paths::LATE_CONTEXT);
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs:399]:
```suggestion
                || match_type(cx, ty, &paths::LATE_CONTEXT);
```

File: clippy_lints/src/loops.rs [hunk 37]
```diff
@@ -2471,45 +2473,53 @@ fn check_needless_collect<'a, 'tcx>(expr: &'tcx Expr<'_>, cx: &LateContext<'a, '
...
+                        NEEDLESS_COLLECT,
+                        span,
+                        NEEDLESS_COLLECT_MSG,
+                        |db| {
+                            let (arg, pred) = if contains_arg.starts_with('&') {
+                                ("x", &contains_arg[1..])
+                            } else {
+                                ("&x", &*contains_arg)
+                            };
+                            db.span_suggestion(
```
Comment (flip1995) [inline clippy_lints/src/loops.rs:2512]:
```suggestion
                        |diag| {
                            let (arg, pred) = if contains_arg.starts_with('&') {
                                ("x", &contains_arg[1..])
                            } else {
                                ("&x", &*contains_arg)
                            };
                            diag.span_suggestion(
```

File: clippy_lints/src/utils/internal_lints.rs [hunk 38]
```diff
@@ -165,7 +229,7 @@ impl EarlyLintPass for ClippyLintsInternal {
                                         CLIPPY_LINTS_INTERNAL,
                                         item.span,
                                         "this constant should be before the previous constant due to lexical \
-                                         ordering",
+                                        ordering",
```
Comment (flip1995) [inline clippy_lints/src/utils/internal_lints.rs:232]:
```suggestion
                                         ordering",
```

**Comment by flip1995** [comment]
@xiongmao86 Thanks for all the work! There were only some formatting errors, which could be fixed in the GH UI, so I did this myself (don't want to bother you more, after all the work).

@bors r+

**Comment by xiongmao86** [comment]
@flip1995, sorry I have appear to be urging to finish, I couldn't help, I try to inhabit the urge and after several pr it have been less intense. 

And I really don't understand why my local branch build is successful and the ci build would fail.

I have pull upstream master, and then I passed `cargo test`, and after that I push to origin.

I think in this case I couldn't possible to fail to build unless due to updating of rust repo (in this case I have to wait for another rustup pr).

If it is due to the change of function signature with out corresponding change in function body. Why would my local build successful?

If it is due to the delay of upstream master update after my push to origin, then github should have warn about that recent change stop the code from merging.

Did I make any mistake? Please tell me, I appreciate any opportunity to learn.

**Comment by flip1995** [comment]
Recently every occurrence of `|db|` was renamed to `|diag|`. But you didn't have that change in your local checkout. When you then changed the wrapper functions you changed the old version with `|db|`. In one function you didn't have to change the last two lines, so they stayed untouched.

Upstream:
```rust
docs_link(&mut diag, lint);
diag.emit();
```

Local:
```rust
docs_link(&mut db, lint);
db.emit();
```

Now Git(Hub) calculates the diff locally only per commit on your local branch, so the `diag` change didn't show up. On PRs the diff is calculated to the upstream master branch. Since no commit touched these two lines on your branch, they didn't got changed, but CI always runs on the changes as if the PR was already merged. So both your changes (with `|db|`) and the upstream changes (with `|diag|`) were included in the code that got checked by the CI. 

I hope I have explained this good enough. I don't think, that I ever saw that subtle of an interaction of non-conflicting git changes.

**Comment by flip1995** [comment]
If the CI fails, but your local build is successful, most of the time a rebase helps.

**Comment by xiongmao86** [comment]
I have the idea now. It's a long pr. Thank you very much for helping.
