### PR TITLE
Fix `unnecessary_to_owned` interaction with macro expansion

### LINKED ISSUE #12821: `unnecessary_to_owned` suggestion cause error when interacting with `println!` macro
### Summary

Clippy thinks the left curly bracket `{` in `println!("{c}")` is an `&`.

### Lint Name

unnecessary_to_owned

### Reproducer

I tried this code:

```rust
fn main() {
    let v: Vec<_> = "hello".chars().collect();
    for c in v.iter().cloned() {
        println!("{c}");
    }
}
```

I saw this happen:

```rust
warning: unnecessary use of `cloned`
 --> src\main.rs:3:14
  |
3 |     for c in v.iter().cloned() {
  |              ^^^^^^^^^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_to_owned
  = note: `#[warn(clippy::unnecessary_to_owned)]` on by default
help: use
  |
3 |     for c in v.iter() {
  |              ~~~~~~~~
help: remove this `&`
  |
4 -         println!("{c}");
4 +         println!("c}");
  |
```

I expected to see this happen:

Do not suggest to remove the `&`.

### Version

```text
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: x86_64-pc-windows-msvc
release: 1.75.0
LLVM version: 17.0.6
```

### Additional Labels

@rustbot label I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by mdm**
fixes #12821 

In the case of an unnecessary `.iter().cloned()`, the lint `unnecessary_to_owned` might suggest to remove the `&` from references without checking if such references are inside a macro expansion. This can lead to unexpected behavior or even broken code if the lint suggestion is applied blindly. See issue #12821 for an example.

This PR checks if such references are inside macro expansions and skips this part of the lint suggestion in these cases.

changelog: [`unnecessary_to_owned`]: Don't suggest to remove `&` inside macro expansion

### CODE REVIEW

File: clippy_lints/src/methods/unnecessary_iter_cloned.rs [hunk 1]
```diff
@@ -124,6 +124,9 @@ pub fn check_for_loop_iter(
                 };
                 diag.span_suggestion(expr.span, "use", snippet, applicability);
                 for addr_of_expr in addr_of_exprs {
+                    if addr_of_expr.span.from_expansion() {
```
[the remark this answers is not in the document]
Comment (y21) [reply clippy_lints/src/methods/unnecessary_iter_cloned.rs:127]: ... I think even better would be to store a `Vec<(Span, String)>` in the visitor directly and then simply call `diag.multipart_suggestion()` here once with that vec as an argument.

A multipart suggestion would be better than what it is currently doing with repeated `diag.span_suggestion` anyway because it would avoid duplicating the same help message multiple times.

File: clippy_lints/src/methods/utils.rs [hunk 2]
```diff
@@ -142,8 +143,12 @@ impl<'cx, 'tcx> Visitor<'tcx> for CloneOrCopyVisitor<'cx, 'tcx> {
         if self.is_binding(expr) {
             if let Some(parent) = get_parent_expr(self.cx, expr) {
                 match parent.kind {
-                    ExprKind::AddrOf(BorrowKind::Ref, Mutability::Not, _) => {
-                        self.addr_of_exprs.push(parent);
+                    ExprKind::AddrOf(BorrowKind::Ref, Mutability::Not, referent) => {
+                        if !parent.span.from_expansion()
+                            && let Ok(snippet) = self.cx.sess().source_map().span_to_snippet(referent.span)
```
Comment (mdm) [inline clippy_lints/src/methods/utils.rs:148]: I'm not sure if this is the best way to convert the span to source code. Feel free to suggest a more suitable way.

Comment (y21) [reply clippy_lints/src/methods/utils.rs:148]: That could work, but we can also take the span of the `&` with `parent.span.with_hi(referent.lo())` [like before](https://github.com/rust-lang/rust-clippy/blob/5aae5f6ae6b4ba0e6ddadea43e6a2bcadcaa2328/clippy_lints/src/methods/unnecessary_iter_cloned.rs#L129) and use the empty string for the suggestion (to remove it). That would probably make this a bit simpler

**Review by y21 — APPROVED** [review]

**Comment by y21** [comment]
Nice improvement, thanks!

@bors r+
