### PR TITLE
needless_doctest_main: handle correctly parse errors

### LINKED ISSUE #6022: clippy fails to check project but no error shown, due to doc comment
EDIT: reduced even further by  `@keiichiw`
````rust


/// ```
/// 'a()'
/// ```
fn main() {}
````
----------------------
````
git clone https://github.com/rust-lang/cargo
cd cargo
git checkout 875e0123259b0b6299903fe4aea0a12ecde9324f
cargo check --all-features --all-targets
find . | grep \.rs$ | xargs touch
cargo clippy --all-features --all-targets
````
This throws an error on my machine but it does not say what the actual problem is, as if something was eating the error message:

````
    Checking cargo-test-support v0.1.0 (/home/matthias/vcs/github/cargo/crates/cargo-test-support)
warning: calling `push_str()` using a single-character string literal
   --> src/bin/cargo/cli.rs:121:5
    |
121 |     version_string.push_str("\n");
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using `push` with a character literal: `version_string.push('\n')`
    |
    = note: `#[warn(clippy::single_char_push_str)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_char_push_str

warning: 1 warning emitted

warning: unneeded `return` statement
   --> crates/cargo-test-support/src/cross_compile.rs:219:13
    |
219 |             return true;
    |             ^^^^^^^^^^^^ help: remove `return`: `true`
    |
    = note: `#[warn(clippy::needless_return)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return

warning: unneeded `return` statement
   --> crates/cargo-test-support/src/cross_compile.rs:222:13
    |
222 |             return false;
    |             ^^^^^^^^^^^^^ help: remove `return`: `false`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return

warning: unneeded `return` statement
   --> crates/cargo-test-support/src/cross_compile.rs:226:9
    |
226 |         return true;
    |         ^^^^^^^^^^^^ help: remove `return`: `true`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return

warning: 3 warnings emitted

error: could not compile `cargo-test-support`.

````

I tried `cargo check` but that seems to work and does not throw any errors.

### Meta

```
clippy 0.0.212 (5099914 2020-09-08)


rustc 1.48.0-nightly (5099914a1 2020-09-08)
binary: rustc
commit-hash: 5099914a16a215794ad243df0cc7a05d91d168e0
commit-date: 2020-09-08
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

### PR DESCRIPTION
**Pull request by ebroto**
Before this change, finding an error when parsing a doctest would make Clippy exit without emitting an error. Now we properly catch a fatal error and ignore it.

Also, if a doctest specifies an edition in the info line, it will be used when parsing it.

changelog: needless_doctest_main: handle correctly parse errors

Fixes #6022

### CODE REVIEW

File: clippy_lints/src/doc.rs [hunk 1]
```diff
@@ -400,13 +401,21 @@ fn check_doc<'a, Events: Iterator<Item = (pulldown_cmark::Event<'a>, Range<usize
...
             Start(CodeBlock(ref kind)) => {
                 in_code = true;
                 if let CodeBlockKind::Fenced(lang) = kind {
-                    is_rust =
-                        lang.is_empty() || !lang.contains("ignore") && lang.split(',').any(|i| RUST_CODE.contains(&i));
+                    let infos = lang.split(',').collect::<Vec<_>>();
+                    is_rust = !infos.iter().any(|&i| i == "ignore")
+                        && infos
+                            .iter()
+                            .any(|i| i.is_empty() || i.starts_with("edition") || RUST_CODE.contains(&i));
```
Comment (Manishearth) [inline clippy_lints/src/doc.rs:414]: Can we do these two lines as a single loop? Perhaps written out as a for loop.

Comment (ebroto) [reply clippy_lints/src/doc.rs]: Done! I thought it would be clearer like this since it's just a couple of elements, but in the end the for loop is more readable and efficient :+1:

**Comment by Manishearth** [comment]
@bors r+

thanks!
