### PR TITLE
Fix false positive for `needless_character_iteration` lint

### LINKED ISSUE #12879: needless_character_iteration false positive
[This transformation isn't correct:](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b18e4300bb75c2cf248a272a4a490740)

```rust
fn main() {
    let s = "Beyoncé";
    // EVERY character isn't ascii
    dbg!(s.chars().all(|c| !char::is_ascii(&c)));
    // ANY character isn't ascii
    dbg!(!s.is_ascii());
}
```

```
[src/main.rs:3:5] s.chars().all(|c| !char::is_ascii(&c)) = false
[src/main.rs:4:5] !s.is_ascii() = true
```

_Originally posted by @aDotInTheVoid in https://github.com/rust-lang/rust-clippy/pull/12815#discussion_r1624071498_

CC @GuillaumeGomez

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #12879.

changelog: Fix false positive for `needless_character_iteration` lint

### CODE REVIEW

File: clippy_lints/src/methods/needless_character_iteration.rs [hunk 1]
```diff
@@ -55,16 +59,27 @@ fn handle_expr(
...
+        ExprKind::Unary(UnOp::Not, expr) => handle_expr(cx, expr, first_param, span, before_chars, !revert, is_all),
         ExprKind::Call(fn_path, [arg]) => {
             if let ExprKind::Path(path) = fn_path.kind
                 && let Some(fn_def_id) = cx.qpath_res(&path, fn_path.hir_id).opt_def_id()
                 && match_def_path(cx, fn_def_id, &["core", "char", "methods", "<impl char>", "is_ascii"])
                 && path_to_local_id(peels_expr_ref(arg), first_param)
                 && let Some(snippet) = snippet_opt(cx, before_chars)
+                // If we have `!is_ascii`, then only `.any()` should warn. And if the condition is
+                // `is_ascii`, then only `.all()` should warn.
+                && revert != is_all
```
Comment (blyxyas) [inline clippy_lints/src/methods/needless_character_iteration.rs:82]: Could you lift this to avoid running the expensive conditions unnecessarily? (Same with the other condition)

**Review by blyxyas — CHANGES_REQUESTED** [review]
Just some optimization, and this should be ready!

File: clippy_lints/src/methods/needless_character_iteration.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply clippy_lints/src/methods/needless_character_iteration.rs:82]: Good point!

**Comment by GuillaumeGomez** [comment]
Moved the condition sooner for better performance as suggested.

**Review by blyxyas — APPROVED** [review]
LGTM, thanks! :heart:
