### PR TITLE
fix: `map_entry` FP on struct member

### LINKED ISSUE #13934: Compile error after applying `clippy::map_entry`
### Summary

After applying a `clippy::map_entry` suggested fix, the generated code fails to compile.  Clippy appears unable to see uses of the given map from within method calls on the same struct.

### Lint Name

clippy::map_entry

### Reproducer

I tried this code:

```rust
use std::collections::HashMap;

struct Member {}

pub struct Foo {
    members: HashMap<u8, Member>,
}

impl Foo {
    pub fn bar(&mut self, input: u8) -> Result<(), String> {
        if self.members.contains_key(&input) {
            Err("already exists".to_string())
        } else {
            self.other();
            self.members.insert(input, Member {});
            Ok(())
        }
    }

    fn other(&self) {
        for key in self.members.keys() {
            println!("key: {}", key);
        }
    }
}
```

I saw this happen:

```
    Checking playground v0.0.1 (/playground)
warning: usage of `contains_key` followed by `insert` on a `HashMap`
  --> src/lib.rs:11:9
   |
11 | /         if self.members.contains_key(&input) {
12 | |             Err("already exists".to_string())
13 | |         } else {
14 | |             self.other();
15 | |             self.members.insert(input, Member {});
16 | |             Ok(())
17 | |         }
   | |_________^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_entry
   = note: `#[warn(clippy::map_entry)]` on by default
help: try
   |
11 ~         if let std::collections::hash_map::Entry::Vacant(e) = self.members.entry(input) {
12 +             self.other();
13 +             e.insert(Member {});
14 +             Ok(())
15 +         } else {
16 +             Err("already exists".to_string())
17 +         }
   |

warning: `playground` (lib) generated 1 warning (run `cargo clippy --fix --lib -p playground` to apply 1 suggestion)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.46s
```

When applied to the original code, this suggestion fails to compile with this error:
```
Compiling playground v0.0.1 (/playground)
error[E0502]: cannot borrow `*self` as immutable because it is also borrowed as mutable
  --> src/lib.rs:12:14
   |
11 |         if let std::collections::hash_map::Entry::Vacant(e) = self.members.entry(input) {
   |                                                               ------------ mutable borrow occurs here
12 |              self.other();
   |              ^^^^ immutable borrow occurs here
13 |              e.insert(Member {});
   |              - mutable borrow later used here

For more information about this error, try `rustc --explain E0502`.
error: could not compile `playground` (lib) due to 1 previous error
```

I expected to see this happen:
I expect clippy to not make this suggestion at all.

### Version

```text
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: aarch64-apple-darwin
release: 1.83.0
LLVM version: 19.1.1
```

### Additional Labels

@rustbot label +l-suggestion-causes-error

### PR DESCRIPTION
**Pull request by profetia**
fixes #13934 

I modified the part for checking if the map is used so that it can check field and index exprs.

changelog: [`map_entry`]: fix FP on struct member

### CODE REVIEW

**Comment by profetia** [comment]
r? clippy

File: clippy_lints/src/entry.rs [hunk 1]
```diff
@@ -562,6 +562,11 @@ impl<'tcx> Visitor<'tcx> for InsertSearcher<'_, 'tcx> {
     }
 }
 
+fn is_map_or_parent_used(cx: &LateContext<'_>, map: &Expr<'_>, expr: &Expr<'_>) -> bool {
+    SpanlessEq::new(cx).eq_expr(map, expr)
+        || matches!(map.kind, ExprKind::Field(inner, _) | ExprKind::Index(inner, _, _) if is_map_or_parent_used(cx, inner, expr))
+}
+
```
Comment (Centri3) [inline clippy_lints/src/entry.rs:569]: I believe `for_each_expr` would be nicer.

Note this usage of `||` is clever but hard to read.

Also, can you try to document this function a bit? My initial 2min look leaves me a bit confused on mostly the name. I'm not sure if it's misleading or I'm missing context not present in the diff.

I can reroll or look closer later but I believe just the refactoring I've suggested is what this needs.

Comment (profetia) [reply clippy_lints/src/entry.rs]: done

File: clippy_lints/src/entry.rs [hunk 2]
```diff
@@ -562,6 +564,19 @@ impl<'tcx> Visitor<'tcx> for InsertSearcher<'_, 'tcx> {
     }
 }
 
+/// Check if the given expression is used for each sub-expression in the given map.
+/// For example, in map `a.b.c.my_map`, The expression `a.b.c.my_map`, `a.b.c`, `a.b`, and `a` are
+/// all checked.
+fn is_each_expr_in_map_used<'tcx>(cx: &LateContext<'tcx>, map: &'tcx Expr<'tcx>, expr: &'tcx Expr<'tcx>) -> bool {
```
Comment (Centri3) [inline clippy_lints/src/entry.rs:570]: `is_any_expr_in_map_used` is closer to what it does, yes?

Comment (profetia) [reply clippy_lints/src/entry.rs]: fair
