### PR TITLE
match_single_binding: Fix invalid suggestion when match scrutinee has side effects

### LINKED ISSUE #7094: Vacuous match body with side-effectful matchee
```rust
fn side_effects() {
    println!("hello there!");
}

fn main() {
    match side_effects() {
        _ => (),
    };
}
```

The clippy error is

```
warning: this match could be replaced by its body itself
 --> src/main.rs:6:5
  |
6 | /     match side_effects() {
7 | |         _ => (),
8 | |     };
  | |_____^ help: consider using the match body instead: `();`
  |
  = note: `#[warn(clippy::match_single_binding)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#match_single_binding
```

But if this fix is automatically applied we lose the side effects. Instead I expect this code to be fixed to

```
    let _ = side_effects();
    // or
    side_effects();
```

### Meta

- `cargo clippy -V`: clippy 0.1.51 (2fd73fab 2021-03-23)
- `rustc -Vv`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-apple-darwin
release: 1.51.0
LLVM version: 11.0.1
```

### PR DESCRIPTION
**Pull request by Y-Nak**
fixes #7094

changelog: `match_single_binding`: Fix invalid suggestion when match scrutinee has side effects

---
`Expr::can_have_side_effects` is used to determine the scrutinee has side effects, while this method is a little bit conservative for our use case. But I'd like to use it to avoid reimplementation of the method and too much heuristics. If you think this is problematic, then I'll implement a custom visitor to address it.

### CODE REVIEW

**Comment by giraffate** [comment]
ping from triage @phansch. Can you have time to review this?

File: clippy_lints/src/matches.rs [hunk 1]
```diff
@@ -1474,15 +1474,34 @@ fn check_match_single_binding<'a>(cx: &LateContext<'a>, ex: &Expr<'a>, arms: &[A
...
+                    snippet_with_applicability(cx, ex.span, "..", &mut applicability),
+                    indent,
+                    snippet_body
+                );
+                span_lint_and_sugg(
+                    cx,
+                    MATCH_SINGLE_BINDING,
+                    expr.span,
+                    "this match could be written as statement sequence",
+                    "consider using statement sequence",
```
Comment (giraffate) [inline clippy_lints/src/matches.rs:1490]:
```suggestion
                    "consider using the scrutinee and body instead",
```

**Comment by Y-Nak** [comment]
Thanks for your review @giraffate! Happy to move forward.

**Review by giraffate — APPROVED** [review]

**Comment by giraffate** [comment]
@bors r+

It looks good, thanks!
