### PR TITLE
Avoid emitting `assigning_clones` when cloned data borrows from the place to clone into

### LINKED ISSUE #12444: assigning_clones: Suggestion conflicts with borrow checker
### Summary

Nightly Clippy started suggesting usage of `clone_into` but applying the suggesting conflicts with the borrow checker because an immutable borrow of the target variable exists. Assigning works because the borrow ends after the clone is done and hence before the assignment.

### Reproducer

I started with the warning:

```console
warning: assigning the result of `ToOwned::to_owned()` may be inefficient
   --> harvester/src/uvp_verbund.rs:169:33
    |
169 | ...                   name = last.to_owned();
    |                       ^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_into()`: `last.clone_into(&mut name)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
```

and after applying the suggestion got:

```console
error[E0502]: cannot borrow `name` as mutable because it is also borrowed as immutable
   --> harvester/src/uvp_verbund.rs:169:49
    |
161 |                         let parts = name.split(", ").collect::<Vec<_>>();
    |                                     ---- immutable borrow occurs here
...
169 |                                 last.clone_into(&mut name);
    |                                      ---------- ^^^^^^^^^ mutable borrow occurs here
    |                                      |
    |                                      immutable borrow later used by call
```

The full code is available [here](https://gitlab.opencode.de/umwelt-info/metadaten/-/blob/e85780d842cac2356e9082a9e889babdb4191e1a/harvester/src/uvp_verbund.rs#L159-L175).

### Version

```text
rustc 1.78.0-nightly (46b180ec2 2024-03-08)
binary: rustc
commit-hash: 46b180ec2452d388c5d9c14009442e2e0beb01d7
commit-date: 2024-03-08
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### LINKED ISSUE #12460: assigning_clones: after fixes were automatically applied the compiler reported errors within these files: – cannot borrow `name` as mutable because it is also borrowed as immutable
### Summary

Since upgrading to the latest nightly I'm seeing this error in my project. I think this was caused by the new lint added in https://github.com/rust-lang/rust-clippy/pull/12077

Output from the sample file included below:

```console
❯ cargo +nightly clippy --color=always --fix --allow-staged
    Checking t-rs v0.1.0 (/tmp/t-rs)
warning: failed to automatically apply fixes suggested by rustc to crate `t_rs`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust-clippy/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0502]: cannot borrow `name` as mutable because it is also borrowed as immutable
 --> src/main.rs:5:38
  |
4 |         if let Some(stripped_name) = name.strip_prefix("baz-") {
  |                                      ---- immutable borrow occurs here
5 |             stripped_name.clone_into(&mut name);
  |                           ---------- ^^^^^^^^^ mutable borrow occurs here
  |                           |
  |                           immutable borrow later used by call

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0502`.
Original diagnostics will follow.

warning: assigning the result of `ToOwned::to_owned()` may be inefficient
 --> src/main.rs:5:13
  |
5 |             name = stripped_name.to_owned();
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_into()`: `stripped_name.clone_into(&mut name)`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
  = note: `#[warn(clippy::assigning_clones)]` on by default

warning: `t-rs` (bin "t-rs") generated 1 warning (run `cargo clippy --fix --bin "t-rs"` to apply 1 suggestion)
warning: failed to automatically apply fixes suggested by rustc to crate `t_rs`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust-clippy/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0502]: cannot borrow `name` as mutable because it is also borrowed as immutable
 --> src/main.rs:5:38
  |
4 |         if let Some(stripped_name) = name.strip_prefix("baz-") {
  |                                      ---- immutable borrow occurs here
5 |             stripped_name.clone_into(&mut name);
  |                           ---------- ^^^^^^^^^ mutable borrow occurs here
  |                           |
  |                           immutable borrow later used by call

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0502`.
Original diagnostics will follow.

warning: `t-rs` (bin "t-rs" test) generated 1 warning (1 duplicate)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.15s
```

### Reproducer

I tried this code:

```rust
fn main() {
    let mut name = "foo".to_owned();
    if name.starts_with("bar") {
        if let Some(stripped_name) = name.strip_prefix("baz-") {
            name = stripped_name.to_owned();
        }
    }
    println!("Name: {name}");
}
```

And I ran:

```shell
cargo +nightly clippy --color=always --fix --allow-staged
```

I expected it to not error, instead I got the output at the top of this issue.

### Version

```text
rustc 1.78.0-nightly (2d24fe591 2024-03-09)
binary: rustc
commit-hash: 2d24fe591f30386d6d5fc2bb941c78d7266bf10f
commit-date: 2024-03-09
host: aarch64-apple-darwin
release: 1.78.0-nightly
LLVM version: 18.1.0
```

### Additional Labels

_No response_

### LINKED ISSUE #12749: assigning_clones: suggestion causes error because of borrowed target
### Summary

When the entity being cloned borrows the former content of the target, the target cannot be replaced using `.clone_into()`.

### Reproducer

I tried this code:

```rust
use std::path::PathBuf;

#[allow(unused)]
fn main() {
    let mut path = PathBuf::from("/a/b/c");
    path = path.components().as_path().to_owned();
}
```

I expected to see this happen: no suggestion

Instead, this happened:

```
warning: assigning the result of `ToOwned::to_owned()` may be inefficient
 --> src/main.rs:6:5
  |
6 |     path = path.components().as_path().to_owned();
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_into()`: `path.components().as_path().clone_into(&mut path)`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
  = note: `#[warn(clippy::assigning_clones)]` on by default
```

Applying the suggestion then leads to:

```
error[E0502]: cannot borrow `path` as mutable because it is also borrowed as immutable
 --> src/main.rs:6:44
  |
6 |     path.components().as_path().clone_into(&mut path);
  |     ----                        ---------- ^^^^^^^^^ mutable borrow occurs here
  |     |                           |
  |     |                           immutable borrow later used by call
  |     immutable borrow occurs here
```

### Version

```text
rustc 1.78.0 (9b00956e5 2024-04-29)
binary: rustc
commit-hash: 9b00956e56009bab2aa15d7bff10916599e3d6d6
commit-date: 2024-04-29
host: x86_64-unknown-linux-gnu
release: 1.78.0
LLVM version: 18.1.2
```

### Additional Labels

@rustbot label I-suggestion-causes-error

### LINKED ISSUE #12757: Clippy demands you violate ownership to satisfy `assigning_clones`
### Summary

I believe this isn't checking to see if it's in any kind of looping structure which makes this kind of lint extremely fallible:
```
   Checking pgrx-sql-entity-graph v0.12.0-alpha.1 (/home/jubilee/tcdi/pgrx/pgrx-sql-entity-graph)
warning: failed to automatically apply fixes suggested by rustc to crate `pgrx_sql_entity_graph`

after fixes were automatically applied the compiler reported errors within these files:

  * pgrx-sql-entity-graph/src/pg_extern/returning.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust-clippy/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0502]: cannot borrow `segments` as mutable because it is also borrowed as immutable
   --> pgrx-sql-entity-graph/src/pg_extern/returning.rs:120:29
    |
107 |                         if let Some(segment) = segments.filter_last_ident("Option") {
    |                                                -------- immutable borrow occurs here
...
120 |                             segments.clone_from(&this_path.path.segments); // recurse deeper
    |                             ^^^^^^^^^----------^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                             |        |
    |                             |        immutable borrow later used by call
    |                             mutable borrow occurs here

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0502`.
Original diagnostics will follow.

warning: assigning the result of `Clone::clone()` may be inefficient
   --> pgrx-sql-entity-graph/src/pg_extern/returning.rs:120:29
    |
120 | ...                   segments = this_path.path.segments.clone(); // recurse deeper
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `clone_from()`: `segments.clone_from(&this_path.path.segments)`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#assigning_clones
    = note: `#[warn(clippy::assigning_clones)]` on by default

warning: `pgrx-sql-entity-graph` (lib test) generated 1 warning (run `cargo clippy --fix --lib -p pgrx-sql-entity-graph --tests` to apply 1 suggestion)
warning: failed to automatically apply fixes suggested by rustc to crate `pgrx_sql_entity_graph`

after fixes were automatically applied the compiler reported errors within these files:

  * pgrx-sql-entity-graph/src/pg_extern/returning.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust-clippy/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0502]: cannot borrow `segments` as mutable because it is also borrowed as immutable
   --> pgrx-sql-entity-graph/src/pg_extern/returning.rs:120:29
    |
107 |                         if let Some(segment) = segments.filter_last_ident("Option") {
    |                                                -------- immutable borrow occurs here
...
120 |                             segments.clone_from(&this_path.path.segments); // recurse deeper
    |                             ^^^^^^^^^----------^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                             |        |
    |                             |        immutable borrow later used by call
    |                             mutable borrow occurs here

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0502`.
Original diagnostics will follow.

warning: `pgrx-sql-entity-graph` (lib) generated 1 warning (1 duplicate)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 4.20s
```

### Reproducer

The source is here:

https://github.com/pgcentralfoundation/pgrx/blob/beb79011a377bb96c34fcc50ae2d652aa1419eb5/pgrx-sql-entity-graph/src/pg_extern/returning.rs#L107-L120

### Version

```text
rustc 1.78.0 (9b00956e5 2024-04-29)
binary: rustc
commit-hash: 9b00956e56009bab2aa15d7bff10916599e3d6d6
commit-date: 2024-04-29
host: x86_64-unknown-linux-gnu
release: 1.78.0
LLVM version: 18.1.2
```

### Additional Labels

@rustbot label: +I-suggestion-causes-error

### LINKED ISSUE #12929: Strange clippy suggestion for `clone_from`
### Description

```rust
use std::{fs::File, io::{BufReader, BufRead}};

fn main() -> std::io::Result<()> {
    let file = File::open("/dev/random")?;
    let mut rand_buf = BufReader::new(file);
    let mut rand_utf8_str = String::new();

    while rand_buf.read_line(&mut rand_utf8_str).is_err() {}
    if let Some(val) = rand_utf8_str.strip_suffix('\n') { // immutable borrow occurs here
        // clippy suggest me to change it
        val.clone_into(&mut rand_utf8_str); // can not compile, why is this suggested?
        // rand_utf8_str = val.to_owned(); // it is the original writing, can compile
    }

    println!("random utf8 string: {:?}", rand_utf8_str);

    Ok(())
 }
```

```shell
cargo clippy -- -D warnings
```

### Version

```text
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by y21**
Fixes #12444 
Fixes #12460
Fixes #12749
Fixes #12757
Fixes #12929

I think the documentation for the function should describe what- and how this is fixing the issues well.
It avoids emitting a warning when the data being cloned borrows from the place to clone into, which is information that we can get from `PossibleBorrowerMap`. Unfortunately, it is a tiny bit tedious to match on the MIR like that and I'm not sure if this is possibly relying a bit too much on the exact MIR lowering for assignments.

Things left to do:
- [x] Handle place projections (or verify that they work as expected)
- [x] Handle non-`Drop` types

changelog: [`assigning_clones`]: avoid warning when the suggestion would lead to a borrow-check error

### CODE REVIEW

File: tests/ui/assigning_clones.rs [hunk 1]
```diff
@@ -246,3 +246,59 @@ impl<'a> Add for &'a mut HasCloneFrom {
...
+
+        let mut s = (NoDrop, NoDrop);
+        let s2 = &s.0;
+        s.0 = s2.clone();
+
+        // This *could* emit a warning, but PossibleBorrowerMap only works with locals so it
+        // considers `s` fully borrowed
+        let mut s = (NoDrop, NoDrop);
+        let s2 = &s.1;
+        s.0 = s2.clone();
```
Comment (y21) [inline tests/ui/assigning_clones.rs:291]: This is a false negative now but fixing it seems like it'd require large changes to `PossibleBorrowerMap` to teach it disjoint borrows, but I suppose this FN might be better than a FP

Comment (workingjubilee) [reply tests/ui/assigning_clones.rs:291]: In a sense, a performance lint is about reducing time wasted by the computer, but as human time is more expensive, it's surely more costly to waste human time if no computing performance is likely to be gained in the process.

**Comment by kornelski** [comment]
It would be great to merge this. Even if it's not perfect, it's much better than what has shipped in stable and causing numerous annoyances.

**Review by Alexendoo — APPROVED** [review]

**Comment by Alexendoo** [comment]
@bors r+

It seems reasonable to me, it is relying on the MIR layout a bit but it seems like it would be fairly straightforward to adapt if that ever changes
