### PR TITLE
Fix for issue 6640

### LINKED ISSUE #6640: unnecessary_wraps suggests to unwrap unit instead of omitting return value
I tried this code:

```rust
fn always_ok() -> Result<(), String> {
    Ok(())
}
```

I expected that clippy suggests omitting return value at all:

```rust
fn always_ok() {
}
```

Instead, it suggests returning unit:

```
warning: this function's return value is unnecessarily wrapped by `Result`
  --> src/main.rs:22:1
   |
22 | / fn always_ok() -> Result<(), String> {
23 | |     Ok(())
24 | | }
   | |_^
   |
   = note: `#[warn(clippy::unnecessary_wraps)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_wraps
help: remove `Result` from the return type...
   |
22 | fn always_ok() -> () {
   |                   ^^
help: ...and change the returning expressions
   |
23 |     ()
   |
```

and it's stupid because if you follow the instructions it shows another lint warning:

```
warning: unneeded unit return type
  --> src/main.rs:22:15
   |
22 | fn always_ok() -> () {
   |               ^^^^^^ help: remove the `-> ()`
   |
   = note: `#[warn(clippy::unused_unit)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit

warning: unneeded unit expression
  --> src/main.rs:23:5
   |
23 |     ()
   |     ^^ help: remove the final `()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit

warning: 2 warnings emitted
```

It should suggest omitting return value in the first place.

Tested on [Rust playgound](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4a8f81c008662f29f5fbbba95222cd91)

### Meta

- `cargo clippy -V`: e.g. clippy 0.1.51 (2021-01-19 c5a96fb)
- `rustc 1.51.0-nightly`

### PR DESCRIPTION
**Pull request by pag4k**
*Please write a short comment explaining your change (or "none" for internal only changes)*
changelog: unnecessary_wraps will now suggest to remove unnecessary wrapped return unit type, like Option<()>
fixes #6640

### CODE REVIEW

**Comment by pag4k** [comment]
Note that I added many comments in the lint because it helped me understand the code. I left them there. Please tell me if I should remove them or if they are wrong.

File: clippy_lints/src/unnecessary_wraps.rs [hunk 1]
```diff
@@ -83,22 +85,43 @@ impl<'tcx> LateLintPass<'tcx> for UnnecessaryWraps {
...
             ("Option", &paths::OPTION_SOME)
-        } else if is_type_diagnostic_item(cx, return_ty(cx, hir_id), sym::result_type) {
+        } else if is_type_diagnostic_item(cx, return_ty, sym::result_type) {
             ("Result", &paths::RESULT_OK)
         } else {
             return;
         };
 
+        // Take the first inner type of the Option or Result. If can't, abort.
+        let inner_ty = if_chain! {
```
Comment (pag4k) [inline clippy_lints/src/unnecessary_wraps.rs:99]: This used to be in span_lint_and_then() below. I moved it here to check if the inner type is unit.

File: clippy_lints/src/unnecessary_wraps.rs [hunk 2]
```diff
@@ -110,39 +133,42 @@ impl<'tcx> LateLintPass<'tcx> for UnnecessaryWraps {
         });
 
         if can_sugg && !suggs.is_empty() {
```
Comment (pag4k) [inline clippy_lints/src/unnecessary_wraps.rs:135]: Maybe I don't understand, but it seems that `can_suggest` will only be true if `!suggest.is_empty()`. So the bool is redundant.

File: clippy_lints/src/unnecessary_wraps.rs [hunk 3]
```diff
@@ -110,39 +133,42 @@ impl<'tcx> LateLintPass<'tcx> for UnnecessaryWraps {
...
+                    cx,
+                    UNNECESSARY_WRAPS,
+                    span,
+                    format!(
+                        "this function's return value is unnecessarily wrapped by `{}`",
+                        return_type_label
+                    )
+                    .as_str(),
+                    |diag| {
                         diag.span_suggestion(
```
Comment (pag4k) [inline clippy_lints/src/unnecessary_wraps.rs:158]: This part is now much simpler now that the inner type if found earlier.

File: clippy_lints/src/unnecessary_wraps.rs [hunk 4]
```diff
@@ -110,39 +133,42 @@ impl<'tcx> LateLintPass<'tcx> for UnnecessaryWraps {
...
-                        .skip(1) // skip `std::option::Option` or `std::result::Result`
-                        .take(1) // take the first outermost inner type
-                        .filter_map(|inner| match inner.unpack() {
-                            GenericArgKind::Type(inner_ty) => Some(inner_ty.to_string()),
-                            _ => None,
-                        });
-                    inner_ty.for_each(|inner_ty| {
+            // Issue 6640: If the inner type is Unit, emit lint similar to clippy::unused_unit.
+            if inner_ty.is_unit() {
+                span_lint_and_sugg(
```
Comment (pag4k) [inline clippy_lints/src/unnecessary_wraps.rs:138]: This is basically a copy from `unused_unit`. Should I change it?

File: tests/ui/unnecessary_wraps.stderr [hunk 5]
```diff
@@ -1,9 +1,118 @@
-error[E0282]: type annotations needed
```
Comment (pag4k) [inline tests/ui/unnecessary_wraps.stderr]: I realized after the first commit that there was an error in the test file.

File: clippy_lints/src/unnecessary_wraps.rs [hunk 6]
```diff
@@ -140,7 +140,7 @@ impl<'tcx> LateLintPass<'tcx> for UnnecessaryWraps {
                     UNNECESSARY_WRAPS,
                     fn_decl.output.span(),
                     "unneeded wrapped unit return type",
-                    format!("remove the `-> {}<()>`", return_type_label).as_str(),
+                    format!("remove the `-> {}<[...]>`", return_type_label).as_str(),
```
Comment (pag4k) [inline clippy_lints/src/unnecessary_wraps.rs:143]: I'm not too sure how to write this to be consistent with both Option and Result.

**Review by xFrednet — COMMENTED** [review]
Hey, it's awesome to see a new contributor welcome to clippy :upside_down_face:.

I'm not an official reviewer, so there might be some things which are debatable, but I hope that this answers some of your questions :+1:. Please ask if something is unclear :)

File: clippy_lints/src/unnecessary_wraps.rs (hunk 4 above)
Comment (xFrednet) [reply clippy_lints/src/unnecessary_wraps.rs:138]: You should probably use `span_lint_and_then` here as well because this lint suggests changes at several places:
1. Changing the return type
2. Changing the actual return expression

`span_lint_and_sugg` only works for one suggestion this would leave the return statements unchanged which would lead to syntax errors until the user updates them. `span_lint_and_then` allows a suggesting for the return type and the for the expressions using `multipart_suggestion`.

--- 

I personally would try to reuse the `span_lint_and_then` and just adjust the suggestions and message string according to the case.
1. We change or remove the return type (`type_snippet`)
2. We have a message which is changed according to the suggestion (`type_change`)
3. The generated suggestions are also adapted based on the change so either 
    * `return Some(XYZ);` -> `return XYZ;` (`Some(XYZ)` -> `XYZ`)
    * `return Some(());` -> `return;` (`Some(())` -> ``)

This would allow the `span_lint_and_then` reuse like this:

```rust
let (type_change, type_snippet) = if inner_ty.is_unit() {
    (
        format!("Remove the return declaration like this:"),
        String::new(),
    )
} else {
    (
        format!("remove `{}` from the return type like this:", return_type_label),
        return_type_label.to_string(),
    )
};

let msg = format!("this function's return value is unnecessarily wrapped by `{}`", return_type_label);

span_lint_and_then(
    cx,
    UNNECESSARY_WRAPS,
    span,
    msg.as_str(),
    |diag| {
        diag.span_suggestion(
            fn_decl.output.span(),
            type_change.as_str(),
            type_snippet,
            Applicability::MaybeIncorrect,
        );
        diag.multipart_suggestion(
            "And then change the returning expressions like this:",
            suggs,
            Applicability::MaybeIncorrect,
        );
    },
);
```

That's just my own style, so there might be better ways or some other way which seems cleaner to you. Just use the one you are most comfortable with :upside_down_face:

File: clippy_lints/src/unnecessary_wraps.rs (hunk 2 above)
Comment (pag4k) [reply clippy_lints/src/unnecessary_wraps.rs:135]: Oh I see! Thank you!

File: clippy_lints/src/unnecessary_wraps.rs (hunk 4 above)
Comment (pag4k) [reply clippy_lints/src/unnecessary_wraps.rs:138]: Thank you for the great suggestion. However, there is one thing I am not certain with. One issue I see with using `span_lint_and_then()` for cases like `-> Option<()>`  is that depending on the function, we would have two different kinds of suggestions: 1) `return ();` -> `return;` and 2) `()` -> remove the line. I wonder if we can always propose good suggestions in both cases, especially for 2).

Comment (xFrednet) [reply clippy_lints/src/unnecessary_wraps.rs:138]: We should still notify the user even if they should just remove a line. `multipart_suggestion` can also be used to remove code by just suggesting an empty string. You already use this in the replacement of the `-> Option<()>`. The only thing you would need to adapt is the suggestion generation (Here is the change in pseudo rust):

```rust
// line 110

// Check if all return expression respect the following condition and collect them.
let is_inner_union = inner_ty.is_unit();
let mut suggs = Vec::new();
let can_sugg = find_all_ret_expressions(cx, &body.value, |ret_expr| {
    if_chain! {
        [...]
        then {
            if is_inner_union {
                suggs.push((ret_expr.span, "".to_string()));
            } else {
                suggs.push((ret_expr.span, snippet(cx, args[0].span.source_callsite(), "..").to_string()));
            }
            true
        } else {
            false
        }
    }
});
```

The span is just set to `ret_expr.span`. I **believe** that this would only be the `Some(())` part from `return Some(())`. The suggestion would therefore leave the simple return, and we don't need to handle any special cases. Could you maybe try this? :upside_down_face:

Comment (pag4k) [reply clippy_lints/src/unnecessary_wraps.rs:138]: Thanks again for the great suggestion. I had already started to try that, but I had given up for the above reason.
So it works, but I see two potential issues:
1. For the case with a `return`, it works, but since the white space between it and the return expression is not included in the latter span, I had to hack a function to included it. I works for my tests, but I don't know if it's robust enough:
```rust
// Given an expression, if it parents expression is a return expression, return its span with the
// whitespaces after `return` keyword. For example, if we have `return 1;`, by passing the
// expression `1`, this function would return the span of ` 1`.
pub fn get_ret_expr_span_with_prefix_space(cx: &LateContext<'_>, ret_expr: &Expr<'_>, span: Span) -> Option<Span> {
	if_chain! {
		// Try to get parent expression which would include `return`.
		if let Some(parent_expr) = get_parent_expr(cx, ret_expr);
		// Verify if that expression is ExprKind::Ret.
		if let ExprKind::Ret(_) = parent_expr.kind;
		// Get the parent expression source.
		if let Ok(parent_expr_source) = cx
			.sess()
			.source_map()
			.span_to_snippet(span.with_lo(parent_expr.span.lo()).with_hi(parent_expr.span.hi()));
		// Find "return"
		if let Some(pos) = parent_expr_source.find("return");
		then {
			#[allow(clippy::cast_possible_truncation)]
			Some(parent_expr.span.with_lo(BytePos(parent_expr.span.lo().0 + pos as u32 + 6)))
		} else {
			None
		}
	}
}
```
2. As you said, the empty string does remove the `Some(())`, but it leaves an empty line (see between `Some(());` and `} else {:
```
LL |         return;
LL |     }
LL |     if a {
LL |         Some(());
LL |
LL |     } else {
``` 
Is there a way to remove this? Or is it fine like this?

Comment (xFrednet) [reply clippy_lints/src/unnecessary_wraps.rs:138]: Creating such a function is a valid option and the more I think about it probably also the cleanest option. :+1: 

I would suggest adding it as an util function similar to [`utils::position_before_rarrow`](https://github.com/rust-lang/rust-clippy/blob/2f19f5f0d71833d450f8290bb154c3572ac58d9d/clippy_lints/src/utils/mod.rs#L761-L787). This is probably something that will be reused in the future. You can then use this by 
1. Calling [`utils::line_span`](https://github.com/rust-lang/rust-clippy/blob/2f19f5f0d71833d450f8290bb154c3572ac58d9d/clippy_lints/src/utils/mod.rs#L789-L804) with the expression span.
2. Snipping the returned span. This should then be the entire line as a string.
3. Get the offset with the new util function.
4. Add the offset to the line span.

All of these steps can probably also be done by the util function itself. 

If you want to remove the entire line like you wanted in your example output you can simply use  [`utils::line_span`](https://github.com/rust-lang/rust-clippy/blob/2f19f5f0d71833d450f8290bb154c3572ac58d9d/clippy_lints/src/utils/mod.rs#L789-L804). The visualization will most likely still show the empty line though. The lint has multiple spans with suggestions and is therefor not automatically applicable anyways. The suggestion is therefor only for the user to see which changes should be done :).

Another way would be to suggest a change that includes the second to last statement like this:

```rust
    if {
        println!("Hello world!");
// From here    v
        Some(());
        return Option::Some(());
    }
//  ^ To here
```

The suggestion would then show the suggestion like:
```rust
LL |        Some(());
LL |    }
```

The suggestion is a bit cleaner but the code to get this suggestion a more complicated with more edge cases. These are the options I can think of. It might be worth to ask over on our [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy) channel if you want more suggestions :).

File: clippy_lints/src/unnecessary_wraps.rs (hunk 6 above)
Comment (camsteffen) [reply clippy_lints/src/unnecessary_wraps.rs:143]: You can just say "remove this return type". No need to repeat the code that is shown and underlined.

The current version of the lint says

```text
...and change the returning expressions
```

For the new cases added here, could you just change that message to

```text
...and remove instances of `Some(())`
```

I don't think it's really necessary to detect whether the line needs to be removed. Unless I'm missing something?

If you go with a more "detailed" approach, just make sure there are more test cases to go with it.

File: clippy_lints/src/unnecessary_wraps.rs (hunk 1 above)
Comment (camsteffen) [reply clippy_lints/src/unnecessary_wraps.rs:99]: This is good. You could simplify this a little more and merge it with the code above like this:

```rust
let (return_type_label, path, inner_ty) = if let ty::Adt(def_id, subst) = return_ty.kind() {
    if cx.tcx.is_diagnostic_item(sym::option_type, def_id) {
		    ("Option", .., subst.type_at(0))
	} else if cx.tcx.is_diagnostic_item(sym::result_type, def_id) {
			("Result", .., subst.type_at(0))
	} else {
			return;
	}
}
```

**Review by camsteffen — CHANGES_REQUESTED** [review]
Some minor comments from me. Looks good overall!

File: clippy_lints/src/unnecessary_wraps.rs (hunk 4 above)
Comment (pag4k) [reply clippy_lints/src/unnecessary_wraps.rs:138]: Thank you again for the long reply.
To be honest, I think I prefer leaving an empty line. I am also worried that by trying to remove line, we might hit some weird edge cases. Just removing the the span of the return expression seems much safer even if the suggestion will not be as clean. So if you approve, I'll go this way.
About the utility function, a function `position_after_return()` would just be a call to `find()`, so I'm not sure it would be worth it. I could add this whole function, but I feel it is a bit too sketchy to go in utisl. :-P But you tell me. :-)

File: clippy_lints/src/unnecessary_wraps.rs (hunk 6 above)
Comment (pag4k) [reply clippy_lints/src/unnecessary_wraps.rs:143]: Thank you for you comment! :-)
Just to be certain to understand, are you suggesting that we do not provide suggestions for the body of the function? Is that what you call the detailed approach?

Comment (camsteffen) [reply clippy_lints/src/unnecessary_wraps.rs:143]: I was not very clear. I meant to use `diag.multipart_suggestion(message, suggs, ..)` just like the existing code, but just change the message for the "unit case" that you are adding. By "detailed" approach, I am referring to the new approach for linting the body that you have been discussing above.

File: clippy_lints/src/unnecessary_wraps.rs (hunk 4 above)
Comment (flip1995) [reply clippy_lints/src/unnecessary_wraps.rs:138]: Generally using `ByteOffset`s in suggestions is almost always a bad idea. That is because it almost always assumes a specific formatting of the code. Also it may remove comments. 

In this case I would just suggest to remove the `Some(())` and just keep the empty line. If the user cares about formatting, `rustfmt` will deal with that anyway. If not ¯\\\_(ツ)\_/¯. Formatting shouldn't be a concern for Clippy.

---

I also thought about adding a utils function, that produces a suggestion to remove an entire line before. But then I found this case:

```rust
if xyz { Some(()) } else { Err(()) }
```

which is valid formatting according to `rustfmt` with some configurations. Just removing the entire line or everything `rfind("\n")` would break the code.

**Comment by Manishearth** [comment]
@bors delegate=camsteffen

(You can r+ yourself now)

File: clippy_lints/src/unnecessary_wraps.rs (hunk 4 above)
Comment (pag4k) [reply clippy_lints/src/unnecessary_wraps.rs:138]: Thank you for the comment.
Yes, I was a bit uncomfortable with using `ByteOffset`. However, without it, I don't know if there is a way to avoid suggesting replacing `return Some(());` by `return ;`. That white space it annoying. :-P
Any alternative?

Comment (flip1995) [reply clippy_lints/src/unnecessary_wraps.rs:138]: Nope, just ignore that whitespace. Formatting shouldn't be a concern for Clippy.

**Review by camsteffen — CHANGES_REQUESTED** [review]
One nit about the message.

Can you also add a negative test with something like `if true { Ok(()) } else { Err(()) }`?

Otherwise looks good! @Manishearth do you want to do a final review?

File: tests/ui/unnecessary_wraps.stderr [hunk 7]
```diff
@@ -97,10 +97,62 @@ help: remove `Option` from the return type...
...
+...  |
+LL | |     }
+LL | | }
+   | |_^
+   |
+help: remove the return type...
+   |
+LL | fn issue_6640_2(a: bool, b: bool) -> Result<(), i32> {
+   |                                      ^^^^^^^^^^^^^^^
+help: ...and then change the returning expressions
```
[the remark this answers is not in the document]
Comment (pag4k) [reply tests/ui/unnecessary_wraps.stderr:147]: About the new message, you are right, it would be more clear.
I am, however, not sure if I should hard-code the `"Some"` and `"Ok"` strings. I could get the text from the actual return expressions in the body of the function, but we never know how the user could format those.
Is there any alternative to hard-coding and this?

[the remark this answers is not in the document]
Comment (camsteffen) [reply tests/ui/unnecessary_wraps.stderr:147]: I think hard-coding them would be fine since it is just `Some` and `Ok`. I'd also be fine with taking that part out of the message like "remove the returned values".

**Comment by camsteffen** [comment]
Nice first contribution! I'll go ahead and wield my delegated powers.

@bors r+

**Comment by pag4k** [comment]
Thank you so much to everybody for the help and patience. With such a great welcome, I certainly want to contribute more. :-)
