### PR TITLE
Fix `suspicious_xor_used_as_pow.rs` performance

### LINKED ISSUE #11060: Small: Optimize `suspicious_xor_used_as_pow`
The `suspicious_xor_used_as_pow` lint is very poorly done (it was my first lint :heart:!), [this lines in particular](https://github.com/rust-lang/rust-clippy/blob/1990b72e8abde637414a683c24ea46f1dd7f830b/clippy_lints/src/suspicious_xor_used_as_pow.rs#L36-L41), instead of getting the context, it takes a snippet of the code. It's horrible.

If someone could fix it, it would improve a lot that lint's performance!

cc @Centri3 Maybe interesting for you?

### PR DESCRIPTION
**Pull request by blyxyas**
The original `suspicious_xor_used_as_pow` lint had poor performance, so I fixed that + a little refactor so that module is readable.

**107 millis. -> 106 millis.** Using `SPEEDTEST` on Rust's VMs

fix #11060 
changelog: [`suspicious_xor_used_as_pow`]: Improve performance by 0.934%

### CODE REVIEW

File: clippy_lints/src/suspicious_xor_used_as_pow.rs [hunk 1]
```diff
@@ -34,21 +36,20 @@ impl LateLintPass<'_> for ConfusingXorAndPow {
...
+            NumericLiteral::from_lit_kind(&snippet(cx, lit_right.span, ".."), &lit_right.node).is_some_and(|x| x.is_decimal())
+            {
+                span_lint_and_sugg(
+                    cx,
+                    SUSPICIOUS_XOR_USED_AS_POW,
+                    expr.span,
+                    "`^` is not the exponentiation operator",
+                    "did you mean to write",
+                    format!("{}.pow({})", lit_left
+                    .node, lit_right.node),
```
Comment (xFrednet) [inline clippy_lints/src/suspicious_xor_used_as_pow.rs:50]: NIT: This format is a little weird. rustfmt sadly doesn't work in functions that have `if-let` chains in them. Can you fix this?

File: clippy_lints/src/suspicious_xor_used_as_pow.rs [hunk 2]
```diff
@@ -34,21 +36,20 @@ impl LateLintPass<'_> for ConfusingXorAndPow {
...
-					        SUSPICIOUS_XOR_USED_AS_POW,
-					        expr.span,
-					        "`^` is not the exponentiation operator",
-					        "did you mean to write",
-					        format!("{}.pow({})", left_val.format(), right_val.format()),
-					        Applicability::MaybeIncorrect,
-					    );
+            matches!(lit_right.node, LitKind::Int(..) | LitKind::Float(..)) &&
+            matches!(lit_left.node, LitKind::Int(..) | LitKind::Float(..)) &&
+            NumericLiteral::from_lit_kind(&snippet(cx, lit_right.span, ".."), &lit_right.node).is_some_and(|x| x.is_decimal())
```
Comment (xFrednet) [inline clippy_lints/src/suspicious_xor_used_as_pow.rs:41]: Is it intentional, that you only check the `is_decimal` for one of the nodes?

File: clippy_lints/src/suspicious_xor_used_as_pow.rs [hunk 3]
```diff
@@ -34,21 +36,20 @@ impl LateLintPass<'_> for ConfusingXorAndPow {
             left.span.ctxt() == right.span.ctxt() &&
```
Comment (xFrednet) [inline clippy_lints/src/suspicious_xor_used_as_pow.rs:36]: Since this was your first lint, I'll also be a bit more nitpicky :wink: 

Can you fix the formatting, to have the && before the condition and not at the end of the line and also remove the tab character in line 34?

**Review by xFrednet — APPROVED** [review]
Looks good to me, just two tiny nits and a question. If the question is interional, you can also r=me afterwards :)

File: clippy_lints/src/suspicious_xor_used_as_pow.rs (hunk 2 above)
Comment (blyxyas) [reply clippy_lints/src/suspicious_xor_used_as_pow.rs:41]: I kinda feel like it's intentional. It doesn't really make sense to check if the left value is decimal, as in mathematical notation the `^` symbol speaks more about the right value than the left.
