### PR TITLE
Fix missing_const_for_fn false positive

### LINKED ISSUE #4449: Wrong suggestion of `const fn` if type implements Drop
Hello together,

The following code snippet (in `src/lib.rs`):
```rust
pub struct A;
impl A {
    #![warn(clippy::missing_const_for_fn)]
    pub fn a(self) -> B {
        B
    }
}
impl Drop for A {
    fn drop(&mut self) {}
}

pub struct B;
```
leads to this suggestion:
```
warning: this could be a const_fn
 --> src/lib.rs:4:5
  |
4 | /     pub fn a(self) -> B {
5 | |         B
6 | |     }
  | |_____^
  |
note: lint level defined here
 --> src/lib.rs:3:13
  |
3 |     #![warn(clippy::missing_const_for_fn)]
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn
```
but the suggested fix (i.e. add the `const` qualifier) is wrong. After the fix the following error occurs:
```
error[E0493]: destructors cannot be evaluated at compile-time
 --> src/lib.rs:4:20
  |
4 |     pub const fn a(self) -> B {
  |                    ^^^^ constant functions cannot evaluate destructors

error: aborting due to previous error
```

# Meta
```
$ cargo clippy -V
clippy 0.0.212 (e3cb40e 2019-06-25)

$ rustc --version
rustc 1.37.0 (eae3437df 2019-08-13)
```

### PR DESCRIPTION
**Pull request by phansch**
We don't want to lint if the type of the method implements drop.
(constant functions cannot evaluate destructors)

changelog: Fix `missing_const_for_fn` false positive

Fixes #4449

### CODE REVIEW

File: tests/ui/missing_const_for_fn/cant_be_const.rs [hunk 1]
```diff
@@ -68,3 +68,16 @@ impl std::ops::Add for Point {
         Point(self.0 + other.0, self.1 + other.1)
     }
 }
+
+pub struct A;
+impl A {
+    // This should not be const because the type implements `Drop`.
+    pub fn a(self) -> B {
+        B
+    }
```
Comment (flip1995) [inline tests/ui/missing_const_for_fn/cant_be_const.rs]: The same problem exists, if another argument of the function implements `Drop`. I think every argument needs to be checked.

```rust
impl B {
    pub fn b(self, c: C) -> B {
        B
    }
}

pub struct C;
impl Drop for C { fn drop(&mut self) {} }
```

Comment (phansch) [reply tests/ui/missing_const_for_fn/cant_be_const.rs]: Oh right, that makes sense! I will have another look tomorrow :+1:

Comment (jfrimmel) [reply tests/ui/missing_const_for_fn/cant_be_const.rs]: Just as a note: this behavior is only true for arguments, that are moved into a function/method. References to types with `Drop` are perfectly okay (both for `self` and other parameters)

**Comment by phansch** [comment]
The lint now checks all arguments for types that implement `Drop`. Should be ready for another review.

**Comment by phansch** [comment]
Apparently I forgot to commit the updated .stderr, will do that later today :man_facepalming:
