### PR TITLE
`default_numeric_fallback`: Fix FP with floating literal

### LINKED ISSUE #7445: FP: `default_numeric_fallback` with floating literal
Lint name: `default_numeric_fallback`

I tried this code:

```rust
#![deny(clippy::default_numeric_fallback)]

fn foo(_f: f64) {}

fn main() {
    foo(12.0);
}
```

I expected to see this happen: no lint triggered.

Instead, this happened: 
```
error: default numeric fallback might occur
 --> src/main.rs:6:9
  |
6 |     foo(12.0);
  |         ^^^^ help: consider adding suffix: `12.0_f64`
  |
```

### Meta

- `cargo clippy -V`: clippy 0.1.55 (d2b04f0 2021-07-07)
- `rustc -Vv`: 
  ```
  rustc 1.55.0-nightly (d2b04f075 2021-07-07)
  binary: rustc
  commit-hash: d2b04f075c0ce010758c4c8674152ff89d1d73f3
  commit-date: 2021-07-07
  host: x86_64-unknown-linux-gnu
  release: 1.55.0-nightly
  LLVM version: 12.0.1
  ```

### PR DESCRIPTION
**Pull request by Y-Nak**
Fix #7445 

changelog: `default_numeric_fallback`: Fix FP with floating literal

### CODE REVIEW

**Review by xFrednet — COMMENTED** [review]
The changes LGTM.

The FP was a result of tests which only checked for the int type. I've looked through the test file, and it seems to me that the first test cases still miss a float counterpart. Could you also add them as a precaution?

```rs
// in the `basic_expr` module
        let x = [1.0, 2.0, 3.0];
        let x = if true { (1.0, 2.0) } else { (3.0, 4.0) };
        let x = match 1.0 {
            1.0 => 1.0,
            _ => 2.0,
        };
 // in the `nested_local` module
         let x: _ = {
            // Should lint this because this literal is not bound to any types.
            let y = 1.0;

            // Should NOT lint this because this literal is bound to `_` of outer `Local`.
            1.0
        };
```

**Comment by Y-Nak** [comment]
Changes:
1. Add more test cases for floating literal
2. Split the i32 and f64 test cases into their own files, otherwise `cargo dev limit_stderr_length` fails

File: tests/ui/default_numeric_fallback_f64.rs [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+
+mod basic_expr {
+    fn test() {
+        // Should lint unsuffixed literals typed `f64`.
+        let x = 0.12;
+        let x = [1., 2., 3.];
+        let x = if true { (1., 2.) } else { (3., 4.) };
+        let x = match 1. {
+            _ => 1.,
+        };
```
Comment (xFrednet) [inline tests/ui/default_numeric_fallback_f64.rs:21]: NIT: This triggers the `clippy::match_single_binding` lint. Could you allow this lint to keep the file error files to only contain `default_numeric_fallback` lint triggers?

```txt
error: this match could be replaced by its body itself
  --> $DIR/default_numeric_fallback_f64.rs:19:17
   |
LL |           let x = match 1. {
   |  _________________^
LL | |             _ => 1.,
LL | |         };
   | |_________^ help: consider using the match body instead: `1.`
   |
   = note: `-D clippy::match-single-binding` implied by `-D warnings`
```

Comment (Y-Nak) [reply tests/ui/default_numeric_fallback_f64.rs:21]: Good catch! I fixed that.

**Review by xFrednet — APPROVED** [review]
LGTM, thank you for the quick fixes and nice work!

@flip1995 I would hand it over to you now :)

File: tests/ui/default_numeric_fallback_f64.rs [hunk 2]
```diff
@@ -0,0 +1,174 @@
+// aux-build:macro_rules.rs
+
+#![warn(clippy::default_numeric_fallback)]
+#![allow(unused)]
+#![allow(clippy::never_loop)]
+#![allow(clippy::no_effect)]
+#![allow(clippy::unnecessary_operation)]
+#![allow(clippy::branches_sharing_code)]
+#![allow(clippy::branches_sharing_code)]
```
Comment (flip1995) [inline tests/ui/default_numeric_fallback_f64.rs:9]: dup

File: tests/ui/default_numeric_fallback_f64.rs [hunk 3]
```diff
@@ -0,0 +1,174 @@
+// aux-build:macro_rules.rs
```
Comment (flip1995) [inline tests/ui/default_numeric_fallback_f64.rs:1]: Is there a reason, why neither the floating point, nor the integer test are tested with `// run-rustfix`? Looking at the `stderr` files this should be possible.

Could you please test if adding `// run-rustfix` Just Works(tm)?

Comment (Y-Nak) [reply tests/ui/default_numeric_fallback_f64.rs:2]: I just forgot to add them.

File: clippy_lints/src/default_numeric_fallback.rs [hunk 4]
```diff
@@ -80,14 +81,23 @@ impl<'a, 'tcx> NumericFallbackVisitor<'a, 'tcx> {
...
 
-                    let sugg = format!("{}_{}", snippet(self.cx, lit.span, ""), suffix);
+                    let src = if let Some(src) = snippet_opt(self.cx, lit.span){
+                        src
+                    } else {
+                        match lit.node  {
+                            LitKind::Int(src, _) =>format!("{}", src),
+                            LitKind::Float(src, _) => format!("{}", src),
+                            _ => { return; }
+                        }
```
Comment (flip1995) [inline clippy_lints/src/default_numeric_fallback.rs:98]: Formattings:

```suggestion
                    let src = if let Some(src) = snippet_opt(self.cx, lit.span) {
                        src
                    } else {
                        match lit.node {
                            LitKind::Int(src, _) => format!("{}", src),
                            LitKind::Float(src, _) => format!("{}", src),
                            _ => return,
                        }
```

**Comment by Y-Nak** [comment]
Changes:
* Fix `NumericLiteral::format`, there was a possibility of producing invalid literals like `1._f32`
*  Remove duplication of `#![allow(clippy::branches_sharing_code)]`
* Add `// run-rustfix`

**Review by flip1995 — COMMENTED** [review]
One more NIT

File: clippy_lints/src/default_numeric_fallback.rs (hunk 4 above)
Comment (Y-Nak) [reply clippy_lints/src/default_numeric_fallback.rs:98]: Just a question:
Could you tell me how do you find formatting problems inside `if_chain`? Is there a good way to find them inside macros?

Comment (flip1995) [reply clippy_lints/src/default_numeric_fallback.rs]: I don't know of anything that would help here. Maybe implementing formatting rules in `rustfmt` for the if_chain macro. Not sure if that would be accepted there though, since this isn't a std macro.

**Comment by flip1995** [comment]
@bors r=xFrednet,flip1995

Thanks!

File: clippy_lints/src/default_numeric_fallback.rs (hunk 4 above)
Comment (Y-Nak) [reply clippy_lints/src/default_numeric_fallback.rs]: I understand. Thanks for the answer!
