### PR TITLE
[`filter_next`]: suggest making binding mutable if it needs to be

### LINKED ISSUE #10029: filter_next: after fixes were automatically applied the compiler reported errors
### Summary

Clippy suggested a lint to replace `foo.filter().next()` with `foo.find()`. However, it didn't mention anything about requiring `foo` to be mutable.

When I ran `cargo clippy --fix` to automatically apply the lint, it caused a compiler error and told me to file an issue on Github.

[You can view the code here](https://github.com/DarylPinto/advent-of-code-2022/blob/1f8ff55/day04b/src/main.rs#L21-L27), as well as in the `Reproducer` section below.

### Lint Name

filter_next

### Reproducer

I tried this code:

```rust
fn puzzle(input: &str) -> usize {
    input
        .lines()
        .filter(|line| {
            let assignments = line
                .split(',')
                .map(|assignment| {
                    assignment
                        .split('-')
                        .filter_map(|n| n.parse::<i32>().ok())
                        .collect::<Vec<_>>()
                })
                .collect::<Vec<_>>();

            let assignment_one = assignments[0][0]..=assignments[0][1];
            let assignment_two = assignments[1][0]..=assignments[1][1];

            assignment_one
                .filter(|n| assignment_two.contains(n))
                .next()
                .is_some()
        })
        .count()
}
```

I saw this happen:

When I ran `cargo clippy --fix` the following output was written to my terminal:

```
after fixes were automatically applied the compiler reported errors within these files:

  * day04b/src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0596]: cannot borrow `assignment_one` as mutable, as it is not declared as mutable
  --> day04b/src/main.rs:24:13
   |
21 |             let assignment_one = assignments[0][0]..=assignments[0][1];
   |                 -------------- help: consider changing this to be mutable: `mut assignment_one`
...
24 |             assignment_one.find(|n| assignment_two.contains(n))
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0596`.
```

I expected to see one of the following things happen:
- Clippy to apply the lint without causing a compiler error
- Clippy to not suggest this lint at all

### Version

```text
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: aarch64-apple-darwin
release: 1.65.0
LLVM version: 15.0.0
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by y21**
Fixes #10029

changelog: [`filter_next`]: suggest making binding mutable if it needs to be and adjust applicability

### CODE REVIEW

File: clippy_lints/src/methods/filter_next.rs [hunk 1]
```diff
@@ -26,15 +42,30 @@ pub(super) fn check<'tcx>(
...
-                "try this",
-                format!("{iter_snippet}.find({filter_snippet})"),
-                Applicability::MachineApplicable,
-            );
+            span_lint_and_then(cx, FILTER_NEXT, expr.span, msg, |diag| {
+                let (applicability, pat) = if let Some(id) = path_to_local(recv)
+                    && let Some(hir::Node::Pat(pat)) = cx.tcx.hir().find(id)
+                    && let hir::PatKind::Binding(BindingAnnotation(_, Mutability::Not), _, ident, _) = pat.kind
+                {
+                    (Applicability::Unspecified, Some((pat.span, ident)))
```
Comment (y21) [inline clippy_lints/src/methods/filter_next.rs:50]: It can no longer be a machine applicable suggestion if it needs to be made mutable because of cases like these:
```rs
let (Ok(f) | Err(f)) = ...;
f.filter(...).next();
```
There are multiple bindings that would need to be made mutable, but `cx.tcx.hir().find(id)` only returns one pattern.

`iter_skip_next` is doing this as well, so I think having it be unspecified is fine.
https://github.com/rust-lang/rust-clippy/blob/ce0a48a9b66148fdd96fddf585f9e11850861a47/clippy_lints/src/methods/iter_skip_next.rs#L23-L35

**Comment by dswij** [comment]
Can you help to review this? @blyxyas

**Comment by blyxyas** [comment]
Yep, will review it! :cowboy_hat_face:

File: clippy_lints/src/methods/filter_next.rs [hunk 2]
```diff
@@ -26,15 +42,30 @@ pub(super) fn check<'tcx>(
...
+                    expr.span,
+                    "try this",
+                    format!("{iter_snippet}.find({filter_snippet})"),
+                    applicability,
+                );
+
+                if let Some((pat_span, ident)) = pat {
+                    diag.span_help(
+                        pat_span,
+                        format!("you will also need to make `{ident}` mutable, because `find` takes `&mut self`"),
```
Comment (blyxyas) [inline clippy_lints/src/methods/filter_next.rs:65]: Knowing `ident`'s span, I think it would be pretty good if it suggested adding a mut directly (instead of a help message, an `Unspecified` suggestion), it would be just doing some span magic and it would be more illustrative.

(Just an opinion, feel free to ignore, the current version is also good)

**Review by blyxyas — APPROVED** [review]
Just a mini-nit, but it's very good.. Thanks :heart:!

File: clippy_lints/src/methods/filter_next.rs (hunk 2 above)
Comment (y21) [reply clippy_lints/src/methods/filter_next.rs:65]: I tried that before, but that didn't work when there is more than one pattern that introduces the identifier, see this comment: https://github.com/rust-lang/rust-clippy/pull/11016#discussion_r1240422104

File: tests/ui/methods_unfixable.rs [hunk 3]
```diff
@@ -0,0 +1,29 @@
+#![warn(clippy::filter_next)]
+
+fn main() {
+    issue10029::puzzle("");
+}
+
+mod issue10029 {
```
Comment (dswij) [inline tests/ui/methods_unfixable.rs:7]: We can probably make this testcase simpler

File: clippy_lints/src/methods/filter_next.rs [hunk 4]
```diff
@@ -1,13 +1,29 @@
...
 use clippy_utils::ty::implements_trait;
+use rustc_ast::{BindingAnnotation, Mutability};
 use rustc_errors::Applicability;
 use rustc_hir as hir;
 use rustc_lint::LateContext;
 use rustc_span::sym;
 
 use super::FILTER_NEXT;
 
+fn path_to_local(expr: &hir::Expr<'_>) -> Option<hir::HirId> {
```
Comment (dswij) [inline clippy_lints/src/methods/filter_next.rs:12]: We have a `path_to_local` helper in `clippy_utils`. Can we use that here?

File: clippy_lints/src/methods/filter_next.rs (hunk 1 above)
Comment (dswij) [reply clippy_lints/src/methods/filter_next.rs:50]: I gues we can walk the parent to find all the bindings, but that's also not simple. This is good enough for now

File: clippy_lints/src/methods/filter_next.rs (hunk 4 above)
Comment (y21) [reply clippy_lints/src/methods/filter_next.rs:12]: If I remember correctly, `path_to_local` doesn't "work" if the local is reached through field accesses, so for example it would return `false` for `a.b[0]` if given the id of the local `a`, but we need it to return `true`, because we use this logic to figure out if a binding needs to be made mutable, and `a.b[0].find_mut(..)` requires `a` be mutable. Maybe this could be better named or have a comment explaining it.

File: tests/ui/methods_unfixable.rs (hunk 3 above)
Comment (dswij) [reply tests/ui/methods_unfixable.rs]: Reducing it is great since it makes us understand the problem more (not in this case though), but also makes it simpler for others to understand what's happening and what is being tested in case anyone looks at this in the future :smile:

Comment (y21) [reply tests/ui/methods_unfixable.rs]: Ok, fair points, I reduced the test case down to the core problem in the last commit👍

File: clippy_lints/src/methods/filter_next.rs (hunk 4 above)
Comment (blyxyas) [reply clippy_lints/src/methods/filter_next.rs:12]: `clippy_utils::path_to_local` is too primitive in my opinion. It only handles the case where the expression is a Path, and its Res is a `Res::Local`. Maybe we should modify it and make it handle this new cases.

[(`path_to_local`'s source)](https://doc.rust-lang.org/beta/nightly-rustc/src/clippy_utils/lib.rs.html#450-457)

**Review by dswij — APPROVED** [review]

**Comment by dswij** [comment]
Thank you! 

@bors r=blyxyas,dswij
