### PR TITLE
Fix issue #12034: add autofixes for unnecessary_fallible_conversions

### LINKED ISSUE #12034: `unnecessary_fallible_conversions` should be fixable with `cargo fix`
### Description

The warnings generated by `unnecessary_fallible_conversions` are trivial to fix; they even have a suggestion already. it would be nice for it to be machine applicable.

```
error: use of a fallible conversion when an infallible one could be used
   --> src/main.rs:651:30
    |
651 |             Some(val) => u64::try_from(val).expect("Failed to convert val into u64"),
    |                               ^^^^^^^^^^^^^ help: use: `From::from`
```

### Version

```text
clippy 0.1.75 (82e1608d 2023-12-21)
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: aarch64-apple-darwin
release: 1.75.0
LLVM version: 17.0.6
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by roife**
fixes #12034

Currently, the `unnecessary_fallible_conversions` lint was capable of autofixing expressions like `0i32.try_into().unwrap()`. However, it couldn't autofix expressions in the form of `i64::try_from(0i32).unwrap()` or `<i64 as TryFrom<i32>>::try_from(0).unwrap()`.

This pull request extends the functionality to correctly autofix these latter forms as well.

changelog: [`unnecessary_fallible_conversions`]: Add autofixes for more forms

### CODE REVIEW

File: tests/ui/unnecessary_fallible_conversions.rs [hunk 1]
```diff
@@ -3,4 +3,16 @@
 fn main() {
     let _: i64 = 0i32.try_into().unwrap();
     let _: i64 = 0i32.try_into().expect("can't happen");
+
+    let _ = i64::try_from(0i32).unwrap();
```
Comment (PartiallyTyped) [inline tests/ui/unnecessary_fallible_conversions.rs:7]: Hi, thanks for contributing!

This is a slight nit, but could you add annotations to indicate whether that line should be linted? This helps avoid regressions when running `uibless` to account for new tests.

```suggestion
    let _ = i64::try_from(0i32).unwrap();
    //~^ ERROR use of a fallible conversion when an infallible one could be used
```

There are some examples here: 
https://rustc-dev-guide.rust-lang.org/tests/ui.html#error-annotation-examples

And some details here:
https://rustc-dev-guide.rust-lang.org/tests/ui.html#error-annotations

Comment (roife) [reply tests/ui/unnecessary_fallible_conversions.rs:14]: Thank you for reminder! I have added the necessary error annotations and included some additional comments in the tests to make it clearer.

File: clippy_lints/src/methods/unnecessary_fallible_conversions.rs [hunk 2]
```diff
@@ -45,47 +46,80 @@ fn check<'tcx>(
...
+        };
+
+        let qpath_spans = qpath.and_then(|qpath| match qpath {
+            QPath::Resolved(_, path) => {
+                let segments = path.segments.iter().map(|seg| seg.ident).collect::<Vec<_>>();
+                (segments.len() == 2).then(|| vec![segments[0].span, segments[1].span])
+            },
+            QPath::TypeRelative(_, seg) => Some(vec![seg.ident.span]),
+            QPath::LangItem(_, _) => unreachable!("`TryFrom` and `TryInto` are not lang items"),
+        });
```
Comment (PartiallyTyped) [inline clippy_lints/src/methods/unnecessary_fallible_conversions.rs:80]: This is a bit of a nit, and may be unnecessary, but if you return `Option<[&'_ span]>`, I think the matching could be cleaner as you will be matching something like

```
(FunctionKind::TryFromFunction, [from_method_span], Some(unwrap_span)) => todo!(),
(FunctionKind::TryFromFunction, [from_cls_span, from_method_span], Some(unwrap_span)) => todo!(),
_ => unreachable!()
```

which I think would make this a bit cleaner, other than that, I think it's very good and a great addition!

**Review by PartiallyTyped — APPROVED** [review]
Looks good to me, thank you for the auto-fixes!

I think we need to find another reviewer for this though 😅 

@rustbot r? clippy

File: clippy_lints/src/methods/unnecessary_fallible_conversions.rs (hunk 2 above)
Comment (roife) [reply clippy_lints/src/methods/unnecessary_fallible_conversions.rs:80]: Sorry it took me so long to see this comment. I tried this but it introduced too many arms (multiple `FunctionKind::TryFromFunction`s and `FunctionKind::TryIntoFunction`s) and made the code more complicated

Comment (PartiallyTyped) [reply clippy_lints/src/methods/unnecessary_fallible_conversions.rs:80]: I see. I am good then, but I think we still need another reviewer with r perms. Maybe zulip?

File: clippy_lints/src/methods/unnecessary_fallible_conversions.rs [hunk 3]
```diff
@@ -29,6 +29,7 @@ fn check<'tcx>(
     node_args: ty::GenericArgsRef<'tcx>,
     kind: FunctionKind,
     primary_span: Span,
+    qpath: Option<&QPath<'_>>,
```
Comment (Centri3) [inline clippy_lints/src/methods/unnecessary_fallible_conversions.rs:32]: imo this should be stored in `FunctionKind`, in `TryFromFunction` and `TryIntoFunction`, as the path is only passed in those cases (and shouldn't be for a method call)

File: clippy_lints/src/methods/unnecessary_fallible_conversions.rs [hunk 4]
```diff
@@ -45,47 +46,80 @@ fn check<'tcx>(
...
+                (other_ty, self_ty, sugg, Applicability::Unspecified)
+            },
+            (FunctionKind::TryIntoFunction, _, _) => {
+                let sugg = vec![(primary_span, String::from("Into::into"))];
+                (self_ty, other_ty, sugg, Applicability::Unspecified)
+            },
+            (FunctionKind::TryIntoMethod, _, _) => {
+                let sugg = vec![(primary_span, String::from("into"))];
+                (self_ty, other_ty, sugg, Applicability::Unspecified)
             },
```
Comment (Centri3) [inline clippy_lints/src/methods/unnecessary_fallible_conversions.rs:122]: Could we simplify this by adding a method to `FunctionKind` for the suggestion? Something like:
`(other_ty, self_ty, kind.sugg(), Applicability::Unspecified)`.

This applies to `self_ty` and `other_ty` as well, not bc of code duplication but just that it's hard to understand what they are (without scrolling up and seeing `source_ty` and `target_ty`). And the entire match should be extracted tbh

Overall this entire match is a bit of a mess, once I have my desktop back (probably this weekend) I'll take a closer look and try my hand at it. It's pretty hard to understand in its current form.

File: clippy_lints/src/methods/unnecessary_fallible_conversions.rs [hunk 5]
```diff
@@ -45,47 +46,80 @@ fn check<'tcx>(
...
+            },
+            (FunctionKind::TryFromFunction, Some(spans), Some(unwrap_span)) => {
+                let sugg = match spans.len() {
+                    1 => vec![(spans[0], String::from("from")), (unwrap_span, String::new())],
+                    2 => vec![
+                        (spans[0], String::from("From")),
+                        (spans[1], String::from("from")),
+                        (unwrap_span, String::new()),
+                    ],
+                    _ => unreachable!(),
```
Comment (Centri3) [inline clippy_lints/src/methods/unnecessary_fallible_conversions.rs:95]: Can we use destructuring here? As an example:
```suggestion
                let sugg = match &*spans {
                    [first] => vec![(first, String::from("from")), (unwrap_span, String::new())],
                    [first, second] => vec![
                        (first, String::from("From")),
                        (second, String::from("from")),
                        (unwrap_span, String::new()),
                    ],
                    _ => unreachable!(),
```
If you want you could also use an enum to remove the wildcard branch, like: `OneSpan(_)` + `TwoSpans(_, _)`.

File: clippy_lints/src/methods/unnecessary_fallible_conversions.rs [hunk 6]
```diff
@@ -45,47 +46,80 @@ fn check<'tcx>(
...
+        let span = if let Some(unwrap_call) = parent_unwrap_call {
+            primary_span.with_hi(unwrap_call.hi())
+        } else {
+            primary_span
+        };
+
+        let qpath_spans = qpath.and_then(|qpath| match qpath {
+            QPath::Resolved(_, path) => {
+                let segments = path.segments.iter().map(|seg| seg.ident).collect::<Vec<_>>();
+                (segments.len() == 2).then(|| vec![segments[0].span, segments[1].span])
```
Comment (Centri3) [inline clippy_lints/src/methods/unnecessary_fallible_conversions.rs:76]: Iterating then collecting into a `Vec` is not worth doing to not do a field access twice. This also turns our borrowed slice into an owned vector, which I don't think is needed? (Maybe I'm missing something about ownership here - can't check rn.)

Destructuring can be used here as well:
```suggestion
                if let [first, second] = path.segments {
                    Some(first.ident.span, second.ident.span)
                } else {
                    None
                }
```

**Review by Centri3 — COMMENTED** [review]
I'll take a closer look once I can. For now I have a few things to suggest

**Comment by roife** [comment]
> For now I have a few things to suggest

Thanks for your suggestions! I have refactored the code according to your advice: I removed the large match statement, split it into several parts, and separated them into various sub-functions, which made the logic of the code much clearer.

File: clippy_lints/src/methods/unnecessary_fallible_conversions.rs [hunk 7]
```diff
@@ -2,25 +2,79 @@ use clippy_utils::diagnostics::span_lint_and_then;
...
+            FunctionKind::TryIntoFunction(_) => "Into::into",
+            FunctionKind::TryIntoMethod => "into",
+        };
+
+        vec![(primary_span, String::from(replacement))]
+    }
+
+    fn machine_applicable_sugg(&self, primary_span: Span, unwrap_span: Span) -> Vec<(Span, String)> {
+        use FunctionKind::*;
+        use SpansKind::*;
```
Comment (Centri3) [inline clippy_lints/src/methods/unnecessary_fallible_conversions.rs:56]: On top of the wildcard, don't do this (match enum variants or unit structs with a single path segment). If you remove the `TryIntoMethod` (or any unit variant), that will instead be a wildcard pattern binding to the ident "TryIntoMethod", instead of a compiler error

There's an open issue for a lint about this #11440

File: clippy_lints/src/methods/unnecessary_fallible_conversions.rs [hunk 8]
```diff
@@ -2,25 +2,79 @@ use clippy_utils::diagnostics::span_lint_and_then;
...
+
+        let (trait_name, fn_name) = {
+            let (a, b) = match self {
+                TryFromFunction(_) => ("From", "from"),
+                TryIntoFunction(_) | TryIntoMethod => ("Into", "into"),
+            };
+            (a.to_string(), b.to_string())
```
Comment (Centri3) [inline clippy_lints/src/methods/unnecessary_fallible_conversions.rs:63]: nit: Should be `to_owned` (https://users.rust-lang.org/t/to-string-vs-to-owned-for-string-literals/1441/2)

**Review by Centri3 — APPROVED** [review]
Just 2 nits, once dogfood passes this is ready :3

File: clippy_lints/src/methods/unnecessary_fallible_conversions.rs (hunk 7 above)
Comment (roife) [reply clippy_lints/src/methods/unnecessary_fallible_conversions.rs:56]: Thanks for the suggestion. How about using `use FunctionKind as F`?

File: clippy_lints/src/methods/unnecessary_fallible_conversions.rs [hunk 9]
```diff
@@ -2,25 +2,74 @@ use clippy_utils::diagnostics::span_lint_and_then;
...
+    TryFromFunction(Option<SpansKind>),
     /// `t.try_into()`
     TryIntoMethod,
     /// `U::try_into(t)`
-    TryIntoFunction,
+    TryIntoFunction(Option<SpansKind>),
+}
+
+impl FunctionKind {
+    fn applicability(&self, parent_unwrap_call: &Option<Span>) -> Applicability {
```
Comment (Centri3) [inline clippy_lints/src/methods/unnecessary_fallible_conversions.rs:33]: Hmm one last thing. I find it a bit weird to do this over `fn sugg()` and return either `default_sugg`/`machine_applicable_sugg` plus the applicability.

It just feels, I dunno, a bit error prone to do `== MachineApplicable` 😅 and weird as usually applicability is lowered to `HasPlaceholders` if we fail to get a snippet of a span.

(Return type will be pretty complex tho. I think this is a sign we need some type alias for a multipart suggestion in the future...)

r=me after this

Comment (Centri3) [reply clippy_lints/src/methods/unnecessary_fallible_conversions.rs:33]: PS the code is fine - I just think it should be rearranged a bit so that we don't match on `Applicability`. Having a fallback like this for when it specifically isn't machine applicable is oke

Comment (roife) [reply clippy_lints/src/methods/unnecessary_fallible_conversions.rs:33]: Merging the calculation of `sugg` and `applicability` into the same process would indeed make it more concise, then it would become:

```rust
fn sugg_appl(&self, parent_unwrap_call: &Option<Span>, primary_span: Span) -> (Applicability, Vec<(Span, String)>) {
        let Some(unwrap_span) = parent_unwrap_call else {
            return ...
        };

        match &self {
            FunctionKind::TryFromFunction(None) | FunctionKind::TryIntoFunction(None) => ...,
            _ => ...,
        }
    }
```

Do I need to make such a change?

Comment (Centri3) [reply clippy_lints/src/methods/unnecessary_fallible_conversions.rs:33]: Yea smth like that.

> Do I need to make such a change?

I'd prefer so. tho I can merge it now and create a followup PR tomorrow once I have my desktop back

**Comment by Centri3** [comment]
@bors r+

ty for your work on this!

**Comment by Centri3** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Sporadic.20macos.20failures

@bors retry
