### PR TITLE
needless-lifetime - nested elision sites

### LINKED ISSUE #2944: Incorrect needless_lifetimes warning for impl Trait based code
Given the following code:
```rust
#![crate_type = "lib"]
#![allow(unused)]
use std::collections::{HashMap, HashSet};

struct MyMap {
    inner: HashMap<u32, HashSet<String>>,
}

impl MyMap {
    fn iter<'a>(&'a self, key: u32) -> Option<impl Iterator<Item = impl AsRef<str> + 'a>> {
        self.inner.get(&key).map(|set| set.iter())
    }
}

fn main() {}
```
[Playground](https://play.rust-lang.org/?gist=59e35513b4c84dd5d8ab725c88080e13&version=nightly&mode=debug&edition=2015)

clippy reports the following:
```
 Checking playground v0.0.1 (file:///playground)
warning: explicit lifetimes given in parameter types where they could be elided
  --> src/main.rs:10:5
   |
10 | /     fn iter<'a>(&'a self, key: u32) -> Option<impl Iterator<Item = impl AsRef<str> + 'a>> {
11 | |         self.inner.get(&key).map(|set| set.iter())
12 | |     }
   | |_____^
   |
   = note: #[warn(needless_lifetimes)] on by default
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#needless_lifetimes

    Finished dev [unoptimized + debuginfo] target(s) in 1.40s
```
But if you take its suggestion and remove `'a` from `iter()`, you get the following compiler error:
```rust
 Compiling playground v0.0.1 (file:///playground)
error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements
  --> src/lib.rs:11:20
   |
11 |         self.inner.get(&key).map(|set| set.iter())
   |                    ^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 10:5...
  --> src/lib.rs:10:5
   |
10 | /     fn iter(&self, key: u32) -> Option<impl Iterator<Item = impl AsRef<str>>> {
11 | |         self.inner.get(&key).map(|set| set.iter())
12 | |     }
   | |_____^
note: ...so that reference does not outlive borrowed content
  --> src/lib.rs:11:9
   |
11 |         self.inner.get(&key).map(|set| set.iter())
   |         ^^^^^^^^^^
   = note: but, the lifetime must be valid for the static lifetime...
note: ...so that return value is valid for the call
  --> src/lib.rs:10:40
   |
10 |     fn iter(&self, key: u32) -> Option<impl Iterator<Item = impl AsRef<str>>> {
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0495`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```
It's possible this is a dupe of an existing issue but a cursory search revealed a few old (and closed) `impl Trait` related bugs, and I didn't find anything current.

### PR DESCRIPTION
**Pull request by montrivo**
Closes #2944

changelog: fix needless-lifetime nested elision site FPs

### CODE REVIEW

**Comment by ebroto** [comment]
r? @ebroto

(I started the review, will try to finish it later in the day)

File: tests/ui/needless_lifetimes.rs [hunk 1]
```diff
@@ -259,4 +259,36 @@ mod issue4291 {
...
+    fn nested_generic_fn_trait_bound<'a, T: Fn() -> &'a i32>(f: T) -> &'a i32 {
+        f()
+    }
+
+    fn nested_where_clause_fn_trait_bound<'a, T>(f: T) -> &'a i32
+    where
+        T: Fn() -> &'a i32,
+    {
+        f()
+    }
```
Comment (ebroto) [inline tests/ui/needless_lifetimes.rs:287]: I think these two cases were already covered by the previous tests.

File: tests/ui/needless_lifetimes.stderr [hunk 2]
```diff
@@ -36,12 +36,6 @@ error: explicit lifetimes given in parameter types where they could be elided (o
 LL | fn lifetime_param_2<'a, 'b>(_x: Ref<'a>, _y: &'b u8) {}
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
-error: explicit lifetimes given in parameter types where they could be elided (or replaced with `'_` if needed by type declaration)
-  --> $DIR/needless_lifetimes.rs:86:1
-   |
-LL | fn fn_bound_2<'a, F, I>(_m: Lt<'a, I>, _f: F) -> Lt<'a, I>
-   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-
```
Comment (ebroto) [inline tests/ui/needless_lifetimes.stderr:44]: With the proposed solution we can avoid this false negative.

File: tests/ui/needless_lifetimes.rs [hunk 3]
```diff
@@ -259,4 +259,36 @@ mod issue4291 {
     }
 }
 
+mod nested_elision_sites {
```
Comment (ebroto) [inline tests/ui/needless_lifetimes.rs:262]: We could add the following tests:
* The snippet with the outlives bound that creates the error for the first case you identified, verbatim.
* Returning a function pointer that takes a function pointer as a parameter, with and without named lifetimes.
* Returning `impl Trait` (just one would suffice) that takes a function pointer as a parameter, with and without named lifetimes.
* Returning/Taking a boxed `dyn Trait`, with and without named lifetimes.
* A function that takes `impl Trait` in parameter position, with and without named lifetimes.

(NOTE: For the cases without named lifetimes, we should make it so it triggers the lint).

**Review by ebroto — CHANGES_REQUESTED** [review]
Sorry for the delay in getting the PR reviewed, this is a complex topic with many edge cases :)

I have two main concerns about the current approach:
* We bail out if we find function pointers or closure trait bounds, but the only case that creates false positives is when those have named lifetimes. This leads to unnecessary false negatives.
* We are duplicating efforts (see below).

Looking at the (long) history of the lint, it seems that it was trying to prevent the same cases you identified in your analysis [here](https://github.com/rust-lang/rust-clippy/issues/2944#issuecomment-680302359) (modulo function pointers, which is a very good catch of yours :+1:)

(I can't put comments on code that has not been edited, so this will be a bit tough to explain correctly)

* For the outlives bound on `impl Trait` in return position, a check was added in #1400. There is even a test which is lost in the crashes directory (`needless_lifetimes_impl_trait`, I think that it's there by mistake). The problem in the issue we are resolving here is that the outlives bound is nested as a type parameter of another `impl Trait`, so the `RefVisitor` needs to recurse into nested items, which we can accomplish by using `NestedVisitorMap::All` in `RefVisitor::nested_visit_map`.

* For trait bounds (in general), the lint is already bailing out if they are found in the generic parameters. This works also for `impl Trait` in parameter position, but not in return position. The fix was introduced in #2855. We can use the same approach for `impl Trait` in return position and for function pointers by "manually" recursing into those looking for named lifetimes, and bail out if we find them.

In `RefVisitor::visit_ty`, we can add this branch to the match for the function pointers:
```rust
            TyKind::BareFn(bare_fn_ty) => {
                let mut visitor = RefVisitor::new(self.cx);
                walk_ty(&mut visitor, ty);
                if visitor.abort || visitor.lts.iter().any(|lt| matches!(lt, RefLt::Named(_))) {
                    self.abort = true;
                }
                return; // don't recurse into the fn declaration
            },

```

For the trait bounds, we can add this snippet inside the for that iterates on `exist_ty.bounds`:
```rust
                        let mut visitor = RefVisitor::new(self.cx);
                        walk_param_bound(&mut visitor, bound);
                        if visitor.abort || visitor.lts.iter().any(|lt| matches!(lt, RefLt::Named(_))) {
                            self.abort = true;
                            return;
                        }
```
(We can maybe factor something out by adding a method to the visitor)

I think this way we can avoid duplicating efforts and the false negatives. Please tell me if something is not clear :)

**Comment by montrivo** [comment]
thanks for the review @ebroto, I'll dive into asap.

File: tests/ui/needless_lifetimes.rs (hunk 1 above)
Comment (montrivo) [reply tests/ui/needless_lifetimes.rs:287]: Indeed, but for a different reason. In the implementation before this PR, the lint gives up if any named lifetime is found in the where clause (the implementation is more sophisticated than that, see `has_where_lifetimes`. I think this is a limitation of the lint and might be improved in the future. I added theses test cases as they are independent of this limitation, in order to protect against potential regressions around nested elision sites in where clauses.

Comment (montrivo) [reply tests/ui/needless_lifetimes.rs:287]: I'll reorder the tests and try to remove duplicates.

Comment (ebroto) [reply tests/ui/needless_lifetimes.rs:287]: > I added these test cases as they are independent of this limitation, in order to protect against potential regressions around nested elision sites in where clauses.

My bad, that makes sense :+1:

File: tests/ui/needless_lifetimes.stderr (hunk 2 above)
Comment (montrivo) [reply tests/ui/needless_lifetimes.stderr]: After rework, this case is no longer linted (as before).

**Comment by montrivo** [comment]
I reworked the impl and tried to integrate it better in the existing code base. I still have to go over the list of test cases suggested by @ebroto.

File: tests/ui/needless_lifetimes.rs (hunk 3 above)
Comment (montrivo) [reply tests/ui/needless_lifetimes.rs:262]: > * The snippet with the outlives bound that creates the error for the first case you identified, verbatim.
The example in the issue
```
fn get_x<'a>(i32_pointer: &'a i32) -> impl Fn() -> &'a i32 {
    move || i32_pointer
}
```
is an equivalent of 
```rust
fn nested_fn_trait_bound<'a>(i: &'a i32) -> impl Fn() -> &'a i32 {
    move || i
}
```
Doesn't need to be verbatim imo.

> *  Returning a function pointer that takes a function pointer as a parameter, with and without named lifetimes. 
> * Returning impl Trait (just one would suffice) that takes a function pointer as a parameter, with and without named lifetimes.

I'll add cases so that fn pointers and trait bound have both with and without named lifetimes cases covered

> * Returning/Taking a boxed dyn Trait, with and without named lifetimes.

I haven't checked the behavior of dyn trait bounds (but the elision rules get more complex as I understood from the reference). I'll add a case and see how that goes.

Comment (ebroto) [reply tests/ui/needless_lifetimes.rs:262]: >Doesn't need to be verbatim imo.

Sorry, I was not very precise, I was refering to [the comment that opened the issue](https://github.com/rust-lang/rust-clippy/issues/2944#issue-343146515), specifically this snippet:
```rust
use std::collections::{HashMap, HashSet};

struct MyMap {
    inner: HashMap<u32, HashSet<String>>,
}

impl MyMap {
    fn iter<'a>(&'a self, key: u32) -> Option<impl Iterator<Item = impl AsRef<str> + 'a>> {
        self.inner.get(&key).map(|set| set.iter())
    }
}

fn main() {}
```

>I'll add cases so that fn pointers and trait bound have both with and without named lifetimes cases covered

I was refering to cases like these:
```rust
    fn fun1<'a>(_: &'a i32) -> fn(fn(&'a i32) -> &'a i32) -> i32 {
        |f| 42
    }
    fn fun2<'a>(_: &'a i32) -> fn(fn(&i32) -> &i32) -> i32 {
        |f| 42
    }

    fn fun3<'a>(_: &'a i32) -> impl Fn(fn(&'a i32)) {
        |f| ()
    }
    fn fun4<'a>(_: &'a i32) -> impl Fn(fn(&i32)) {
        |f| ()
    }
```

>I haven't checked the behavior of dyn trait bounds

I thought about these just for completeness. If it turns out the lint does not work as expected, we can open another issue to deal with that.

Comment (montrivo) [reply tests/ui/needless_lifetimes.rs:262]: I've added tests cases similar to those you suggest. 

Concerning the `Iterator<Item = impl AsRef<str> + 'a>>` mentioned in the issue, there is a similar one in `needless_lifetimes_impl_trait.rs`: 
```rust 
impl Bar {
    fn baz<'a>(&'a self) -> impl Foo + 'a {
        Baz { bar: self }
    }
}
```
I'll copy it in the main test file as well.

As for `dyn Fn`, I'm struggling to find a realistic example that doesn't break other elision rules such as multiple identical lifetime references in the fn arguments.

Comment (ebroto) [reply tests/ui/needless_lifetimes.rs:262]: >Concerning the Iterator<Item = impl AsRef<str> + 'a>> mentioned in the issue, there is a similar one in needless_lifetimes_impl_trait.rs

Yeah that one can be included too :+1: 
But the one I was refering in my previous comment should be included too, because the type  `Option<impl Iterator<Item = impl AsRef<str> + 'a>>` includes the outlives bound for the nested `impl Trait`, which should not be linted now.

>As for dyn Fn, I'm struggling to find a realistic example that doesn't break other elision rules such as multiple identical lifetime references in the fn arguments.

Let's leave that one out then, to be fair it's not really related to the issue.

Comment (ebroto) [reply tests/ui/needless_lifetimes.rs:262]: I'll try to dig into your rework ASAP, but if I can't make it today it may take a couple days as I will be out of town.

File: clippy_lints/src/utils/paths.rs [hunk 4]
```diff
@@ -42,6 +42,9 @@ pub const FILE_TYPE: [&str; 3] = ["std", "fs", "FileType"];
 pub const FMT_ARGUMENTS_NEW_V1: [&str; 4] = ["core", "fmt", "Arguments", "new_v1"];
 pub const FMT_ARGUMENTS_NEW_V1_FORMATTED: [&str; 4] = ["core", "fmt", "Arguments", "new_v1_formatted"];
 pub const FMT_ARGUMENTV1_NEW: [&str; 4] = ["core", "fmt", "ArgumentV1", "new"];
+pub const FN: [&str; 3] = ["core", "ops", "Fn"];
+pub const FN_MUT: [&str; 3] = ["core", "ops", "FnMut"];
+pub const FN_ONCE: [&str; 3] = ["core", "ops", "FnOnce"];
```
Comment (ebroto) [inline clippy_lints/src/utils/paths.rs:47]: I would prefer to not hardcode those here in this case. The previous implementation managed to avoid those without explicitly checking those paths, was there something wrong about it?

**Review by ebroto — CHANGES_REQUESTED** [review]
I did not have time to dig into the rewrite (sorry about that, I had smaller changes in mind), and sadly won't have until around the end of the week. Hopefully I will recover my normal schedule after that :)

I see some review comments were not applied ([here](https://github.com/rust-lang/rust-clippy/pull/5978/files#r485168705), both cases), and some ui tests are crashing. Please ping me back with those addressed.

File: tests/ui/needless_lifetimes.rs (hunk 3 above)
Comment (montrivo) [reply tests/ui/needless_lifetimes.rs:277]: > But the one I was refering in my previous comment should be included too, because the type Option<impl Iterator<Item = impl AsRef<str> + 'a>> includes the outlives bound for the nested impl Trait, which should not be linted now.

@ebroto As I understand it, nested `impl Trait`s with lifetimes are only problematic if it is itself a candidate for elision (Fn, FnOnce, FnMut). The example you mention works fine with elided lifetimes (`Iterator<Item = impl AsRef<str> + '_>>`). In the issue analysis, I propose to continue linting this case.

File: clippy_lints/src/utils/paths.rs (hunk 4 above)
Comment (montrivo) [reply clippy_lints/src/utils/paths.rs:47]: This pr is mainly about handling these special cases, isn't it? If outer lifetimes are found in any trait bound involving these three, the lint does not apply. Other traits are fine.

File: tests/ui/needless_lifetimes.rs (hunk 3 above)
Comment (ebroto) [reply tests/ui/needless_lifetimes.rs:277]: >In the issue analysis, I propose to continue linting this case.

I would prefer not linting here or giving the final suggestion, as I think we should never suggest code that does not compile, but this is indeed debatable. I would like to have more opinions on this, so I've [asked in zulip](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Suggest.20erroneous.20code.20if.20fix.20is.20simple.3F/near/210751560).

Comment (ebroto) [reply tests/ui/needless_lifetimes.rs:277]: After hearing others' thoughts on this, I think we can go with your proposal :+1: 

Following @flip1995 suggestion there, we could explain this special case in the documentation / known problems.

File: clippy_lints/src/utils/paths.rs (hunk 4 above)
Comment (ebroto) [reply clippy_lints/src/utils/paths.rs:47]: After looking at the rewrite, I think it makes sense having those added.

**Review by ebroto — CHANGES_REQUESTED** [review]
I can't reproduce the test crashes locally now :+1: 

Besides my two last comments, I think we still miss some cases with fn pointers inside fn pointers/trait bounds:
```rust
    fn fun1<'a>(_: &'a i32) -> fn(fn(&'a i32) -> &'a i32) -> i32 {
        |f| 42
    }
    fn fun2<'a>(_: &'a i32) -> fn(fn(&i32) -> &i32) -> i32 {
        |f| 42
    }

    fn fun3<'a>(_: &'a i32) -> impl Fn(fn(&'a i32)) {
        |f| ()
    }
    fn fun4<'a>(_: &'a i32) -> impl Fn(fn(&i32)) {
        |f| ()
    }
```
(I've tested them and they work as expected)

**Comment by montrivo** [comment]
Thanks @ebroto .
Didn't have much contribution time last week. Will try to finish this asap.

File: tests/ui/needless_lifetimes.rs [hunk 5]
```diff
@@ -259,4 +259,86 @@ mod issue4291 {
...
+
+    // don't lint
+    fn pointer_fn_in_input_position<'a>(f: fn(&'a i32) -> &'a i32, i: &'a i32) -> &'a i32 {
+        f(i)
+    }
+    fn pointer_fn_in_output_position<'a>(_: &'a i32) -> fn(&'a i32) -> &'a i32 {
+        |i| i
+    }
+    // lint
+    fn pointer_fn_elidable<'a>(f: fn(&i32) -> &i32, i: &'a i32) -> &'a i32 {
```
[the remark this answers is not in the document]
Comment (montrivo) [reply tests/ui/needless_lifetimes.rs:339]: Nice catch, this one was a bug :+1:

**Comment by montrivo** [comment]
@ebroto I should have addressed all your remarks.

**Review by ebroto — APPROVED** [review]
LGTM!

Sorry for the long review process. I'd like to thank you for this fix and in general for your continued efforts in fixing long standing bugs. Your work is very much appreciated.

**Comment by montrivo** [comment]
Happy to see this merged! Thanks @ebroto for the multiple reviews ;)
