### PR TITLE
Correctly handle bracketed type in `default_constructed_unit_struct`

### LINKED ISSUE #12654: default_constructed_unit_structs sugg causes error
### Summary

.

### Reproducer

I tried this code:

```rust
struct G;

impl PartialEq<B> for G {
	fn eq(&self, _: &B) -> bool {
		true
	}
}

#[derive(Debug, Default)]
struct B;


fn main() {
    let _ = G::eq(&G, dbg!(&<_>::default()));
}

```

Instead, this happened:
```
warning: use of `default` to create a unit struct
  --> ./tests/ui/lint/non-local-defs/generics.rs:14:31
   |
14 |     let _ = G::eq(&G, dbg!(&<_>::default()));
   |                               ^^^^^^^^^^^^ help: remove this call to `default`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#default_constructed_unit_structs
   = note: requested on the command line with `-W clippy::default-constructed-unit-structs`
```

This does not work lol
```
error: expected one of `>` or `as`, found `<eof>`
   --> src/main.rs:14:30
    |
14  |     let _ = G::eq(&G, dbg!(&<_));
    |                              ^ expected one of `>` or `as`
    |
```

### Version

```text
rustc 1.79.0-nightly (ab5bda1aa 2024-04-08)
binary: rustc
commit-hash: ab5bda1aa70f707014e2e691e43bc37a8819252a
commit-date: 2024-04-08
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.3
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by samueltardieu**
There were two bugs here. Let's assume `T` is a singleton type implementing `Default` and that `f()` takes a `T`:

- `f(<T>::default())` cannot be replaced by `f(<T)` as it was (incorrect spans – this is tricky because the type relative path uses a base span covering only `T`, not `<T>`) (third commit)
- The argument of `f(<_>::default())` is inferred correctly, but cannot be replaced by `<_>` or `_`, as this cannot be used to infer an instance of a singleton type (first commit).

The second commit offers better error messages by pointing at the whole expression.

Fix #12654 

changelog: [`default_constructed_unit_struct`]: do not suggest incorrect fix when using a type surrounded by brackets

### CODE REVIEW

**Comment by samueltardieu** [comment]
r? clippy

File: clippy_lints/src/default_constructed_unit_structs.rs [hunk 1]
```diff
@@ -70,15 +71,26 @@ impl LateLintPass<'_> for DefaultConstructedUnitStructs {
             && let var @ ty::VariantDef { ctor: Some((hir::def::CtorKind::Const, _)), .. } = def.non_enum_variant()
             && !var.is_field_list_non_exhaustive()
             && !expr.span.from_expansion() && !qpath.span().from_expansion()
+            // do not suggest replacing an expression by a type name with placeholders
+            && !base.is_suggestable_infer_ty()
         {
-            span_lint_and_sugg(
+            let mut removals = vec![(expr.span.with_lo(qpath.qself_span().hi()), String::new())];
+            if expr.span.with_source_text(cx, |s| dbg!(s).starts_with('<')) == Some(true) {
```
Comment (y21) [inline clippy_lints/src/default_constructed_unit_structs.rs:78]: Looks like you forgot to remove a `dbg` here (maybe we should run clippy_lints dogfood with `-Dclippy::dbg`)

**Review by y21 — APPROVED** [review]
LGTM, r=me with the dbg removed

File: clippy_lints/src/default_constructed_unit_structs.rs (hunk 1 above)
Comment (samueltardieu) [reply clippy_lints/src/default_constructed_unit_structs.rs]: Thanks for catching this! I've submitted https://github.com/rust-lang/rust-clippy/pull/14579 to avoid this in the future.
