### PR TITLE
`single_component_path_imports`: ignore `pub(crate) use some_macro;`

### LINKED ISSUE #7106: `single_component_path_imports`: False positive for exporting macros within crate
Lint name: `single_component_path_imports`

I tried this code:

```rust
mod a {
    macro_rules! foo {
        () => {
            println!("foo")
        };
    }
    // This use statement is required to allow non-parent modules in the same crate to use it,
    // while preventing other crates from using it
    pub(crate) use foo;
}

// The rest isn't necessary to reproduce but it shows why it's a false positive
mod b {
    use super::a;
    pub(crate) fn bar() {
        a::foo!();
    }
}

fn main() {
    b::bar();
}
```

I expected to see this happen: no lint warnings

Instead, this happened:

```
warning: this import is redundant
 --> src/main.rs:9:5
  |
9 |     pub(crate) use foo;
  |     ^^^^^^^^^^^^^^^^^^^ help: remove it entirely
  |
  = note: `#[warn(clippy::single_component_path_imports)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_component_path_imports
```

Note that I cannot use `#[macro_use]` in this scenario because `b` is a sibling module of `a`, not a parent, so you can't declare `#[macro_use] mod a;` in `b`.

### Meta

- `cargo clippy -V`: clippy 0.1.51 (2fd73fab 2021-03-23)
- `rustc -Vv`:
  ```
  rustc 1.51.0 (2fd73fabe 2021-03-23)
  binary: rustc
  commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
  commit-date: 2021-03-23
  host: x86_64-apple-darwin
  release: 1.51.0
  LLVM version: 11.0.1
  ```

### PR DESCRIPTION
**Pull request by cherryblossom000**
Fixes #7106

*Please write a short comment explaining your change (or "none" for internal only changes)*

changelog: Ignore exporting a macro within a crate using `pub(crate) use some_macro;` for [`single_component_path_imports`]

### CODE REVIEW

File: clippy_lints/src/single_component_path_imports.rs [hunk 1]
```diff
@@ -105,14 +119,22 @@ fn track_uses(
         ItemKind::Mod(_, ModKind::Loaded(ref items, ..)) => {
             check_mod(cx, &items);
         },
+        ItemKind::MacroDef(MacroDef { macro_rules: true, .. }) => {
```
Comment (cherryblossom000) [inline clippy_lints/src/single_component_path_imports.rs:122]: I had a brief look at [the macros 2.0 RFC](https://github.com/rust-lang/rust/issues/39412), and it seems like it will introduce a better way of declaring a macro's visibility:

```rust
pub(crate) macro foo { /* ... */ }
```

That's why I've included `macro_rules: true` so this only applies to `macro_rules!` macros, but I'm not too sure about this.

File: clippy_lints/src/single_component_path_imports.rs [hunk 2]
```diff
@@ -105,14 +119,22 @@ fn track_uses(
...
+            macros.push(item.ident.name);
+        },
         ItemKind::Use(use_tree) => {
             let segments = &use_tree.prefix.segments;
 
+            let should_report =
+                |name: &Symbol| !macros.contains(name) || matches!(item.vis.kind, VisibilityKind::Inherited);
```
Comment (cherryblossom000) [inline clippy_lints/src/single_component_path_imports.rs:129]: When I remove the `&Symbol` type annotation, I get this error:

```rust
error[E0597]: `name` does not live long enough
   --> clippy_lints/src/single_component_path_imports.rs:150:50
    |
150 | ...                       if should_report(&name) {
    |                              ------------- ^^^^^ borrowed value does not live long enough
    |                              |
    |                              borrow later used here
...
153 | ...                   }
    |                       - `name` dropped here while still borrowed
```

**Review by Manishearth — APPROVED** [review]
