### PR TITLE
make ignored internally mutable types for `mutable-key` configurable

### LINKED ISSUE #5325: mutable_key_type false positives
Hello!

We're getting false positives with the `mutable_key_type` rule: https://circleci.com/gh/libra/libra/41319?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

It seems to be triggered by this:

```
HashSet<ProtocolId>
```

where [ProtocolId](https://github.com/libra/libra/blob/07be050b658dd8d4402ef877cc0ac47eaff92c57/network/src/protocols/wire/messaging/v1/mod.rs#L31) is defined as 

```
pub type ProtocolId = protocols::wire::messaging::v1::ProtocolId;
```

which is

```
#[repr(u8)]
#[derive(Clone, Copy, Debug, Hash, Eq, PartialEq, Deserialize_repr, Serialize_repr)]
pub enum ProtocolId {
    ConsensusRpc = 0,
    ConsensusDirectSend = 1,
    MempoolDirectSend = 2,
    StateSynchronizerDirectSend = 3,
    DiscoveryDirectSend = 4,
    HealthCheckerRpc = 5,
    IdentityDirectSend = 6,
}
```

I wasn't able to reproduce it with a simple example, so not sure why clippy is getting triggered here.

### PR DESCRIPTION
**Pull request by llogiq**
We had some false positives where people would create their own types that had interior mutability unrelated to hash/eq. This addition lets you configure this as e.g. `arc-like-types=["bytes::Bytes"]`

This fixes #5325 by allowing users to specify the types whose innards like `Arc` should be ignored (the generic types are still checked) for the sake of detecting inner mutability.

r? @Alexendoo

---

changelog: Allow configuring types to ignore internal mutability in `mutable-key`

### CODE REVIEW

File: clippy_lints/src/utils/conf.rs [hunk 1]
```diff
@@ -387,6 +387,11 @@ define_Conf! {
     ///
     /// The maximum size of the `Err`-variant in a `Result` returned from a function
     (large_error_threshold: u64 = 128),
+    /// Lint::MUTABLE_KEY
+    ///
+    /// A list of paths to types that should be treated like `Arc`, i.e. ignored but
+    /// for the generic parameters for determining interior mutability
+    (arc_like_types: Vec<String> = Vec::new()),
```
Comment (Alexendoo) [inline clippy_lints/src/utils/conf.rs:394]: Seems like a reasonable escape hatch, I think the name might be better as a bit more direct, `ignore_interior_mutability` or something along those lines as there may be other types that aren't `Arc`-like

What do you think about setting the default to `vec!["bytes::Bytes"]` to cover the seemingly most popular false positive?

File: clippy_lints/src/mut_key.rs [hunk 2]
```diff
@@ -78,98 +78,116 @@ declare_clippy_lint! {
...
-            if is_std_collection || is_box {
-                // The type is mutable if any of its type parameters are
-                substs.types().any(|ty| is_interior_mutable_type(cx, ty, span))
-            } else {
-                !ty.has_escaping_bound_vars()
-                    && cx.tcx.layout_of(cx.param_env.and(ty)).is_ok()
-                    && !ty.is_freeze(cx.tcx.at(span), cx.param_env)
+    // We want to lint 1. sets or maps with 2. not immutable key types and 3. no unerased
+    // generics (because the compiler cannot ensure immutability for unknown types).
+    fn check_ty_<'tcx>(&self, cx: &LateContext<'tcx>, span: Span, ty: Ty<'tcx>) {
```
[the remark this answers is not in the document]
Comment (llogiq) [reply clippy_lints/src/mut_key.rs:133]: That clashes with `LateLintPass::check_ty`.

**Comment by llogiq** [comment]
Thanks @Alexendoo for the review. I incorporated your suggestions.

File: clippy_lints/src/mut_key.rs [hunk 3]
```diff
@@ -78,98 +78,119 @@ declare_clippy_lint! {
...
+            },
+            _ => false,
+        }
+    }
+
+    fn is_arc_like(&self, cx: &LateContext<'_>, did: hir::def_id::DefId) -> bool {
+        !self.ignore_interior_mutability.is_empty()
+            && match_any_def_paths_iter(cx, did, self.ignore_interior_mutability.iter().map(|s| s.split("::")))
+                .is_some()
     }
```
Comment (Alexendoo) [inline clippy_lints/src/mut_key.rs:195]: Could use `def_path_res(..).opt_def_id()` in a `check_crate` to build a `DefIdSet` one time, similar to how `disallowed_types` does it https://github.com/rust-lang/rust-clippy/blob/191c9839f0bad1c2bfec17d55bacb94d2e83f1a1/clippy_lints/src/disallowed_types.rs#L89-L103

Then checking if a type is ignored can be a single lookup

File: tests/ui-toml/mut_key/clippy.toml [hunk 4]
```diff
@@ -0,0 +1 @@
+arc-like-types = ["mut_key::Counted"]
```
Comment (Alexendoo) [inline tests/ui-toml/mut_key/clippy.toml:1]: Needs a key name update

File: clippy_lints/src/mut_key.rs (hunk 3 above)
Comment (llogiq) [reply clippy_lints/src/mut_key.rs]: The problem here is that the queries used by `def_path_res` don't work on local items. It needed a good bunch of code to work around this. I'm not sure if this is absolutely correct (it might need additional code to cater for the namespace_hint), but it works in my case. If this becomes a problem, we can revisit it in a later PR.

File: clippy_lints/src/mut_key.rs [hunk 5]
```diff
@@ -78,98 +80,130 @@ declare_clippy_lint! {
...
 impl<'tcx> LateLintPass<'tcx> for MutableKeyType {
+    fn check_crate(&mut self, cx: &LateContext<'tcx>) {
+        self.ignore_mut_def_ids.clear();
+        let mut path = Vec::new();
+        for ty in &self.ignore_interior_mutability {
+            path.extend(ty.split("::"));
+            if let Some(id) = def_path_res(cx, &path[..], Some(Namespace::TypeNS)).opt_def_id() {
+                self.ignore_mut_def_ids.insert(id);
+                //} else {
+                //    cx.sess().note_without_error(&format!("not found: {ty}"));
```
Comment (Alexendoo) [inline clippy_lints/src/mut_key.rs:100]:
```suggestion
```

File: clippy_utils/src/lib.rs [hunk 6]
```diff
@@ -642,7 +647,60 @@ pub fn def_path_res(cx: &LateContext<'_>, path: &[&str], namespace_hint: Option<
...
+                        ItemKind::TyAlias(_, _) => DefKind::TyAlias,
+                        ItemKind::OpaqueTy(_) => DefKind::OpaqueTy,
+                        ItemKind::Union(_, _) => DefKind::Union,
+                        ItemKind::Trait(_, _, _, _, _) => DefKind::Trait,
+                        ItemKind::TraitAlias(_, _) => DefKind::TraitAlias,
+                        ItemKind::Impl(_) => DefKind::Impl,
+                    };
+                    if path.is_empty() {
+                        return Res::Def(def_kind, item_def_id.to_def_id());
+                    }
```
Comment (Alexendoo) [inline clippy_utils/src/lib.rs:693]: I *think* the `cx.tcx.def_kind(item_def_id)` query should work still here

File: clippy_utils/src/lib.rs [hunk 7]
```diff
@@ -1811,6 +1869,22 @@ pub fn match_any_def_paths(cx: &LateContext<'_>, did: DefId, paths: &[&[&str]])
...
+) -> Option<usize>
+where
+    P: IntoIterator<Item = &'a str>,
+{
+    let search_path = cx.get_def_path(did);
+    paths
+        .into_iter()
+        .position(|p| p.into_iter().map(Symbol::intern).eq(search_path.iter().copied()))
+}
+
```
Comment (Alexendoo) [inline clippy_utils/src/lib.rs:1887]: Now unused

```suggestion
```

File: clippy_utils/src/lib.rs [hunk 8]
```diff
@@ -586,14 +586,19 @@ pub fn def_path_res(cx: &LateContext<'_>, path: &[&str], namespace_hint: Option<
...
-        tcx.crates(())
+    fn find_crate(cx: &LateContext<'_>, name: &str) -> Option<DefId> {
+        cx.tcx
+            .crates(())
             .iter()
             .copied()
-            .find(|&num| tcx.crate_name(num).as_str() == name)
+            .find(|&num| cx.tcx.crate_name(num).as_str() == name)
             .map(CrateNum::as_def_id)
     }
```
Comment (Alexendoo) [inline clippy_utils/src/lib.rs:596]: This change looks like it became no longer necessary

File: clippy_utils/src/lib.rs [hunk 9]
```diff
@@ -586,14 +586,19 @@ pub fn def_path_res(cx: &LateContext<'_>, path: &[&str], namespace_hint: Option<
...
 
+    if path.first() == Some(&"crate") || path.first().copied() == cx.sess().opts.crate_name.as_deref() {
+        return def_path_res_local(cx, &path[1..]);
+    }
```
Comment (Alexendoo) [inline clippy_utils/src/lib.rs:600]: We may actually not want to handle `crate`, it would resolve to different paths for each package in the workspace, and I think also each bin/lib target within a single package

Could also move this down one statement to use `base` in place of `path.first()` to guard against any zero length path weirdness

Comment (llogiq) [reply clippy_utils/src/lib.rs]: Ok, I have removed the `crate`, and used `base`.

File: clippy_utils/src/lib.rs (hunk 8 above)
Comment (llogiq) [reply clippy_utils/src/lib.rs]: Reverted.

**Comment by Alexendoo** [comment]
Nice, thanks!

@bors r+
