### PR TITLE
Fix map_clone with deref and clone

### LINKED ISSUE #6239: `map_clone` suggests removing clone altogether
I tried this code (https://github.com/rust-lang/rust/blob/a6ff925f8b5598a1f6d84964525baa1d4a08fd63/compiler/rustc_codegen_ssa/src/back/write.rs#L1026):

```rust
    let cgcx = CodegenContext::<B> {
        incr_comp_session_dir: sess.incr_comp_session_dir_opt().map(|r| r.clone()),
    };
```

I expected to see this happen: Not sure this lint should have fired in the first place? This is a `Ref`, not an iterator.

Instead, this happened: Clippy suggests removing the map altogether, giving a type error.

```
error[E0308]: mismatched types
    --> compiler/rustc_codegen_ssa/src/back/write.rs:1014:32
     |
1014 |         incr_comp_session_dir: sess.incr_comp_session_dir_opt(),
     |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::path::PathBuf`, found struct `std::cell::Ref`
     |
     = note: expected enum `std::option::Option<std::path::PathBuf>`
                found enum `std::option::Option<std::cell::Ref<'_, std::path::PathBuf, >>`

Original diagnostics will follow.

warning: you are needlessly cloning iterator elements
    --> compiler/rustc_codegen_ssa/src/back/write.rs:1014:64
     |
1014 |         incr_comp_session_dir: sess.incr_comp_session_dir_opt().map(|r| r.clone()),
     |                                                                ^^^^^^^^^^^^^^^^^^^ help: remove the `map` call
     |
     = note: `#[warn(clippy::map_clone)]` on by default
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_clone
```

### Meta

- `cargo clippy -V`: clippy 0.0.212 (ffa2e7a 2020-10-24)

### PR DESCRIPTION
**Pull request by camsteffen**
changelog: Fix map_clone false positive with deref coercion

Fixes #6239

### CODE REVIEW

**Comment by camsteffen** [comment]
Learning as I go... I'm changing my implementation to check for autoderef adjustments instead of checking for `impl Clone`. This seems more conservative.

**Comment by camsteffen** [comment]
Rebased to fix the merge conflict.

**Comment by flip1995** [comment]
Thanks for keeping this up to date.  And thanks for all your recent contributions! Sadly currently almost all of our maintainers are busy with IRL stuff and only get to review a few times a week at best.

**Comment by camsteffen** [comment]
No worries!

File: clippy_lints/src/map_clone.rs [hunk 1]
```diff
@@ -75,11 +76,14 @@ impl<'tcx> LateLintPass<'tcx> for MapClone {
...
-                                    && match_trait_method(cx, closure_expr, &paths::CLONE_TRAIT) {
-
-                                    let obj_ty = cx.typeck_results().expr_ty(&obj[0]);
+                            hir::ExprKind::MethodCall(ref method, _, [obj], _) => if_chain! {
+                                if ident_eq(name, obj) && method.ident.name == sym::clone;
+                                if match_trait_method(cx, closure_expr, &paths::CLONE_TRAIT);
+                                // no autoderefs
+                                if !cx.typeck_results().expr_adjustments(obj).iter()
+                                    .any(|a| matches!(a.kind, Adjust::Deref(Some(..))));
+                                let obj_ty = cx.typeck_results().expr_ty(obj);
```
Comment (ebroto) [inline clippy_lints/src/map_clone.rs:85]: nit, but we could move this line inside the `then` block for readability.

**Review by ebroto — CHANGES_REQUESTED** [review]

File: clippy_lints/src/map_clone.rs (hunk 1 above)
Comment (camsteffen) [reply clippy_lints/src/map_clone.rs:85]: makes sense

**Comment by ebroto** [comment]
@bors r+

Thanks! (for this and for Polite :smile:)
