### PR TITLE
fix misleading doc for explicit_counter_loop lint

### LINKED ISSUE #4472: Unexpected needless_range_loop, expected explicit_counter_loop
The following code triggered the [needless_range_loop][needless_range_loop] lint, which would be a false positive, given the condition uses `i`.

```rust
let arr = [10, 20, 30];

for i in 0..arr.len() {
    if i != 1 {
        println!("{}", arr[i]);
    }
}
```

Instead the [explicit_counter_loop][explicit_counter_loop] lint would be expected.

```rust
let arr = [10, 20, 30];

for (i, x) in arr.iter().enumerate() {
    if i != 1 {
        println!("{}", x);
    }
}
```

Version: clippy 0.0.212 (082cfa7 2019-06-07)

[needless_range_loop]: https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
[explicit_counter_loop]: https://rust-lang.github.io/rust-clippy/master/index.html#explicit_counter_loop

### PR DESCRIPTION
**Pull request by awoimbee**
changelog: replace misleading examples for explicit_counter_loop & more concise `Why is it bad?` section

This fixes #4472

### CODE REVIEW

File: clippy_lints/src/loops.rs [hunk 1]
```diff
@@ -298,26 +298,25 @@ declare_clippy_lint! {
...
     /// **Example:**
     /// ```rust
     /// # let v = vec![1];
-    /// # fn foo(bar: usize) {}
     /// # fn bar(bar: usize, baz: usize) {}
-    /// for i in 0..v.len() { foo(v[i]); }
-    /// for i in 0..v.len() { bar(i, v[i]); }
+    /// let mut i = 0;
+    /// for item in &v {
+    ///     bar(i, *item)
```
Comment (flip1995) [inline clippy_lints/src/loops.rs]:
```suggestion
    ///     bar(i, *item);
```

**Comment by awoimbee** [comment]
Does this happen often ?
It looks like the script ran into a memory limit on macOS, I don't see how a simple doc update could have caused that.
(See [error 137 in Travis CI](https://github.com/travis-ci/travis-ci/issues/4665), macOS has less RAM: [specs of build environments](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system))
The tests are passing on Linux and Windows.

(PS: sorry for the missing semicolon !)

**Comment by flip1995** [comment]
I restarted the job. Should be ok, let's wait.

**Comment by flip1995** [comment]
It seems that it was travis' fault.

@bors r+ Thanks!
