### PR TITLE
fix: `unused_unit` suggests wrongly when unit never type fallback

### LINKED ISSUE #14577: `unused_unit` triggers when the type annotation is needed to compile
### Summary

When running the code snippet from [the 2024 edition guide](https://doc.rust-lang.org/edition-guide/rust-2024/never-type-fallback.html) it triggers the `unused_unit` lint, even though removing the type annotation will make the code stop compiling.

Encountered in https://github.com/bevyengine/bevy/issues/18778

### Lint Name

unused_unit

### Reproducer

```rust
trait Unit {}
impl Unit for () {}

fn run<R: Unit>(f: impl FnOnce() -> R) {
    f();
}


fn main() {
    run(|| -> () { todo!() });
}
```

Output
```
warning: unneeded unit return type
  --> src/main.rs:12:11
   |
12 |     run(|| -> () { todo!() });
   |           ^^^^^^ help: remove the `-> ()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit
   = note: `#[warn(clippy::unused_unit)]` on by default
```

### Version

```text

```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by profetia**
Closes rust-lang/rust-clippy#14577.

Migrate this lint to late pass and avoids `unit_never_type_fallback` since it is no longer permitted in Rust 2024.

changelog: [`unused_unit`] fix wrong suggestions when unit never type fallback

### CODE REVIEW

**Comment by profetia** [comment]
The migration looks fine now, but other tests began to fail in `cargo uibless`. I have no idea why this happen. Could you give me some help? @samueltardieu

**Review by Jarcho — CHANGES_REQUESTED** [review]

File: clippy_lints/src/unused_unit.rs [hunk 1]
```diff
@@ -32,29 +40,101 @@ declare_clippy_lint! {
...
+                && let ExprKind::Closure(closure) = expr.kind
+                && !closure.bound_generic_params.is_empty()
+            {
                 return;
             }
 
-            lint_unneeded_unit_return(cx, ty, span);
+            // unit never type fallback is no longer supported since Rust 2024. For more information,
+            // see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/never-type-fallback.html>
+            if self.msrv.meets(cx, msrvs::UNIT_NEVER_TYPE_FALLBACK)
```
[the remark this answers is not in the document]
Comment (profetia) [reply clippy_lints/src/unused_unit.rs]: Thanks!

File: clippy_lints/src/unused_unit.rs [hunk 2]
```diff
@@ -34,27 +41,89 @@ declare_clippy_lint! {
...
+                && let Node::Expr(expr) = cx.tcx.hir_node_by_def_id(def_id)
+                && let ExprKind::Closure(closure) = expr.kind
+                && !closure.bound_generic_params.is_empty()
+            {
+                return;
+            }
+
+            // unit never type fallback is no longer supported since Rust 2024. For more information,
+            // see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/never-type-fallback.html>
+            if cx.tcx.sess.edition() == Edition::Edition2024
```
Comment (Jarcho) [inline clippy_lints/src/unused_unit.rs:70]: Should be `>=` not `==`.

Comment (profetia) [reply clippy_lints/src/unused_unit.rs]: Thank you!

File: tests/ui/unused_unit.rs [hunk 3]
```diff
@@ -120,3 +120,24 @@ mod issue9949 {
...
+        run(|| -> () { todo!() });
+    }
+
+    struct UnitStruct;
+    impl UnitStruct {
+        fn apply<F: for<'c> Fn(&'c mut Self)>(&mut self, f: F) {
+            todo!()
+        }
+    }
+}
```
Comment (Jarcho) [inline tests/ui/unused_unit.rs:143]: Forgot to mention this but you'll need to test the file with multiple editions.

You can add the revisions to the top of the test
```rust
//@revisions: edition2021 edition2024
//@[edition2021] edition:2021
//@[edition2024] edition:2024
```

Error markers are the same if they occur in both editions. If the error only occurs in one edition you can use `//~[edition2021]` to mark just the specific line.

This should also have a trailing line feed.

Comment (Jarcho) [reply tests/ui/unused_unit.rs:143]: `ui_test` should be testing the fixed code under the same settings it was made with. Can you push the code so I can see whats going on?

Comment (profetia) [reply tests/ui/unused_unit.rs]: Pushed

Comment (profetia) [reply tests/ui/unused_unit.rs]: Any help?

Comment (Jarcho) [reply tests/ui/unused_unit.rs]: It's compiling on the 2021 edition. You're getting the migration lint `dependency_on_unit_never_type_fallback` which you'll need to add as allowed.

Comment (profetia) [reply tests/ui/unused_unit.rs]: Thank you!

**Review by Jarcho — APPROVED** [review]
Thank you.
