### PR TITLE
fix `for x in y unsafe { }`

### LINKED ISSUE #12514: `needless-for-each` does not add braces before `unsafe` block
### Summary

Necessary curly braces not inserted before an `unsafe` block inside a `for-each`.
`-D clippy::needless-for-each` implied by `-D clippy::pedantic`

### Reproducer

I tried this code:

```rust
// Where `array` is an `&mut Vec<T>`:
array.iter().for_each(|val| unsafe {
    // code goes here...
});
```

I expected to see this happen:
```rust
/// Notice that it automatically adds the necessary curly braces  : )
help: try
   |
11 ~         for val in array.iter() { unsafe {
12 +             // code goes here...
13 +         }}
   |
```
Instead, this happened:
```rust
help: try
   |
11 ~         for val in array.iter() unsafe {
12 +             // code goes here...
13 +         }
   |
/// This is the error before the attempt-to-replace
The following errors were reported:
error: expected `{`, found keyword `unsafe`
  --> ...
   |
11 |         for val in array.iter() unsafe {
   |                                 ^^^^^^ expected `{`
   |
help: try placing this code inside a block
   |
11 ~         for val in array.iter() { unsafe {
12 |             // code goes here...
13 ~         } }
   |
```

### Version

```text
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-pc-windows-gnu
release: 1.76.0
LLVM version: 17.0.6
```

### Additional Labels

@rustbot label +l-suggestion-causes-error

### PR DESCRIPTION
**Pull request by bend-n**
fixes #12514

----

changelog: [`needless_for_each`]: unsafe block in for loop body suggestion

### CODE REVIEW

File: clippy_lints/src/needless_for_each.rs [hunk 1]
```diff
@@ -68,7 +68,8 @@ impl<'tcx> LateLintPass<'tcx> for NeedlessForEach {
             // e.g. `v.iter().for_each(f)` is simpler and clearer than using `for` loop.
             && let ExprKind::Closure(&Closure { body, .. }) = for_each_arg.kind
             && let body = cx.tcx.hir().body(body)
-            && let ExprKind::Block(..) = body.value.kind
+            // Skip the lint if the body is not safe.
```
Comment (Nilstrieb) [inline clippy_lints/src/needless_for_each.rs:71]: this comment isn't very useful, it would be more useful to comment why it skips the lint

**Comment by llogiq** [comment]
I'd be fine with both.

**Review by J-ZhengLi — COMMENTED** [review]
Well... from what I see 👀, skipping the lint completely when `unsafe` block is involved doesn't really fits the lint's description, where it says:

>`for_each` may be used after applying iterator transformers like
> `filter` for better readability and performance. It may also be used to fit a simple
> operation on one line.
> But when none of these apply, a simple `for` loop is more idiomatic.

It might be a good idea to specify it in the doc as well, of why it's skipping the `unsafe`.

Also, make sure you put a `fixes: ` with the issue number which you're trying to fix (I believe it's #12514 correct?) in your PR summary, therefore when this got merged, that issue will be closed automatically by bot.

File: clippy_lints/src/needless_for_each.rs [hunk 2]
```diff
@@ -68,7 +68,9 @@ impl<'tcx> LateLintPass<'tcx> for NeedlessForEach {
             // e.g. `v.iter().for_each(f)` is simpler and clearer than using `for` loop.
             && let ExprKind::Closure(&Closure { body, .. }) = for_each_arg.kind
             && let body = cx.tcx.hir().body(body)
-            && let ExprKind::Block(..) = body.value.kind
+            // Skip the lint if the body is not safe, so as not to suggest `for … in … unsafe {}`
+            // and suggesting `for … in … { unsafe { } }` is a little ugly.
+            && let ExprKind::Block(Block { rules: BlockCheckMode::DefaultBlock, .. }, ..) = body.value.kind
```
Comment (J-ZhengLi) [inline clippy_lints/src/needless_for_each.rs:73]: In case you ever want to support the `ugly` suggestion 😂, you may want to take `rules` out, then format the suggestion accordingly, such as:

```rust
if let BlockCheckMode::UnsafeBlock(_) = rules {
    Sugg::hir_with_applicability(cx, body.value, "..", &mut applicability).blockify()
} else {
    Sugg::hir_with_applicability(cx, body.value, "..", &mut applicability)
}
```

at line 102.

Which gives the correct suggestion

**Review by J-ZhengLi — COMMENTED** [review]
Oh, one more thing~

File: clippy_lints/src/needless_for_each.rs (hunk 2 above)
Comment (bend-n) [reply clippy_lints/src/needless_for_each.rs:73]: `.blockify()`? huh.

**Comment by bend-n** [comment]
> Also, make sure you put a `fixes: ` with the issue number which you're trying to fix (I believe it's #12514 correct?) in your PR summary, therefore when this got merged, that issue will be closed automatically by bot.

huh, i just found the issue on my own, that person seems to have discovered it at nearly the exact same time as me.

**Comment by J-ZhengLi** [comment]
> 
> huh, i just found the issue on my own, that person seems to have discovered it at nearly the exact same time as me.

Well... I saw both that one issue and your PR are the first on the list, and that issue was posted a few hours prior, so I thought you were trying to fix that issue, oops 😅

**Comment by llogiq** [comment]
@bend-n I see a warning of:
The head ref may contain hidden characters: "\u{1F980}"

Can you fix that? It's probably some sort of wide space in some comment. Also I'd like to see a "Known Issues" section in the docs that tells people they should expect the lint not to trigger for unsafe blocks.

**Comment by bend-n** [comment]
please lookup `u+1f980`:
image

**Comment by llogiq** [comment]
Thank you both for the clarification and the fix.

@bors r+
