### PR TITLE
Fix `let_and_return` with temporary variables, and distinguish between Rust editions

### LINKED ISSUE #14164: `let_and_return` can generate code that does not compile when lifetimes are involved
### Summary

While writing some code that makes use of [rusqlite](https://docs.rs/crate/rusqlite/latest) I hit a clippy lint that generates code that cannot compile. Basically, when I create a prepared statement in a block inside my function, and return the result of that query out of the block, I am required to set the variable into a result and return the value (I'm not fully sure why, maybe the compiler can't tell the drop order and given it's a copy type, does not copy if I don't alias). The clippy suggestion asks to remove the binding to a variable, but that code does not compile. You can find the example below

### Lint Name

let_and_return

### Reproducer

I tried this code:

```rust
use rusqlite::{named_params, Connection};

let conn = Connection::open_in_memory()?;
// [...]
let count: Option<u32> = {
    let mut stmt = conn.prepare("SELECT COUNT(*) FROM table WHERE id = :id")?;
    let c = stmt
        .query_map(
            named_params! {
                ":id": 1,
            },
            |r| r.get(0),
        )?
        .next()
        .transpose()?;
    c
};
```

(example can be found in [rdelfin/minrep-clippy-bug](https://github.com/rdelfin/minrep-clippy-bug/blob/main/src/main.rs)

I saw this happen: (after running `cargo clippy --fix`)

```
$ cargo clippy --fix
    Checking minrep-clippy-bug v0.1.0 (/Users/ricdelfin/code/minrep-clippy-bug)
warning: failed to automatically apply fixes suggested by rustc to crate `minrep_clippy_bug`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust-clippy/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0597]: `stmt` does not live long enough
  --> src/main.rs:12:9
   |
10 |           let mut stmt = conn.prepare("SELECT COUNT(*) FROM table WHERE id = :id")?;
   |               -------- binding `stmt` declared here
11 |
12 |           stmt
   |           -^^^
   |           |
   |  _________borrowed value does not live long enough
   | |
13 | |             .query_map(
14 | |                 named_params! {
15 | |                     ":id": 1,
16 | |                 },
17 | |                 |r| r.get(0),
18 | |             )?
   | |______________- a temporary with access to the borrow is created here ...
...
21 |       };
   |       -- ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `std::ops::ControlFlow<std::result::Result<std::convert::Infallible, rusqlite::Error>, rusqlite::MappedRows<'_, {closure@src/main.rs:17:17: 17:20}>>`
   |       |
   |       `stmt` dropped here while still borrowed
   |
   = note: the temporary is part of an expression at the end of a block;
           consider forcing this temporary to be dropped sooner, before the block's local variables are dropped
help: for example, you could save the expression's value in a new local variable `x` and then make `x` be the expression at the end of the block
   |
12 ~         let x = stmt
13 |             .query_map(
...
19 |             .next()
20 ~             .transpose()?; x
   |

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0597`.
Original diagnostics will follow.

warning: returning the result of a `let` binding from a block
  --> src/main.rs:20:9
   |
11 | /         let c = stmt
12 | |             .query_map(
13 | |                 named_params! {
14 | |                     ":id": 1,
...  |
18 | |             .next()
19 | |             .transpose()?;
   | |__________________________- unnecessary `let` binding
20 |           c
   |           ^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return
   = note: `#[warn(clippy::let_and_return)]` on by default
help: return the expression directly
   |
11 ~
12 ~         stmt
13 +             .query_map(
14 +                 named_params! {
15 +                     ":id": 1,
16 +                 },
17 +                 |r| r.get(0),
18 +             )?
19 +             .next()
20 +             .transpose()?
   |

warning: `minrep-clippy-bug` (bin "minrep-clippy-bug") generated 1 warning (run `cargo clippy --fix --bin "minrep-clippy-bug"` to apply 1 suggestion)
warning: failed to automatically apply fixes suggested by rustc to crate `minrep_clippy_bug`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust-clippy/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0597]: `stmt` does not live long enough
  --> src/main.rs:12:9
   |
10 |           let mut stmt = conn.prepare("SELECT COUNT(*) FROM table WHERE id = :id")?;
   |               -------- binding `stmt` declared here
11 |
12 |           stmt
   |           -^^^
   |           |
   |  _________borrowed value does not live long enough
   | |
13 | |             .query_map(
14 | |                 named_params! {
15 | |                     ":id": 1,
16 | |                 },
17 | |                 |r| r.get(0),
18 | |             )?
   | |______________- a temporary with access to the borrow is created here ...
...
21 |       };
   |       -- ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `std::ops::ControlFlow<std::result::Result<std::convert::Infallible, rusqlite::Error>, rusqlite::MappedRows<'_, {closure@src/main.rs:17:17: 17:20}>>`
   |       |
   |       `stmt` dropped here while still borrowed
   |
   = note: the temporary is part of an expression at the end of a block;
           consider forcing this temporary to be dropped sooner, before the block's local variables are dropped
help: for example, you could save the expression's value in a new local variable `x` and then make `x` be the expression at the end of the block
   |
12 ~         let x = stmt
13 |             .query_map(
...
19 |             .next()
20 ~             .transpose()?; x
   |

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0597`.
Original diagnostics will follow.

warning: `minrep-clippy-bug` (bin "minrep-clippy-bug" test) generated 1 warning (1 duplicate)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.18s
```

I expected to see this happen:

No output, lint should not apply

### Version

```text
rustc 1.84.1 (e71f9a9a9 2025-01-27)
binary: rustc
commit-hash: e71f9a9a98b0faf423844bf0ba7438f29dc27d58
commit-date: 2025-01-27
host: aarch64-apple-darwin
release: 1.84.1
LLVM version: 19.1.5
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by samueltardieu**
The first commit fixes #14164 by making sure that temporaries with non-static references are also looked for in expressions coming from expansion. The shortcut that was done skipped those parts and reported an absence of short-lived temporaries, which was incorrect.

The second commit distinguishes between edition 2024 and earlier ones. Starting from edition 2024, the problematic drop order has been fixed, and block variables, which might be referenced in a block expression, are freed after the block expression itself. This allows more `let_and_return` cases to be reported starting with edition 2024, whereas in earlier editions an intermediary variable was necessary to reorder the drops.

Incidentally, since Clippy is compiled in edition 2024 mode, the second commit has led to a fix in `clippy_lints/src/matches/significant_drop_in_scrutinee.rs`.

changelog: [`let_and_return`]: lint more cases in edition 2024, and fix a false positive involving short-lived block temporary variables in earlier editions.

### CODE REVIEW

File: tests/ui/let_and_return.rs [hunk 1]
```diff
@@ -244,4 +252,15 @@ fn issue12801() {
     }
 }
 
+// Do not lint
```
Comment (llogiq) [inline tests/ui/let_and_return.rs:255]: Should we change that to "Only lint in edition 2024 or later"?

**Review by llogiq — COMMENTED** [review]
That's a very thoroughly tested change. Great work! I have just one small question, otherwise this looks merge-worthy.

File: tests/ui/let_and_return.rs (hunk 1 above)
Comment (samueltardieu) [reply tests/ui/let_and_return.rs]: Good catch, thanks, comment removed in the second commit (and the error marker is explicit concerning which edition is concerned). I've let it in the first commit, as before separating the editions this is not linted.

**Comment by samueltardieu** [comment]
Note that this fix necessarily increases the risk of a false negative, but:

- no existing test switched to "no lint", and the newly added one would have been a false positive before the fix
- a false negative is less a problem than a false positive
- those false negatives will disappear as more people switch to edition 2024 which has no longer this drop order issue

**Comment by llogiq** [comment]
Thank you!
