### PR TITLE
[`let_underscore_untyped`]: fix false positive on async function

### LINKED ISSUE #12395: let_underscore_untyped false positive when using _ as a parameter name in an async function
### Summary

when naming a parameter `_` in an async function, the lint throws a false-positive

### Lint Name

let_underscore_untyped

### Reproducer

I tried this code:

```rust
async fn foo(_: u8) {}
```

I saw this happen:

```
warning: non-binding `let` without a type annotation
   --> src/main.rs:1:14
    |
115 | async fn foo(_: u8) {}
    |              ^
    |
help: consider adding a type annotation
   --> src/main.rs:1:15
    |
115 | async fn foo(_: u8) {}
    |               ^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_untyped
```

I expected to see this happen:
no warning

### Version

```text
rustc -Vv
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: aarch64-apple-darwin
release: 1.76.0
LLVM version: 17.0.6
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by samueltardieu**
changelog: [`let_underscore_untyped`]: fix false positive on async function

Fix #12395

### CODE REVIEW

File: clippy_lints/src/let_underscore.rs [hunk 1]
```diff
@@ -200,7 +200,7 @@ impl<'tcx> LateLintPass<'tcx> for LetUnderscore {
                 }
 
                 // Ignore if it is from a procedural macro...
-                if is_from_proc_macro(cx, init) {
+                if is_from_proc_macro(cx, init) || init.span.from_expansion() {
```
Comment (Alexendoo) [inline clippy_lints/src/let_underscore.rs:203]: Let's check if `local.source` is `Normal` at the top of the function since it would be fine to lint `let _ = some_macro!();`, we can remove the `default_binding_modes` check also in that case

Comment (samueltardieu) [reply clippy_lints/src/let_underscore.rs]: Indeed, I hadn't noticed the `source` field. Done.

**Review by Alexendoo — APPROVED** [review]

**Comment by Alexendoo** [comment]
Thanks! @bors r+
