### PR TITLE
`arc_with_non_send_sync`: reword and move to `suspicious`

### LINKED ISSUE #11079: Deny-by-default is too strong for `arc_with_non_send_sync`
### Summary

The recently added `arc_with_non_send_sync` is deny-by-default. The description claims that "Wrapping a type in Arc doesn’t add thread safety to the underlying data, so data races could occur when touching the underlying data.". However, this is only true in the presence of unsafe code - when this lint fires, the `Arc` itself will be `!Send/!Sync`, preventing it from being shared between threads by safe code (and sound unsafe code).

This lint fired several times in my project - while it's a legitimate lint, I think warn-by-default would be a more reasonable setting.

### Reproducer

I tried this code:

```rust
use std::cell::Cell;
use std::sync::Arc;

fn main() {
    let _a = Arc::new(Cell::new(0));
}
```

I expected to see this happen:

A warn-by-default lint.

Instead, this happened:

```
error: usage of `Arc<T>` where `T` is not `Send` or `Sync`
 --> src/main.rs:5:14
  |
5 |     let _a = Arc::new(Cell::new(0));
  |              ^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: consider using `Rc<T>` instead or wrapping `T` in a std::sync type like `Mutex<T>`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#arc_with_non_send_sync
  = note: `#[deny(clippy::arc_with_non_send_sync)]` on by default
```

### Version

```text
rustc 1.72.0-nightly (839e9a6e1 2023-07-02)
binary: rustc
commit-hash: 839e9a6e1210934fd24b15548b811a97c77138fc
commit-date: 2023-07-02
host: x86_64-unknown-linux-gnu
release: 1.72.0-nightly
LLVM version: 16.0.5
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by Alexendoo**
Fixes #11079

changelog: [`arc_with_non_send_sync`]: move to complexity

### CODE REVIEW

File: clippy_lints/src/arc_with_non_send_sync.rs [hunk 1]
```diff
@@ -16,61 +15,65 @@ declare_clippy_lint! {
...
-    ///     // This is not safe, as `RefCell` does not implement `Sync`.
+    ///     // `RefCell` is `!Sync`, so either the `Arc` should be replaced with an `Rc`
+    ///     // or the `RefCell` replaced with something like a `RwLock`
     ///     let b = Arc::new(RefCell::new(42));
     /// }
     /// ```
     #[clippy::version = "1.72.0"]
     pub ARC_WITH_NON_SEND_SYNC,
-    correctness,
+    complexity,
```
Comment (Centri3) [inline clippy_lints/src/arc_with_non_send_sync.rs:37]: I'd say this fits better in `suspicious`. This doesn't really make code more complex

**Comment by Alexendoo** [comment]
The regex crate updated which is the cause of the test failures, I'll fix that shortly in a separate PR

**Review by Centri3 — APPROVED** [review]

**Comment by Centri3** [comment]
I'm happy with this. Thanks! Just need to wait for the other PR to be merged, I suppose

Nice `if_chain!` -> let chains, btw.

cc @Manishearth

**Comment by Manishearth** [comment]
(@Alexendoo feel free to r=Centri3 when ready)
