### PR TITLE
if_same_then_else: don't assume multiplication is always commutative

### LINKED ISSUE #5698: False positive for `if_same_then_else`
I'm getting what I think is a false positive for the `if_same_then_else` lint

For this function
```rust
pub fn euclidean_length(&self) -> T {
    if self.columns() == 1 {
        // column vector
        (self.transpose() * self).scalar().sqrt()
    } else if self.rows() == 1 {
        // row vector
        (self * self.transpose()).scalar().sqrt()
    } else {
        panic!("Cannot compute unit vector of a non vector, rows: {}, columns: {}",
            self.rows(), self.columns());
    }
}
```

clippy returns an error
```
error: this `if` has identical blocks
   --> src/matrices/mod.rs:830:36
    |
830 |           } else if self.rows() == 1 {
    |  ____________________________________^
831 | |             // row vector
832 | |             (self * self.transpose()).scalar().sqrt()
833 | |         } else {
    | |_________^
    |
    = note: `#[deny(clippy::if_same_then_else)]` on by default
note: same as this
   --> src/matrices/mod.rs:827:32
    |
827 |           if self.columns() == 1 {
    |  ________________________________^
828 | |             // column vector
829 | |             (self.transpose() * self).scalar().sqrt()
830 | |         } else if self.rows() == 1 {
    | |_________^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#if_same_then_else
```

These two blocks are not the same, the order of the matrices on each side of the `*` make the difference between computing the inner product or the outer product.

### PR DESCRIPTION
**Pull request by ebroto**
changelog: Don't assume multiplication is always commutative in [`if_same_then_else`]

Fixes #5698

### CODE REVIEW

File: clippy_lints/src/utils/hir_utils.rs [hunk 1]
```diff
@@ -309,18 +309,15 @@ fn swap_binop<'a>(
...
-        | BinOpKind::BitOr => Some((binop, rhs, lhs)),
+        BinOpKind::Add | BinOpKind::Eq | BinOpKind::Ne | BinOpKind::BitAnd | BinOpKind::BitXor | BinOpKind::BitOr => {
+            Some((binop, rhs, lhs))
+        },
         BinOpKind::Lt => Some((BinOpKind::Gt, rhs, lhs)),
         BinOpKind::Le => Some((BinOpKind::Ge, rhs, lhs)),
         BinOpKind::Ge => Some((BinOpKind::Le, rhs, lhs)),
         BinOpKind::Gt => Some((BinOpKind::Lt, rhs, lhs)),
-        BinOpKind::Shl
+        BinOpKind::Mul
```
Comment (matthiaskrgr) [inline clippy_lints/src/utils/hir_utils.rs:319]: I'd like to have a comment here that there were false positives involving matrices, besides this, r=me :) 

This also makes me wonder if we could differentiate between primitive types and structs (like matrices etc), either way, the change looks fine to me.

@bors delegate=ebroto

**Comment by matthiaskrgr** [comment]
Let's try this again...
@bors delegate=ebroto

File: clippy_lints/src/utils/hir_utils.rs (hunk 1 above)
Comment (ebroto) [reply clippy_lints/src/utils/hir_utils.rs]: I thought about it, but wasn't sure if it was worth the trouble TBH

**Comment by flip1995** [comment]
@matthiaskrgr To give privileges to the author you also can just comment `delegate+` 👍 (Also bors commands don't work in any review comments)
