### PR TITLE
[significant_drop_tightening] Fix #10413

### LINKED ISSUE #10413: Incorrect suggestion for has_significant_drop
### Summary

The has_significant_drop lint only (seems to) considers the first usage of a locked value and suggests an incorrect correction of the code.

### Lint Name

has_significant_drop

### Reproducer

The code comes from https://github.com/Thomasdezeeuw/heph/blob/8be6cfa97d6870cc7e086e63e32608976c6d76f1/inbox/src/lib.rs#L519-L529. The relevant part:

```rust
    // self.registered_waker: Option<task::Waker>
    // self.channel.sender_wakers: Mutex<Vec<task::Waker>>
        if let Some(waker) = self.registered_waker.take() {
            let mut sender_wakers = self.channel.sender_wakers.lock().unwrap();
            let idx = sender_wakers.iter().position(|w| w.will_wake(&waker));
            if let Some(idx) = idx {
                let waker = sender_wakers.swap_remove(idx);
                unlock(sender_wakers);
                drop(waker);
            }
        }
```

The suggestion Clippy makes:

```
error: temporary with significant `Drop` can be early dropped
   --> inbox/src/lib.rs:523:21
    |
522 |           if let Some(waker) = self.registered_waker.take() {
    |  ___________________________________________________________-
523 | |             let mut sender_wakers = self.channel.sender_wakers.lock().unwrap();
    | |                     ^^^^^^^^^^^^^
524 | |             let idx = sender_wakers.iter().position(|w| w.will_wake(&waker));
525 | |             if let Some(idx) = idx {
...   |
529 | |             }
530 | |         }
    | |_________- temporary `sender_wakers` is currently being dropped at the end of its contained scope
    |
    = note: this might lead to unnecessary resource contention
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#significant_drop_tightening
    = note: `-D clippy::significant-drop-tightening` implied by `-D clippy::nursery`
help: merge the temporary construction with its single usage
    |
523 ~
524 +             let idx = self.channel.sender_wakers.lock().unwrap().position(|w| w.will_wake(&waker));
    |
help: remove separated single usage
    |
524 -             let idx = sender_wakers.iter().position(|w| w.will_wake(&waker));
524 +
    |
```

We can't move the lock into the line with `idx` as `sender_wakers` (the locked value) is used later on. Clippy however doesn't seem to see/understand this.

I guess the basic problem is that Clippy is only considering a single use of the locked value, while in the code above their are two uses.

### Version

```text
rustc 1.69.0-nightly (d962ea578 2023-02-26)
binary: rustc
commit-hash: d962ea57899d64dc8a57040142c6b498a57c8064
commit-date: 2023-02-26
host: x86_64-apple-darwin
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Additional Labels

@rustbot label+I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by c410-f3r**
Fix #10413

This is quite a rewrite that unfortunately took a  large amount of time. I tried my best to comment what is going on to easy review but feel free to ask any question.

The problem basically is that the current algorithm is only taking into consideration single blocks which means that things like the following don't work or show unpredictable results.

```rust
let mutex = Mutex::new(1);
{
  let lock = mutex.lock().unwrap();
  {
    let _ = *lock;
  }
}
```

The solve the issue, each path that refers a lock is now being tracked individually.

```
changelog: [`significant_drop_tightening`]: Lift the restriction of only considerate single blocks
```

### CODE REVIEW

**Comment by c410-f3r** [comment]
@dswij I can re-roll if you don't have time to review

**Comment by dswij** [comment]
Sorry for the delay, I had started to look into this but then fell a bit ill last week. I will take a look asap

File: clippy_lints/src/significant_drop_tightening.rs [hunk 1]
```diff
@@ -350,73 +208,244 @@ impl<'cx, 'sdt, 'tcx> SigDropChecker<'cx, 'sdt, 'tcx> {
...
+            self.manage_has_expensive_expr_after_last_attr();
+        }
+        if let Some(expr) = block.expr {
+            self.ap.curr_stmt = Cow::Owned(dummy_stmt_expr(expr));
+            self.visit_expr(expr);
+            self.ap.curr_block_hir_id = block.hir_id;
+            self.ap.curr_block_span = block.span;
+            self.manage_has_expensive_expr_after_last_attr();
         }
+    }
```
Comment (dswij) [inline clippy_lints/src/significant_drop_tightening.rs:282]: I'm not sure if I understand completely, but I think this is the difference with the previous implementation? i.e. now we check for blocks and any nested block?

Comment (c410-f3r) [reply clippy_lints/src/significant_drop_tightening.rs:282]: The previous algorithm used to check all individual occurrences of `Block` through `LateLintPass::check_block` but now everything starts in the root block of `fn`through `LateLintPass::check_fn` to properly track the subsequent nested block children.

**Comment by c410-f3r** [comment]
There is still related work to be done that I would like to continue pursuing with this PR merged, as such, I will try another reviewer.

r? clippy

**Comment by Jarcho** [comment]
With a quick look this seems ok.

With that said, getting this lint to a state where it could be removed from the nursery will requiring rewriting this as a MIR lint. It needs to be able to track lifetimes for it to not have a large number of false positives. e.g. 
```rust
let mut locked = foo.lock();
let borrow = &mut *locked;
let references_borrow = bar(borrow);
// and so on
```

**Comment by c410-f3r** [comment]
Yeah, such thing will allow me to close #9399 but something tells me that it will take a long time to finish :)

**Comment by c410-f3r** [comment]
@Jarcho I can re-roll again if you don't have the time to review

**Comment by Jarcho** [comment]
Sorry, I've been sick the past few weeks.

Since this is in the nursery I'll consider the lint still a WIP. I'll just reiterate that you can't fully fix this lint at the HIR level. You can reference `needless_clone` for how to write a MIR lint the needs to deal with lifetimes.

Since there doesn't seem to be any new issues added with this. @bors r+

**Comment by c410-f3r** [comment]
The CI failure has been fixed.Thank you, @Jarcho!
