### PR TITLE
Fix FP in `same_item_push`

### LINKED ISSUE #5979: same_item_push being suggested for values that are not Copy or Clone
Similar to #5902 but instead of a mutated value, it's suggesting it for a value that is not `Copy` nor `Clone`.

Silly example:

```rust
fn main() {
    let mut vec = vec![];
    for _ in 0 .. 10 {
        vec.push(std::fs::File::open("foobar").unwrap());
    }
}
```

This gives the warning:

```
warning: it looks like the same item is being pushed into this Vec
 --> src/main.rs:4:9
  |
4 |         vec.push(std::fs::File::open("foobar").unwrap());
  |         ^^^
  |
  = note: `#[warn(clippy::same_item_push)]` on by default
  = help: try using vec![std::fs::File::open("foobar").unwrap();SIZE] or vec.resize(NEW_SIZE, std::fs::File::open("foobar").unwrap())
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#same_item_push
```

Note the suggested replacements don't even compile.

### Meta

- `cargo clippy -V`: clippy 0.0.212 (397b390cc 2020-08-27)
- `rustc -Vv`:
```
rustc 1.48.0-nightly (397b390cc 2020-08-27)
binary: rustc
commit-hash: 397b390cc76ba1d98f80b2a24a371f708dcc9169
commit-date: 2020-08-27
host: x86_64-pc-windows-msvc
release: 1.48.0-nightly
LLVM version: 11.0
  ```

### PR DESCRIPTION
**Pull request by giraffate**
Don't emit a lint when the pushed item doesn't have Clone trait

Fix #5979

changelog: Fix FP in `same_item_push` not to emit a lint when the pushed item doesn't have Clone trait

### CODE REVIEW

**Comment by ebroto** [comment]
r? @ebroto 

(Will dig into this later)

File: clippy_lints/src/loops.rs [hunk 1]
```diff
@@ -1140,43 +1140,51 @@ fn detect_same_item_push<'tcx>(
...
-                                SAME_ITEM_PUSH,
-                                vec.span,
-                                "it looks like the same item is being pushed into this Vec",
-                                None,
-                                &format!(
-                                    "try using vec![{};SIZE] or {}.resize(NEW_SIZE, {})",
-                                    item_str, vec_str, item_str
-                                ),
-                            )
+            let ty = cx.typeck_results().expr_ty(pushed_item);
```
Comment (ebroto) [inline clippy_lints/src/loops.rs:1143]: We should use the `T` in `Vec<T>` instead of the type of the pushed item, as those could differ if coercion kicks in. For example this would still be linted:
```rust
#[derive(Clone)]
struct S {}

trait T {}
impl T for S {}

fn test() {
    let mut vec: Vec<Box<dyn T>> = Vec::new();
    for _ in 0..10 {
        vec.push(Box::new(S{}));
    }
    vec.resize(20, Box::new(S{})); // => this gives a compilation error, resize not implemented for Vec<Box<dyn T>>
}
``` 

We can get the type parameter using `vec_ty.walk().nth(1).unwrap().expect_ty();`. `vec_ty` can be obtained using `expr_ty` on the `vec` variable.

**Review by ebroto — CHANGES_REQUESTED** [review]
Besides the requested change, I think we should restrict `same_item_push` to just literals and constants (and immutable bindings that are initialized with those). Allowing the pushed item to be an arbitrary expression is very difficult to get right as there are many possibilities for false positives. For example, the very same function used in the test can return different values when called multiple times.

Would you be up to do that change, either in this PR or in a follow-up?

File: clippy_lints/src/loops.rs (hunk 1 above)
Comment (giraffate) [reply clippy_lints/src/loops.rs]: Thanks for your review! I fixed it.

**Comment by giraffate** [comment]
@ebroto Thanks for your comment! I agree with restricting `same_item_push` to suppress many false positives. 

> I think we should restrict same_item_push to just literals and constants (and immutable bindings that are initialized with those).

I have a question. In the above restriction, does this test emit a lint? This pattern is mentioned in the original issue https://github.com/rust-lang/rust-clippy/issues/4078 of `same_item_push`.

https://github.com/rust-lang/rust-clippy/blob/f98ffa271d0112d04b482e1d61228d99bf006ccf/tests/ui/same_item_push.rs#L13-L17


> Would you be up to do that change, either in this PR or in a follow-up?

I will prepare a follow-up PR.

**Comment by ebroto** [comment]
> I have a question. In the above restriction, does this test emit a lint? This pattern is mentioned in the original issue #4078 of same_item_push.

I think we should keep it simple for now and not special case this. We can always extend the lint later, but IMO the simpler approach will still be valuable to those that are not familiar with `resize()` and `vec![x; N]`.

These are the cases I had in mind:
```rust
const VALUE: usize = 42; // doesn't matter how it's initialized

fn main() {
    let mut vec = Vec::new();
    for _ in 0..20 {
        vec.push(42); // literal
    }

    let mut vec = Vec::new();
    for _ in 0..20 {
        vec.push(VALUE); // constant
    }

    // For bindings, we should check if shadowing is involved

    let mut vec = Vec::new();
    let x = 42; // immutable, initialized with literal, could be inside the loop
    for _ in 0..20 {
        vec.push(x);
    }

    let mut vec = Vec::new();
    let x = VALUE; // immutable, initialized with constant, could be inside the loop
    for _ in 0..20 {
        vec.push(x);
    }
}

```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4ae83a46b595becac8bda85ee6ec0831))

> I will prepare a follow-up PR.

Great, thanks in advance!

**Comment by ebroto** [comment]
@bors r+

Thanks!

**Review by ebroto — APPROVED** [review]

**Comment by giraffate** [comment]
> I think we should keep it simple for now and not special case this. We can always extend the lint later, but IMO the simpler approach will still be valuable to those that are not familiar with resize() and vec![x; N].

Ok, I agree with you. Thanks!
