### PR TITLE
[`redundant_closure_call`]: avoid duplicated `async` keyword when triggering on closure that returns `async` block

### LINKED ISSUE #11357: redundant_closure_call: suggestion does not work if inner expression is async block
### Summary

Suggestion does not work if the inner expression is `async` block.

### Reproducer

I tried this code:

```rust
let x = (|| async {})().await;
```

I expected to see this happen:

```rust
let x = async {}.await;
```

Instead, this happened:

```rust
let x = async async {}.await;
```

### Version

```text
rustc 1.73.0-nightly (31395ec38 2023-07-24)
binary: rustc
commit-hash: 31395ec38250b60b380fd3c27e94756aba3557de
commit-date: 2023-07-24
host: x86_64-unknown-linux-gnu
release: 1.73.0-nightly
LLVM version: 16.0.5
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by KisaragiEffective**
close #11357

----

*Please write a short comment explaining your change (or "none" for internal only changes)*

changelog: [`redundant_closure_call`]: avoid duplicated `async` keyword when triggering on closure that returns `async` block

### CODE REVIEW

File: clippy_lints/src/redundant_closure_call.rs [hunk 1]
```diff
@@ -62,9 +62,9 @@ impl<'tcx> Visitor<'tcx> for ReturnVisitor {
 
 /// Checks if the body is owned by an async closure
 fn is_async_closure(body: &hir::Body<'_>) -> bool {
-    if let hir::ExprKind::Closure(closure) = body.value.kind
-        && let [resume_ty] = closure.fn_decl.inputs
-        && let hir::TyKind::Path(hir::QPath::LangItem(hir::LangItem::ResumeTy, ..)) = resume_ty.kind
+    if let hir::ExprKind::Closure(_) = body.value.kind
+        && let Some(kind) = body.generator_kind
+        && kind == GeneratorKind::Async(AsyncGeneratorKind::Closure)
```
Comment (llogiq) [inline clippy_lints/src/redundant_closure_call.rs:67]: Could we pull those statements together? As in

```suggestion
        && let Some(GeneratorKind::Async(AsyncGeneratorKind::Closure)) = body.generator_kind
```

**Review by llogiq — COMMENTED** [review]
I'm not sure how to make it work right now. Let's see if the discussion on zulip brings a solution.

File: clippy_lints/src/redundant_closure_call.rs [hunk 2]
```diff
@@ -61,10 +61,15 @@ impl<'tcx> Visitor<'tcx> for ReturnVisitor {
...
-        && let hir::TyKind::Path(hir::QPath::LangItem(hir::LangItem::ResumeTy, ..)) = resume_ty.kind
+fn is_async_closure(cx: &LateContext<'_>, body: &hir::Body<'_>) -> bool {
+    if let hir::ExprKind::Closure(desugared_outer_closure) = body.value.kind
+        && let desugared_outer_closure_body = cx.tcx.hir().body(desugared_outer_closure.body)
+        && let hir::ExprKind::Closure(desugared_inner_closure) = desugared_outer_closure_body.value.kind
+        // NB: `async || 42` is desugared into `|| |mut __context: #[lang = "ResumeTy"] | 42`; so
+        //     we need to check if the only input was that lang item.
+        && let [compiler_generated_resume_ty] = desugared_inner_closure.fn_decl.inputs
+        && let hir::TyKind::Path(hir::QPath::LangItem(hir::LangItem::ResumeTy, ..)) =
+            compiler_generated_resume_ty.kind
```
Comment (y21) [inline clippy_lints/src/redundant_closure_call.rs:72]: This fixes it for me and seems to pass all tests (modulo nits; might need to fmt, etc...)
```suggestion
    if let hir::ExprKind::Closure(desugared_inner_closure) = body.value.kind
        && let desugared_inner_closure_body = cx.tcx.hir().body(desugared_inner_closure.body)
        && let Some(GeneratorKind::Async(AsyncGeneratorKind::Closure)) = desugared_inner_closure_body.generator_kind
```

I think I explained it confusingly on zulip yesterday, sorry for that. The `body: &hir::Body<'_>` that this function receives is already the **outer** closure body, so the variable name on line 65 "desugared_outer_closure" is not right. That is already the inner closure. There's no other closures after it, so trying to get another closure won't work.
This is also why the async closure `(async || 2)().await` tests failed: this function would never return true. It's trying to get one closure too much

File: clippy_lints/src/redundant_closure_call.rs [hunk 3]
```diff
@@ -155,14 +157,15 @@ impl<'tcx> LateLintPass<'tcx> for RedundantClosureCall {
...
+                            if let hir::ExprKind::Closure(closure) = body.kind {
+                                let async_closure_body = cx.tcx.hir().body(closure.body);
 
-                            // `async x` is a syntax error, so it becomes `async { x }`
-                            if !matches!(async_closure_body.value.kind, hir::ExprKind::Block(_, _)) {
-                                hint = hint.blockify();
+                                // `async x` is a syntax error, so it becomes `async { x }`
+                                if !matches!(async_closure_body.value.kind, hir::ExprKind::Block(_, _)) {
+                                    hint = hint.blockify();
+                                }
```
Comment (y21) [inline clippy_lints/src/redundant_closure_call.rs:168]: Does this part of the diff functionally change anything? As far as I can tell, only indendation changed and the closure check was moved into its own `if`, right? Is that necessary? I believe this isn't technically right or wrong, because this check always succeeds if `generator_kind` is async (this check was already done in `is_async_closure`), but afaict it does it here again to get the inner closure body to figure out if we have `async || 1`, in which case it needs to add a block: `async { 1 }`, or if the body is already a block: `async || { 1 }`, in which case calling `blockify` is unnecessary (would result in `async { { 1 } }`

**Comment by KisaragiEffective** [comment]
rebased.

**Comment by y21** [comment]
CI is failing, do you need help with this or is this still a wip?

**Comment by KisaragiEffective** [comment]
This is still wip, I think I have reverted necessary commit.

**Comment by llogiq** [comment]
@rustbot author

@KisaragiEffective Please tell rustbot "review" when you've got the PR ready for review. Or do you need any help going forward?

File: tests/ui/redundant_closure_call_fixable.rs [hunk 4]
```diff
@@ -84,3 +85,17 @@ fn issue9956() {
...
+    (|| async {})().await;
+}
+
+mod issue11707 {
+    use core::future::Future;
+
+    fn spawn_on(fut: impl Future<Output = ()>) {}
+
+    fn demo() {
+        spawn_on(((|| async move {})()));
```
Comment (KisaragiEffective) [inline tests/ui/redundant_closure_call_fixable.rs:99]: Note for self: remove double-paren

**Comment by llogiq** [comment]
Looks good to me. Thank you!

@bors r+
