### PR TITLE
Fix `let_unit_value` suggests wrongly for format macros

### LINKED ISSUE #15061: The suggestion of  let_unit_value is invalid when the value is used in formatted in print
### Description

```
let res = returns_unit();
returns_result(res).unwrap();
println!("The result is {res:?}");
```
The suggestion of above code is 
```
help: omit the `let` binding and replace variable usages with `()`
   |
22 ~     returns_unit();
23 ~     returns_result(()).unwrap();
24 ~     println!("The result is {():?}");
```
But `println!("The result is {():?}");` is not valid.

### Version

```text
rustc 1.86.0 (05f9846f8 2025-03-31)
binary: rustc
commit-hash: 05f9846f893b09a1be1fc8560e33fc3c815cfecb
commit-date: 2025-03-31
host: aarch64-apple-darwin
release: 1.86.0
LLVM version: 19.1.7
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by profetia**
Closes rust-lang/rust-clippy#15061

changelog: [`let_unit_value`] fix wrong suggestions for format macros

### CODE REVIEW

**Comment by profetia** [comment]
r? clippy

**Comment by profetia** [comment]
r? clippy

File: tests/ui/let_unit.rs [hunk 1]
```diff
@@ -198,3 +198,13 @@ pub fn issue12594() {
...
 }
+
+fn issue15061() {
+    fn return_unit() {}
+    fn do_something(x: ()) {}
+
+    let res = return_unit();
+    //~^ let_unit_value
+    do_something(res);
+    println!("{res:?}");
```
Comment (ada4a) [inline tests/ui/let_unit.rs:209]: Would it be possible to include a (non-machine-applicable) suggestion to remove this `res` as well? Then we could get rid of `let res = ` entirely

Comment (llogiq) [reply tests/ui/let_unit.rs:209]: I'm ok with this PR as is. Further improvements can have their own PRs, as a treat.

**Comment by llogiq** [comment]
Thank you!
