### PR TITLE
don't lint field_reassign when field in closure

### LINKED ISSUE #10136: `field_reassign_with_default` false positive with closure capturing variable that was initialized to default
### Summary

The `field_reassign_with_default` lint performs a check to make sure that the the reassignment does not involve the variable that was initialized with `default()`, but this check fails if the variable is captured by a closure.

### Lint Name

field_reassign_with_default

### Reproducer

I tried this code:

```rust
struct Collection {
    items: Vec<i32>,
    len: usize,
}

impl Default for Collection {
    fn default() -> Self {
        Self {
            items: vec![1, 2, 3],
            len: 0,
        }
    }
}

fn main() {
    let mut c = Collection::default();
    c.len = (|| c.items.len())();
}
```

I saw this happen:

```
warning: field assignment outside of initializer for an instance created with Default::default()
  --> src/main.rs:17:5
   |
17 |     c.len = (|| c.items.len())();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: consider initializing the variable with `Collection { len: (|| c.items.len())(), ..Default::default() }` and removing relevant reassignments
  --> src/main.rs:16:5
   |
16 |     let mut c = Collection::default();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#field_reassign_with_default
   = note: `#[warn(clippy::field_reassign_with_default)]` on by default

```

I expected to see this happen:

The lint should not trigger since the expression that `c.len` is being reassigned to involves `c`, making the suggestion invalid.

### Version

```text
rustc 1.66.0 (69f9c33d7 2022-12-12)
binary: rustc
commit-hash: 69f9c33d71c871fc16ac445211281c6e7a340943
commit-date: 2022-12-12
host: x86_64-unknown-linux-gnu
release: 1.66.0
LLVM version: 15.0.2
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by EricWu2003**
fixes #10136 

This change makes the ContainsName struct visit all interior expressions, which means that ContainsName will return true even if `name` is used in a closure within `expr`.

---

changelog: FP: [`field_reassign_with_default`]: No longer lints cases, where values are initializes from closures capturing struct values
[#10143](https://github.com/rust-lang/rust-clippy/pull/10143)

### CODE REVIEW

**Comment by EricWu2003** [comment]
Could someone advise on whether I should be using `nested_filter::All` or `nested_filter::OnlyBodies`? I did not understand the documentation very well for these two structs.

File: clippy_utils/src/lib.rs [hunk 1]
```diff
@@ -1253,22 +1255,33 @@ pub fn get_item_name(cx: &LateContext<'_>, expr: &Expr<'_>) -> Option<Symbol> {
...
-pub struct ContainsName {
+pub struct ContainsName<'a, 'tcx> {
+    pub cx: &'a LateContext<'tcx>,
     pub name: Symbol,
     pub result: bool,
 }
 
-impl<'tcx> Visitor<'tcx> for ContainsName {
+impl<'a, 'tcx> Visitor<'tcx> for ContainsName<'a, 'tcx> {
+    type NestedFilter = nested_filter::All;
```
Comment (Manishearth) [inline clippy_utils/src/lib.rs:1265]: yeah i think it should be OnlyBodies here, All includes things like impls, etc, whereas OnlyBodies just covers closures and consts.

We actually don't want to include consts but that's niche enough and it doesn't hurt to check extra

Comment (EricWu2003) [reply clippy_utils/src/lib.rs]: 👍 Thanks. I made a change to use `nested_filter::OnlyBodies` instead.

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
are you ready for merging, or is this a draft for some other reason too?

**Comment by EricWu2003** [comment]
I was ready for merging. Sorry, I forgot to remove the draft marker.

**Comment by Manishearth** [comment]
@bors r+

Thanks!!
