### PR TITLE
Fix to_string_in_format_args in parens

### LINKED ISSUE #9540: Incorrect fix for to_string_in_format_args
~I just discovered another bug in the format args parser `FormatArgsExpn::parse` while creating more tests for #9233.~

Add this test case to the [tests/ui/format_args.rs](https://github.com/rust-lang/rust-clippy/blob/master/tests/ui/format_args.rs) `main()` to see it fail:

```rust
print!("error: something failed at {}", (Location::caller().to_string()));
//                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  (does not include parens)
```

~The resulting `format_args.args[0].param.value` has a span does NOT include the surrounding parenthesis, which means that it suggest this:~

Auto-fix is incorrectly suggesting this:

```
error: `to_string` applied to a type that implements `Display` in `print!` args
  --> $DIR/format_args.rs:86:64
   |
LL |     print!("error: something failed at {}", (Location::caller().to_string()));
   |                                                                ^^^^^^^^^^^^^ help: remove this
```

which results in an incompilabre

```rust
print!("error: something failed at {}", (Location::caller());  // <-- missing closing parenthesis
````

cc: @Alexendoo

### PR DESCRIPTION
**Pull request by nyurik**
Fix suggestions like

```
print!("error: something failed at {}", (Location::caller().to_string()));
```

where the parenthesis enclose some portion of the value.

Fixes #9540

changelog: [`to_string_in_format_args`]: fix incorrect fix when value is enclosed in parenthesis

### CODE REVIEW

File: tests/ui/format_args.rs [hunk 1]
```diff
@@ -114,6 +115,16 @@ fn main() {
...
+    print!("{}", (Location::caller().to_string()));
+    print!("{}", ((Location::caller()).to_string()));
+    #[rustfmt::skip]
+    print!("{}", (Location::caller()
+        .
+        to_string()));
+    #[rustfmt::skip]
+    print!("{}", ((Location::caller())
+        .
+        to_string()));
```
Comment (Alexendoo) [inline tests/ui/format_args.rs:127]: Can remove these since they're the same as the above two aside from formatting

```suggestion
```

Comment (nyurik) [reply tests/ui/format_args.rs:127]: @Alexendoo I made it this way on purpose because I wanted to ensure that the surround spacing is also captured.  I didn't want to just grab the dot, i wanted to grab everything after the ending of the prior expression.

**Comment by nyurik** [comment]
CC: @llogiq in case you want to look at this one too - similar to the format args one

File: tests/ui/format_args.rs (hunk 1 above)
Comment (Alexendoo) [reply tests/ui/format_args.rs:127]: Sorry for the delay! 😅 

Generally we don't need to worry about whitespace to that degree as rustfmt will take care of it

**Review by Alexendoo — APPROVED** [review]

**Comment by Alexendoo** [comment]
Thanks!

@bors r+
