### PR TITLE
Fix ICE caused in unwrap module

### LINKED ISSUE #5579: assert panics in unwrap lint
Clippy panics during linting of this code:

```
trait IsErr {
    fn is_err(&self, err: &str) -> bool;
}

impl<T> IsErr for Option<T> {
    fn is_err(&self, _err: &str) -> bool {
        true
    }
}

fn main() {
    let t = Some(1);

    if t.is_err("") {
        t.unwrap();
    }
}
```

https://github.com/rust-lang/rust-clippy/blob/ceddf34b2ec054e704166914da0e1fe0cab1a45c/clippy_lints/src/unwrap.rs#L113

Something like this should do the trick:
```
is_type_diagnostic_item(cx, ty, sym!(option_type))
        && ["is_some", "is_none"].contains(&&*name)
        || is_type_diagnostic_item(cx, ty, sym!(result_type))
            && ["is_ok", "is_err"].contains(&&*name)
```

### PR DESCRIPTION
**Pull request by ebroto**
changelog: Fix ICE in unwrap module with unexpected number of parameters for method of Option/Result

Fixes #5579

### CODE REVIEW

File: tests/ui/checked_unwrap/simple_conditionals.rs [hunk 1]
```diff
@@ -78,3 +78,24 @@ fn main() {
 
     assert!(x.is_ok(), "{:?}", x.unwrap_err()); // ok, it's a common test pattern
 }
+
+mod issue_5579 {
```
Comment (flip1995) [inline tests/ui/checked_unwrap/simple_conditionals.rs:82]: Can you move this test in its own file in the crashes dir: `tests/ui/crashes/ice-5579.rs`
