### PR TITLE
`invalid_null_ptr_usage`: fix false positives for `std::ptr::slice_from_raw_parts` functions

### LINKED ISSUE #13445: False positive for invalid null pointer usage lint when creating raw slice pointer
### Summary

Null slice pointers are valid Rust (i.e. `*[T]`), and only a null slice reference (`&[T]`) is actually a problem and leads to undefined behavior, but Clippy unnecessarily complains that it is "invalid" to create a null slice pointer and falsely asserts that it must be non-null. The offending lines are here: https://github.com/rust-lang/rust-clippy/blob/dbcd82885f4730077fabd57340d7e297122bc596/clippy_lints/src/ptr.rs#L255-256

### Lint Name

invalid_null_ptr_usage

### Reproducer

Here is a reproducible example that erroneously emits the warning:

```rust
#[warn(clippy::invalid_null_ptr_usage)]

fn main() {
    let _: *const [u8] = std::ptr::slice_from_raw_parts(std::ptr::null(), 0);
}
```

The output is:

```
warning: pointer must be non-null
 --> src/main.rs:4:57
  |
4 |     let _: *const [u8] = std::ptr::slice_from_raw_parts(std::ptr::null(), 0);
  |                                                         ^^^^^^^^^^^^^^^^ help: change this to: `core::ptr::NonNull::dangling().as_ptr()`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#invalid_null_ptr_usage
note: the lint level is defined here
 --> src/main.rs:1:8
  |
1 | #[warn(clippy::invalid_null_ptr_usage)]
```

### Version

rustc 1.83.0-nightly (7042c269c 2024-09-23)
binary: rustc
commit-hash: 7042c269c166191cd5d8daf0409890903df7af57
commit-date: 2024-09-23
host: x86_64-unknown-linux-gnu
release: 1.83.0-nightly
LLVM version: 19.1.0

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by ljgermain**
fixes #13445
changelog: [`invalid_null_ptr_usage`]: fix false positives for `std::ptr::slice_from_raw_parts` functions

### CODE REVIEW

File: tests/ui/invalid_null_ptr_usage.rs [hunk 1]
```diff
@@ -25,11 +25,6 @@ fn main() {
 
         let _a: A = std::ptr::replace(std::ptr::null_mut(), A);
 
-        let _slice: *const [usize] = std::ptr::slice_from_raw_parts(std::ptr::null(), 0);
```
Comment (Centri3) [inline tests/ui/invalid_null_ptr_usage.rs:28]: This shouldn't be removed, this should end up checking that it doesn't lint instead

File: clippy_lints/src/ptr.rs [hunk 2]
```diff
@@ -277,8 +277,6 @@ fn check_invalid_ptr_usage<'tcx>(cx: &LateContext<'tcx>, expr: &'tcx Expr<'_>) {
             | sym::ptr_read_unaligned
             | sym::ptr_read_volatile
             | sym::ptr_replace
-            | sym::ptr_slice_from_raw_parts
```
Comment (Centri3) [inline clippy_lints/src/ptr.rs:280]: I feel like this should still lint this, just with checking the next usages (before the next reassignment) to ensure it's used. Because yeah, just linting the function ends up being incorrect. But this is a lot for just a single part of this lint so I don't think it should be added rn. Can you leave a comment about this?

Comment (ljgermain) [reply clippy_lints/src/ptr.rs:280]: Done.

**Review by Centri3 — COMMENTED** [review]
Looks good, thanks!
