### PR TITLE
Fix FP on `if_then_some_else_none` when there is early return

### LINKED ISSUE #7870: False positive with `clippy::if_then_some_else_none`
Lint name:

`clippy::if_then_some_else_none`

I tried this code:

```rust
#![warn(clippy::if_then_some_else_none)]

fn f(b: bool, v: Option<()>) -> Option<()> {
    if b {
        v?;

        Some(())
    } else {
        None
    }
}
```

I expected to see this happen: Clippy does not warn `clippy::if_then_some_else_none`.

Instead, this happened: Clippy  warns that code can be simplified.

### Meta

**Rust version (`rustc -Vv`):**

```
rustc 1.58.0-nightly (91b931926 2021-10-23)
binary: rustc
commit-hash: 91b931926fd49fc97d1e39f2b8206abf1d77ce7d
commit-date: 2021-10-23
host: x86_64-pc-windows-msvc
release: 1.58.0-nightly
LLVM version: 13.0.0
```

### PR DESCRIPTION
**Pull request by dswij**
closes #7870 

changelog: [`if_then_some_else_none`] now does not fire when there is early return

### CODE REVIEW

**Review by xFrednet — COMMENTED** [review]
The implementation looks good to me. 

---

For future reference: The example in the issue could in theory still use `bool::then()` and then call flatten on the result like this([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=88c0a3f85ca9a40fac08ec7f935188a1))

```rs
 fn f2(b: bool, v: Option<()>) -> Option<()> {
    b.then(|| {
        v?;
        Some(())
    })
    .flatten()
}
```

However, this only works if the early return is also inside the return expression of function. I like this solution implemented in this PR. Just wanted to document it for future reference :upside_down_face:

File: clippy_lints/src/if_then_some_else_none.rs [hunk 1]
```diff
@@ -73,6 +73,7 @@ impl LateLintPass<'_> for IfThenSomeElseNone {
         if_chain! {
             if let Some(higher::If { cond, then, r#else: Some(els) }) = higher::If::hir(expr);
             if let ExprKind::Block(then_block, _) = then.kind;
+            if !stmts_contains_early_return(then_block.stmts);
```
[the remark this answers is not in the document]
Comment (dswij) [reply clippy_lints/src/if_then_some_else_none.rs]: Done 🙂

File: clippy_lints/src/if_then_some_else_none.rs [hunk 2]
```diff
@@ -99,18 +100,26 @@ impl LateLintPass<'_> for IfThenSomeElseNone {
...
+                    );
                 span_lint_and_help(
                     cx,
                     IF_THEN_SOME_ELSE_NONE,
                     expr.span,
                     "this could be simplified with `bool::then`",
                     None,
                     &help,
-                );
+                    );
```
Comment (xFrednet) [inline clippy_lints/src/if_then_some_else_none.rs:111]: rustfmt sadly doesn't work inside macros. Could you fix this indention and the one in line 103? Then it's all good :+1:

**Review by xFrednet — APPROVED** [review]
Looks good, only one small formatting NIT :sweat_smile:

File: clippy_lints/src/if_then_some_else_none.rs (hunk 2 above)
Comment (dswij) [reply clippy_lints/src/if_then_some_else_none.rs:111]: Hm, I thought that this change was because of rustfmt 🤔

Comment (xFrednet) [reply clippy_lints/src/if_then_some_else_none.rs]: These indentations also often happen in my editor, when I move code around. It's good that rustfmt is really solid otherwise, and this might be fixed when Rust supports `if let` chains in the future :upside_down_face:

**Review by xFrednet — APPROVED** [review]

**Comment by xFrednet** [comment]
Looks good to me, thank you for the bug fix! :upside_down_face: 

@bors r+
