### PR TITLE
Post lint on the type HIR node

### LINKED ISSUE #15708: Strange behaviour with #[expect]'ing lints from #[derive] attributes
### Summary

[Running clippy on the below code sample](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=85c6cff000e0bd3b235c73922440ac8d) raises *both* an error from the deny-by-default `derived_hash_with_manual_eq` and a `unfulfilled_lint_expectations` warning from the `#[expect]` failing to fire. This would be understandable on its own, if it were a case of the `#[expect]` not properly applying to the code generated by the `#[derive]`. However, I'm left confused because if I instead use `#[allow]`, that emits nothing as I'd expect, i.e. `allow`, but not `expect`, is correctly picking up on the lint and silencing it. 

I checked my understanding of `#[expect]` in the reference, but the [relevant section](https://doc.rust-lang.org/reference/attributes/diagnostics.html#r-attributes.diagnostics.expect.fulfillment) only seems to talk about what happens if the warning is silenced by other things in inner scopes relative to the `#[expect]`, rather than how `#[expect]` applies to non-warnings. 

Would it be possible to clarify this behaviour? I also don't know if this is coming from clippy or rustc proper

### Lint Name

unfulfilled_lint_expectations

### Reproducer

I tried this code:

```rust
#[expect(
    clippy::derived_hash_with_manual_eq,
    reason = "..."
)]
#[derive(Debug, Clone, Copy, Eq, PartialOrd, Ord, Hash)]
pub struct Span {
    start: usize,
    end: usize,
}

impl PartialEq for Span {
    fn eq(&self, other: &Self) -> bool {
        self.start
            .cmp(&other.start)
            .then(self.end.cmp(&other.end))
            .is_eq()
    }
}
```

I saw this happen:

```
27 | #[derive(Debug, Clone, Copy, Eq, PartialOrd, Ord, Hash)]
   |                                                   ^^^^
   |
note: `PartialEq` implemented here
  --> src\token_data.rs:89:1
   |
89 | impl PartialEq for Span {
   | ^^^^^^^^^^^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derived_hash_with_manual_eq
   = note: `#[deny(clippy::derived_hash_with_manual_eq)]` on by default

warning: this lint expectation is unfulfilled
  --> src\token_data.rs:24:5
   |
24 |     clippy::derived_hash_with_manual_eq,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: In order to override dummy values in test mode
   = note: `#[warn(unfulfilled_lint_expectations)]` on by default
```

I expected to see this happen:
* No emitted lints. 

### Version

```text
rustc 1.88.0 (6b00bc388 2025-06-23)
binary: rustc
commit-hash: 6b00bc3880198600130e1cf62b8f8a93494488cc
commit-date: 2025-06-23
host: x86_64-pc-windows-msvc
release: 1.88.0
LLVM version: 20.1.5
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by samueltardieu**
Out of the 5 lints in the `derive` directory, only two of them (`unsafe_derive_deserialize` and `derive_partial_eq_without_eq`) posted the lint on the ADT node. This fixes the situation for the three other lints:

- `derived_hash_with_manual_eq`
- `derive_ord_xor_partial_ord`
- `expl_impl_clone_on_copy`

This allows `#[expect]` to be used on the ADT to silence the lint.

Also, this makes `expl_impl_clone_on_copy` properly use an "help" message instead of a "note" one when suggesting a fix.

Fixes rust-lang/rust-clippy#15708
Fixes rust-lang/rust-clippy#13356

changelog: [`derived_hash_with_manual_eq`]: honor the use of `#[expect]` on the type to which the lint applies
changelog: [`derive_ord_xor_partial_ord`]: honor the use of `#[expect]` on the type to which the lint applies
changelog: [`expl_impl_clone_on_copy`]: honor the use of `#[expect]` on the type to which the lint applies

### CODE REVIEW

**Comment by ada4a** [comment]
Oh, I was trying to do basically this for https://github.com/rust-lang/rust-clippy/issues/13356, which complains about the particular case of `derived_hash_with_manual_eq`, so that issue can be closed as well.

Speaking of that lint, you have a small typo in its name -- `derive` instead of `derived`. Although the other lints use `derive`, and one could argue that that sounds more natural -- maybe this lint should be renamed?

**Comment by samueltardieu** [comment]
> Oh, I was trying to do basically this for #13356, which complains about the particular case of `derived_hash_with_manual_eq`, so that issue can be closed as well.
> 
> Speaking of that lint, you have a small typo in its name -- `derive` instead of `derived`. Although the other lints use `derive`, and one could argue that that sounds more natural -- maybe this lint should be renamed?

I fixed the typo, thanks. Yeah, it should probably be renamed, but not in this PR though. I'll note that #13356 will be closed as well.

File: tests/ui/derive.rs [hunk 1]
```diff
@@ -130,3 +130,16 @@ fn issue14558() {
 }
 
 fn main() {}
+
```
Comment (blyxyas) [inline tests/ui/derive.rs:133]: Could you add a deny unfulfilled_expectations so that no future commits allows it and then another one breaks this again?

File: tests/ui/derive_ord_xor_partial_ord.rs [hunk 2]
```diff
@@ -76,3 +76,18 @@ mod use_ord {
 }
 
 fn main() {}
+
```
Comment (blyxyas) [inline tests/ui/derive_ord_xor_partial_ord.rs:79]: Same here

File: tests/ui/derived_hash_with_manual_eq.rs [hunk 3]
```diff
@@ -41,3 +41,19 @@ impl std::hash::Hash for Bah {
 }
 
 fn main() {}
+
```
Comment (blyxyas) [inline tests/ui/derived_hash_with_manual_eq.rs:44]: …and here

**Review by blyxyas — CHANGES_REQUESTED** [review]

File: tests/ui/derive.rs (hunk 1 above)
Comment (samueltardieu) [reply tests/ui/derive.rs:133]: Done.

Comment (samueltardieu) [reply tests/ui/derive.rs:133]: Note that an alternative would be the second commit of #15723. If you want, I can revert the change I made here, and clean up #15723 to only add the option to `Clippy.toml`. Otherwise, I'll submit #15723 for discussion after this one is merged.

Comment (samueltardieu) [reply tests/ui/derive.rs:133]: From the discussion on #15723, it appears that `-Dwarnings` is used, so the `#![deny(unfulfilled_lint_expectations)]` is not needed as it transformed from a warning (its default state) into an error.

I'll revert the changes.

Comment (blyxyas) [reply tests/ui/derive.rs:133]: :+1:

**Review by blyxyas — APPROVED** [review]
LGTM, thanks for the bugfix!
