### PR TITLE
correct suggestions in `no_std`

### LINKED ISSUE #13895: `redundant_closure` makes incorrect suggestion
### Summary

`redundant_closure` lint sometimes makes incorrect suggestion in a `no_std` environment.

### Reproducer

I tried this code:

```rust
#![no_std]
extern crate alloc;
use alloc::vec;
use alloc::vec::Vec;

fn main() {
    let _: Option<Vec<u8>>= true.then(|| vec![]);
}
```

I expected to see this happen:

Suggest code that compiles successfully in a `no_std` environment, e.g. using `alloc::vec::Vec`, or not linting.

Instead, this happened:

The following was suggested, which fails to compile:
```rust
#![no_std]
extern crate alloc;
use alloc::vec;
use alloc::vec::Vec;

fn main() {
    let _: Option<Vec<u8>>= true.then(std::vec::Vec::new);
}
```

### Version

```text
rustc 1.85.0-nightly (dd84b7d5e 2024-12-27)
binary: rustc
commit-hash: dd84b7d5eec3c20d7fcd13e6450af029d3cece9d
commit-date: 2024-12-27
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.6
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by lapla-cogito**
I opened https://github.com/rust-lang/rust-clippy/pull/13896 before. However, I found that there're more cases where Clippy suggests to use modules that belong to the `std` crate even in a `no_std` environment. Therefore, this PR include the changes I've made in #13896 and new changes to fix cases I found this time to prevent wrong suggestions in `no_std` environments as well.

changelog: [`redundant_closure`]: correct suggestion in `no_std`
changelog: [`repeat_vec_with_capacity`]: correct suggestion in `no_std`
changelog: [`single_range_in_vec_init`]: don't emit suggestion to use `Vec` in `no_std`
changelog: [`drain_collect`]: correct suggestion in `no_std`
changelog: [`map_with_unused_argument_over_ranges`]: correct suggestion in `no_std`

also close #13895

### CODE REVIEW

File: clippy_lints/src/single_range_in_vec_init.rs [hunk 1]
```diff
@@ -125,7 +125,7 @@ impl LateLintPass<'_> for SingleRangeInVecInit {
                     span,
                     format!("{suggested_type} of `Range` that is only one element"),
                     |diag| {
-                        if should_emit_every_value {
+                        if should_emit_every_value && !is_no_std_crate(cx) {
```
Comment (lapla-cogito) [inline clippy_lints/src/single_range_in_vec_init.rs:128]: In a `no_std` environment, we can use `alloc::vec::Vec`, but this assumes the existence of a heap allocator, so Clippy shouldn't suggest to use `alloc::vec::Vec` in general because it violates the purpose of `Applicability::MaybeIncorrect`. Also, using `Applicability::Unspecified` is noisy in such environments.

**Comment by lapla-cogito** [comment]
r? clippy

**Review by Manishearth — APPROVED** [review]
