### PR TITLE
fix: `option_if_let_else` suggests wrongly when coercion requires explicit cast

### LINKED ISSUE #11059: `clippy::option_if_let_else` suggests invalid code fix
### Summary

The code produced by clippy is in theory correct in my eyes, but in reality the type checker doesn't understand it.

### Reproducer

I tried this code:

```rust
if let Some(id) = &v.as_class().unwrap().id {
    Box::new(std::iter::once(Vertex::Span(id.span)))
} else {
    Box::new(std::iter::empty())
}
```

I expected to see this happen: to get working code after a quick fix.
Instead, this happened: The quick fix produces the following non-working code:
```rust
v.as_class().unwrap().id.as_ref().map_or_else(
    || Box::new(std::iter::empty()),
    |id| Box::new(std::iter::once(Vertex::Span(id.span))),
)
```
Which is invalid because:
```
error[E0308]: mismatched types
   --> crates\oxc_linter\src\lint_adapter2.rs:217:35
    |
217 |                     |id| Box::new(std::iter::once(Vertex::Span(id.span))),
    |                          -------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Empty<_>`, found `Once<Vertex<'_>>`
    |                          |
    |                          arguments to this function are incorrect
    |
    = note: expected struct `std::iter::Empty<_>`
               found struct `std::iter::Once<lint_adapter2::Vertex<'_>>`
note: associated function defined here
   --> C:\Users\jason\.rustup\toolchains\nightly-2023-06-02-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\alloc\src\boxed.rs:215:12
    |
215 |     pub fn new(x: T) -> Self {
    |            ^^^

```

### Version

```text
rustc 1.72.0-nightly (d59363ad0 2023-06-01)
binary: rustc
commit-hash: d59363ad0b6391b7fc5bbb02c9ccf9300eef3753
commit-date: 2023-06-01
host: x86_64-pc-windows-msvc
release: 1.72.0-nightly
LLVM version: 16.0.4
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by profetia**
Closes #11059

changelog: `option_if_let_else`: fix wrong suggestion when coersion requires explicit cast

### CODE REVIEW

File: clippy_lints/src/option_if_let_else.rs [hunk 1]
```diff
@@ -219,6 +224,21 @@ fn try_get_option_occurrence<'tcx>(
...
+    let some_adj = cx.typeck_results().expr_adjustments(some_body);
+    let none_adj = cx.typeck_results().expr_adjustments(none_body);
+
+    // TODO: check if there are more cases that require explicit cast
+    some_ty != none_ty
+        && some_adj
+            .iter()
+            .chain(none_adj.iter())
+            .any(|adj| matches!(adj.kind, Adjust::Pointer(PointerCoercion::Unsize)))
+}
```
Comment (samueltardieu) [inline clippy_lints/src/option_if_let_else.rs:240]: As-is, this fixes only parts of the problem. For example, the following will still fail with a bad suggestion:

```rust
static S: String = String::new();

fn foo(o: Option<&str>) -> &str {
    if let Some(o) = o {
        o
    } else {
        &S
    }
}
```

Comment (profetia) [reply clippy_lints/src/option_if_let_else.rs:240]: Fair, I'm considering to produce a turbo fish for the `map_or_else` as an alternative solution.

File: clippy_lints/src/option_if_let_else.rs [hunk 2]
```diff
@@ -184,6 +185,11 @@ fn try_get_option_occurrence<'tcx>(
             }
         }
 
+        let noen_ty_adj = cx.typeck_results().expr_ty_adjusted(none_body);
```
Comment (samueltardieu) [inline clippy_lints/src/option_if_let_else.rs:188]: Typo?

File: clippy_lints/src/option_if_let_else.rs [hunk 3]
```diff
@@ -184,6 +185,11 @@ fn try_get_option_occurrence<'tcx>(
...
+        let none_ty = cx.typeck_results().expr_ty(none_body);
+        let method_generics =
+            (method_sugg == "map_or_else" && noen_ty_adj != none_ty).then(|| format!("::<{}, _, _>", noen_ty_adj));
```
Comment (samueltardieu) [inline clippy_lints/src/option_if_let_else.rs:191]: Can't you checked that the adjustments are empty instead of comparing the types?

**Review by samueltardieu — COMMENTED** [review]
Nit: there is also a typo "coersion → coercion" in the PR title and in the commit message

File: clippy_lints/src/option_if_let_else.rs (hunk 3 above)
Comment (profetia) [reply clippy_lints/src/option_if_let_else.rs]: Changed. Thanks!

File: tests/ui/option_if_let_else.fixed [hunk 4]
```diff
@@ -268,3 +268,19 @@ fn issue11893() {
         panic!("Haven't thought about this condition.");
     }
 }
+
+mod issue11059 {
+    use std::fmt::Debug;
+
+    fn box_coercion_unsize(o: Option<i32>) -> Box<dyn Debug> {
+        o.map_or_else::<std::boxed::Box<dyn std::fmt::Debug>, _, _>(|| Box::new("foo"), |o| Box::new(o))
```
Comment (samueltardieu) [inline tests/ui/option_if_let_else.fixed:276]: Is that really an improvement over the original code? It looks pretty hard to read compared to the other.

Comment (profetia) [reply tests/ui/option_if_let_else.fixed:276]: It might be better if there is a way to shorten the type name. The bright side to add turbo fish is that it guarantees the correctness, and does not need to be tailored case by case.

Comment (profetia) [reply tests/ui/option_if_let_else.fixed]: I changed it to a placeholder, it should be much better now.

File: tests/ui/option_if_let_else_unfixable.stderr [hunk 5]
```diff
@@ -0,0 +1,17 @@
+error: use Option::map_or_else instead of an if let/else
+  --> tests/ui/option_if_let_else_unfixable.rs:8:9
+   |
+LL |         if let Some(o) = o { Box::new(o) } else { Box::new("foo") }
```
Comment (dswij) [inline tests/ui/option_if_let_else_unfixable.stderr:4]: I'm having doubts whether this suggestion is an improvement. Any thoughts? @rust-lang/clippy

Comment (Alexendoo) [reply tests/ui/option_if_let_else_unfixable.stderr:4]: I think it shouldn't lint if it needs to suggest a turbofish personally, since it's not a very common style

p.s. https://doc.rust-lang.org/nightly/nightly-rustc/clippy_utils/fn.expr_requires_coercion.html may work well here

Comment (profetia) [reply tests/ui/option_if_let_else_unfixable.stderr]: Updated. Though I still think we should at least give a lint, but not try fixing it.

Comment (dswij) [reply tests/ui/option_if_let_else_unfixable.stderr]: It's fine to ignore it if the suggestion is pretty much worse. Thanks! :)

**Review by dswij — APPROVED** [review]
Thank you!
