### PR TITLE
 Fix type suggestion for manual_is_ascii_check

### LINKED ISSUE #13913: `manual_is_ascii_check` suggests incorrect type
### Summary

The manual_is_ascii_check lint suggests an incompatible type, leading to a compilation error. The lambda requires `|c: &char|`, but clippy inserts `|c: char|` instead.

I think this is related to #11988.

### Reproducer

I tried this code:

```rust
fn main() {
    let digits: String = "1234ABCD"
        .chars()
        .take_while(|c| ('0'..='9').contains(c)) // <-- line that is changed
        .collect();

    println!("{digits}");
}

```

I expected to see this happen:
- either `.take_while(|c| c.is_ascii_digit())`
- or `.take_while(|c: &char| c.is_ascii_digit())`

Instead, this happened:
- `.take_while(|c: char| c.is_ascii_digit())`

### Version

```text
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: x86_64-unknown-linux-gnu
release: 1.83.0
LLVM version: 19.1.1
```

### Additional Labels

@rustbot label I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by Otto-AA**
Fixes #13913 .

changelog: [`manual_is_ascii_check`]: fix type suggestions for references

Previously it only derived `char` and `u8` types, now it should always annotate the lambda parameter with the correct type (e.g. `&char`).

I'm quite new to Rust and this is my first contact with clippy, so I'm open for suggetions :)

### CODE REVIEW

File: clippy_lints/src/manual_is_ascii_check.rs [hunk 1]
```diff
@@ -123,18 +123,14 @@ impl<'tcx> LateLintPass<'tcx> for ManualIsAsciiCheck {
...
         && ty_span == span
     {
-        let ty_str = match lit.node {
-            Char(_) => "char",
-            Byte(_) => "u8",
-            _ => return None,
-        };
+        let arg_type = cx.typeck_results().expr_ty(arg);
+        let ty_str = arg_type.to_string();
         return Some((*ty_span, ty_str));
```
Comment (Alexendoo) [inline clippy_lints/src/manual_is_ascii_check.rs:134]: Thanks!

Just one nit, we can return the `Ty` here to avoid allocating the extra string since it implements `Display`

Comment (Otto-AA) [reply clippy_lints/src/manual_is_ascii_check.rs]: Thanks for the hint, I've updated this part now

**Review by Alexendoo — APPROVED** [review]
Great, thank you!
