### PR TITLE
size_of_in_element_count: Disable lint on division by byte-size

### LINKED ISSUE #6511: size_of_in_element_count false-positive when dividing byte-size by element size
#### I tried [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e7b5de7d2e24d7d0ccafc827eccfa635) code:

```rust
fn main() {
    let bytes = [0u8, 1u8, 2u8, 3u8];
    let shorts: &[u16] = unsafe {
        std::slice::from_raw_parts(
            bytes.as_ptr() as *const _,
            bytes.len() / std::mem::size_of::<u16>(),
        )
    };
    dbg!(shorts);
}
```

#### I expected to see this happen:

No `size_of_in_element_count` lint warning/error when _dividing_ by `size_of`.

#### Instead, this happened:

```rust
    Checking playground v0.0.1 (/playground)
error: found a count of bytes instead of a count of elements of `T`
 --> src/main.rs:6:13
  |
6 |             bytes.len() / std::mem::size_of::<u16>(),
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[deny(clippy::size_of_in_element_count)]` on by default
  = help: use a count of elements instead of a count of bytes, it already gets multiplied by the size of the type
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#size_of_in_element_count
```

#6394 recently introduced the `size_of_in_element_count` to catch cases where byte sizes instead of element sizes are passed into `from_raw_parts` and related functions. However, `size_of` is used in the example above to _convert away from_ byte sizes by _dividing_ instead of multiplying. After all the linter error states:

> use a count of elements instead of a count of bytes, it already gets multiplied by the size of the type

When no count of bytes nor multiplication is used here at all.

CC @nico-abram 

### Meta

- `cargo +nightly clippy -V`: `clippy 0.0.212 (257becb 2020-12-27)`
- `rustc +nightly -Vv`:
  ```
  rustc 1.51.0-nightly (257becbfe 2020-12-27)
  binary: rustc
  commit-hash: 257becbfe4987d1f7b12af5a8dd5ed96697cd2e8
  commit-date: 2020-12-27
  host: x86_64-unknown-linux-gnu
  release: 1.51.0-nightly
  ```

### PR DESCRIPTION
**Pull request by MarijnS95**
Fixes #6511

It is fairly common to divide some length in bytes by the byte-size of a single element before creating a `from_raw_parts` slice or similar operation. This lint would erroneously disallow such expressions.

Just in case, instead of simply disabling this lint in the RHS of a division, keep track of the inversion and enable it again on recursive division.

---

changelog: Do not trigger size_of_in_element_count when dividing by element size

### CODE REVIEW

File: clippy_lints/src/size_of_in_element_count.rs [hunk 1]
```diff
@@ -50,10 +51,13 @@ fn get_size_of_ty(cx: &LateContext<'tcx>, expr: &'tcx Expr<'_>) -> Option<Ty<'tc
...
             }
         },
-        ExprKind::Binary(op, left, right) if BinOpKind::Mul == op.node || BinOpKind::Div == op.node => {
-            get_size_of_ty(cx, left).or_else(|| get_size_of_ty(cx, right))
+        ExprKind::Binary(op, left, right) if BinOpKind::Mul == op.node => {
+            get_size_of_ty(cx, left, inverted).or_else(|| get_size_of_ty(cx, right, inverted))
         },
-        ExprKind::Cast(expr, _) => get_size_of_ty(cx, expr),
+        ExprKind::Binary(op, left, right) if BinOpKind::Div == op.node => {
+            get_size_of_ty(cx, left, inverted).or_else(|| get_size_of_ty(cx, right, !inverted))
```
Comment (MarijnS95) [inline clippy_lints/src/size_of_in_element_count.rs:58]: This duplication could have been "simplified" with `(BinOpKind::Div == op.node) ^ inverted` in a single match arm, not sure if that's too complex though?

**Comment by MarijnS95** [comment]
@nico-abram Is there by chance a test you'd be fine to remove? I guess it should be fine to test all affected functions just once to make sure they trigger, then test all the expression variants on just one function (ie. no need to test `size_of` _and_ `size_of_val`, or a certain multiplication pattern multiple times).

**Comment by nico-abram** [comment]
I think most of the tests left are testing different functions/methods. Maybe you can combine some of the element count expression tests with tests for specific functions?

Like removing `unsafe { copy_nonoverlapping(x.as_ptr(), y.as_mut_ptr(), size_of_val(&x[0])) };` and putting that expression in one of the other calls

If possible IMO keeping each case as cleanly separated as possible is best but I'm not a maintainer. Whoever reviews this can probably give you better feedback

**Comment by MarijnS95** [comment]
@nico-abram Correct, in hindsight the top half tests various functions (ie. none has been accidentally skipped from the linting code), the bottom half tests all expressions. There was only one overlapping thing with `copy()` which has been removed to get back below 200 lines.

I guess the only recommended solution beyond that is to split the test out in two parts (one for function inclusion, the other for variation in the expressions), but that doesn't seem necessary in this MR at least (unless one wishes to re-add the test for `copy()`).

**Comment by ThibsG** [comment]
On another side, do you think it's relevant to also fix #6590 here?

**Comment by MarijnS95** [comment]
@ThibsG That looks like exactly the mistake this lint is protecting against. The function described there takes a single `u8` as input, that interpreted as slice should have a constant length of `1`. I guess it only makes more sense to use the constant `1` or the output from `.len()`, not `size_of::<u8>` nor multiplied by that,

Otherwise, matching types left and right is a completely different issue (and iirc why this lint doesn't trigger when the type on the left and right is different).

File: clippy_lints/src/size_of_in_element_count.rs (hunk 1 above)
Comment (flip1995) [reply clippy_lints/src/size_of_in_element_count.rs:58]: Yeah, that would add too much complexity IMO

**Review by flip1995 — APPROVED** [review]
Changes LGTM

>There was only one overlapping thing with copy() which has been removed to get back below 200 lines.

This restriction is Clippy is there to keep tests to a maintainable size. Please don't remove tests because of this. Your suggestion of splitting up the tests sounds reasonable to me. Please do this in a separate commit.

**Comment by MarijnS95** [comment]
@flip1995 Thanks for confirming, the tests are now split up in two files distinguishing function "completeness" and expression variants.

If I understand the docs correctly, I should now (be able to) do this:

@rustbot label -S-waiting-on-author +S-waiting-on-review

Right?

**Review by flip1995 — APPROVED** [review]

**Comment by flip1995** [comment]
@bors r+

Thanks! Great job!
