### PR TITLE
Change the criteria of `interior_mutable_const`

### LINKED ISSUE #5050: declare_interior_mutable_const for Option
Hello!

This trait
```rust
pub trait SomeTrait {
    const VAL: Option<Self>;
}
```
triggers
```rust
error: a const item should never be interior mutable
  |
6 |     const VAL: Option<Self>;
  |     ^^^^^^^^^^^------------^
  |                |
  |                consider requiring `std::option::Option<Self>` to be `Copy`
  |
```
which is this lint: https://rust-lang.github.io/rust-clippy/master/index.html#declare_interior_mutable_const

Apparently the corresponding test is this? https://github.com/rust-lang/rust-clippy/blob/master/tests/ui/non_copy_const.rs (not sure!)

Thing is, it doesnt test `Option<T>` and additionally: is interior mutability for const Options even such a big deal?

I'm simply trying to figure out if I'm implementing a foot-gun right now if I `allow` this. I don't intent to ever manipulate this const and will only use it for `PartialEq` and `Eq` purposes.

EDIT: @frozolotl on Discord suggested removing `Option` from the trait and it should indeed still trigger. And it does. Note: The suggestion to require Copy is not possible in my case.

### PR DESCRIPTION
**Pull request by rail-rain**
This implements my suggestion [here](https://github.com/rust-lang/rust-clippy/issues/5050#issuecomment-680310889), and so hopefully fixes #5050.

* stop linting associated types and generic type parameters
* start linting ones in trait impls
  whose corresponding definitions in the traits are generic
* remove the `is_copy` check
  as presumably the only purpose of it is to allow
  generics with `Copy` bounds as `Freeze` is internal
  and generics are no longer linted
* remove the term 'copy' from the tests
  as being `Copy` no longer have meaning

---

changelog: Change the criteria of `declare_interior_mutable_const` and `borrow_interior_mutable_const` to narrow the lints to only lint things that defenitly is a interior mutable type, not potentially.

### CODE REVIEW

File: clippy_lints/src/non_copy_const.rs [hunk 1]
```diff
@@ -110,10 +112,15 @@ impl Source {
...
 
 fn verify_ty_bound<'tcx>(cx: &LateContext<'tcx>, ty: Ty<'tcx>, source: Source) {
-    if ty.is_freeze(cx.tcx.at(DUMMY_SP), cx.param_env) || is_copy(cx, ty) {
-        // An `UnsafeCell` is `!Copy`, and an `UnsafeCell` is also the only type which
-        // is `!Freeze`, thus if our type is `Copy` we can be sure it must be `Freeze`
-        // as well.
+    // Ignore types whose layout is unknown since `is_freeze` reports every generic types as `!Freeze`,
+    // making it indistinguishable from `UnsafeCell`. i.e. it isn't a tool to prove a type is
+    // 'unfrozen'. However, this code causes a false negative in which
+    // a type contains a layout-unknown type, but also a unsafe cell like `const CELL: Cell<T>`.
```
Comment (flip1995) [inline clippy_lints/src/non_copy_const.rs:118]: Can you add a test for this, with the remark, that this is a FN? (Or maybe I just missed the test)

**Review by flip1995 — COMMENTED** [review]
LGTM overall. Linting trait impls over trait definitions is definitely the better approach here. The tests are a little mind boggling with the spaghetti traits, but they also looked good to me.

File: clippy_lints/src/non_copy_const.rs (hunk 1 above)
Comment (rail-rain) [reply clippy_lints/src/non_copy_const.rs:118]: You're right; I didn't write the test for it and I'm happy to do so. However, I probably hesitated to add more things to this already complicated test since just opening the test file is enough to make my mind go blank. The current state of the test is a by-product of my attempt to retain the original form as much as possible. And, I've thought about it, how about splitting the traits and giving these some self-descriptive name? For example:

```rust
trait ConcreteDefinitions {
    const ATOMIC: AtomicUsize;
    const INTEGER: u64;
}

trait AssocTypes {
    type TypeToBeFrozen;
    type TypeToBeUnfrozen;

    const CONST_TO_BE_FROZEN: TypeToBeFrozen;
    const CONST_TO_BE_UNFROZEN: TypeToBeUnfrozen;
}

trait BothOfCellAndGeneric<T> {
    const DIRECT: Cell<T>;
    const INDIRECT: Cell<*const T>;
}
```

...and so on (plus impls of these). As a downside, it requires rewriting the test, makes the diff useless.

Comment (flip1995) [reply clippy_lints/src/non_copy_const.rs:118]: I also struggled to understand the tests and had to go back and forth to understand what's going on. So splitting it up in multiple traits or otherwise improving the tests would be great! You can also create a dir for these tests and split them up in multiple files, if you think that would help. 

So I'm happy how the tests are currently (+the FN test), but would be happier with a better/easier to understand test structure.

Comment (rail-rain) [reply clippy_lints/src/non_copy_const.rs:117]: Thank you and I'm glad to hear it's OK for you to review a quite heavily restructured test!

And, you were *right*; it've caught a little false positive where `Cell<*const T>` gets linted at the trait impl, in addition to the trait def.

File: tests/ui/declare_interior_mutable_const.rs [hunk 2]
```diff
@@ -34,60 +34,135 @@ static STATIC_TUPLE: (AtomicUsize, String) = (ATOMIC, STRING);
...
+
+impl SelfType for u64 {
+    const SELF: Self = 16;
+}
+
+impl SelfType for AtomicUsize {
+    // this (interior mutable `Self` const) exists in `parking_lot`.
+    // `const_trait_impl` will replace it in the future, hopefully.
+    const SELF: Self = AtomicUsize::new(17); //~ ERROR interior mutable
+}
```
Comment (flip1995) [inline tests/ui/declare_interior_mutable_const.rs:136]: Basically copy&paste this with `Option<Self>`.

**Review by flip1995 — APPROVED** [review]
Thanks for the test restructure. This looks really good to me now and is way easier to understand.

Can you add the example from #5050 to the tests? I don't see why it should still get linted, but `Self` in a generics position made problems in the past for other lints. So basically the same as the part of the test with the `SelfType` trait, just with `Option` wrapped around `Self`. Also add a comment referring to the issue #5050, please.

File: clippy_lints/src/non_copy_const.rs (hunk 1 above)
Comment (flip1995) [reply clippy_lints/src/non_copy_const.rs:117]: > `Cell<*const T>` gets linted at the trait impl, in addition to the trait def.

Did you already fix that? I don't see this behavior in the `.stderr` file.

Comment (rail-rain) [reply clippy_lints/src/non_copy_const.rs:117]: Yes, I've bundled it with the test rewrite. The part of that which changes `has_type_flags` to `layout_of` in `non_copy_const.rs`.

**Comment by rail-rain** [comment]
Of cource. Do you prefer `Option<Self>` in an new trait? I've put it in `SelfType`, but if you do let me know. I will change it so.

**Comment by flip1995** [comment]
Perfect, thanks!

@bors r+

**Comment by flip1995** [comment]
@bors retry

A failure in the "Set up job" step seems really weird. I hope we don't have to debug this...
