### PR TITLE
fix: `map_entry` FP inside closure

### LINKED ISSUE #11976: map_entry, suggestion produces invalid borrow inside closure
### Summary

The `map_entry` lint is suppressed if the hash map is accessed between the call to `HashMap::contains_key` and the later call to `HashMap::insert`.  However, it does not check for access of the hash map occurring within a closure.  As a result, the suggestion's use of `HashMap::entry` starts a mutable borrow of the entire hashmap, conflicting with call to `HashMap::get` that occurred between the `contains_key` and `insert`.

In the example below, if the line `let _ = || hashmap.get(&0);` is replaced with `hashmap.get(&0);`, the lint is no longer suggested.

### Lint Name

map_entry

### Reproducer

I tried this code:

```rust
fn main() {
    let mut hashmap = std::collections::HashMap::new();
    if !hashmap.contains_key(&0) {
        let _ = || hashmap.get(&0);
        hashmap.insert(0, 0);
    }
}
```

I saw this happen:

```
warning: usage of `contains_key` followed by `insert` on a `HashMap`
 --> src/main.rs:3:5
  |
3 | /     if !hashmap.contains_key(&0) {
4 | |         let _ = || hashmap.get(&0);
5 | |         hashmap.insert(0, 0);
6 | |     }
  | |_____^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_entry
  = note: `#[warn(clippy::map_entry)]` on by default
help: try
  |
3 ~     hashmap.entry(0).or_insert_with(|| {
4 +         let _ = || hashmap.get(&0);
5 +         0
6 +     });
  |

warning: `temp` (bin "temp") generated 1 warning (run `cargo clippy --fix --bin "temp"` to apply 1 suggestion)
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
```

I expected to see this happen: No clippy suggestions produced.

### Version

```text
rustc 1.76.0-nightly (06e02d5b2 2023-12-09)
binary: rustc
commit-hash: 06e02d5b259c1e88cbf0c74366d9e0a4c7cfd6d9
commit-date: 2023-12-09
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by profetia**
Closes #11976 

changelog: [`map_entry`]: fix FP inside closure

### CODE REVIEW

File: clippy_lints/src/entry.rs [hunk 1]
```diff
@@ -544,6 +544,10 @@ impl<'tcx> Visitor<'tcx> for InsertSearcher<'_, 'tcx> {
                 ExprKind::InlineAsm(_) => {
                     self.can_use_entry = false;
                 },
+                ExprKind::Closure(closure) => {
+                    self.is_single_insert = false;
```
Comment (samueltardieu) [inline clippy_lints/src/entry.rs:548]: Omitting this line or even setting the value to `true` will still pass all the existing UI tests. Do you have an idea of an UI test which would display a different message if this line was absent?

Comment (profetia) [reply clippy_lints/src/entry.rs:548]: Emm.. How does this happen? I tested locally and removing this line will cause a FP.

Comment (profetia) [reply clippy_lints/src/entry.rs]: I cannot think of one. I will just remove it for now.

**Review by Alexendoo — APPROVED** [review]
Thanks!
