### PR TITLE
fix [`excessive_precision`] suggestions on floats written in scientific notation

### LINKED ISSUE #12954: The excessive_precision linter suggestion causes a compilation error
### Summary

The lint suggests truncating `3.0000000000000000e+00` to `3` which causes a "mismatched types" compilation error.

### Lint Name

clippy::excessive_precision

### Reproducer

I tried this code:

```rust
pub const DATA: f64 = 3.0000000000000000e+00;
```

I saw this happen:

```
cargo clippy --fix --allow-staged
    Checking clippy_test v0.1.0 (C:\dev\tencek\sandbox\rust\clippy_test)
warning: failed to automatically apply fixes suggested by rustc to crate `clippy_test`

after fixes were automatically applied the compiler reported errors within these files:

  * src\data.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust-clippy/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0308]: mismatched types
 --> src\data.rs:1:23
  |
1 | pub const DATA: f64 = 3;
  |                       ^
  |                       |
  |                       expected `f64`, found integer
  |                       help: use a float literal: `3.0`

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0308`.
Original diagnostics will follow.

warning: float has excessive precision
 --> src\data.rs:1:23
  |
1 | pub const DATA: f64 = 3.0000000000000000e+00;
  |                       ^^^^^^^^^^^^^^^^^^^^^^ help: consider changing the type or truncating it to: `3`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#excessive_precision
  = note: `#[warn(clippy::excessive_precision)]` on by default

warning: `clippy_test` (bin "clippy_test") generated 1 warning (run `cargo clippy --fix --bin "clippy_test"` to apply 1 suggestion)
warning: failed to automatically apply fixes suggested by rustc to crate `clippy_test`

after fixes were automatically applied the compiler reported errors within these files:

  * src\data.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust-clippy/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0308]: mismatched types
 --> src\data.rs:1:23
  |
1 | pub const DATA: f64 = 3;
  |                       ^
  |                       |
  |                       expected `f64`, found integer
  |                       help: use a float literal: `3.0`

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0308`.
Original diagnostics will follow.
```

I expected to see this happen:
Probably this:
```rust
pub const DATA: f64 = 3.0;
```

### Version

```text
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-pc-windows-msvc
release: 1.79.0
LLVM version: 18.1.7
```

### Additional Labels

I-suggestion-causing-error

### PR DESCRIPTION
**Pull request by apoisternex**
fixes #12954

changelog: fix [`excessive_precision`] suggestions on float literal written in scientific notation

### CODE REVIEW

**Comment by y21** [comment]
Thanks for the PR! Can you add the code from the linked issue as a test case (in tests/ui/excessive_precision.rs)?

**Comment by apoisternex** [comment]
> Thanks for the PR! Can you add the code from the linked issue as a test case (in tests/ui/excessive_precision.rs)?

Added :smile:

File: tests/ui/excessive_precision.rs [hunk 1]
```diff
@@ -78,4 +78,7 @@ fn main() {
     const NEG_INF1: f32 = -1.0e+33f32;
     const NEG_INF2: f64 = -1.0e+3300f64;
     const NEG_INF3: f32 = -3.40282357e+38_f32;
+
+    // issue #12954
+    const _: f64 = 3.0000000000000000e+00;
```
Comment (y21) [inline tests/ui/excessive_precision.rs:83]: While we're here, can you also add `3.0000000000000000` as a test case?

It currently doesn't emit a warning (because it takes a different code path in the lint code), which is fine, but just to make sure it doesn't regress later, because the fix in this PR wouldn't apply to that literal if it got into the numeric literal code as there's no exponent and would end up with "3" as the suggestion again.

**Review by y21 — APPROVED** [review]

**Comment by y21** [comment]
And could you please also squash the commits?

File: tests/ui/excessive_precision.rs (hunk 1 above)
Comment (apoisternex) [reply tests/ui/excessive_precision.rs:83]: Sure
