### PR TITLE
fix `must_use_unit` suggestion when there're multiple attributes

### LINKED ISSUE #12320: `must_use_unit` fails to apply if it's one of many attrs
### Summary

.

### Reproducer

I tried this code:

```rust
#[cfg_attr(all(), must_use, deprecated)]
fn main() { }
```
```
warning: this unit-returning function has a `#[must_use]` attribute
 --> src/main.rs:2:1
  |
1 | #[cfg_attr(all(), must_use, deprecated)]
  |                   -------- help: remove the attribute
2 | fn main() { }
  | ^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#must_use_unit
  = note: `#[warn(clippy::must_use_unit)]` on by default
```

in this case we need to remove the "," as well otherwise we end up with a syntax error lol

```
error: expected identifier, found `,`
 --> src/main.rs:1:19
  |
1 | #[cfg_attr(all(), , deprecated)]
  |                   ^
  |                   |
  |                   expected identifier
  |                   help: remove this comma
```

### Version

```text
rustc 1.78.0-nightly (3246e7951 2024-02-19)
binary: rustc
commit-hash: 3246e79513cb89ddbfc0f21cb5a877e5b321dcc5
commit-date: 2024-02-19
host: x86_64-unknown-linux-gnu
release: 1.78.0-nightly
LLVM version: 18.1.0
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by lapla-cogito**
fix #12320 

When there're multiple attributes, clippy suggests leaving an extra comma and it makes an error.

changelog: [`must_use_unit`]:  No longer make incorrect suggestions when multiple attributes present.

### CODE REVIEW

File: clippy_lints/src/functions/must_use.rs [hunk 1]
```diff
@@ -92,28 +92,62 @@ pub(super) fn check_trait_item<'tcx>(cx: &LateContext<'tcx>, item: &'tcx hir::Tr
...
+            span_lint_and_then(
+                cx,
+                MUST_USE_UNIT,
+                fn_header_span,
+                "this unit-returning function has a `#[must_use]` attribute",
+                |diag| {
+                    diag.span_suggestion(attr.span, "remove the attribute", "", Applicability::MachineApplicable);
+                },
+            );
+        } else {
```
Comment (lapla-cogito) [inline clippy_lints/src/functions/must_use.rs:120]: If this conditional branch is reached and the length of `attrs` is 1, then it should be `#[must_use]` and clippy can suggest i'n the same way as before

**Comment by llogiq** [comment]
That's a good improvement, although just finding the span of the `must_use`, optionally including the comma and following whitespace would reduce the potential churn even more, especially when you consider the fact that those other attributes may be arbitrarily large.
