### PR TITLE
Additional restrictions

### LINKED ISSUE #4655: Some extra pedantic checks?
Hey, I would love to add a few lints to that which are fairly super pedantic. We use them (or rather a shell script that checks for them :P) at the moment to ensure error handling/non crashy behaviour in our codebase they sum up to:

*  no  unwrap
* no unimplemented
* no unreachable
* no  panic
* no let _ on results.
* no expect
* no dbg!
* no std::process::exit
* no bracket access `[....]`

but before I go ahead I'd like to get an opinion of those would be accepted?

### PR DESCRIPTION
**Pull request by Licenser**
Add restriction lints for `panic!`, `unreachable!`, `todo!` and `.expect(...)`

changelog: Add 5 new `restriction` lints: `panic`, `unreachable`, `todo`, `option_expect_used`, `result_expect_used`

### CODE REVIEW

**Comment by llogiq** [comment]
Since you have `panic!` and `unimplemented!`, you probably also want to catch `todo!` which was recently sent on its way to stabilization.

**Comment by Licenser** [comment]
yes! thanks I didn't knew that it makes total sense :D

File: tests/ui/panic_unimplemented.rs [hunk 1]
```diff
@@ -65,4 +77,6 @@ fn main() {
     ok_nomsg();
     ok_escaped();
     unimplemented();
+    unreachable();
```
Comment (flip1995) [inline tests/ui/panic_unimplemented.rs]: Since you separated out `panic!`, can you also separate these test cases?

Comment (Licenser) [reply tests/ui/panic_unimplemented.rs]: I would have left panic in but panic and panic with sensible message clash.

**Comment by Licenser** [comment]
The failures seem to relate to something outside of the PR, and I can't run tests locally any more either because of a dependency failing, is that a known issue?

**Comment by llogiq** [comment]
We likely need another rustup. Hang in there, we'll tell you when it's ready to rebase.

File: clippy_lints/src/methods/mod.rs [hunk 2]
```diff
@@ -90,6 +90,63 @@ declare_clippy_lint! {
...
+    ///
+    /// Better:
+    ///
+    /// ```rust
+    /// let opt = Some(1);
+    /// opt?;
+    /// ```
+    pub OPTION_EXPECT_USED,
+    restriction,
+    "using `Option.unwrap()`, which should at least get a better message using `expect()`"
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
    "using `Option.expect()`, which might be better handled"
```

File: clippy_lints/src/methods/mod.rs [hunk 3]
```diff
@@ -2044,6 +2129,7 @@ fn lint_ok_expect(cx: &LateContext<'_, '_>, expr: &hir::Expr, ok_args: &[hir::Ex
         if let Some(error_type) = get_error_type(cx, result_type);
         if has_debug_impl(error_type, cx);
 
+
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
```

File: clippy_lints/src/panic_unimplemented.rs [hunk 4]
```diff
@@ -25,6 +25,22 @@ declare_clippy_lint! {
...
+    ///
+    /// **Known problems:** None.
+    ///
+    /// **Example:**
+    /// ```no_run
+    /// panic!("even with a good reason");
+    /// ```
+    pub PANIC,
+    restriction,
+    "missing parameters in `panic!` calls"
```
Comment (flip1995) [inline clippy_lints/src/panic_unimplemented.rs]: copy pasted

File: clippy_lints/src/panic_unimplemented.rs [hunk 5]
```diff
@@ -41,7 +57,39 @@ declare_clippy_lint! {
...
+    /// ```
+    pub TODO,
+    restriction,
+    "`todo!` should not be present in production code"
+}
+
+declare_clippy_lint! {
+    /// **What it does:** Checks for usage of `unreachable!`.
+    ///
+    /// **Why is this bad?** This macro can cause cause code to panics
```
Comment (flip1995) [inline clippy_lints/src/panic_unimplemented.rs]:
```suggestion
    /// **Why is this bad?** This macro can cause code to panic
```

File: tests/ui/methods.rs [hunk 6]
```diff
@@ -1,7 +1,13 @@
 // aux-build:option_helpers.rs
 // compile-flags: --edition 2018
 
-#![warn(clippy::all, clippy::pedantic, clippy::option_unwrap_used)]
+#![warn(
+    clippy::all,
+    clippy::pedantic,
+    clippy::option_unwrap_used,
+    clippy::option_expect_used,
+    clippy::result_expect_used
```
Comment (flip1995) [inline tests/ui/methods.rs]: Can you put the `expect` tests in their own file? See #2038

File: tests/ui/panic_unimplemented.rs (hunk 1 above)
Comment (flip1995) [reply tests/ui/panic_unimplemented.rs]: We want to split up the tests as much as possible, see #2038. Since the unreachable, panic, unimplemented and todo tests are pretty small, it may make sense to group them in a `panicking_macros.rs` test file.

**Comment by flip1995** [comment]
Rustup is done and Clippy master builds again.

File: tests/ui/methods.rs (hunk 6 above)
Comment (Licenser) [reply tests/ui/methods.rs]: i can, i'm a bit unsure what the methodology is, from the tests I looked at it usually was "file per lint test" and tried to stick that, i.e. the `expect` tests are in methods as they're in the lint pass for methods, the `unreachable` is in the panic_unimplemented as it's in that lint pass. I couldn't put `panic` in panic_unimplemented since it clashed with the other panic tests there but looking at methods.rs I could add it as a warning.

So should I put all the new lints into a new file or make one file each or combine them all into their lint passes?

Comment (flip1995) [reply tests/ui/methods.rs]: "one file per lint" is a goal, that we want to achieve, but we're not really there yet, as you can see in the `methods.rs` test file. (Also "one file per lint" can also mean grouping some of the lints, when it makes sense, e.g. the 4 panic macro `Lint`s) 

For clarification: `Lint != LintPass`. One file per `LintPass` would be too big, since for example the `methods` module uses a single `LintPass` to check X (X=big number, that I don't want to count) `Lint`s.

> So should I put all the new lints into a new file or make one file each or combine them all into their lint passes?

What I would suggest is to put the `expect` lint tests in one file and the panic macro tests in their own file. 

So for the currently implemented lints, you should create 2 test files:

1. `tests/ui/panicking_macros.rs`, which tests:
    - `panic`
    - `unimplemented` (Move this tests out of `panic_unimplemented.rs` into the new file; also maybe rename the `panic_unimplemented.rs` file)
    - `unreachable`
    - `todo`
2. `tests/ui/expect`, which tests:
    - `option_expect_used`
    - `result_expect_used`

---

Bonus points, if you also move the `unwrap` lints to their own file.

**Comment by Licenser** [comment]
Split out the tests into two now sets `expect_unwrap` that cover `.expct("")` and `.unwrap("")` for `Result` and `Option` - I moved one test from methods in there. And as suggested `panicking_macros`.

File: clippy_lints/src/panic_unimplemented.rs (hunk 4 above)
Comment (Licenser) [reply clippy_lints/src/panic_unimplemented.rs]: fixed :)

**Comment by flip1995** [comment]
Tests look really good now, thanks!

If you want to, we can merge this PR already as it is right now and you can add the remaining 2 lints  in another PR. Only thing left to do here, would be to squash some of the commits.

**Comment by Licenser** [comment]
Ja I wanted to ask about the squashing policy anyway :D will do and rebase so we can pull them in.

**Comment by Licenser** [comment]
Commits are squashed!

**Comment by flip1995** [comment]
Thanks, I like PRs that add 5 new lints at once 🎉 

@bors r+
