### PR TITLE
Fix issue4503

### LINKED ISSUE #4503: Suggested lint: use "!is_dir()" instead of "is_file()"
A lot of people have a tendency to assume files and directories are all there are they have to think about, and that if its not a file, its clearly a directory, and vice versa.

The documentation even suggests this if you don't think it through, by saying that `is_file()` and `is_dir()` are mutually exclusive.

However, not all things that return false from `is_file()` are directories, and plenty of special file types return false for *both* `is_dir()` and `is_file()`

A lot of the time, when people make the `is_file()` check, they're not asking "is this a regular file as opposed to a special one", they're asking "is this a thing that I can read and get bytes from".

A particular situation where one might be calling `is_file()` and prematurely rejecting it is when the file in question is a user specified path, *and* that specified path is a pipe, as constructed by the bash command:

```bash
fooprogram <( program that outputs )
```

`fooprogram` gets passed `/dev/fd/63` (or similar) as the first parameter, and that is not a regular file, but it is for all general purposes something that can be safely treated as a file.

Subsequently, the better advice here is to check for `if !file.is_dir()` in preparation for doing reads from it.

Excerpts from `man 7 inode`

```
 The following mask values are defined for the file type:

           S_IFMT     0170000   bit mask for the file type bit field

           S_IFSOCK   0140000   socket
           S_IFLNK    0120000   symbolic link
           S_IFREG    0100000   regular file
           S_IFBLK    0060000   block device
           S_IFDIR    0040000   directory
           S_IFCHR    0020000   character device
           S_IFIFO    0010000   FIFO

       Thus, to test for a regular file (for example), one could write:

           stat(pathname, &sb);
           if ((sb.st_mode & S_IFMT) == S_IFREG) {
               /* Handle regular file */
           }
```

strace output of an example of this usage (noting the value of st_mode):
```
strace -v cat <( echo hello )
execve("/bin/cat", ["cat", "/dev/fd/63"], .... )
... 
openat(AT_FDCWD, "/dev/fd/63", O_RDONLY) = 3
fstat(3, {
  st_dev=makedev(0, 0xb),
  st_ino=63079295,
  st_mode=S_IFIFO|0600, 
  st_nlink=1,
  st_uid=1000, 
  st_gid=1000,
  st_blksize=4096,
  st_blocks=0,
  st_size=0,
  st_atime=1567670286 /* 2019-09-05T19:58:06.632258848+1200 */, 
  st_atime_nsec=632258848, 
  st_mtime=1567670286 /* 2019-09-05T19:58:06.633258850+1200 */, 
  st_mtime_nsec=633258850, 
  st_ctime=1567670286 /* 2019-09-05T19:58:06.633258850+1200 */, 
  st_ctime_nsec=633258850
}) = 0
...
read(3, "hello\n", 131072)              = 6
write(1, "hello\n", 6)                  = 6
read(3, "", 131072)                     = 0
close(3)                                = 0
close(1)                                = 0
```

Current rust code for sys::unix::fs::FileType
https://github.com/rust-lang/rust/blob/a24f636e60a5da57ab641d800ac5952bbde98b65/src/libstd/sys/unix/fs.rs#L195-L201

```rust
impl FileType {
    pub fn is_dir(&self) -> bool { self.is(libc::S_IFDIR) }
    pub fn is_file(&self) -> bool { self.is(libc::S_IFREG) }
    pub fn is_symlink(&self) -> bool { self.is(libc::S_IFLNK) }

    pub fn is(&self, mode: mode_t) -> bool { self.mode & libc::S_IFMT == mode }
}
```

But it may be worth noting the users assumptions do seem to hold true on Windows, where "is_file()" is just shorthand for "!is_symlink() && !is_directory()". But even then, if you're only asking "Can I read a thing", the "!is_symlink()" check is something you don't want to be doing, so **even there**, the "!is_dir()" is possibly the right call. Ugh.

https://github.com/rust-lang/rust/blob/a24f636e60a5da57ab641d800ac5952bbde98b65/src/libstd/sys/windows/fs.rs#L586-L617

```rust
impl FileType {
    fn new(attrs: c::DWORD, reparse_tag: c::DWORD) -> FileType {
        FileType {
            attributes: attrs,
            reparse_tag: reparse_tag,
        }
    }
    pub fn is_dir(&self) -> bool {
        !self.is_symlink() && self.is_directory()
    }
    pub fn is_file(&self) -> bool {
        !self.is_symlink() && !self.is_directory()
    }
    pub fn is_symlink(&self) -> bool {
        self.is_reparse_point() && self.is_reparse_tag_name_surrogate()
    }
    pub fn is_symlink_dir(&self) -> bool {
        self.is_symlink() && self.is_directory()
    }
    pub fn is_symlink_file(&self) -> bool {
        self.is_symlink() && !self.is_directory()
    }
    fn is_directory(&self) -> bool {
        self.attributes & c::FILE_ATTRIBUTE_DIRECTORY != 0
    }
    fn is_reparse_point(&self) -> bool {
        self.attributes & c::FILE_ATTRIBUTE_REPARSE_POINT != 0
    }
    fn is_reparse_tag_name_surrogate(&self) -> bool {
        self.reparse_tag & 0x20000000 != 0
    }
}
```

### PR DESCRIPTION
**Pull request by xiongmao86**
Fixes #4503.

changelog: Add a lint checking user are using FileType.is_file() method and suggest using !FileType.is_dir().

- [x] Followed [lint naming conventions][lint_naming]
- [x] Added passing UI tests (including committed `.stderr` file)
- [x] `cargo test` passes locally
- [x] Executed `./util/dev update_lints`
- [x] Added lint documentation
- [x] Run `./util/dev fmt`

### CODE REVIEW

**Comment by xiongmao86** [comment]
I had lint logic ready. But when I `cargo +nightly-2019-09-09 test`, The `dogfood` test failed.

This is the log from running `cargo +nightly-2019-09-09 test --test dogfood`:
```bash
rui@Lenovo:~/rust-clippy$ cargo +nightly-2019-09-09 test --test dogfood
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running target/debug/deps/dogfood-da4d84be69e33eac

running 2 tests
test dogfood ... FAILED
test dogfood_tests ... ok

failures:

---- dogfood stdout ----
status: exit code: 101
stdout: 
stderr:     Blocking waiting for file lock on package cache
   Compiling clippy v0.0.212 (/home/rui/rust-clippy)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/rui/.rustup/toolchains/nightly-2019-09-09-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.116t1ydy9ideddxg.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.163er32nmi7i36pe.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.1ggtkyrc3oenmcow.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.20xr7xreua862t0y.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.28z0stdj5wo2lkee.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.2kr03yngyvde3sd3.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.2pkqb6drnwr2zy7j.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.2uv4sjofn9kgntiv.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.2zwnvc543cg2456c.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.323gbj0k1ti6llmh.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.37bp07cn2d9m9cy4.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.3b5kb8rod2da6nlp.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.3nxwsh6mbz8819ob.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.3z2ur4iakbv5rf1l.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.4b9h8zo2ui6hqsso.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.4seg0arvr30n67wd.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.4zza8vk65w7e5qzb.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.50fo9vdt11t5e3f7.rcgu.o" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.v3rurly6dbtaens.rcgu.o" "-o" "/home/rui/rust-clippy/target/dogfood/debug/deps/libclippy.so" "-Wl,--version-script=/tmp/rustc0PiOEV/list" "/home/rui/rust-clippy/target/dogfood/debug/deps/clippy.468osoaaakpbp2ax.rcgu.o" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/home/rui/rust-clippy/target/dogfood/debug/deps" "-L" "/home/rui/.rustup/toolchains/nightly-2019-09-09-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libclippy_lints-34e56af20e3b7735.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libregex_syntax-84d19ad960b7da43.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/liburl-a69906a5d0e3aac3.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libpercent_encoding-d21f1bd1e24cdd4b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libidna-6e9a113b5168a2e3.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libunicode_normalization-0c489a3cf5589085.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libunicode_bidi-a3b77945ab3bd48f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libpulldown_cmark-a18b014193a39e2c.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libmemchr-b331e9160fa8f7f2.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libunicase-4ece29bee923cb36.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libbitflags-78fdf4f4a9a4744e.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libitertools-ce73c6a363071bf7.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libeither-72736a1b4824b363.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libcargo_metadata-b9866a601bdca73d.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libserde_json-cfcd9bd5c841e46e.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libryu-1b56339d1bed781e.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libitoa-419d61021aca3f4b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libquine_mc_cluskey-64386ead9a25021c.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libsemver-4006e56a5bfe5e4f.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libsemver_parser-1a06cb80a18ec96a.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libsmallvec-99e107c914a6b5d2.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libmatches-970bad7e3b4dc43a.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/liblazy_static-ec0a077c25ca9a34.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libif_chain-30615dbbdbaf241b.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libtoml-ba77f8fb49059904.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc0PiOEV/libserde-5ada223979f81eba.rlib" "-Wl,--no-whole-archive" "-L" "/home/rui/.rustup/toolchains/nightly-2019-09-09-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bdynamic" "-lrustc_driver-7f59143e8d87d50e" "-L" "/home/rui/.rustup/toolchains/nightly-2019-09-09-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-ltest-be322d795464d73e" "-Wl,--start-group" "-L" "/home/rui/.rustup/toolchains/nightly-2019-09-09-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lstd-8b07ab0b0fc43a5b" "-Wl,--end-group" "-Wl,-Bstatic" "/tmp/rustc0PiOEV/libcompiler_builtins-7e9599474821408b.rlib" "-Wl,-Bdynamic" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil" "-shared"
  = note: /usr/bin/ld: /tmp/rustc0PiOEV/libclippy_lints-34e56af20e3b7735.rlib(clippy_lints-34e56af20e3b7735.4kqlnbpflzwa5vjh.rcgu.o): bad reloc symbol index (0x6000000d >= 0x33) for offset 0x21a047 in section `.debug_info'
          /usr/bin/ld: /tmp/rustc0PiOEV/libclippy_lints-34e56af20e3b7735.rlib(clippy_lints-34e56af20e3b7735.4kqlnbpflzwa5vjh.rcgu.o): error adding symbols: bad value
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `clippy`.

To learn more, run the command again with --verbose.

thread 'dogfood' panicked at 'assertion failed: output.status.success()', tests/dogfood.rs:28:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    dogfood

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test dogfood'
```

File: clippy_lints/src/methods/mod.rs [hunk 1]
```diff
@@ -1010,6 +1010,12 @@ declare_clippy_lint! {
     "`.chcked_add/sub(x).unwrap_or(MAX/MIN)`"
 }
 
+declare_clippy_lint! {
+    pub FILETYPE_IS_FILE,
+    style,
+    "`FileType.is_file` does not cover all files the can be read."
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
    "`FileType::is_file` does not cover all files that can be read"
```
Also exchange the `.` with `::` below.

File: clippy_lints/src/methods/mod.rs [hunk 2]
```diff
@@ -2185,6 +2193,22 @@ fn lint_map_or_none<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, expr: &'tcx hir::Expr,
     }
 }
 
+fn lint_filetype_is_file(cx: &LateContext<'_, '_>, expr: &hir::Expr, args: &[hir::Expr]) {
+    const LINT_MSG: &str = "`FileType.is_file()` does not cover all readable file types in linux.";
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: What about other platforms? Clippy has to support Linux, macOS and Windows.

```suggestion
    const LINT_MSG: &str = "`FileType::is_file()` does not cover all readable file types in linux";
```

File: clippy_lints/src/methods/mod.rs [hunk 3]
```diff
@@ -2185,6 +2193,22 @@ fn lint_map_or_none<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, expr: &'tcx hir::Expr,
...
+    const HELP_MSG: &str = "Use `!FileType.is_dir()` instead.";
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
    const HELP_MSG: &str = "use `!FileType.is_dir()` instead";
```

This could maybe be an auto applicable suggestion. This mustn't be done in this PR though.

File: clippy_lints/src/lib.rs [hunk 4]
```diff
@@ -13,6 +13,7 @@
 #![cfg_attr(feature = "deny-warnings", deny(warnings))]
 #![feature(crate_visibility_modifier)]
 #![feature(concat_idents)]
+#![feature(bind_by_move_pattern_guards)]
```
Comment (flip1995) [inline clippy_lints/src/lib.rs]:
```suggestion
```

This is stable on nightly

**Comment by xiongmao86** [comment]
@flip1995 CI build failed. How can I find out which version of toolchain to download for fixing the build?

**Comment by llogiq** [comment]
We currently have a problem with the build we don't quite know how to solve, and it will likely include a fix in rustc. I think the best plan is to wait until the issue is solved, which will hopefully happen within the next 24 hours.

File: tests/compile-test.rs [hunk 5]
```diff
@@ -98,7 +98,7 @@ fn run_mode(mode: &str, dir: PathBuf) {
     compiletest::run_tests(&cfg);
 }
 
-#[allow(clippy::identity_conversion)]
+#[allow(clippy::identity_conversion, clippy::filetype_is_file)]
```
[the remark this answers is not in the document]
Comment (xiongmao86) [reply tests/compile-test.rs]: @flip1995 When you are saying this lint behaves correctly on windows/macOS, do you mean the lint logic is incomplete, I need to rule out cases like the case in this file; or do you mean the description of the lint does not cover the case in the windows/macOS?

[the remark this answers is not in the document]
Comment (flip1995) [reply tests/compile-test.rs]: I don't really know, if `is_file` is the same for windows and for linux/macOS. IIUC the issue describes a difference between windows and linux? Sadly I don't have time to really read up on this currently. You can ignore this for now and I'll get back to you some time later.

---
The case when `is_file` is negated by `!` needs to be handled though.

[the remark this answers is not in the document]
Comment (jplatte) [reply tests/compile-test.rs]: Why should `!x.is_file` be treated differently that `x.is_file`? To me, this looks exactly like the type of code the lint is supposed to trigger on, where `is_file` is seemingly used to check whether a path refers to a thing you can open as opposed to a directory (not a regular file as opposed to a symlink / fifo / whatever).

[the remark this answers is not in the document]
Comment (xiongmao86) [reply tests/compile-test.rs]: @jplatte, I assume it is checking with `!x.is_file` with special intention, otherwise `x.is_dir` is more apparent. But I am not sure though.

[the remark this answers is not in the document]
Comment (flip1995) [reply tests/compile-test.rs]: Oh yeah, I meant, that this lint should check for `!is_file` and suggest `is_dir`.

[the remark this answers is not in the document]
Comment (xiongmao86) [reply tests/compile-test.rs]: Oh, @jplatte @flip1995, do you mean the lint should also checking for `!x.is_file()` and suggest `x.is_dir()` instead. Not saying that the statement `!file.file_type()?.is_file()` in this function should be change to `file.file_type()?.is_dir()`?

[the remark this answers is not in the document]
Comment (flip1995) [reply tests/compile-test.rs]: Both, the `!file.file_type()?.is_file()` should be changed to `file.file_type()?.is_dir()` and the lint should check for `!x.is_file`

File: tests/ui/filetype_is_file.rs [hunk 6]
```diff
@@ -0,0 +1,23 @@
+#![warn(clippy::filetype_is_file)]
+
+fn main() -> std::io::Result<()> {
+    use std::ops::BitOr;
+    use std::fs;
+
+    // !filetype.is_dir()
+    if fs::metadata("foo.txt")?.file_type().is_file() {
```
Comment (xiongmao86) [inline tests/ui/filetype_is_file.rs]: @flip1995 I have add two new case to be implemented, but didn't touch the origin lint logic, but why doesn't this line trigger lints?

Comment (flip1995) [reply tests/ui/filetype_is_file.rs]: I don't really know why, whis should trigger the lint. Can you post the output of `dbg!(&args[0])` and `dbg!(ty)`?

**Comment by xiongmao86** [comment]
Thank you.

**Comment by xiongmao86** [comment]
@flip1995 do you have time to review my code now?

File: clippy_lints/src/methods/mod.rs [hunk 7]
```diff
@@ -1102,6 +1102,40 @@ declare_clippy_lint! {
     "Check for offset calculations on raw pointers to zero-sized types"
 }
 
+declare_clippy_lint! {
+    /// **What it does:** Checks for `FileType::is_file()`.
+    ///
+    /// **Why is this bad?** When people testing a file type with `FileType::is_file`
+    /// they are testing whether a path is something they can get bytes from. But
+    /// `is_file` doesn't cover special file types in unix-like systems. and not covering
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
    /// `is_file` doesn't cover special file types in unix-like systemsand does not cover symlinks
```

File: clippy_lints/src/methods/mod.rs [hunk 8]
```diff
@@ -1102,6 +1102,40 @@ declare_clippy_lint! {
...
+    /// symlink in windows. Using `!FileType::is_dir()` is a better way to that intention.
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
    /// in windows. Using `!FileType::is_dir()` is a better way to do this.
```

File: clippy_lints/src/methods/mod.rs [hunk 9]
```diff
@@ -1102,6 +1102,40 @@ declare_clippy_lint! {
...
+    /// ```rust,ignore
+    /// let metadata = std::fs::metadata("foo.txt")?;
+    /// let filetype = metadata.file_type();
+    ///
+    /// if filetype.is_file() {
+    ///     // read file
+    /// }
+    /// ```
+    ///
+    /// should be writing as:
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
    /// should be written as:
```

File: clippy_lints/src/methods/mod.rs [hunk 10]
```diff
@@ -1102,6 +1102,40 @@ declare_clippy_lint! {
...
+    /// let metadata = std::fs::metadata("foo.txt")?;
+    /// let filetype = metadata.file_type();
+    ///
+    /// if !filetype.is_dir() {
+    ///     // read file
+    /// }
+    /// ```
+    pub FILETYPE_IS_FILE,
+    style,
+    "`FileType::is_file` is not recommended to test for readable file type."
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
    "`FileType::is_file` is not recommended to test for readable file type"
```

File: clippy_lints/src/methods/mod.rs [hunk 11]
```diff
@@ -3169,3 +3205,26 @@ fn check_pointer_offset(cx: &LateContext<'_, '_>, expr: &hir::Expr<'_>, args: &[
...
+        if let hir::ExprKind::Unary(op, _) = parent.kind;
+        if op == hir::UnNot;
+        then {
+            let lint_msg = "`!FileType::is_file()` does not deny all readable file types";
+            let help_msg = "use `FileType::is_dir()` instead";
+            span_help_and_lint(cx, FILETYPE_IS_FILE, parent.span, lint_msg, help_msg);
+        } else {
+            let lint_msg = "`FileType::is_file()` does not cover all readable file types";
+            let help_msg = "use `!FileType::is_dir()` instead";
+            span_help_and_lint(cx, FILETYPE_IS_FILE, expr.span, lint_msg, help_msg);
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: IMO a better lint message would be "
```rust
let lint_msg = format!("`{}FileType::is_file()` only covers regular files", /*either "!" or "", depending on the case*/);
let help_msg = format!("use `{}FileType::is_dir()` instead", /*either "!" or "", depending on the case*/);
```

File: clippy_lints/src/methods/mod.rs [hunk 12]
```diff
@@ -1102,6 +1102,40 @@ declare_clippy_lint! {
...
+    /// ```rust,ignore
+    /// let metadata = std::fs::metadata("foo.txt")?;
+    /// let filetype = metadata.file_type();
+    ///
+    /// if !filetype.is_dir() {
+    ///     // read file
+    /// }
+    /// ```
+    pub FILETYPE_IS_FILE,
+    style,
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: I don't think this lint should be `warn-by-default`, since just calling `FileType::is_file()` is totally fine in it self. I would suggest to make this a 
```suggestion
    restriction,
```
lint. (A run of `./util/dev update_lints` will be required)

File: clippy_lints/src/methods/mod.rs (hunk 11 above)
Comment (xiongmao86) [reply clippy_lints/src/methods/mod.rs]: I am not sure it is ok to say `!FileType::is_file()` only covers regular files? Because `!FileType.is_file()` is true only if FileType is a dir. In this case `FileType::is_file()` covers regular files, but `!FileType::is_file()` (with `!`) does not.

File: clippy_lints/src/methods/mod.rs (hunk 7 above)
Comment (xiongmao86) [reply clippy_lints/src/methods/mod.rs]: Missing a comma here.
```suggestion
    /// `is_file` doesn't cover special file types in unix-like systems, and doesn't cover
```

File: clippy_lints/src/methods/mod.rs (hunk 11 above)
Comment (flip1995) [reply clippy_lints/src/methods/mod.rs]: `!FileType.is_file()` should also be true for symlinks, shouldn't it?

Comment (xiongmao86) [reply clippy_lints/src/methods/mod.rs]: Eh, that's not what I meant. I am not an native English speaker, and I am not sure "`!FileType::is_file()` only covers regular files" would be perceived as when FileType is a regular file return true not as when FileType is not a regular file return true.

File: clippy_lints/src/methods/mod.rs [hunk 13]
```diff
@@ -3169,3 +3205,35 @@ fn check_pointer_offset(cx: &LateContext<'_, '_>, expr: &hir::Expr<'_>, args: &[
...
+        } else {
+            lint_unary = "";
+            verb = "covers";
+            help_unary = "!";
+            span = expr;
+        }
+    }
+    let lint_msg = format!("`{}FileType::is_file()` only {} regular files", lint_unary, verb);
+    let help_msg = format!("use `{}FileType::is_dir()` instead", help_unary);
+    span_help_and_lint(cx, FILETYPE_IS_FILE, span.span, &lint_msg, &help_msg);
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
    span_help_and_lint(cx, FILETYPE_IS_FILE, span, &lint_msg, &help_msg);
```

and then write `parent/expr.span` above.

Comment (xiongmao86) [inline clippy_lints/src/methods/mod.rs]: @flip1995 Is this change Ok?

File: clippy_lints/src/methods/mod.rs [hunk 14]
```diff
@@ -3169,3 +3205,35 @@ fn check_pointer_offset(cx: &LateContext<'_, '_>, expr: &hir::Expr<'_>, args: &[
...
+    let verb: &str;
+    let lint_unary: &str;
+    let help_unary: &str;
+    if_chain! {
+        if let Some(parent) = get_parent_expr(cx, expr);
+        if let hir::ExprKind::Unary(op, _) = parent.kind;
+        if op == hir::UnNot;
+        then {
+            lint_unary = "!";
+            verb = "denys";
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
            verb = "denies";
```

**Comment by xiongmao86** [comment]
Ready to merge. @flip1995 thank you very much for helping me with this pr.

**Comment by flip1995** [comment]
Can you squash some commits? Especially the "Update clippy_lints/..." commits.

**Comment by xiongmao86** [comment]
@flip1995 is this ok? or should I also change the rest update commits?

**Comment by flip1995** [comment]
Another `update_lints` is required. When you're done, please remove the "[WIP]" status from the PR title

**Comment by xiongmao86** [comment]
Update to rust master build.

**Comment by flip1995** [comment]
Uh the rustup is in #5040. Can you revert these changes here?

**Comment by xiongmao86** [comment]
@flip1995, How can I find out the progress of rustup in advance, are there any keyword to search the pull request? or any other means? How can I find out which version of rust to use. I revert the commit, but some other problem show up when I `cargo test`.

**Comment by flip1995** [comment]
You can just execute `sh setup-toolchain.sh` in the clippy root, which installs the latest rustc master. Rustups are required, when the compiler changes some internals, which Clippy depends on and therefore Clippy breaks. Most of the time, we don't get notified beforehand. But when something breaks, an issue like rust-lang/rust#68107 gets opened in the rust compiler. After that Clippy needs a fix, called a rustup, like #5025 #5040 #4218 .... This should be done in a separate PR though.

**Comment by flip1995** [comment]
Now this should be good to go! :tada: Thanks for all the work!

@bors r+

**Comment by xiongmao86** [comment]
@flip1995, accomplished something finally. Thank you very much for helping me with this pr.
