### PR TITLE
fix `from_over_into` false positive with conflicting blanket From impl

### LINKED ISSUE #16823: `from_over_into` suggests turning `Into` into conflicting `From`
### Summary

For a newtype like `struct Foo(String)`, Rust permits `impl<T> From<T> for Foo where String: From<T>`. In the presence of this, `impl From<Foo> for String` is not allowed due to conflicting implementations, but as a workaround `impl Into<String> for Foo` is permitted. However, `clippy` suggests turning the latter into the former.

### Lint Name

from_over_into

### Reproducer

I tried this code:

```rust
pub struct Foo(pub String);

impl<T> From<T> for Foo
where
    String: From<T>,
{
    fn from(label: T) -> Self {
        Self(String::from(label))
    }
}

// Triggers `clippy::from_over_into`.
impl Into<String> for Foo {
    fn into(self) -> String {
        self.0
    }
}

// Suggestion from `clippy::from_over_into`. Uncommenting gives:
//
// ```
// error[E0119]: conflicting implementations of trait `From<Foo>` for type `Foo`
//  --> src/lib.rs:3:1
//   |
// 3 | / impl<T> From<T> for Foo
// 4 | | where
// 5 | |     String: From<T>,
//   | |____________________^
//   |
//   = note: conflicting implementation in crate `core`:
//           - impl<T> From<T> for T;
// ```
// impl From<Foo> for String {
//     fn from(foo: Foo) -> Self {
//         foo.0
//     }
// }
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=58f7daf18ca84b0769ba54b77d913f4c))

I saw this happen:

```
warning: an implementation of `From` is preferred since it gives you `Into<_>` for free where the reverse isn't true
  --> src/lib.rs:13:1
   |
13 | impl Into<String> for Foo {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: `impl From<Local> for Foreign` is allowed by the orphan rules, for more information see
           https://doc.rust-lang.org/reference/items/implementations.html#trait-implementation-coherence
   = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.94.0/index.html#from_over_into
   = note: `#[warn(clippy::from_over_into)]` on by default
help: replace the `Into` implementation with `From<Foo>`
   |
13 ~ impl From<Foo> for String {
14 ~     fn from(val: Foo) -> Self {
15 ~         val.0
   |
```

I expected to see this happen: Clippy not suggesting a fix that results in compiler error.

### Version

Tested both stable and latest beta:

```text
rustc 1.95.0-beta.7 (cc969f3c4 2026-04-03)
binary: rustc
commit-hash: cc969f3c457b2ce350fb9fda6c784cc9813b5c71
commit-date: 2026-04-03
host: x86_64-unknown-linux-gnu
release: 1.95.0-beta.7
LLVM version: 22.1.2
```

```text
rustc 1.94.1 (e408947bf 2026-03-25)
binary: rustc
commit-hash: e408947bfd200af42db322daf0fadfe7e26d3bd1
commit-date: 2026-03-25
host: x86_64-unknown-linux-gnu
release: 1.94.1
LLVM version: 21.1.8
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by pocopepe**
fixes rust-lang/rust-clippy#16823

This is my first contribution to Clippy,  happy to make changes if the approach isn't quite right

changelog: [`from_over_into`]: don't lint when a blanket `From` impl would cause a coherence conflict

### CODE REVIEW

File: clippy_lints/src/from_over_into.rs [hunk 1]
```diff
@@ -163,11 +165,21 @@ impl<'tcx> Visitor<'tcx> for SelfFinder<'_, 'tcx> {
     }
 }
 
+fn has_blanket_from_impl<'tcx>(cx: &LateContext<'tcx>, self_ty: Ty<'tcx>) -> bool {
+    let Some(from_def_id) = cx.tcx.get_diagnostic_item(sym::From) else {
+        return false;
+    };
+    cx.tcx.all_impls(from_def_id).any(|impl_id| {
```
Comment (Alexendoo) [inline clippy_lints/src/from_over_into.rs]: This can use `cx.tcx.non_blanket_impls_for_ty` to avoid iterating over all `From` impls

Despite the name `impl From<T> for Foo` is stored in [`TraitImpls::non_blanket_impls`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/trait_def/struct.TraitImpls.html#structfield.non_blanket_impls), this disagrees with [the glossary](https://doc.rust-lang.org/nightly/reference/glossary.html?highlight=blanket#blanket-implementation) but I'm not sure which one is correct

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-clippy/16881/5800532ce08a453bb0eb60c4d6661500fc8c7b33..2d6808aa1107b08b14d4394f431dfa53c91d599c)*

Comment (pocopepe) [reply clippy_lints/src/from_over_into.rs]: thanks for pointing it out, also dropped the `self_ty ==` check since `non_blanket_impls_for_ty` already handles that

**Review by Alexendoo — APPROVED** [review]
Thanks!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-clippy/16881/5800532ce08a453bb0eb60c4d6661500fc8c7b33..5c81d3af11f8d782b36d800ee6680a5bdacf60dd)*
