### PR TITLE
Remove powi, "square can be computed more efficiently"

### LINKED ISSUE #7058: "square can be computed more efficiently" is wrong
Lint name:
`suboptimal_flops`

I tried this code:

```rust
#![warn(clippy::suboptimal_flops)]

pub fn sample_sqr(x: f64) -> f64 {
    x.powi(2)
}
```

I expected to see this happen: it should pass.

Instead, this happened: it says "square can be computed more efficiently" and suggests to use `x * x` instead.

This is incorrect, because, unlike `powf`, `powi` produces exactly same native code as `x * x`, and is more natural to read (IMO). If anything, due to usage of intrinsic, it might be optimised even more than bare expression, although they're unlikely to be different on practice.

### Meta

- `cargo clippy -V`: clippy 0.1.53 (2e495d2 2021-04-08)
- `rustc -Vv`:
  ```
	  rustc 1.53.0-nightly (2e495d2e8 2021-04-08)
	  binary: rustc
	  commit-hash: 2e495d2e845cf27740e3665f718acfd3aa17253e
	  commit-date: 2021-04-08
	  host: x86_64-unknown-linux-gnu
	  release: 1.53.0-nightly
	  LLVM version: 12.0.0
  ```

### PR DESCRIPTION
**Pull request by mucinoab**
powi(2) produces exactly the same native code as x * x
powi was part of the [`suboptimal_flops`] lint

fixes #7058
changelog: Remove powi [`suboptimal_flops`], "square can be computed more efficiently"

### CODE REVIEW

File: clippy_lints/src/floating_point_arithmetic.rs [hunk 1]
```diff
@@ -297,60 +297,6 @@ fn check_powf(cx: &LateContext<'_>, expr: &Expr<'_>, args: &[Expr<'_>]) {
...
-                        "square can be computed more efficiently",
-                        "consider using",
-                        format!(
-                            "{}.mul_add({}, {})",
-                            Sugg::hir(cx, &args[0], ".."),
-                            Sugg::hir(cx, &args[0], ".."),
-                            Sugg::hir(cx, other_addend, ".."),
-                        ),
-                        Applicability::MachineApplicable,
-                    );
```
Comment (giraffate) [inline clippy_lints/src/floating_point_arithmetic.rs:335]: Why does this case also removed?

Comment (mucinoab) [reply clippy_lints/src/floating_point_arithmetic.rs:335]: It is just a special case for https://github.com/rust-lang/rust-clippy/blob/c8d52e35c10ca7cfa841309a7db4052344b710bf/clippy_lints/src/floating_point_arithmetic.rs#L403
Should we keep it?

Comment (giraffate) [reply clippy_lints/src/floating_point_arithmetic.rs:335]: In the related issue, I found that the case of `x * x` was discussed, but I couldn't find the discussion of `mul_add`. So I don't know why this case needs to be removed as same.

If there is no reason, I think it would be better to keep it.

**Comment by mucinoab** [comment]
@giraffate I did some changes. Should we keep the same names for everything?

**Review by giraffate — APPROVED** [review]
@mucinoab It looks good! Can you squash the commits and mark this PR as ready?

**Comment by mucinoab** [comment]
@giraffate All done.

**Comment by giraffate** [comment]
@bors r+

Thanks!
