### PR TITLE
Fix suggestion on fully qualified syntax

### LINKED ISSUE #10850: `explicit_deref_methods` malformed suggestion on fully qualified syntax
### Summary

`explicit_deref_methods` gives a malformed suggestion when it's emitted on fully qualified syntax.

### Reproducer

I tried this code:

```rust
<Foo as Deref>::deref(foo);
```

Where `Foo` implements `Deref`.

I saw this happen:

```
&*<Foo as Deref>::deref;
```

I expected to see this happen:

```
&*foo;
```

### Version

```text
rustc 1.71.0-nightly (a2b1646c5 2023-05-25)
binary: rustc
commit-hash: a2b1646c597329d0a25efa3889b66650f65de1de
commit-date: 2023-05-25
host: x86_64-pc-windows-gnu
release: 1.71.0-nightly
LLVM version: 16.0.4
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by Centri3**
fixes #10850

changelog: [`explicit_deref_methods`]: Fix malformed suggestion on `Foo::deref(&foo)`

### CODE REVIEW

File: clippy_lints/src/dereference.rs [hunk 1]
```diff
@@ -1503,12 +1512,25 @@ fn report<'tcx>(cx: &LateContext<'tcx>, expr: &'tcx Expr<'_>, state: State, data
...
             } else {
                 expr_str.into_owned()
             };
 
+            // Fix #10850, changes suggestion if it's `Foo::deref` instead of `foo.deref`. Since `Foo::deref` is
+            // a `Call` instead of a `MethodCall` this should catch all instances of this, even if it's fully
+            // qualified or whatnot.
+            if is_final_ufcs && let Some(args) = call_args {
+                // Remove ref if it's there
+                let arg = if let ExprKind::AddrOf(.., arg) = args[0].kind {
```
Comment (Centri3) [inline clippy_lints/src/dereference.rs:1526]: Is there a function that does this for me? Since this does feel a tad hacky.

Comment (Centri3) [reply clippy_lints/src/dereference.rs:1526]: I also feel this could break on something like `*foo` if it's `&&Foo` but I haven't tested this yet.

**Comment by Alexendoo** [comment]
The `Foo` part can participate in type inference

```rust
use std::ops::Deref;

fn main() {
    let a = Default::default();
    let b = String::deref(&a);
}
```

Maybe we ought to preserve `Foo::deref` anyway though as unlike `.deref()` it does provide more information to the reader than the equivalent `&*`, what type is being deref'd can be confusing

**Comment by llogiq** [comment]
Thanks @Alexendoo for taking on the review, and thanks @Centri3 for pushing this forward!

@bors r+
