### PR TITLE
lint when calling the blanket `Into` impl from a `From` impl

### LINKED ISSUE #11150: Using into() in the From trait without having implemented Into should generate a compilation error.
### Code

```Rust
fn main() {
    #[derive(Debug)]
    struct Number(f32);

    impl From<f32> for Number {
        fn from(value: f32) -> Self {
            value.into()
        }
    }

    let value: Number = (10.0).into();
    println!("{value:?}");
}
```

### Current output

```Shell
Compiling number v0.1.0 (/home/number)
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target/debug/number`

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
[1]    25988 IOT instruction (core dumped)  cargo run
```

### Desired output

The compiler should detect that we are calling Into<Number> for f32 trait which is automatically implemented by From<f32> for Number trait in our implementation of the From<f32> for Number trait.

### Rationale and extra context

_No response_

### Other cases

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by y21**
Closes #11150
```
warning: function cannot return without recursing
  --> x.rs:9:9
   |
9  | /         fn from(value: f32) -> Self {
10 | |             value.into()
11 | |         }
   | |_________^
   |
note: recursive call site
  --> x.rs:10:13
   |
10 |             value.into()
   |             ^^^^^^^^^^^^
```

I'm also thinking that we can probably generalize this lint to #11032 at some point (instead of hardcoding a bunch of impls), like how rustc's `unconditional_recursion` works, at least up to one indirect call, but this still seems useful for now :)

I've also noticed that we use `fn_def_id` in a bunch of lints and then try to get the node args of the call in a separate step, so I made a helper function that does both in one. I intend to refactor a bunch of uses of `fn_def_id` to use this later

I can add more test cases, but this is already using much of the same logic that exists for the other impls that this lint looks for (e.g. making sure that there are no conditional returns).

changelog: [`unconditional_recursion`]: emit a warning inside of `From::from` when unconditionally calling the blanket `.into()` impl

### CODE REVIEW

File: clippy_lints/src/unconditional_recursion.rs [hunk 1]
```diff
@@ -19,11 +20,11 @@ use rustc_trait_selection::traits::error_reporting::suggestions::ReturnsVisitor;
...
 declare_clippy_lint! {
     /// ### What it does
-    /// Checks that there isn't an infinite recursion in `PartialEq` trait
-    /// implementation.
+    /// Checks that there isn't an infinite recursion in trait
+    /// implementations.
     ///
     /// ### Why is this bad?
-    /// This is a hard to find infinite recursion which will crashing any code
+    /// This is a hard to find infinite recursion which will crash any code
```
Comment (hamirmahal) [inline clippy_lints/src/unconditional_recursion.rs:27]:
```suggestion
    /// This is a hard to find infinite recursion that will crash any code.
```

File: clippy_lints/src/unconditional_recursion.rs [hunk 2]
```diff
@@ -394,6 +393,33 @@ impl UnconditionalRecursion {
...
+    };
+
+    // Check if we are calling `Into::into` where the node args match with our `From::from` signature:
+    // From::from signature: fn(S1) -> S2
+    // <S1 as Into<S2>>::into(s1), node_args=[S1, S2]
+    // If they do match, then it must mean that it is the blanket impl,
+    // which calls back into our `From::from` again (`Into` is not specializable).
+    // rustc's unconditional_recursion already catches calling `From::from` directly
+    if let Some((fn_def_id, node_args)) = fn_def_id_with_node_args(cx, expr)
+        && let Some((s1, s2)) = node_args.iter().filter_map(ty::GenericArg::as_type).collect_tuple()
```
Comment (Jarcho) [inline clippy_lints/src/unconditional_recursion.rs:412]:
```suggestion
&& let [s1, s2] = node_args
&& let (Some(s1), Some(s2)) = (s1.as_type(), s2.as_type())
```

**Review by Jarcho — COMMENTED** [review]
This should have some negative tests. Otherwise Looks good.

**Comment by y21** [comment]
added a few more tests I could think of in the last commit, if you have some more concrete ones I can add them. Also removed an unnecessary `get_trait_def_id` which could be using diagnostic items

**Review by Jarcho — APPROVED** [review]
@bors delegate

All looks good. r=me after squashing.

**Comment by y21** [comment]
squashed
@bors r=Jarcho
