### PR TITLE
fix incorrect suggestion for `!(a >= b) as i32 == c`

### LINKED ISSUE #12761: suggestion from nonminimal_bool with integer cast creates a syntax error due to parentheses removal
### Summary

When a bool expression is not minimal and the result is cast to an integer, the lint can "forget" the correct parentheses order triggering incorrect suggestions.  

### Reproducer

I tried this code:

```rust
fn f(a: i32) -> bool {
    !(1 >= 2) as i32 == a
}
```

I expected to see this suggested:

```rust
fn f(a: i32) -> bool {
    (1 < 2) as i32 == a
}
```

Instead, clippy suggested:

```warning: this boolean expression can be simplified
 --> src/main.rs:2:5
  |
2 |     !(1 >= 2) as i32 == a
  |     ^^^^^^^^^ help: try: `1 < 2`
```

and `cargo clippy --fix` produced: 

```
error: comparison operators cannot be chained
 --> src/main.rs:2:7
  |
2 |     1 < 2 as i32 == a
  |       ^          ^^
  |
help: parenthesize the comparison
  |
2 |     (1 < 2 as i32) == a
  |     +            +

error: aborting due to 1 previous error
```

which is additionally not a good suggestion since `(1 < 2 as i32) == a` has a type error.

### Version

```text
rustc 1.80.0-nightly (d2d24e395 2024-05-03)
binary: rustc
commit-hash: d2d24e395a1e4fcee62ca17bf4cbddb1f903af97
commit-date: 2024-05-03
host: aarch64-apple-darwin
release: 1.80.0-nightly
LLVM version: 18.1.4
```

### Additional Labels

@rustbot label +l-suggestion-causes-error

### PR DESCRIPTION
**Pull request by CoCo-Japan-pan**
fixes #12761 

The expression `!(a >= b) as i32 == c` got simplified to `a < b as i32 == c`, but this is a syntax error.
The result we want is `(a < b) as i32 == c`.
This is fixed by adding a parenthesis to the suggestion given in `check_simplify_not` when the boolean expression is casted.

changelog: [`nonminimal_bool`]: fix incorrect suggestion for `!(a >= b) as i32 == c`

### CODE REVIEW

**Review by Centri3 — COMMENTED** [review]
I'd say we should use `Sugg::maybe_par` in `clippy_utils` for this. The code is correct for this case, but it's missing other cases (mostly binary ops) where parentheses are required. For example, `!(1 >= 2) | true == a` also causes the same issue, which the suggested function handles.

**Comment by CoCo-Japan-pan** [comment]
I wasn't familiar with the `clippy_utils::sugg`, and I think my code is redundant, but I'll push this for now.
I thought we have to keep the parent expression, so I added a stack, but maybe just applying `Sugg::maybe_par` to the `suggestion` in `let Some(suggestion) = simplify_not(cx, inner)` was sufficient?

**Comment by CoCo-Japan-pan** [comment]
Given the fact that `simplify_not` only deals with `ExprKind::Binary` and `ExprKind::MethodCall`, I believe the problem occurs only when we simplify `ExprKind::Binary`, and the expression belongs to `ExprKind::Cast` or `ExprKind::Binary`, so I changed the `need_parens` logic.

**Comment by Centri3** [comment]
Well, this code is incorrect:
```rust
fn a(a: bool) -> bool {
    (!(4 > 3)).b()
}

trait B {
    fn b(&self) -> bool { true }
}

impl B for bool {}
```

Really, is there any reason not to use `Sugg` directly? It's easier than getting the parent expression as well.

File: clippy_lints/src/booleans.rs [hunk 1]
```diff
@@ -176,13 +180,28 @@ fn check_inverted_bool_in_condition(
     );
 }
 
-fn check_simplify_not(cx: &LateContext<'_>, expr: &Expr<'_>) {
+fn check_simplify_not(cx: &LateContext<'_>, expr: &Expr<'_>, parent_expr: Option<&Expr<'_>>) {
```
Comment (Centri3) [inline clippy_lints/src/booleans.rs:183]: You can get the parent using `get_parent_expr`

**Comment by CoCo-Japan-pan** [comment]
Using `Sugg::maybe_par` would be like this?
Or should we get the modified `Expr` (not just the `String`) from `simplify_not`, and then apply `maybe_par`?
Currently it doesn't see the parent expression, and adds an unnecessary parenthesis to some expressions like below.
```
if !(12 == a) {}
   ^^^^^^^^^^ help: try: `(12 != a)`
```

**Comment by CoCo-Japan-pan** [comment]
Excluded the case when the parent expression is the `ExprKind::DropTemps(_)` to avoid adding unnecessary parenthesis.

**Comment by Centri3** [comment]
> and adds an unnecessary parenthesis to some expressions like below.

Yes, I know, this is a non-issue as `unused_parens` will almost always catch it and if it doesn't that's fine too.

Why do we need the parent expression? Is there any case where it misses required parentheses in that case? This feels overly complicated for 2 characters that will likely be removed on the next clippy run.

**Comment by CoCo-Japan-pan** [comment]
Deleted the parent expression stuff.

File: clippy_lints/src/booleans.rs [hunk 2]
```diff
@@ -203,6 +203,20 @@ fn check_simplify_not(cx: &LateContext<'_>, msrv: &Msrv, expr: &Expr<'_>) {
         && let Some(suggestion) = simplify_not(cx, msrv, inner)
         && cx.tcx.lint_level_at_node(NONMINIMAL_BOOL, expr.hir_id).0 != Level::Allow
     {
+        use clippy_utils::sugg::{Sugg, has_enclosing_paren};
+        let maybe_par = if let Some(sug) = Sugg::hir_opt(cx, inner) {
+            match sug.maybe_par() {
```
Comment (Centri3) [inline clippy_lints/src/booleans.rs:208]: So we actually both misunderstood `maybe_par` in our own ways, and my bad. In this case you usually don't match on it, as it essentially adds parentheses around all `MaybeParen` that don't already have them and all `BinOp`s, and turns them into `NonParen` (which now is a `str` with parentheses around it). This is so it can be used in `format!` with a piece of the original code for use in the suggestion.

But that's not the case here, we aren't printing it, only seeing if it needs parentheses. So really, the only thing here that will ever be hit is `NonParen` and `MaybeParen`. Instead, refer to the implementation of [`maybe_par`](https://doc.rust-lang.org/nightly/nightly-rustc/src/clippy_utils/sugg.rs.html#339-355) and copy it a bit. If it's `MaybeParen` (with `has_enclosing_paren == false`) or `BinOp`, then you return true.

Comment (CoCo-Japan-pan) [reply clippy_lints/src/booleans.rs]: It seemed like `matches!` couldn't handle both if guards and `|` , so used the usual match.

**Review by Centri3 — COMMENTED** [review]
Thanks :+1:
