### PR TITLE
Fixed FP in `unused_io_amount` for Ok(lit), unrachable! and unwrap de…

### LINKED ISSUE #12208: `unused_io_amount` false positive if the result is matched by `Ok(<literal>)` or `unreachable!()` cases
### Summary

See the reproducer. I believe it's introduced by #12005. cc @PartiallyTyped

I saw there are two issues:
1. We should consider `Ok(<literal>)` as used, as the read amount is actually checked.
2. We should consider `Ok(_) => unreachable!()` as used, as we are explicitly asserting the read must fail for some reason. I'm not quite sure how exactly we should do this. As simply checking if the arm has type `!` would instead yield a false-negative for `Ok(_) => return`. 

### Lint Name

unused_io_amount

### Reproducer

Given this code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=fb571019516a72fb6b51e9c0ea40ae14)):
```rust
pub fn work(rdr: &mut dyn std::io::Read) {
    match rdr.read(&mut [0]) {
        Ok(0) => println!("EOF"),
        Ok(_) => println!("fully read"),
        Err(_) => println!("fail"),
    }
}

pub fn work2(rdr: &mut dyn std::io::Read) {
    match rdr.read(&mut [0]) {
        Ok(_) => unreachable!(),
        Err(_) => println!("expected"),
    }
}
```

I saw this happen:

```
error: read amount is not handled
 --> src/lib.rs:2:11
  |
2 |     match rdr.read(&mut [0]) {
  |           ^^^^^^^^^^^^^^^^^^
  |
  = help: use `Read::read_exact` instead, or handle partial reads
note: the result is consumed here, but the amount of I/O bytes remains unhandled
 --> src/lib.rs:4:9
  |
4 |         Ok(_) => println!("fully read"),
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount
  = note: `#[deny(clippy::unused_io_amount)]` on by default

error: read amount is not handled
  --> src/lib.rs:10:11
   |
10 |     match rdr.read(&mut [0]) {
   |           ^^^^^^^^^^^^^^^^^^
   |
   = help: use `Read::read_exact` instead, or handle partial reads
note: the result is consumed here, but the amount of I/O bytes remains unhandled
  --> src/lib.rs:11:9
   |
11 |         Ok(_) => unreachable!(),
   |         ^^^^^^^^^^^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount
```

I expected to see this happen: no errors or warnings emitted.

### Version

```text
(Playground) 0.1.77 (2024-01-27 6b4f1c5)
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by PartiallyTyped**
…sugar

Fixes fp caused by linting on Ok(_) for all cases outside binding.

We introduce the following rules for match exprs.
- `panic!` and `unreachable!` are treated as consumed.
- `Ok( )` patterns outside `DotDot` and `Wild` are treated as consuming.

changelog: FP [`unused_io_amount`] when matching Ok(literal) or unreachable

fixes #12208 

r? @blyxyas

### CODE REVIEW

**Comment by PartiallyTyped** [comment]
Sorry for opening this can of worms, and for taking as long to fix this ._.

File: clippy_lints/src/unused_io_amount.rs [hunk 1]
```diff
@@ -130,23 +170,46 @@ fn should_lint<'a>(cx: &LateContext<'a>, mut inner: &'a hir::Expr<'a>) -> Option
     check_io_mode(cx, inner)
 }
 
-fn pattern_is_ignored_ok(cx: &LateContext<'_>, pat: &hir::Pat<'_>) -> bool {
+enum OkPatternKind {
```
Comment (blyxyas) [inline clippy_lints/src/unused_io_amount.rs:173]: This could be removed and all instances removed by booleans, and all checking would be easier.

File: clippy_lints/src/unused_io_amount.rs [hunk 2]
```diff
@@ -130,23 +170,46 @@ fn should_lint<'a>(cx: &LateContext<'a>, mut inner: &'a hir::Expr<'a>) -> Option
...
+fn is_unreachable_or_panic(cx: &LateContext<'_>, expr: &hir::Expr<'_>) -> bool {
+    let expr = peel_blocks(expr);
+    let Some(macro_call) = root_macro_call_first_node(cx, expr) else {
+        return false;
+    };
+    if is_panic(cx, macro_call.def_id) {
+        if cx.tcx.hir().is_inside_const_context(expr.hir_id) {
+            return false;
+        }
+        return true;
```
Comment (blyxyas) [inline clippy_lints/src/unused_io_amount.rs:210]:
```suggestion
        return !cx.tcx.hir().is_inside_const_context(expr.hir_id);
```

File: clippy_lints/src/unused_io_amount.rs [hunk 3]
```diff
@@ -82,37 +85,74 @@ impl<'tcx> LateLintPass<'tcx> for UnusedIoAmount {
...
+    }
+    if is_unreachable_or_panic(cx, arm.body) {
+        // if the body is unreachable or there is a panic,
+        // we consider the result to be consumed
+        return ControlFlow::Continue(());
+    }
+
+    if let Some(OkPatternKind::WildOrDotDot) = extract_ok_pattern(cx, arm.pat) {
+        return ControlFlow::Break(arm.pat);
+    }
```
Comment (blyxyas) [inline clippy_lints/src/unused_io_amount.rs:132]: With that previous comment, this could be:

```suggestion
    return extract_ok_pattern(cx, arm.pat);
```

This would also need to return a bool. But as this is the only the branch that returns meaningful information, making the switch won't be hard I'd suppose.

File: clippy_lints/src/unused_io_amount.rs [hunk 4]
```diff
@@ -82,37 +85,74 @@ impl<'tcx> LateLintPass<'tcx> for UnusedIoAmount {
...
-            if !found_arms.is_empty() {
-                emit_lint(cx, expr.span, op, found_arms.as_slice());
+        // we will capture only the case where the match is Ok( ) or Err( )
+        // prefer to match the minimum possible, and expand later if needed
+        // to avoid false positives on something as used as this
+        hir::ExprKind::Match(expr, arms @ [_, _], hir::MatchSource::Normal) if let Some(op) = should_lint(cx, expr) => {
+            let ok_arm = arms.iter().try_for_each(|arm| non_consuming_ok_arm(cx, arm));
+            let err_arm = arms.iter().try_for_each(|arm| non_consuming_err_arm(cx, arm));
+            if let (ControlFlow::Break(ok_pat), ControlFlow::Break(_)) = (ok_arm, err_arm) {
+                emit_lint(cx, expr.span, op, &[ok_pat.span]);
```
Comment (blyxyas) [inline clippy_lints/src/unused_io_amount.rs:152]: This would then be:

```suggestion
            if ok_arm && err_arm {
                emit_lint(cx, expr.span, op, &[ok_arm.pat.span]);
```

**Review by blyxyas — CHANGES_REQUESTED** [review]
Just some early reviews and a proposal to make the code easier

**Comment by PartiallyTyped** [comment]
Do you agree with the changes to the structural matching of the match?

**Comment by blyxyas** [comment]
Watch match specifically? Like, the general pattern matching? It's good, even if a little bit confusing (I assume because of the time urgency)

**Comment by PartiallyTyped** [comment]
Sorry, basically based on your comments on the issue, I changed the matching logic to only consider two arm cases and nothing else.

Once this is stabilized I'd like to clean it up further.

File: clippy_lints/src/unused_io_amount.rs (hunk 3 above)
Comment (PartiallyTyped) [reply clippy_lints/src/unused_io_amount.rs:132]: If we return a bool here, then we lose information on which arm is doing what.

These are used to pull the right patterns out of a slice of 2 pats.

**Comment by PartiallyTyped** [comment]
Ok, this looks better.

**Review by blyxyas — COMMENTED** [review]
I think that this may be ready to merged! What do you think? Is there something else that needs to be addressed?

**Comment by PartiallyTyped** [comment]
I hold no objections, but I have the hunch that this can be achieved in a simpler manner.

If you think it's okay to merge — given the urgency — then okay. Worst case we revert the changes completely.

Would you like me to rebase and squash?

**Comment by blyxyas** [comment]
Please :)

**Comment by PartiallyTyped** [comment]
Done, thanks again and sorry :(

**Review by blyxyas — APPROVED** [review]
Meow meow LGTM! Thanks :heart:

**Comment by blyxyas** [comment]
No need to be sorry, you didn't see an edge case, in the same way that I didn't. Instead of having shame of our human error, we should be thankful of the person that filled the issue that led to this moment.

@bors r+

**Comment by PartiallyTyped** [comment]
This is getting silly 😭
