### PR TITLE
Track `clippy.toml` and `Cargo.toml` in `file_depinfo`

### LINKED ISSUE #2130: Re-run after modifying config file
For cases if after adding/removing rules:
- `clippy` behaves differently on the same source;
- config contains invalid keys or values.

Currently, if the run before modifying config was successful then the run after that will silently pass too which can give a false assertion "your code is fine even now". It would be useful to trigger `clippy` re-run without having to `touch` the source itself.

To reproduce the 2nd use-case:
```sh
$ cat clippy.toml
enum-variant-name-threshold = 0
$ cargo +nightly clippy
# run successful
$ echo 'foo = "bar"' >> clippy.toml
$ cargo +nightly clippy
# run successful but should fail with
# "error reading Clippy's configuration file: unknown field `foo`"
$ touch src/main.rs  # whatever source file
$ cargo +nightly clippy
# fails with "error reading Clippy's configuration file: unknown field `foo`"
# ^ expected behavior on the previous run
```

### LINKED ISSUE #8512: Updating Cargo.toml file doesn't change the lint
### Summary

The `cargo_common_metadata` lint should update when the `Cargo.toml` file is changed. I wasn't able to get clippy to recognize the fact that my `Cargo.toml` file had the categories value in it until I saved my `lib.rs` file

### Lint Name

cargo_common_metadata

### Reproducer

I tried this code:

```toml
[package]
name = "botic"
description = "A time crate that handles leap seconds"
version = "0.1.0"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/botahamec/botic"
keywords = ["date", "time", "calendar"]
categories = ["date-and-time", "parser-implementations", "value-formatting"]
```

I saw this happen:

```
warning: package `botic` is missing `package.categories` metadata
  |
note: the lint level is defined here
 --> src\lib.rs:2:9
  |
2 | #![warn(clippy::cargo)]
  |         ^^^^^^^^^^^^^
  = note: `#[warn(clippy::cargo_common_metadata)]` implied by `#[warn(clippy::cargo)]`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cargo_common_metadata

warning: `botic` (lib) generated 1 warning
```

I expected no warning to appear

### Version

```text
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-pc-windows-msvc
release: 1.59.0
LLVM version: 13.0.0
```

### Additional Labels

@rustbot -label I-false-negative

### PR DESCRIPTION
**Pull request by Alexendoo**
Causes cargo to re-run clippy when those paths are modified
    
Also tracks the path to `clippy-driver` in debug mode to remove the workarounds in `cargo dev lint` and `lintcheck` (cc @matthiaskrgr)

changelog: Automatically re-run Clippy if `Cargo.toml` or `clippy.toml` are modified

Fixes #2130
Fixes #8512

r? @flip1995

### CODE REVIEW

File: clippy_dev/src/lint.rs [hunk 1]
```diff
@@ -36,20 +36,12 @@ pub fn run<'a>(path: &str, args: impl Iterator<Item = &'a String>) {
     } else {
         exit_if_err(Command::new("cargo").arg("build").status());
 
-        // Run in a tempdir as changes to clippy do not retrigger linting
-        let target = tempfile::Builder::new()
```
Comment (flip1995) [inline clippy_dev/src/lint.rs:40]: This is great! Do we still use the `tempfile` dep anywhere or can this be removed?

**Review by flip1995 — APPROVED** [review]
LGTM. Just one question. r=me if the tempfile dep cannot be removed.

File: clippy_dev/src/lint.rs (hunk 1 above)
Comment (Alexendoo) [reply clippy_dev/src/lint.rs:40]: Seems not, removed it

**Comment by flip1995** [comment]
@bors r+

Thanks!
