### PR TITLE
Fix `bool_to_int_with_if` false positive with `if let`

### LINKED ISSUE #9706: Incorrect code suggestion when using if-let expression
### Summary

Code suggestion causes code not to compile because the suggestion assumes if-let expressions work where normal conditions do, which is not the case.

### Reproducer

```rust
enum Foo {
    Bar,
}

fn bug(x: Foo) -> i32 {
    if let Foo::Bar = x {
        1
    } else {
        0
    }
}
```

Clippy suggests the code below which does not compile.

```rust
enum Foo {
    Bar,
}

fn bug(x: Foo) -> i32 {
    i32::from(let Foo::Bar = x)
}
```

`cargo check` output:
```rust
error: expected expression, found `let` statement
   |
   |     i32::from(let Foo::Bar = x)
   |               ^^^

error: `let` expressions are not supported here
   |
   |     i32::from(let Foo::Bar = x)
   |               ^^^^^^^^^^^^^^^^
   |
   = note: only supported directly in conditions of `if` and `while` expressions

error[E0658]: `let` expressions in this position are unstable
   |
   |     i32::from(let Foo::Bar = x)
   |               ^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
   = help: add `#![feature(let_chains)]` to the crate attributes to enable
```

### Version

```text
rustc 1.66.0-nightly (7fcf850d7 2022-10-23)
binary: rustc
commit-hash: 7fcf850d7942804990a1d2e3fe036622a0fe4c74
commit-date: 2022-10-23
host: x86_64-pc-windows-msvc
release: 1.66.0-nightly
LLVM version: 15.0.2
```

### Additional Labels

@rustbot label +I-suggestion-causes-error +bool_to_int_with_if

### PR DESCRIPTION
**Pull request by Alexendoo**
Fixes #9706

changelog: FP: [`bool_to_int_with_if`]: Now ignores `if let` statements

### CODE REVIEW

File: tests/ui/bool_to_int_with_if.rs [hunk 1]
```diff
@@ -123,3 +124,22 @@ fn side_effect() {}
...
+    B,
+}
+
+fn if_let(a: Enum, b: Enum) {
+    if let Enum::A = a {
+        1
+    } else {
+        2
+    };
+
```
Comment (xFrednet) [inline tests/ui/bool_to_int_with_if.rs:139]: These examples should trigger the lint, as it only detects `if <expr> {1} else {0}` AFAIK.

Could you update the example, to use these literals? :upside_down_face:

File: clippy_lints/src/bool_to_int_with_if.rs [hunk 2]
```diff
@@ -52,9 +53,9 @@ impl<'tcx> LateLintPass<'tcx> for BoolToIntWithIf {
 }
 
 fn check_if_else<'tcx>(cx: &LateContext<'tcx>, expr: &'tcx rustc_hir::Expr<'tcx>) {
-    if let ExprKind::If(check, then, Some(else_)) = expr.kind
+    if let Some(If { cond, then, r#else: Some(r#else) }) = If::hir(expr)
```
Comment (xFrednet) [inline clippy_lints/src/bool_to_int_with_if.rs:56]: I'm considering if it would be nicer to suggest `i32::from(matches!(X, Y))` instead of ignoring `if let` cases completely. That would be shorter in most cases, but maybe not more readable. This is just a thought, so I'm fine with this as well.

**Review by xFrednet — COMMENTED** [review]
Once small nit and one question, otherwise looks good to me :)

File: tests/ui/bool_to_int_with_if.rs (hunk 1 above)
Comment (Alexendoo) [reply tests/ui/bool_to_int_with_if.rs:139]: Whoops 😄

File: clippy_lints/src/bool_to_int_with_if.rs (hunk 2 above)
Comment (Alexendoo) [reply clippy_lints/src/bool_to_int_with_if.rs:56]: Not sure on that one, I think it's a bit too complex personally

Comment (xFrednet) [reply clippy_lints/src/bool_to_int_with_if.rs:56]: Okay, then let's just ignore this case. Creating the suggestion would also not be too much fun

**Review by xFrednet — APPROVED** [review]

**Comment by xFrednet** [comment]
Looks good to me, thank you!

Lord Bors, would you please use your magic powers to merge this PR?
