### PR TITLE
fix: `unnested_or_patterns` suggests wrongly in `let`

### LINKED ISSUE #9952: unnested_or_patterns removes parens: top-level or-patterns are not allowed in `let` bindings
### Summary

.

### Lint Name

unnested_or_patterns

### Reproducer

I tried this code:

```rust
fn main() {
    let (0 | (1 | _)) = 0;
}
```

I saw this happen:

```

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error: top-level or-patterns are not allowed in `let` bindings
 --> src/main.rs:2:9
  |
2 |     let 0 | 1 | _ = 0;
  |         ^^^^^^^^^ help: wrap the pattern in parentheses: `(0 | 1 | _)`

error: aborting due to previous error

Original diagnostics will follow.

warning: unnecessary parentheses around pattern
 --> src/main.rs:2:14
  |
2 |     let (0 | (1 | _)) = 0;
  |              ^     ^
  |
  = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
  |
2 -     let (0 | (1 | _)) = 0;
2 +     let (0 | 1 | _) = 0;
  |

warning: unnested or-patterns
 --> src/main.rs:2:9
  |
2 |     let (0 | (1 | _)) = 0;
  |         ^^^^^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnested_or_patterns
  = note: requested on the command line with `-W clippy::unnested-or-patterns`
help: nest the patterns
  |
2 |     let 0 | 1 | _ = 0;
  |         ~~~~~~~~~


```

### Version

```text
rustc 1.67.0-nightly (b3bc6bf31 2022-11-24)
binary: rustc
commit-hash: b3bc6bf31265ac10946a0832092dbcedf9b26805
commit-date: 2022-11-24
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by profetia**
Closes #9952

changelog: [`unnested_or_patterns`] fix wrong suggestion in `let`

### CODE REVIEW

**Review by samueltardieu — COMMENTED** [review]
This is one way to fix it up, but there might be a simpler one. By fixing the visitor in `insert_necessary_parens()` to not remove parens (if any) on the outermost pattern, you get the same result without having to introduce `PatternSource`. This could be something like:

```rust
fn remove_all_parens(pat: &mut P<Pat>) {
    #[derive(Default)]
    struct Visitor {
        is_inner: bool,
    }
    impl MutVisitor for Visitor {
        fn visit_pat(&mut self, pat: &mut P<Pat>) {
            let is_inner = mem::replace(&mut self.is_inner, true);
            walk_pat(self, pat);
            pat.kind = match &mut pat.kind {
                Paren(i) if is_inner => mem::replace(&mut i.kind, Wild),
                _ => return,
            };
        }
    }
    Visitor::default().visit_pat(pat);
}
```

The only difference in output with what you are proposing is that you wouldn't "fix" the outermost parens if the user chose to use them. For example, this would transform:

```rust
if let (0 | (1 | 2)) = …
```

into 

```rust
if let (0 | 1 | 2) = …
```

whereas your change also drops the outermost parens. Even if this is correct, this is not what the lint advertises, and this is redundant with rustc's `unused_parens` lint.

**Comment by profetia** [comment]
> This is one way to fix it up, but there might be a simpler one. By fixing the visitor in `insert_necessary_parens()` to not remove parens (if any) on the outermost pattern, you get the same result without having to introduce `PatternSource`. This could be something like (with minimal diffs to the existing visitor):
> 
> ```rust
> fn remove_all_parens(pat: &mut P<Pat>) {
>     #[derive(Default)]
>     struct Visitor {
>         is_inner: bool,
>     }
>     impl MutVisitor for Visitor {
>         fn visit_pat(&mut self, pat: &mut P<Pat>) {
>             let is_inner = mem::replace(&mut self.is_inner, true);
>             walk_pat(self, pat);
>             pat.kind = match &mut pat.kind {
>                 Paren(i) if is_inner => mem::replace(&mut i.kind, Wild),
>                 _ => return,
>             };
>         }
>     }
>     Visitor::default().visit_pat(pat);
> }
> ```
> 
> The only difference in output with what you are proposing is that this wouldn't "fix" the outermost parens if the user chose to use them. For example, this would transform:
> 
> ```rust
> if let (0 | (1 | 2)) = …
> ```
> 
> into
> 
> ```rust
> if let (0 | 1 | 2) = …
> ```
> 
> whereas your change also drops the outermost parens. Even if dropping them is correct, this is not what the lint advertises, and this might be considered redundant with rustc's `unused_parens` lint.

Good advice! Thanks!

File: clippy_lints/src/unnested_or_patterns.rs [hunk 1]
```diff
@@ -120,18 +120,24 @@ fn lint_unnested_or_patterns(cx: &EarlyContext<'_>, pat: &Pat) {
...
-    struct Visitor;
+    #[derive(Default)]
+    struct Visitor {
+        /// If is not in the outer most pattern
+        is_inner: bool,
+    }
+
     impl MutVisitor for Visitor {
         fn visit_pat(&mut self, pat: &mut P<Pat>) {
+            let is_inner = mem::replace(&mut self.is_inner, true);
```
Comment (flip1995) [inline clippy_lints/src/unnested_or_patterns.rs:131]: Using `mem::replace` here looks a bit overkill to me.
```suggestion
            *self.is_inner = true;
```

File: clippy_lints/src/unnested_or_patterns.rs [hunk 2]
```diff
@@ -120,18 +120,24 @@ fn lint_unnested_or_patterns(cx: &EarlyContext<'_>, pat: &Pat) {
...
             walk_pat(self, pat);
             let inner = match &mut pat.kind {
-                Paren(i) => mem::replace(&mut i.kind, Wild),
+                Paren(i) if is_inner => mem::replace(&mut i.kind, Wild),
```
Comment (flip1995) [inline clippy_lints/src/unnested_or_patterns.rs:134]:
```suggestion
                Paren(i) if self.is_inner => mem::replace(&mut i.kind, Wild),
```

**Review by flip1995 — APPROVED** [review]
Thanks, just a NIT.

File: clippy_lints/src/unnested_or_patterns.rs (hunk 1 above)
Comment (profetia) [reply clippy_lints/src/unnested_or_patterns.rs]: Not really a overkill I think, but anyway I've replaced with normal ways.

File: clippy_lints/src/unnested_or_patterns.rs [hunk 3]
```diff
@@ -120,18 +120,25 @@ fn lint_unnested_or_patterns(cx: &EarlyContext<'_>, pat: &Pat) {
...
+    #[derive(Default)]
+    struct Visitor {
+        /// If is not in the outer most pattern
+        is_inner: bool,
+    }
+
     impl MutVisitor for Visitor {
         fn visit_pat(&mut self, pat: &mut P<Pat>) {
+            let is_inner = self.is_inner;
+            self.is_inner = true;
```
Comment (flip1995) [inline clippy_lints/src/unnested_or_patterns.rs:132]: Oh, you need the old value below. I completely missed that. So the `mem::replace` is actually the better way to do this. Sorry for the back and forth..

Comment (profetia) [reply clippy_lints/src/unnested_or_patterns.rs]: Rolled back. Thank you!

File: clippy_lints/src/unnested_or_patterns.rs [hunk 4]
```diff
@@ -120,18 +120,24 @@ fn lint_unnested_or_patterns(cx: &EarlyContext<'_>, pat: &Pat) {
 
 /// Remove all `(p)` patterns in `pat`.
 fn remove_all_parens(pat: &mut P<Pat>) {
-    struct Visitor;
+    #[derive(Default)]
+    struct Visitor {
+        /// If is not in the outer most pattern
```
Comment (y21) [inline clippy_lints/src/unnested_or_patterns.rs:125]: Can you also add a short comment on why this is needed, because it may not be obvious to someone without the context (maybe just something like, "this is needed because top level or-patterns are not allowed in let statements, so we preserve those")?

**Review by y21 — APPROVED** [review]
Also looks good to me, just one small suggestion

File: clippy_lints/src/unnested_or_patterns.rs (hunk 4 above)
Comment (profetia) [reply clippy_lints/src/unnested_or_patterns.rs]: Added. Thanks!
