### PR TITLE
Fix ICE in vec_box lint and add run-rustfix

### LINKED ISSUE #3720: ICE with simple struct
From https://github.com/rust-lang/rust/issues/57548

```rust
struct TraitVec<T: ?Sized> {
    inner: Vec<Box<T>>,
}

fn main() {}
```
ICE's when running cargo clippy, on both 2015 and 2018, stable, beta and nightly.

<details>
<summary>Backtrace</summary>

```
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:605:9
stack backtrace:
   0:     0x7f697e2f3293 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hece581721779b75b
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x7f697e2eba9b - std::sys_common::backtrace::_print::h05875bcf0afb6551
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x7f697e2ef4b6 - std::panicking::default_hook::{{closure}}::hdd48438b5e5f9b47
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:     0x7f697e2ef234 - std::panicking::default_hook::h553bd44823b4f3d9
                               at src/libstd/panicking.rs:215
   4:     0x7f6980100bbf - rustc::util::common::panic_hook::h343c593de08a5649
   5:     0x7f697e2efc8d - std::panicking::rust_panic_with_hook::h10fdd500781c0438
                               at src/libstd/panicking.rs:482
   6:     0x7f697f100abc - std::panicking::begin_panic::h891bda7e2b6dffe7
   7:     0x7f697f11dd7e - rustc_errors::Handler::bug::h35cc5bab3fbf90d5
   8:     0x7f697fd11fb2 - rustc::util::bug::opt_span_bug_fmt::{{closure}}::h91a903973cfe859b
   9:     0x7f697fd113a9 - rustc::ty::context::tls::with_opt::{{closure}}::h67b9d270800cdb3e
  10:     0x7f697fd112c4 - rustc::ty::context::tls::with_context_opt::he04fb99820d54d61
  11:     0x7f697fd11356 - rustc::ty::context::tls::with_opt::h1f3ed13a09ea7d54
  12:     0x7f697fd11ec4 - rustc::util::bug::opt_span_bug_fmt::h4c49005d785a43f0
  13:     0x7f697fd11e36 - rustc::util::bug::bug_fmt::h87514f0e33d1de7e
  14:     0x7f698096a394 - rustc_typeck::collect::type_of::h00dea050795262cd
  15:     0x56298fe1b4c1 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::type_of<'tcx>>::compute::{{closure}}::h3baa7ac9b6458e18
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:965
  16:     0x56298fe902b8 - rustc::ty::query::__query_compute::type_of::h1d495d41c29a386e
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:924
  17:     0x56298fe8f524 - rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::type_of<'tcx>>::compute::h02a04903cb2dff56
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:957
  18:     0x56298ff3d7dc - rustc::dep_graph::graph::DepGraph::with_task_impl::hedb077de29835f33
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/dep_graph/graph.rs:303
  19:     0x56298ff4a331 - rustc::dep_graph::graph::DepGraph::with_task::h92d042332b2d8591
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/dep_graph/graph.rs:190
  20:     0x56298f1c7664 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job::{{closure}}::{{closure}}::hb46d664ac9d77eab
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:554
  21:     0x56298f1e9643 - <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start::{{closure}}::{{closure}}::heb051eeb36408197
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:220
  22:     0x56298fef983c - rustc::ty::context::tls::enter_context::{{closure}}::hd398195d3d1d0e48
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/context.rs:1956
  23:     0x56298ff18aba - rustc::ty::context::tls::set_tlv::h933baa9cd96060a3
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/context.rs:1889
  24:     0x56298fef417c - rustc::ty::context::tls::enter_context::h0ee7fd335d78a047
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/context.rs:1955
  25:     0x56298f1e2f2a - <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start::{{closure}}::h4e4b3d61fb21a159
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:219
  26:     0x56298ff0ec36 - rustc::ty::context::tls::with_related_context::{{closure}}::h6fa865290ba07071
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/context.rs:2062
  27:     0x56298fef3748 - rustc::ty::context::tls::with_context::{{closure}}::hf36054a22c321881
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/context.rs:2046
  28:     0x56298feff7e0 - rustc::ty::context::tls::with_context_opt::h62fdfa3a325e2740
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/context.rs:2036
  29:     0x56298feeb802 - rustc::ty::context::tls::with_context::hfb4f10b1bf1e7484
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/context.rs:2046
  30:     0x56298ff0ad80 - rustc::ty::context::tls::with_related_context::h99c14afbec929fd5
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/context.rs:2058
  31:     0x56298f1b9b3b - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job::{{closure}}::h3cddd698cf2be7f1
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:208
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:547
  32:     0x56298f71d8b4 - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::try_get_with::h6e56a2d0c38ae908
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:233
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:546
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:371
  33:     0x56298f229262 - clippy_lints::types::check_ty::hb49c0ec652375911
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:653
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:1023
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc/ty/query/plumbing.rs:1015
                               at clippy_lints/src/types.rs:285
  34:     0x56298f2280f2 - <clippy_lints::types::TypePass as rustc::lint::LateLintPass<'a, 'tcx>>::check_struct_field::h39155b7594a07b14
                               at clippy_lints/src/types.rs:190
  35:     0x7f697faebbb0 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_struct_field::he30385029d9677ed
  36:     0x7f697faeb8dc - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_variant_data::h370799e7f98e251c
  37:     0x7f69801601d4 - rustc::hir::intravisit::walk_item::h1473058a67d37e9c
  38:     0x7f697faea26b - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item::h96f8dc7cfcad9412
  39:     0x7f697faec700 - <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod::hf60c927e6a13586b
  40:     0x7f698015a99e - rustc::hir::intravisit::walk_crate::h2d3f911875fbedd6
  41:     0x7f697faeedfb - rustc::lint::context::check_crate::h9b29687d649f96ab
  42:     0x7f6980fc3de5 - rustc::util::common::time::hc201220c8b8493e4
  43:     0x7f6980fafc95 - <std::thread::local::LocalKey<T>>::with::hc0b0bb96a5dcced3
  44:     0x7f6980f49cf4 - rustc::ty::context::TyCtxt::create_and_enter::h7685f671e8c5067c
  45:     0x7f698102a007 - rustc_driver::driver::compile_input::h9bd1a0f1e939c5dd
  46:     0x7f6980fcd5f2 - rustc_driver::run_compiler_with_pool::h025259bbe4bb0533
  47:     0x7f6980f5ccd5 - <scoped_tls::ScopedKey<T>>::set::h4d221376d505cbbc
  48:     0x7f6980fcc44a - rustc_driver::run_compiler::h3cb2e6cbc0da52ae
  49:     0x56298f1466a7 - clippy_driver::main::{{closure}}::h6376c8bda0485e35
                               at src/driver.rs:145
  50:     0x56298f186b89 - rustc_driver::run::{{closure}}::{{closure}}::h787d7348cabd9a5c
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc_driver/lib.rs:169
  51:     0x56298f146edf - <scoped_tls::ScopedKey<T>>::set::hdeedd1058b7d6454
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  52:     0x56298f141b2a - syntax::with_globals::{{closure}}::hccc753b0af6a915a
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/libsyntax/lib.rs:112
  53:     0x56298f146e19 - <scoped_tls::ScopedKey<T>>::set::h7d091b5d66b117f9
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  54:     0x56298f141aa1 - syntax::with_globals::hd954fc28aca1c1b1
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/libsyntax/lib.rs:111
  55:     0x56298f186b58 - rustc_driver::run::{{closure}}::h628b437d99fc00db
                               at /rustc/74256630117fedf479edbd1145cac47c88036aec/src/librustc_driver/lib.rs:168
```

</details>

### PR DESCRIPTION
**Pull request by phansch**
Includes https://github.com/rust-lang/rust-clippy/pull/3726

`hir::Ty` doesn't seem to know anything about type bounds and
`cx.tcx.type_of(def_id)` caused an ICE when it was passed a generic type
with a bound:

```
src/librustc_typeck/collect.rs:1311: unexpected non-type Node::GenericParam: Type { default: None, synthetic: None }
```

Converting it to a proper `Ty` fixes the ICE and catches a few more places
where the lint applies.

Fixes #3720

### CODE REVIEW

File: tests/ui/vec_box_sized.rs [hunk 1]
```diff
@@ -1,17 +1,36 @@
...
+    use super::UnsizedStruct;
+
+    struct C(Vec<Box<UnsizedStruct>>);
+
+    struct StructWithVecBoxButItsUnsized {
+        unsized_type: Vec<Box<UnsizedStruct>>,
+    }
+
+    struct TraitVec<T: ?Sized> {
+        // Regression test for #2720. This was causing an ICE.
```
Comment (phansch) [inline tests/ui/vec_box_sized.rs]: woops, also a wrong issue number. Will fix this and the merge conflict later today.
