### PR TITLE
don't trigger `blocks_in_conditions` when the condition contains a `return`

### LINKED ISSUE #9911: blocks_in_conditions can't deal with return expression in condition
### Summary

.

### Lint Name

blocks_in_if_conditions

### Reproducer

I tried this code:

```rust
fn main() {
    if { return } {}
}

```

I saw this happen:
`cargo clippy --fix -- -Aclippy::all -Wclippy::blocks_in_if_conditions`
```
    Checking clpy v0.1.0 (/tmp/clpy)
warning: failed to automatically apply fixes suggested by rustc to crate `clpy`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error: expected `{`, found `}`
 --> src/main.rs:3:1
  |
3 | }
  | ^ expected `{`
  |
note: the `if` expression is missing a block after this condition
 --> src/main.rs:2:8
  |
2 |     if return {}
  |        ^^^^^^^^^

error: aborting due to previous error

Original diagnostics will follow.

warning: unreachable block in `if` or `while` expression
 --> src/main.rs:2:19
  |
2 |     if { return } {}
  |          ------   ^^ unreachable block in `if` or `while` expression
  |          |
  |          any code following this expression is unreachable
  |
  = note: `#[warn(unreachable_code)]` on by default

warning: omit braces around single expression condition
 --> src/main.rs:2:8
  |
2 |     if { return } {}
  |        ^^^^^^^^^^ help: try: `return`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#blocks_in_if_conditions
  = note: requested on the command line with `-W clippy::blocks-in-if-conditions`

warning: `clpy` (bin "clpy") generated 2 warnings (run `cargo fix --bin "clpy"` to apply 1 suggestion)
warning: `clpy` (bin "clpy" test) generated 2 warnings (2 duplicates)
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
```

### Version

```text
rustc 1.67.0-nightly (c5d82ed7a 2022-11-19)
binary: rustc
commit-hash: c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b
commit-date: 2022-11-19
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by lapla-cogito**
fixes #9911

changelog: [`blocks_in_conditions`]: don't trigger the lint when the condition contains a `return`

### CODE REVIEW

File: tests/ui/blocks_in_conditions.rs [hunk 1]
```diff
@@ -118,6 +118,13 @@ mod issue_12016 {
     }
 }
 
+fn issue_9911() {
+    if { return } {}
+
+    let a = 1;
+    if { if a == 1 { return } else { true } } {}
```
Comment (samueltardieu) [inline tests/ui/blocks_in_conditions.rs:125]: Shouldn't this one get linted? It looks like `if if a == 1 { return } else { true } {}` doesn't trigger an error. `return` seems only problematic when present in isolation.

Comment (lapla-cogito) [reply tests/ui/blocks_in_conditions.rs:125]: Although this case compiles, it is very hard to read and error-prone I think, so this lint should not be triggered here.

Comment (samueltardieu) [reply tests/ui/blocks_in_conditions.rs:125]: Sure, but isn't this true of many complicated code for which we would still lint, such as loops, etc.? I was wondering why one would need to look for `return` in sub-expressions, when a simpler `&& !matches!(ex.kind, ExprKind::Ret(None))` would probably solve the issue. In particular, it would still allow to transform `if { return 42 } {}` into `if return 42 {}` as this is not ambiguous (even if both are evenly distasteful).

Comment (lapla-cogito) [reply tests/ui/blocks_in_conditions.rs:125]: > isn't this true of many complicated code for which we would still lint, such as loops, etc.?

For example, if a loop containing a `return` is used as a condition, wouldn't linting it ultimately lead to suggesting less readable code? Since this lint is a style lint, I think such situations should be avoided as much as possible. That's why, in this implementation, I intentionally check inside subexpressions without using something like `clippy_utils::visitors::Descend`.

Comment (Manishearth) [reply tests/ui/blocks_in_conditions.rs:125]: I feel like this code is confusing either way. I'm not sure if we should lint about it, people shouldn't be returning from a condition in the first place.

Comment (lapla-cogito) [reply tests/ui/blocks_in_conditions.rs:125]: I think it would be reasonable to have a separate style lint for cases like this. However, we still need to decide how this lint should behave in such cases. If the lint ends up suggesting code that is harder to read, then I believe it shouldn’t be triggered here (which is essentially the current implementation). WDYT?

Comment (Manishearth) [reply tests/ui/blocks_in_conditions.rs:125]: I agree with that.

Comment (lapla-cogito) [reply tests/ui/blocks_in_conditions.rs:125]: Alright, I'll submit an issue and implement that lint. In any case, this can be merged, right?

Comment (Manishearth) [reply tests/ui/blocks_in_conditions.rs:125]: Sure, I'll let @samueltardieu approve this PR, let me know if you need a merge.

File: clippy_lints/src/blocks_in_conditions.rs [hunk 2]
```diff
@@ -86,6 +88,20 @@ impl<'tcx> LateLintPass<'tcx> for BlocksInConditions {
...
+                            if let ExprKind::Ret(..) = e.kind {
+                                ControlFlow::Break(())
+                            } else {
+                                ControlFlow::Continue(())
+                            }
+                        })
+                        .is_some()
+                        {
+                            return;
+                        }
```
Comment (samueltardieu) [inline clippy_lints/src/blocks_in_conditions.rs:103]: This code already exists as `clippy_utils::contains_return()`. You should also update the comment before this `if` if you refactor it to use `contains_return()`.

```suggestion
                        if expr.span.from_expansion() || ex.span.from_expansion() || contains_return(block.expr) {
                            return;
                        }
```

**Review by samueltardieu — CHANGES_REQUESTED** [review]
Just a small refactoring and this looks ok.

File: clippy_lints/src/blocks_in_conditions.rs (hunk 2 above)
Comment (lapla-cogito) [reply clippy_lints/src/blocks_in_conditions.rs]: Thanks, I rewrote it to use `contains_return`, but I deliberately separated the logic from the original `if` for readability purposes.

File: clippy_lints/src/blocks_in_conditions.rs [hunk 3]
```diff
@@ -86,6 +86,13 @@ impl<'tcx> LateLintPass<'tcx> for BlocksInConditions {
                         if expr.span.from_expansion() || ex.span.from_expansion() {
                             return;
                         }
+
+                        // Linting should not be triggered to cases where `return` is included in the condition.
+                        // #9911
```
Comment (samueltardieu) [inline clippy_lints/src/blocks_in_conditions.rs:91]: Nit: I personally dislike using a issue number here (it is already present in the tests which would fail if this was removed), but there are already a few instances of it (but not many) in the sources.  This is different than using "TODO see issue #xxx" because in this case there is an action needed.

**Review by samueltardieu — APPROVED** [review]
LGTM, I have a nit but it is not blocking. @Manishearth you can queue it if it's ok with you.

File: clippy_lints/src/blocks_in_conditions.rs (hunk 3 above)
Comment (Manishearth) [reply clippy_lints/src/blocks_in_conditions.rs:91]: I think it's fine to have context like this noted
