### PR TITLE
Fix false positive in write_literal and print_literal (numeric literals)

### LINKED ISSUE #6335: False positive: print_literal with numeric literal arguments
I tried this code:

```rust
println!("{}", 0xdead_beefu32)
```

I expected to see this happen: no warnings, the decimal conversion is printed.

Instead, this happened:

```
warning: literal with an empty format string
 --> src/main.rs:2:20
  |
2 |     println!("{}", 0xdead_beefu32)
  |                    ^^^^^^^^^^^^^^
  |
  = note: `#[warn(clippy::print_literal)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#print_literal
```

The same issue appears with float literals. The problem is that the source code representation need not equate the printed number in any obvious way. As hopefully shown by the example above, there are a number of conversion applied to literals that might make their decimal Display representation rather non-obvious. The motivation for the source code representation is entirely different, showing rather how they might be derive or related to a specification document. Examples where the source representation is different than the Display one include:

* `1.200` to show the number of significant digits of a constant.
* `0b11001` for numbers with bit flags.
* `1_000_001` as recommended for splitting long numbers.
* `123.0E+77` for engineering numbers.

### Meta

- `cargo clippy -V`: 0.0.212 (2020-11-13 74f7e32)
- `rustc -V: 1.4.25-nightly (2020-11-11 0f29ff6)

### PR DESCRIPTION
**Pull request by pro-grammer1**
changelog: No longer lint numeric literals in [`write_literal`] and [`print_literal`].

Fixes #6335

### CODE REVIEW

**Comment by pro-grammer1** [comment]
Fixes #6335

File: clippy_lints/src/write.rs [hunk 1]
```diff
@@ -442,7 +443,12 @@ impl Write {
                 return (Some(fmtstr), None);
             };
             match &token_expr.kind {
-                ExprKind::Lit(_) => {
+                ExprKind::Lit(lit)
+                    if match lit.kind {
+                        LitKind::Int(_, _) | LitKind::Float(_, _) => false,
+                        _ => true,
+                    } =>
```
Comment (ebroto) [inline clippy_lints/src/write.rs:450]:
```suggestion
                ExprKind::Lit(lit) if !matches!(lit.kind, LitKind::Int(..) | LitKind::Float(..)) => {
```
We can simplify using `matches!()`

File: clippy_lints/src/write.rs [hunk 2]
```diff
@@ -460,10 +466,16 @@ impl Write {
...
+                }
                 ExprKind::Assign(lhs, rhs, _) => {
-                    if let ExprKind::Lit(_) = rhs.kind {
-                        if let ExprKind::Path(_, p) = &lhs.kind {
+                    if_chain! {
+                        if let ExprKind::Lit(ref lit) = rhs.kind;
+                        if match lit.kind {
+                            LitKind::Int(_, _) | LitKind::Float(_, _) => false,
+                            _ => true,
+                        };
```
Comment (ebroto) [inline clippy_lints/src/write.rs:476]:
```suggestion
                        if !matches!(lit.kind, LitKind::Int(..) | LitKind::Float(..));
```
Same here

**Review by ebroto — CHANGES_REQUESTED** [review]
Just some nits. 

Also, the reference file for the tests needs to be updated because the `stderr` files have changed, as we are not linting if the literals are ints/floats. To do this, you can run the `tests/ui/update-all-references.sh` script.

**Comment by giraffate** [comment]
ping from triage @pro-grammer1. There seems to be some fixes left to be done. Do you have any questions on how to preceed here?

**Comment by giraffate** [comment]
ping from triage @pro-grammer1. According to the triage procedure, I close this because there has no activity in 2 weeks from previous ping. If you have more time to work on this, feel free to reopen.

**Comment by pro-grammer1** [comment]
I've made the changes, so I would like to reopen this.

**Comment by giraffate** [comment]
Thanks for taking time to work on this! I reopen this.

**Comment by pro-grammer1** [comment]
I've made the suggested changes and updated the tests. Is there anything else I should do?

File: tests/ui/crashes/ice-3891.stderr [hunk 3]
```diff
@@ -1,10 +1,10 @@
-error: invalid suffix `x` for integer literal
+error: invalid suffix `x` for number literal
   --> $DIR/ice-3891.rs:2:5
    |
 LL |     1x;
    |     ^^ invalid suffix `x`
    |
-   = help: the suffix must be one of the integral types (`u32`, `isize`, etc)
+   = help: the suffix must be one of the numeric types (`u32`, `isize`, `f32`, etc.)
```
Comment (flip1995) [inline tests/ui/crashes/ice-3891.stderr:7]: Why did this change? This is a rustc lint and should be unaffected by a Clippy PR. (rebase gone wrong?)

**Review by flip1995 — COMMENTED** [review]
Oli was faster, but I have a comment anyway :smile:
