### PR TITLE
just_underscores_and_digits: fix false positive in error recovery scenario

### LINKED ISSUE #12302: False positive of `just_underscores_and_digits` when missing R_ANGLE when ending type prameters
### Summary

As it's said in the title, something like `Type<T` will trigger this bug.

### Lint Name

clippy::just_underscores_and_digits

### Reproducer

```rust
pub struct Aa<T>(PhantomData<T>);

fn aa(a: Aa<String) {

}
```

I saw this happen:

```
warning: consider choosing a more descriptive name
   --> rizlium_editor/src/extensions/editing/world_view/cam_response.rs:130:13
    |
130 | fn aa(a: Aa<String) {
    |             ^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#just_underscores_and_digits
    = note: `#[warn(clippy::just_underscores_and_digits)]` on by default
```

also, regular "Syntax error" did worked.

### Version

```text
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: x86_64-unknown-linux-gnu
release: 1.75.0
LLVM version: 17.0.6
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #12302

changelog: [`just_underscores_and_digits`]: fix false positive in error recovery scenario

### CODE REVIEW

File: clippy_dev/src/fmt.rs [hunk 1]
```diff
@@ -291,7 +291,12 @@ fn run_rustfmt(context: &FmtContext) -> Result<(), Error> {
             let entry = entry.expect("failed to find tests");
             let path = entry.path();
 
-            if path.extension() != Some("rs".as_ref()) || entry.file_name() == "ice-3891.rs" {
+            if path.extension() != Some("rs".as_ref())
+                || path
+                    .components()
+                    .any(|component| component.as_os_str() == "syntax-error-recovery")
```
Comment (samueltardieu) [inline clippy_dev/src/fmt.rs:297]: Rather than checking any component, you can check the one just before the file name:

```suggestion
                || path
                    .components()
                    .rev()
                    .nth(1)
                    .is_some_and(|c| c.as_os_str() == "syntax-error-recovery")
```

File: clippy_dev/src/fmt.rs [hunk 2]
```diff
@@ -290,8 +290,14 @@ fn run_rustfmt(context: &FmtContext) -> Result<(), Error> {
         .filter_map(|entry| {
             let entry = entry.expect("failed to find tests");
             let path = entry.path();
-
-            if path.extension() != Some("rs".as_ref()) || entry.file_name() == "ice-3891.rs" {
+            if path.extension() != Some("rs".as_ref())
+                || path
+                    .components()
+                    .rev()
+                    .nth(1)
```
Comment (blyxyas) [inline clippy_dev/src/fmt.rs:297]: This is a double ended iterator

```suggestion
                    .nth_back(1)
```

**Review by blyxyas — COMMENTED** [review]
Could you rebase? And in the midst of rebasing, implement this little refactor?
(We have a lint for `.last()` -> `.next_back()` on DoubleEnderIterators, maybe that should be expanded to this usecase?)

**Review by blyxyas — APPROVED** [review]
LGTM, thanks! :heart:
