### PR TITLE
Fix two missing_const_for_fn false positives

### LINKED ISSUE #3841: Trait functions cannot be `const`
When implementing a trait, clippy currently suggests making one of the functions `const`. That is [currently not possible](https://github.com/rust-lang/rfcs/blob/master/text/0911-const-fn.md#detailed-design). At least for now, it seems like this should be an exception.

### PR DESCRIPTION
**Pull request by phansch**
Fixes #3841 

* Fixes false positive in external macros
* Fixes false positive when implement trait methods

### CODE REVIEW

File: clippy_lints/src/missing_const_for_fn.rs [hunk 1]
```diff
@@ -114,6 +115,18 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for MissingConstForFn {
     }
 }
 
+fn is_trait_method(cx: &LateContext<'_, '_>, hir_id: HirId) -> bool {
```
Comment (oli-obk) [inline clippy_lints/src/missing_const_for_fn.rs]: I think you may be able to use https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/fn.trait_of_item.html instead of this function. There's no docs on the function, so it might have panic cases, but as long as it's only used on methods, it should be fine

Comment (phansch) [reply clippy_lints/src/missing_const_for_fn.rs]: I tried that and it only reported the traits of the default impl methods, not of normal trait methods like in the example :/

**Comment by jhpratt** [comment]
@phansch Any timeline for this fix to go live? Running `rustup component add clippy` followed by `cargo clippy --version` gives 2019-03-03 (0.0.212) — before this patch was applied.

**Comment by phansch** [comment]
@jhpratt It's currently included in Rusts beta channel and should hit stable with Rust 1.35 on May 23rd. (It's unlikely that it will be included in a possible 1.34.1 release as it's a disabled-by-default lint)

**Comment by jhpratt** [comment]
It's not available on nightly beforehand? I guess that's where my confusion is at.

**Comment by phansch** [comment]
Oh I misunderstood the Clippy version. It should be available in nightly after `nightly-2019-03-12.`
