### PR TITLE
[fix] [`redundant_closure_for_method_calls`] Suggest relative paths for local modules

### LINKED ISSUE #10854: `redundant_closure_for_method_calls` suggests the wrong path for types across inline modules
I tried this code:

```
cargo clippy --fix
```

Instead, this happened: 

```
warning: failed to automatically apply fixes suggested by rustc to crate `project`

after fixes were automatically applied the compiler reported errors within these files:

  * src/pane/list.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see 
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0433]: failed to resolve: use of undeclared crate or module `data`
   --> src/pane/list.rs:119:39
    |
119 |             let e = e.into_iter().map(data::game_data::EncounterType::icon);
    |                                       ^^^^ use of undeclared crate or module `data`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
Original diagnostics will follow.
```

The mentioned line is different as quoted above, it's:
```rust
            let e = e.into_iter().map(|e|e.icon());
```

Either `crate::data::game_data::EncounterType::icon` or `EncounterType::icon` does work without any changes.

### Meta

`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: aarch64-apple-darwin
release: 1.69.0
LLVM version: 15.0.7
```

## Nightly

on nightly the error is slightly different

```
warning: failed to automatically apply fixes suggested by rustc to crate `project`

after fixes were automatically applied the compiler reported errors within these files:

  * src/pane/list.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see 
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust-clippy/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0433]: failed to resolve: use of undeclared crate or module `data`
   --> src/pane/list.rs:119:39
    |
119 |             let e = e.into_iter().map(data::game_data::EncounterType::icon);
    |                                       ^^^^ use of undeclared crate or module `data`
    |
help: consider importing this enum
    |
1   + use crate::pane::list::EncounterType;
    |
help: if you import `EncounterType`, refer to it directly
    |
119 -             let e = e.into_iter().map(data::game_data::EncounterType::icon);
119 +             let e = e.into_iter().map(EncounterType::icon);
    |

error: aborting due to previous error
```

nightly version:
```
rustc 1.72.0-nightly (498553fc0 2023-05-29)
binary: rustc
commit-hash: 498553fc04f6a3fdc53412320f4e913bc53bc267
commit-date: 2023-05-29
host: aarch64-apple-darwin
release: 1.72.0-nightly
LLVM version: 16.0.4
```

### PR DESCRIPTION
**Pull request by modelflat**
Fixes #10854.

Currently, `redundant_closure_for_method_calls` suggest incorrect paths when a method defined on a struct within inline mod is referenced (see the description in the aforementioned issue for an example; also see [this playground link](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=f7d3c5b2663c9bd3ab7abdb0bd38ee43) for the current-version output for the test cases added in this PR). It will now try to construct a relative path path to the module and suggest it instead.

changelog: [`redundant_closure_for_method_calls`] Fix incorrect path suggestions for types within local modules

### CODE REVIEW

**Comment by modelflat** [comment]
@Centri3 Thanks for the suggestion! I moved `get_ucfs_type_name` to `lib.rs` in the utils. Considering the size of `lib.rs` I'd probably prefer to put it into a separate module, but I'm not sure which one is the most suitable... so I guess `lib.rs` it is 🙂

File: clippy_utils/src/lib.rs [hunk 1]
```diff
@@ -2884,3 +2885,111 @@ op_utils! {
...
+                if let DefPathData::TypeNs(ns1) = l.data {
+                    path.push(ns1.to_string());
+                }
+                // Otherwise ignore
+            },
+            // mod_a::mod_b::mod_c::sym refers to
+            // mod_a::sym  ::     ::
+            // (looking at mod_c)
+            EitherOrBoth::Right(r) => {
+                if let DefPathData::TypeNs(_) = r.data {
```
Comment (Centri3) [inline clippy_utils/src/lib.rs:2967]: This would probably be better as a guard instead (same with the above)

File: clippy_utils/src/lib.rs [hunk 2]
```diff
@@ -2884,3 +2885,111 @@ op_utils! {
...
+                    path.push(String::from("super"));
+                }
+                // Otherwise ignore
+            },
+            EitherOrBoth::Both(l, r) => match (l.data, r.data) {
```
Comment (Centri3) [inline clippy_utils/src/lib.rs:2972]: afaict, this can be simplified by pushing `l` and `r` if they're `TypeNs`.

File: clippy_utils/src/lib.rs [hunk 3]
```diff
@@ -2884,3 +2885,111 @@ op_utils! {
...
+
+/// Produce a relative path from `from` to `to`. Suitable for user output/suggestions.
+///
+/// This ignores use items, and assumes that the target path is visible from the source
+/// path (which _should_ be a reasonable assumption since we in order to be able to use an object of
+/// certain type T, T is required to be visible).
+///
+/// TODO make use of `use` items. Maybe we should have something more sophisticated like
+/// rust-analyzer does? <https://docs.rs/ra_ap_hir_def/0.0.169/src/ra_ap_hir_def/find_path.rs.html#19-27>
+fn get_relative_path(from: &DefPath, to: &DefPath) -> String {
```
Comment (Centri3) [inline clippy_utils/src/lib.rs:2942]: This should document that `from` and `to` have to be local.

File: clippy_utils/src/lib.rs [hunk 4]
```diff
@@ -2884,3 +2885,111 @@ op_utils! {
...
+            let ty = tcx.type_of(def_id).instantiate_identity();
+            match ty.kind() {
+                rustc_ty::Adt(adt, _) => get_path_to_callee(tcx, from, adt.did()),
+                rustc_ty::Array(..)
+                | rustc_ty::Dynamic(..)
+                | rustc_ty::Never
+                | rustc_ty::RawPtr(_)
+                | rustc_ty::Ref(..)
+                | rustc_ty::Slice(_)
+                | rustc_ty::Tuple(_) => format!("<{}>", EarlyBinder::bind(ty).instantiate(tcx, args)),
```
Comment (Centri3) [inline clippy_utils/src/lib.rs:2914]: We need to handle these too, I'm pretty sure. This should recursively go through each nested type and get the relative path for each.

Not an issue for the lint in question, but if somebody uses this on something like `(super::A, super::super::B)` it'll still be broken afaik.

**Comment by blyxyas** [comment]
Seeing as Catherine is pretty busy (judging from her GitHub contribution graph) so I'll take from now on some of her reviews.

r? @blyxyas

File: clippy_utils/src/lib.rs [hunk 5]
```diff
@@ -2884,3 +2886,116 @@ op_utils! {
...
+            // consider:
+            // a::b::c  ::d::sym refers to
+            // e::f::sym:: ::
+            // when looking at `d`
+            Right(DefPathData::TypeNs(_)) => go_up_by += 1,
+            _ => {},
+        }
+    }
+
+    repeat(String::from("super")).take(go_up_by).chain(path).join("::")
```
Comment (blyxyas) [inline clippy_utils/src/lib.rs:3000]: Seeing the result, I think that we should maybe cap `go_up_by` at like 2, AFAIK people prefer having `crate::a::b` than `super::super::super::super::b` in their codebase.

**Review by blyxyas — COMMENTED** [review]
Very good first iteration.

**Comment by blyxyas** [comment]
@modelflat Are you there?

**Comment by modelflat** [comment]
@blyxyas yep, hopefully I'll get some time to work on it in December

**Comment by blyxyas** [comment]
@modelflat Would you like for other person to finish this contribution?

**Comment by modelflat** [comment]
@blyxyas Hi! Sorry I completely forgot about this one. I've got some spare time now so can work on it. Pls take a look at the newest changes when you have time, I resolved conflicts and addressed your comments

File: clippy_utils/src/lib.rs (hunk 5 above)
Comment (modelflat) [reply clippy_utils/src/lib.rs]: I really like this idea, implemented!

**Review by blyxyas — APPROVED** [review]
LGTM! Could you squash these commits? ฅ*•ω•*ฅ♡

File: tests/ui/eta.rs [hunk 6]
```diff
@@ -417,3 +417,57 @@ fn _closure_with_types() {
     let _ = f2(|x: u32| f(x));
     let _ = f2(|x| -> u32 { f(x) });
 }
+
+/// https://github.com/rust-lang/rust-clippy/issues/10854.
```
Comment (blyxyas) [inline tests/ui/eta.rs:421]: (mini-fix)

```suggestion
/// https://github.com/rust-lang/rust-clippy/issues/10854
```
