### PR TITLE
fix incorrect suggestion in `suboptimal_flops`

### LINKED ISSUE #10003: Incorrect suggestion for `clippy::suboptimal_flops`
### Summary

Clippy suggests that I change `1_f64 - (x - 1.0).powi(2)` into `(x - 1.0).mul_add(-x - 1.0, 1_f64)`, but these expressions do not yield identical results.

### Lint Name

clippy::suboptimal_flops

### Reproducer

I tried this code:

```rust
1_f64 - (x - 1.0).powi(2)
```

I saw this happen:

```
multiply and add expressions can be calculated more efficiently and accurately
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#suboptimal_flopsclippy[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message?2#file[...]%2Fsrc%2Feasing%2Ffunction.rs)
function.rs(70, 5): consider using: `(x - 1.0).mul_add(-x - 1.0, 1_f64)`
```

The suggested expression is not equivalent to the original. Some examples:

```rust
1_f64 - (x - 1.0).powi(2), where x = 0.25, gives 0.4375
(x - 1_f64).mul_add(-x - 1_f64, 1_f64), where x = 0.25, gives 1.9375
```

```rust
1_f64 - (x - 1.0).powi(2), where x = 0.5, gives 0.75
(x - 1_f64).mul_add(-x - 1_f64, 1_f64), where x = 0.5, gives 1.75
```

```rust
1_f64 - (x - 1.0).powi(2), where x = 0.75, gives 0.9375
(x - 1_f64).mul_add(-x - 1_f64, 1_f64), where x = 0.75, gives 1.4375
```

```rust
1_f64 - (x - 1.0).powi(2), where x = 1, gives 1
(x - 1_f64).mul_add(-x - 1_f64, 1_f64), where x = 1, gives 1
```

```rust
1_f64 - (x - 1.0).powi(2), where x = 0, gives 0
(x - 1_f64).mul_add(-x - 1_f64, 1_f64), where x = 0, gives 2
```

### Version

```text
rustc 1.67.0-nightly (1eb62b123 2022-11-27)
binary: rustc
commit-hash: 1eb62b1235fd77200e6bd967d70e83c0f2497233
commit-date: 2022-11-27
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Related

Probably related to [https://github.com/rust-lang/rust-clippy/issues/4735](https://github.com/rust-lang/rust-clippy/issues/4735) and [https://github.com/rust-lang/rust-clippy/issues/4751](https://github.com/rust-lang/rust-clippy/issues/4751), but this is fairly dangerous.

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by EricWu2003**
fixes #10003

There was an error when trying to negate an expression like `x - 1.0`. We used to format it as `-x - 1.0` whereas a proper negation would be `-(x - 1.0)`.

Therefore, we add parentheses around the expression when it is `ExprKind::Binary`.

We also add parentheses around multiply and divide expressions, even though this is not strictly necessary.

changelog: [`suboptimal_flops`]: fix incorrect suggestion caused by an incorrect negation of floating point expressions.

### CODE REVIEW

File: clippy_lints/src/floating_point_arithmetic.rs [hunk 1]
```diff
@@ -324,7 +324,11 @@ fn check_powi(cx: &LateContext<'_>, expr: &Expr<'_>, receiver: &Expr<'_>, args:
                     let maybe_neg_sugg = |expr, hir_id| {
                         let sugg = Sugg::hir(cx, expr, "..");
                         if matches!(op, BinOpKind::Sub) && hir_id == rhs.hir_id {
-                            format!("-{sugg}")
+                            if let ExprKind::Binary(..) = expr.kind {
+                                format!("-({sugg})")
+                            } else {
+                                format!("-{sugg}")
+                            }
```
Comment (Jarcho) [inline clippy_lints/src/floating_point_arithmetic.rs:331]: Using `sugg.maybe_paren()` would handle more cases.

Comment (EricWu2003) [reply clippy_lints/src/floating_point_arithmetic.rs]: Thanks for the advice! I should have guessed that there would be something in the `Sugg` struct that would take care of cases like this.

**Comment by Jarcho** [comment]
Thank you. @bors r+
