### PR TITLE
Fix FP in `print_stdout`

### LINKED ISSUE #6041: print_stdout should not look in build.rs
The [print_stdout](https://rust-lang.github.io/rust-clippy/master/index.html#print_stdout) clippy rule is interesting, but it should not look in `build.rs` files as they can contain legitimate cargo directives as `println!("cargo:X")`.

### PR DESCRIPTION
**Pull request by giraffate**
Fix #6041 

This lint shouldn't be emitted in `build.rs` as `println!` and `print!` are used for the build script.

changelog: none

### CODE REVIEW

**Review by ebroto — CHANGES_REQUESTED** [review]
I left some comments regarding the detection of build scripts

File: clippy_lints/src/write.rs [hunk 1]
```diff
@@ -236,7 +237,15 @@ impl EarlyLintPass for Write {
 
     fn check_mac(&mut self, cx: &EarlyContext<'_>, mac: &MacCall) {
         if mac.path == sym!(println) {
-            span_lint(cx, PRINT_STDOUT, mac.span(), "use of `println!`");
+            let filename = cx.sess.source_map().span_to_filename(mac.span());
+            if_chain! {
+                if let FileName::Real(filename) = filename;
+                if let Some(filename) = filename.local_path().file_name();
+                if filename != "build.rs";
```
[the remark this answers is not in the document]
Comment (giraffate) [reply clippy_lints/src/write.rs]: > We could leverage the fact that Cargo sets the crate name for build scripts to build_script_build. 

I didn't know that! Thanks!

File: tests/ui/build.rs [hunk 2]
```diff
@@ -0,0 +1,10 @@
+#![warn(clippy::print_stdout)]
```
[the remark this answers is not in the document]
Comment (giraffate) [reply tests/ui/build.rs]: > // compile-flags: --crate-name=build_script_build

I didn't even know that! It' so useful. Thanks!

**Comment by giraffate** [comment]
@ebroto Thanks for your review! I addressed these.

File: clippy_lints/src/write.rs [hunk 3]
```diff
@@ -235,8 +235,20 @@ impl EarlyLintPass for Write {
     }
 
     fn check_mac(&mut self, cx: &EarlyContext<'_>, mac: &MacCall) {
+        fn is_build_scripts(cx: &EarlyContext<'_>) -> bool {
```
Comment (ebroto) [inline clippy_lints/src/write.rs:238]:
```suggestion
        fn is_build_script(cx: &EarlyContext<'_>) -> bool {
```

File: clippy_lints/src/write.rs [hunk 4]
```diff
@@ -235,8 +235,20 @@ impl EarlyLintPass for Write {
...
+            // We could leverage the fact that Cargo sets the crate name
+            // for build scripts to `build_script_build`.
```
Comment (ebroto) [inline clippy_lints/src/write.rs:240]:
```suggestion
            // Cargo sets the crate name for build scripts to `build_script_build`
```

**Review by ebroto — CHANGES_REQUESTED** [review]
Besides the nits, two things:

* ` tests/ui/print_stdout_build_script.stderr` can be removed, sorry I did not see that in my first review.
* I was thinking that we should add an integration test also to make sure the lint actually ignores real build scripts. Could you please add a `build.rs` file under `clippy_workspace_tests` similar to the `print_stdout_build_script.rs` that you added? This will be tested by the dogfood tests.

File: tests/ui/build.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (ebroto) [reply tests/ui/build.rs]: No problem! You can see all the available commands [here](https://rustc-dev-guide.rust-lang.org/tests/adding.html#header_commands).

**Comment by giraffate** [comment]
>I was thinking that we should add an integration test also to make sure the lint actually ignores real build scripts. Could you please add a build.rs file under clippy_workspace_tests similar to the print_stdout_build_script.rs that you added (also referencing the issue)? This will be tested by the dogfood tests.

Thanks for your review. It's a good suggestion. However, I tried it but the build script under `clippy_workspace_tests` didn't work in the dogfood tests for some reason.

File: clippy_workspace_tests/build.rs [hunk 5]
```diff
@@ -0,0 +1,5 @@
+fn main() {
```
Comment (ebroto) [inline clippy_workspace_tests/build.rs:1]:
```suggestion
#![deny(clippy::print_stdout)]

fn main() {
```

Comment (ebroto) [reply clippy_workspace_tests/build.rs:1]: Given that `print_stdout` is a restriction lint we have to enable it manually. I think that may be the reason it didn't work for you.

Another thing to take into account is that cargo will not re-run the build script if the script did not change since the last build.

**Review by ebroto — COMMENTED** [review]
I think the only missing thing was the `deny` attribute. I'll merge this if the tests pass.

Thanks for making Clippy better!

File: clippy_workspace_tests/build.rs (hunk 5 above)
Comment (giraffate) [reply clippy_workspace_tests/build.rs:3]: Thanks! As you say, `print_stdout` lint needed to be manually enabled.
