### PR TITLE
Fix `as_deref_mut` false positives in `needless_option_as_deref`

### LINKED ISSUE #7846: False positive in needless_option_as_deref if Option cannot be moved
Lint name:
needless_option_as_deref

I tried this code:

```rust
fn main() {
    let mut i = 0;
    let mut opt_vec = vec![Some(&mut i)];
    opt_vec[0].as_deref_mut().unwrap();
}
```

Clippy complains:
```
warning: derefed type is same as origin
 --> src/main.rs:4:5
  |
4 |     opt_vec[0].as_deref_mut().unwrap();
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `opt_vec[0]`
  |
  = note: `#[warn(clippy::needless_option_as_deref)]` on by default
```

However, when applying the suggestion, the build fails:
```
error[E0507]: cannot move out of index of `Vec<Option<&mut i32>>`
 --> src/main.rs:4:5
  |
4 |     opt_vec[0].unwrap();
  |     ^^^^^^^^^^ move occurs because value has type `Option<&mut i32>`, which does not implement the `Copy` trait
  |
help: consider borrowing the `Option`'s content
  |
4 |     opt_vec[0].as_ref().unwrap();
  |               +++++++++
```
### Meta

**Rust version (`rustc -Vv`):**
```
rustc 1.58.0-nightly (bd41e09da 2021-10-18)
binary: rustc
commit-hash: bd41e09da334697c0f993b36685cb599061d9faa
commit-date: 2021-10-18
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```

@rustbot label +I-suggestion-causes-error

### LINKED ISSUE #8047: Beta/1.57: Wrong suggestion with `needless_option_as_deref` lint
Lint name: needless_option_as_deref

I tried this code:

```rust
fn foo(_x: Option<&mut i32>) {}

fn main() {
    let mut y = 0;
    let mut x = Some(&mut y);
    
    foo(x.as_deref_mut());
    println!("{:?}", x);
}
```

I expected to see this happen: no clippy warnings

Instead, this happened:

```
warning: derefed type is same as origin
 --> src/main.rs:7:9
  |
7 |     foo(x.as_deref_mut());
  |         ^^^^^^^^^^^^^^^^ help: try this: `x`
  |
  = note: `#[warn(clippy::needless_option_as_deref)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_option_as_deref

warning: `playground` (bin "playground") generated 1 warning
```

See playground link: https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=2a51686bfc1dd26539145888b18e8b09

Applying that suggestion causes compilation to fail:

```
error[E0382]: borrow of moved value: `x`
 --> src/main.rs:8:22
  |
5 |     let mut x = Some(&mut y);
  |         ----- move occurs because `x` has type `Option<&mut i32>`, which does not implement the `Copy` trait
6 |     
7 |     foo(x);
  |         - value moved here
8 |     println!("{:?}", x);
  |                      ^ value borrowed here after move
```

### Meta

**Rust version (`rustc -Vv`):**
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0
```

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by Alexendoo**
Also moves it into `methods/`

Fixes #7846
Fixes #8047

changelog: [`needless_option_as_deref`]: No longer lints for `as_deref_mut` on Options that cannot be moved

supersedes #8064

### CODE REVIEW

File: clippy_lints/src/methods/mod.rs [hunk 1]
```diff
@@ -2106,6 +2107,30 @@ declare_clippy_lint! {
     "using `.collect::<Vec<String>>().join(\"\")` on an iterator"
 }
 
+declare_clippy_lint! {
+    /// ### What it does
+    /// Checks for no-op uses of Option::{as_deref,as_deref_mut},
```
Comment (giraffate) [inline clippy_lints/src/methods/mod.rs:2112]: nits
```suggestion
    /// Checks for no-op uses of `Option::{as_deref,as_deref_mut}`,
```

Comment (Alexendoo) [reply clippy_lints/src/methods/mod.rs]: 👍 Changed

**Review by giraffate — APPROVED** [review]

**Comment by giraffate** [comment]
@bors r+

It looks good, thanks!
