### PR TITLE
proper applicability for `obfuscated_if_else`

### LINKED ISSUE #14034: `obfuscated_if_else` doesn't check for side effects in subexpressions
### Summary

The lint suggests changing `b.then_some(x).unwrap_or(y)` into `if b { x } else { y }` without checking that the evaluation of `x` and `y` (whose evaluation is short-circuited in the suggested change) doesn't have any side effect. 

### Reproducer

I tried this code:

```rust
#![allow(clippy::all)]
#![warn(clippy::obfuscated_if_else)]

fn allocate(counter: &mut u32) -> u32 {
    *counter += 1;
    *counter
}

fn main() {
    let mut counter = 0;
    let a = 3;
    let c = (a == 1)
        .then_some(allocate(&mut counter))
        .unwrap_or(allocate(&mut counter));
    assert_eq!(c, 2);
    assert_eq!(counter, 2);
}
```

which runs without error.

Clippy proposed to transform it into:

```rust
#![allow(clippy::all)]
#![warn(clippy::obfuscated_if_else)]

fn allocate(counter: &mut u32) -> u32 {
    *counter += 1;
    *counter
}

fn main() {
    let mut counter = 0;
    let a = 3;
    let c = if (a == 1) { allocate(&mut counter) } else { allocate(&mut counter) };
    assert_eq!(c, 2);
    assert_eq!(counter, 2);
}
```

which fails the test `assert_eq!(c, 2)` because only one call to `allocate` now took place.

At minimum, the applicability should be downgraded from `MachineApplicable` to `MaybeIncorrect`.

### Version

```text
rustc 1.86.0-nightly (049355708 2025-01-18)
binary: rustc
commit-hash: 049355708383ab1b9a1046559b9d4230bdb3a5bc
commit-date: 2025-01-18
host: x86_64-unknown-linux-gnu
release: 1.86.0-nightly
LLVM version: 19.1.7
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by lapla-cogito**
fix #14034 

The currect implementation of `obfuscated_if_else` sometimes makes incorrect suggestions when the original code have side effects (see the example in the above issue). I think this can be fixed by changing the applicability depending on whether it can have side effects or not.

changelog: [`obfuscated_if_else`]: change applicability when the original code can have side effects

### CODE REVIEW

File: clippy_lints/src/methods/obfuscated_if_else.rs [hunk 1]
```diff
@@ -19,7 +19,12 @@ pub(super) fn check<'tcx>(
     let recv_ty = cx.typeck_results().expr_ty(then_recv);
 
     if recv_ty.is_bool() {
-        let mut applicability = Applicability::MachineApplicable;
+        let mut applicability = if then_arg.can_have_side_effects() || unwrap_arg.can_have_side_effects() {
```
Comment (Centri3) [inline clippy_lints/src/methods/obfuscated_if_else.rs:22]: I believe `clippy_utils::eager_or_lazy::switch_to_eager_eval` is the function you're looking for :)

Comment (Centri3) [reply clippy_lints/src/methods/obfuscated_if_else.rs:22]: PS, this should also probably have tests

Comment (lapla-cogito) [reply clippy_lints/src/methods/obfuscated_if_else.rs:22]: Is it appropriate to use `switch_to_eager_eval`? For example, the applicability will be `MaybeIncorrect` by using it:
```rust
true.then_some("a").unwrap_or("b");
```
I think this should be autofixed.

Anyway, I think it's definitely true that some tests should be added to address this issue, so I've added it.

Comment (Centri3) [reply clippy_lints/src/methods/obfuscated_if_else.rs:22]: I don't see how it could be. `ExprKind::Lit(_)` explicitly does nothing in `expr_eagerness`. The hir-tree also shows it is indeed just a literal. Am I missing something?

Comment (lapla-cogito) [reply clippy_lints/src/methods/obfuscated_if_else.rs]: Oh, I think I was sleepwalking... I realized I had the conditional expression completely wrong, and indeed `switch_to_eager_eval` works. Thank you.

**Comment by lapla-cogito** [comment]
Rebased to resolve conflicts.

**Review by Centri3 — APPROVED** [review]
