### PR TITLE
assertions_on_constants: ignore indirect `cfg!`

### LINKED ISSUE #7597: assertions_on_constants incorrectly lints indirect usage of `cfg!`
Lint name: assertions_on_constants

I tried this code:

```rust
const CFG_FLAG: bool = cfg!(config_thing);

fn main() {
    assert!(!CFG_FLAG); // This gives a warning
    assert!(!cfg!(config_thing)); // But direct usage of cfg! is suppressed
}
```

Indirect usage of `cfg!()` flags should not give a warning, just like direct usage.

### Meta

- `cargo clippy -V`: `clippy 0.1.56 (0fa3190 2021-08-12)`
- `rustc -Vv`: 

```
rustc 1.56.0-nightly (0fa319039 2021-08-12)
binary: rustc
commit-hash: 0fa3190394475a84360b34e074e719d519bc40f1
commit-date: 2021-08-12
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

This false positive also happens on the latest stable as well...

Thanks for your time!

### PR DESCRIPTION
**Pull request by pitaj**
Fixes #7597

changelog: [`assertions_on_constants`] ignore constants indirectly based on `cfg!`

### CODE REVIEW

File: clippy_utils/src/consts.rs [hunk 1]
```diff
@@ -400,6 +400,27 @@ impl<'a, 'tcx> ConstEvalLateContext<'a, 'tcx> {
         let res = self.typeck_results.qpath_res(qpath, id);
         match res {
             Res::Def(DefKind::Const | DefKind::AssocConst, def_id) => {
+                // Check if this constant is based on `cfg!(..)`,
+                // which is NOT constant for our purposes.
+                if let Some(mut node) = self.lcx.tcx.hir().get_if_local(def_id) {
+                    loop {
+                        match node {
+                            Node::Item(&Item {
+                                kind: ItemKind::Const(_, body_id),
```
Comment (flip1995) [inline clippy_utils/src/consts.rs:409]: How would code look like that has nested `const` items? I don't see any tests for this. I have a feeling that walking down this chain isn't necessary.

File: tests/ui/assertions_on_constants.rs [hunk 2]
```diff
@@ -28,6 +28,19 @@ fn main() {
...
     assert!(cfg!(feature = "hey") || cfg!(not(feature = "asdf")));
+
+    let flag: bool = cfg!(not(feature = "asdf"));
+    assert!(flag);
+
+    const CFG_FLAG: &bool = &cfg!(feature = "hey");
+    assert!(!CFG_FLAG);
+
+    const INDIRECT_FLAG: bool = !foo::CFG_FLAG;
+    assert!(CFG_FLAG);
```
[the remark this answers is not in the document]
Comment (pitaj) [reply tests/ui/assertions_on_constants.rs:41]: Good catch

File: clippy_utils/src/consts.rs [hunk 3]
```diff
@@ -400,6 +400,85 @@ impl<'a, 'tcx> ConstEvalLateContext<'a, 'tcx> {
         let res = self.typeck_results.qpath_res(qpath, id);
         match res {
             Res::Def(DefKind::Const | DefKind::AssocConst, def_id) => {
+                // Check if this constant is based on `cfg!(..)`,
+                // which is NOT constant for our purposes.
+                if let Some(node) = self.lcx.tcx.hir().get_if_local(def_id) {
+                    fn node_contains_cfg_expn(tcx: TyCtxt<'_>, n: Node<'_>) -> bool {
```
Comment (pitaj) [inline clippy_utils/src/consts.rs:406]: Not sure if this should live somewhere else. It could maybe be useful to others as as more generic `clippy_utils::contains_expn_of(e: &Expr, name: &str) -> bool`. Or it could just live in the `assertions_on_constants` lint.

File: clippy_utils/src/consts.rs [hunk 4]
```diff
@@ -567,6 +575,69 @@ impl<'a, 'tcx> ConstEvalLateContext<'a, 'tcx> {
     }
 }
 
+fn node_contains_cfg_expn(tcx: TyCtxt<'_>, n: Node<'_>) -> bool {
```
Comment (pitaj) [inline clippy_utils/src/consts.rs:578]: Not sure where this should live. I can see a few options:
- here
- more generic version `clippy_utils::contains_expn_of(e: &Expr, name: &str)`
- in the `assertions_on_constants` lint

I can see it being useful in other lints like `needless_bool`.

Comment (flip1995) [reply clippy_utils/src/consts.rs:578]: I agree with @giraffate The current impl would also no longer lint on things like `const _: bool = [cfg!("bla"); 10].len() > 5;`, just because there is a `cfg!` somewhere in the expression. But the `cfg!` in this case has absolutely no influence on the value of the resulting `bool`. 

I would also just check for direct `cfg!` and possibly extend this checks if other issues are opened about more complex cases that would make sense to allow.

Comment (pitaj) [reply clippy_utils/src/consts.rs:578]: I figure a false negative is better than a false positive, but I understand not wanting to add so much complexity for little benefit.

**Review by giraffate — APPROVED** [review]
It looks good. Can you squash the commits?

**Comment by pitaj** [comment]
@giraffate squashed

**Comment by giraffate** [comment]
@bors r+

Thanks!
