### PR TITLE
manual_let_else: let/else is not divergent by default

### LINKED ISSUE #10296: manual_let_else wrong suggestion when else block doesn't diverge
### Summary

It seems that let-else inside the else block of a manual let-else tricks the lint into thinking the block diverges, resulting in a suggestion that is a compile error.

### Lint Name

manual_let_else

### Reproducer

I tried this code:

```rust
#![warn(clippy::manual_let_else)]
fn main() {
    let _x = if let Some(x) = Some(1) {
        x
    } else {
        let Some(_z) = Some(3) else {
            return
        };
        1
    };
}
```

I saw this happen:

```
warning: this could be rewritten as `let...else`
  --> src/main.rs:3:5
   |
3  | /     let _x = if let Some(x) = Some(1) {
4  | |         x
5  | |     } else {
6  | |         let Some(_z) = Some(3) else {
...  |
9  | |         1
10 | |     };
   | |______^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_let_else
note: the lint level is defined here
  --> src/main.rs:1:9
   |
1  | #![warn(clippy::manual_let_else)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^
help: consider writing
   |
3  ~     let Some(x) = Some(1) else {
4  +         let Some(_z) = Some(3) else {
5  +             return
6  +         };
7  +         1
8  +     };
   |
```

### Version

```text
rustc 1.69.0-nightly (11d96b593 2023-02-01)
binary: rustc
commit-hash: 11d96b59307b1702fffe871bfc2d0145d070881e
commit-date: 2023-02-01
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by samueltardieu**
The divergent `else` block of a `let`/`else` statement does not make the `let/else` statement itself divergent.

Fixes #10296 

changelog: [`manual_let_else`]: do not consider `let`/`else` to be divergent by default

### CODE REVIEW

File: clippy_lints/src/manual_let_else.rs [hunk 1]
```diff
@@ -162,61 +163,107 @@ fn emit_manual_let_else(cx: &LateContext<'_>, span: Span, expr: &Expr<'_>, pat:
...
-    fn is_never(cx: &LateContext<'_>, expr: &'_ Expr<'_>) -> bool {
-        if let Some(ty) = cx.typeck_results().expr_ty_opt(expr) {
-            return ty.is_never();
-        }
-        false
+/// Check whether an expression is divergent. May give false negatives.
+pub fn expr_diverges(cx: &LateContext<'_>, expr: &Expr<'_>) -> bool {
+    enum Descend {
+        Yes,
+        No,
```
Comment (Alexendoo) [inline clippy_lints/src/manual_let_else.rs:170]: 👋

Does the `Descend` from `clippy_utils` not work here?

Comment (samueltardieu) [reply clippy_lints/src/manual_let_else.rs:170]: Right, it is `pub`, pushing a fix.

**Review by Alexendoo — APPROVED** [review]

**Comment by Alexendoo** [comment]
Thanks! this is a good way of doing it 👍

@bors r+
