### PR TITLE
Fixed issue #15192

### LINKED ISSUE #15192: large_enum_variant propose a wrong solution for no_std
### Summary

For `clippy::large_enum_variant`, it proposes a solution that uses `Box`:

```
...
...
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
   = note: `#[warn(clippy::large_enum_variant)]` on by default
help: consider boxing the large fields to reduce the total size of the enum
   |
62 -     WriteMacro([u8; MACRO_SPACE_SIZE]),
62 +     WriteMacro(Box<[u8; MACRO_SPACE_SIZE]>),
```

But my current project is `no_std`, which means no allocator is available by default, so the proposed solution is wrong.

### PR DESCRIPTION
**Pull request by lkshayb**
Fixes rust-lang/rust-clippy#15192 by adding checks for no_std while giving out Box recommendation

```
changelog: [`large_enum_variant`]: Dont suggest `Box` in `no_std` mode
```

### CODE REVIEW

**Comment by samueltardieu** [comment]
The `changelog` line in the PR description should contain the lint name in square brackets and quotes, such as in

```
changelog: [`large_enum_variant`]: do not suggest `Box` in `no_std` mode
```

(note also the quotes around `Box` and `no_std`)

This way it will be easily transformed into a link to the lint description when integrated in `CHANGELOG.md` when we issue the release notes.

**Comment by lkshayb** [comment]
@samueltardieu Thanks ! I've updated the changelog line as suggested .

File: tests/ui/large_enum_variant_no_std.rs [hunk 1]
```diff
@@ -0,0 +1,16 @@
+#![no_std]
+#![no_main]
```
Comment (y21) [inline tests/ui/large_enum_variant_no_std.rs]: Tests are built as library crates, so you should be able to largely simplify this. The `#![no_main]` and panic handling code shouldn't be needed.

```rs
#![no_std]
#![warn(clippy::large_enum_variant)]

enum Myenum {
    //~^ ERROR: large size difference between variants
    Small(u8),
    Large([u8; 1024]),
}
```

**Comment by lkshayb** [comment]
@y21 Thanks for the feedback . You are correct that a downgraded help message should be used . I will update my pull request to follow the same and also I'll edit out the `panic handler` and `#[no_main]`.

**Comment by lkshayb** [comment]
@y21 I have implemented the suggestions you made . Please review it now.

File: clippy_lints/src/large_enum_variant.rs [hunk 2]
```diff
@@ -149,7 +150,9 @@ impl<'tcx> LateLintPass<'tcx> for LargeEnumVariant {
                                 return;
                             }
                         }
-                        diag.span_help(def.variants[variants_size[0].ind].span, help_text);
+                        if !is_no_std_crate(cx) {
```
Comment (y21) [inline clippy_lints/src/large_enum_variant.rs]: Is this `if` here on purpose? My suggestion was to always at least show the help message, no matter what, as a guidance in case the user has some other way to add indirection, even without access to `alloc`.

As is implemented right now, it will still suppress the help message entirely in `#![no_std]` (as can be seen in the test)

Comment (y21) [reply clippy_lints/src/large_enum_variant.rs]: Actually, looking at the git history on this branch, it looks like this was correct in https://github.com/lkshayb/rust-clippy/commit/0ac806d6dcf10316e8eec7b35ccc0ca7c91c4eb8 , but was then later reverted again in https://github.com/lkshayb/rust-clippy/commit/3e6d5759b99c27b26a6429b9bfa3143662a0535b

Comment (lkshayb) [reply clippy_lints/src/large_enum_variant.rs]: Thx @y21 for pointing this out . I've updated the pr now . and also squashed all the commits into one.

**Comment by lkshayb** [comment]
@y21 I've implemented the changes and squashed all the commits into one , please review now .

**Review by y21 — APPROVED** [review]
Thanks!

**Comment by y21** [comment]
Ah, looks like there's a 32-bit stderr of the test that wasn't blessed. They're a bit annoying to bless on 64 bit, but in this case since it's just the help message that changed everywhere, you could also just do a manual replace in `tests/ui/large_enum_variant.32bit.stderr`.

Also, while you're fixing that, minor nit: could you also reword the commit to something more descriptive? Thanks!

**Comment by lkshayb** [comment]
@y21 I've blessed the 32 bit stederr manually and also changed the commit message .
