### PR TITLE
fix: `unnecessary_cast` suggests extra brackets when in macro

### LINKED ISSUE #14640: Unnecessary curve brackets in suggestion generated by [`unnecessary_cast`] lint
### Summary

Suggestion generated by this lint have unnecessary curve brackets. It also auto apply this brackets with `--fix` flag.

### Reproducer

I tried this code:

```rust
use std::vec::Vec;

fn main() {
    let x = 5usize;
    let vec: Vec<u64> = vec![1, 2, 3, 4, 5];
    assert_eq!(vec.len(), x as usize);
}

```

I expected to see this happen when I run `cargo clippy`:
```
warning: casting to the same type is unnecessary (`usize` -> `usize`)
 --> src/main.rs:6:27
  |
6 |     assert_eq!(vec.len(), x as usize);
  |                           ^^^^^^^^^^ help: try: `x`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
  = note: `#[warn(clippy::unnecessary_cast)]` on by default
```

Instead, this happened:
```
warning: casting to the same type is unnecessary (`usize` -> `usize`)
 --> src/main.rs:6:27
  |
6 |     assert_eq!(vec.len(), x as usize);
  |                           ^^^^^^^^^^ help: try: `{ x }`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_cast
  = note: `#[warn(clippy::unnecessary_cast)]` on by default
```

My rust version:
```
rustc -Vv
rustc 1.85.0-nightly (21fe748be 2024-12-11)
binary: rustc
commit-hash: 21fe748be15271ea5804e0507cd699b675efe038
commit-date: 2024-12-11
host: aarch64-apple-darwin
release: 1.85.0-nightly
LLVM version: 19.1.5
```

### Version

```text

```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by profetia**
Closes rust-lang/rust-clippy#14640 

changelog: [`unnecessary_cast`] fix extra brackets in suggestions when in macro

### CODE REVIEW

File: clippy_lints/src/casts/unnecessary_cast.rs [hunk 1]
```diff
@@ -157,8 +157,10 @@ pub(super) fn check<'tcx>(
         // `*x.foo()`, which changes what the `*` applies on).
         // The same is true if the expression encompassing the cast expression is a unary
         // expression or an addressof expression.
-        let needs_block = matches!(cast_expr.kind, ExprKind::Unary(..) | ExprKind::AddrOf(..))
-            || get_parent_expr(cx, expr).is_some_and(|e| matches!(e.kind, ExprKind::Unary(..) | ExprKind::AddrOf(..)));
+        let needs_block = (matches!(cast_expr.kind, ExprKind::Unary(..) | ExprKind::AddrOf(..))
+            || get_parent_expr(cx, expr).is_some_and(|e| {
+                matches!(e.kind, ExprKind::Unary(..) | ExprKind::AddrOf(..)) && !e.span.from_expansion()
+            }));
```
Comment (samueltardieu) [inline clippy_lints/src/casts/unnecessary_cast.rs:163]: This seems arbitrary, and wrong (from the start, not only because of your change). For example, the following will fail before and after this change:

```rust
let _ = (5i32 as i64 as i64).abs();
```

as it will suggest

```rust
let _ = 5i32 as i64.abs();
```

Also, why is a block added, rather than parentheses? I can't find justifications for it in #12365.

I think the logic here needs to be rethought properly:
- How to get a proper snippet (the `Sugg` interface is probably better)
- Where will the snippet be inserted, and does it require parentheses in this position? We can put some, using `.maybe_paren()`, if it is in receiver position, or as part of a binary (inclusing casts) or a unary (or unary-like, like `&…`) operation.

Comment (profetia) [reply clippy_lints/src/casts/unnecessary_cast.rs]: Good idea! Thank you!

File: clippy_lints/src/casts/unnecessary_cast.rs [hunk 2]
```diff
@@ -157,21 +158,20 @@ pub(super) fn check<'tcx>(
         // `*x.foo()`, which changes what the `*` applies on).
```
Comment (Jarcho) [inline clippy_lints/src/casts/unnecessary_cast.rs:158]: This comment should either be removed or edited as well.

**Review by Jarcho — CHANGES_REQUESTED** [review]
One minor nit, otherwise looks ok.

File: clippy_lints/src/casts/unnecessary_cast.rs (hunk 2 above)
Comment (profetia) [reply clippy_lints/src/casts/unnecessary_cast.rs]: Thank you!

File: clippy_lints/src/casts/unnecessary_cast.rs [hunk 3]
```diff
@@ -150,28 +151,20 @@ pub(super) fn check<'tcx>(
...
-            } else {
-                cast_str
+            |diag| {
+                let mut applicability = Applicability::MachineApplicable;
+                let sugg = Sugg::hir_with_applicability(cx, cast_expr, "..", &mut applicability);
+                if applicability != Applicability::MachineApplicable {
+                    return;
+                }
+
+                diag.span_suggestion(expr.span, "try", sugg.maybe_paren().to_string(), applicability);
```
Comment (samueltardieu) [inline clippy_lints/src/casts/unnecessary_cast.rs:166]: By not checking where you insert it and applying `.maybe_paren()` systematically, you will create unneeded extra pairs of parentheses, for example in

```rust
let _ = 5i32 as i64 as i64;
```

where this will suggest

```rust
let _ = (5i32 as i64);
```

I'll let @Jarcho determine if it is a bother or not.

Comment (profetia) [reply clippy_lints/src/casts/unnecessary_cast.rs]: I modified it to only `maybe_paren()` when there is already paren around the cast expr. This will not solve all the problems, but will at least not introduce new parens.

Comment (Jarcho) [reply clippy_lints/src/casts/unnecessary_cast.rs]: Since you're already doing something with this you can use `expr.precedence() < parent.precedence()` to be more accurate.

Comment (profetia) [reply clippy_lints/src/casts/unnecessary_cast.rs]: Added. Thanks!

File: clippy_lints/src/casts/unnecessary_cast.rs [hunk 4]
```diff
@@ -150,28 +151,36 @@ pub(super) fn check<'tcx>(
...
+
+                let snip = snippet_with_applicability(cx, expr.span, "..", &mut applicability);
+                if applicability != Applicability::MachineApplicable {
+                    return;
+                }
+
+                let need_paren = if let Node::Expr(parent) = cx.tcx.parent_hir_node(expr.hir_id) {
+                    cast_expr.precedence() < parent.precedence()
+                } else {
+                    has_enclosing_paren(&snip)
```
Comment (Jarcho) [inline clippy_lints/src/casts/unnecessary_cast.rs:174]: You no longer need this with the precedence check in place.

File: clippy_lints/src/casts/unnecessary_cast.rs [hunk 5]
```diff
@@ -150,28 +151,36 @@ pub(super) fn check<'tcx>(
...
+                };
+
+                diag.span_suggestion(
+                    expr.span,
+                    "try",
+                    if need_paren { sugg.maybe_paren() } else { sugg }.to_string(),
```
Comment (Jarcho) [inline clippy_lints/src/casts/unnecessary_cast.rs:180]: Since you're no longer actually using `maybe_paren` to add parenthesis just use `format!("({snip})")` rather than using `hir::Sugg`.

**Review by Jarcho — CHANGES_REQUESTED** [review]

File: clippy_lints/src/casts/unnecessary_cast.rs (hunk 5 above)
Comment (profetia) [reply clippy_lints/src/casts/unnecessary_cast.rs]: Thank you!

File: tests/ui/unnecessary_cast.stderr [hunk 6]
```diff
@@ -209,7 +209,7 @@ error: casting to the same type is unnecessary (`i32` -> `i32`)
   --> tests/ui/unnecessary_cast.rs:227:18
    |
 LL |         let _ = &(x as i32);
-   |                  ^^^^^^^^^^ help: try: `{ x }`
```
Comment (Jarcho) [inline tests/ui/unnecessary_cast.stderr:212]: Now that I'm looking at this again the old suggestion was indeed correct. `&x` and `&{ x }` are actually different things. The issue opened is only correct because the `Display` impl for references doesn't care about the address used.

The approach take in this PR won't fix the problem without adding bad suggestions. Sorry for not noticing initially.

Comment (profetia) [reply tests/ui/unnecessary_cast.stderr:212]: I can keep the paren one if there is one originally. And TBH I dont really understand why `&x` and `&{ x }` is different.

Comment (Jarcho) [reply tests/ui/unnecessary_cast.stderr:212]: `&{ x }` move the value of `x` and then takes a reference to the temporary and `&x` takes a reference to `x` directly. `&(x as _)` behaves like the former since a cast will always produce a temporary.

File: clippy_lints/src/casts/unnecessary_cast.rs [hunk 7]
```diff
@@ -150,26 +150,32 @@ pub(super) fn check<'tcx>(
...
+        enum MaybeParenOrBlock {
+            Paren,
+            Block,
+            Nothing,
+        }
+
+        let surrounding = match cx.tcx.parent_hir_node(expr.hir_id) {
+            // Changing `&(x as i32)` to `&x` would change the meaning of the code because the previous creates
+            // a reference to the temporary while the latter creates a reference to the original value.
+            Node::Expr(parent) if !parent.span.from_expansion() && matches!(parent.kind, ExprKind::AddrOf(..)) => {
```
[the remark this answers is not in the document]
Comment (profetia) [reply clippy_lints/src/casts/unnecessary_cast.rs]: Thank you!

File: clippy_lints/src/casts/unnecessary_cast.rs [hunk 8]
```diff
@@ -150,26 +166,26 @@ pub(super) fn check<'tcx>(
...
-        // with higher precedence than the unary operator (`(*x as T).foo()` would become
-        // `*x.foo()`, which changes what the `*` applies on).
-        // The same is true if the expression encompassing the cast expression is a unary
-        // expression or an addressof expression.
-        let needs_block = matches!(cast_expr.kind, ExprKind::Unary(..) | ExprKind::AddrOf(..))
-            || get_parent_expr(cx, expr).is_some_and(|e| matches!(e.kind, ExprKind::Unary(..) | ExprKind::AddrOf(..)));
+        let surrounding = match cx.tcx.parent_hir_node(expr.hir_id) {
+            // Changing `&(x as i32)` to `&x` would change the meaning of the code because the previous creates
+            // a reference to the temporary while the latter creates a reference to the original value.
+            Node::Expr(parent) if !parent.span.from_expansion() && is_borrow_expr(cx, parent) => {
```
Comment (Jarcho) [inline clippy_lints/src/casts/unnecessary_cast.rs:172]: You'll want to specifically check for the `format_args` macro rather than `from_expansion`. I think `cx.tcx.is_diagnostic_item(sym::format_args_macro, span.ctxt().outer_expn_data().macro_def_id)`.

This is only fine to do here because we know `Display<&T>` just forwards the call to `Display<T>`.

Comment (profetia) [reply clippy_lints/src/casts/unnecessary_cast.rs:172]: This will make `assert_eq!(vec.len(), x as usize)` suggesting `{ x }`. I use `from_expansion` so that we only keep the original borrowing behavior when the user  really intend to do so, not when it is generated by macro.

Comment (Jarcho) [reply clippy_lints/src/casts/unnecessary_cast.rs:172]: You can also allow `assert_eq`, `assert_ne`, `debug_assert_eq` and `debug_assert_ne`. In which case you'll want `cx.tcx.get_diagnostic_name(macro_id, Some(...))`. All the macros are diagnostic items.

Comment (profetia) [reply clippy_lints/src/casts/unnecessary_cast.rs]: Thank you!

File: clippy_lints/src/casts/unnecessary_cast.rs [hunk 9]
```diff
@@ -142,6 +144,33 @@ pub(super) fn check<'tcx>(
...
+            const ALLOWED_MACROS: &[Symbol] = &[
+                sym::format_args_macro,
+                sym::assert_eq_macro,
+                sym::debug_assert_eq_macro,
+                sym::assert_ne_macro,
+                sym::debug_assert_ne_macro,
+            ];
+            matches!(expr.span.ctxt().outer_expn_data().macro_def_id, Some(def_id) if 
+                ALLOWED_MACROS.iter().any(|&sym| cx.tcx.is_diagnostic_item(sym, def_id)))
+        }
```
Comment (Jarcho) [inline clippy_lints/src/casts/unnecessary_cast.rs:172]: You want to use `get_diagnostic_name` when checking for multiple possible diagnostic items.

File: clippy_lints/src/casts/unnecessary_cast.rs [hunk 10]
```diff
@@ -150,26 +179,26 @@ pub(super) fn check<'tcx>(
...
-        // with higher precedence than the unary operator (`(*x as T).foo()` would become
-        // `*x.foo()`, which changes what the `*` applies on).
-        // The same is true if the expression encompassing the cast expression is a unary
-        // expression or an addressof expression.
-        let needs_block = matches!(cast_expr.kind, ExprKind::Unary(..) | ExprKind::AddrOf(..))
-            || get_parent_expr(cx, expr).is_some_and(|e| matches!(e.kind, ExprKind::Unary(..) | ExprKind::AddrOf(..)));
+        // Changing `&(x as i32)` to `&x` would change the meaning of the code because the previous creates
+        // a reference to the temporary while the latter creates a reference to the original value.
+        let surrounding = match cx.tcx.parent_hir_node(expr.hir_id) {
+            Node::Expr(parent) if !is_in_allowed_macro(cx, parent) && is_borrow_expr(cx, parent) => {
```
Comment (Jarcho) [inline clippy_lints/src/casts/unnecessary_cast.rs:185]: Small perf nit: The macro check only needs to occur for `AddrOf` expressions and like it currently does the adjustment check only needs to occur for other expressions.

File: clippy_lints/src/casts/unnecessary_cast.rs [hunk 11]
```diff
@@ -142,6 +144,33 @@ pub(super) fn check<'tcx>(
...
+            Nothing,
+        }
+
+        fn is_borrow_expr(cx: &LateContext<'_>, expr: &Expr<'_>) -> bool {
+            matches!(expr.kind, ExprKind::AddrOf(..))
+                || cx
+                    .typeck_results()
+                    .expr_adjustments(expr)
+                    .iter()
+                    .any(|adj| matches!(adj.kind, Adjust::Borrow(_)))
```
Comment (Jarcho) [inline clippy_lints/src/casts/unnecessary_cast.rs:159]: Another small nit: Only the first adjustment needs to be checked. Any later borrow would have to borrow a temporary.

**Review by Jarcho — CHANGES_REQUESTED** [review]
Just a couple of small perf nits.

File: clippy_lints/src/casts/unnecessary_cast.rs (hunk 9 above)
Comment (profetia) [reply clippy_lints/src/casts/unnecessary_cast.rs]: Updated. Thank you!

**Review by Jarcho — APPROVED** [review]
Thank you.
