### PR TITLE
useless use of format! should return function directly

### LINKED ISSUE #7066: useless use of `format!`: should return function directly
I tried this code:

```bash
$ cargo clippy --all-targets --all-features -- -D clippy::all
```

1. Linter says:
```rust
let v: Vec<String> = vec!["foo".to_string(), "bar".to_string()];
let s: String = format!("{}", &*v.join("\n"));
// useless use of `format!`: help: consider using `.to_string()`: `&*v.join("\n").to_string()`
```

2. After fix what linter says:
```rust
let v: Vec<String> = vec!["foo".to_string(), "bar".to_string()];
let s: String = &*v.join("\n").to_string();
// IDE error: mismatched types [E0308] expected `String`, found `&<unknown>`
// Linter error: mismatched types: expected struct `std::string::String`, found `&str`
```

3. Manually fix:
```rust
v.join("\n").to_string()
//           ^^^^^^^^^^^^ redundant clone: help: remove this
```

I expected to see this happen: *explanation*

```
help: consider using `v.join("\n")`
```

Instead, this happened: *explanation*

```
useless use of `format!`: help: consider using `.to_string()`: `&*v.join("\n").to_string()`
```

### Meta

- `cargo clippy -V`: `clippy 0.1.51 (2fd73fab 2021-03-23)`
- `rustc -Vv`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-apple-darwin
release: 1.51.0
LLVM version: 11.0.1
```

**EDIT:** _Accidiantelly opened issue format as `false-negative`, can someone please change label to `false-positive`?_

### PR DESCRIPTION
**Pull request by basavesh**
fixes #7066 

changelog: [`useless_format`] wraps the content in the braces when it's needed.

r? @giraffate

### CODE REVIEW

File: clippy_lints/src/format.rs [hunk 1]
```diff
@@ -136,7 +136,7 @@ fn on_new_v1<'tcx>(cx: &LateContext<'tcx>, expr: &'tcx Expr<'_>) -> Option<Strin
                 if let Some(s_src) = snippet_opt(cx, lit.span) {
                     // Simulate macro expansion, converting {{ and }} to { and }.
                     let s_expand = s_src.replace("{{", "{").replace("}}", "}");
-                    return Some(format!("{}.to_string()", s_expand))
+                    return Some(format!("({}).to_string()", s_expand))
```
Comment (basavesh) [inline clippy_lints/src/format.rs:139]: Probably this change is also not required.

**Review by giraffate — CHANGES_REQUESTED** [review]
Thanks for your work, and welcome to Clippy!

Parentheses should be put only when it's needed, not all. `maybe_par` method in `utils` may be useful for this case.

Also, Can a test like the one described in the related issue be added?

**Comment by basavesh** [comment]
fixes https://github.com/rust-lang/rust-clippy/issues/7078

**Review by giraffate — APPROVED** [review]
It looks good, thanks!

Can you squash commits?

**Comment by giraffate** [comment]
@bors r+

Thanks!
