### PR TITLE
FIX(12243): redundant_guards

### LINKED ISSUE #12243: redundant_guards does not take const fn-ness into account
### Summary

When inside a const fn there are additional restrictions that redundant_guards appears to not consider.

### Lint Name

redundant_guards

### Reproducer

I tried this code:

```rust
pub const fn handle(x: &str) -> u32 {
    match x {
        y if y.is_empty() => 2,
        _ => 3,
    }
}
```

I saw this happen:

```
warning: redundant guard
 --> src/lib.rs:3:14
  |
3 |         y if y.is_empty() => 2,
  |              ^^^^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_guards
  = note: `#[warn(clippy::redundant_guards)]` on by default
help: try
  |
3 -         y if y.is_empty() => 2,
3 +         "" => 2,
  |
```

However applying that suggestion results in:

```
error[E0015]: cannot match on `str` in constant functions
 --> src/lib.rs:3:9
  |
3 |         "" => 2,
  |         ^^
  |
  = note: `str` cannot be compared in compile-time, and therefore cannot be used in `match`es
  = note: calls in constant functions are limited to constant functions, tuple structs and tuple variants
```

### Version

```text
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: x86_64-unknown-linux-gnu
release: 1.76.0
LLVM version: 17.0.6
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by not-elm**
Fixed #12243 

changelog: Fix[`redundant_guards`]

I have made a correction so that no warning does  appear when y.is_empty() is used within a constant function as follows.

```rust
pub const fn const_fn(x: &str) {
    match x {
        // Shouldn't lint.
        y if y.is_empty() => {},
        _ => {},
    }
}
```

### CODE REVIEW

**Comment by not-elm** [comment]
Thank you for pointing me to the alternative.
Please review again as it has been corrected.

File: tests/ui/redundant_guards_const_fn.rs [hunk 1]
```diff
@@ -0,0 +1,47 @@
+#![allow(clippy::single_match)]
```
Comment (y21) [inline tests/ui/redundant_guards_const_fn.rs:1]: Is there a reason that this is its own test file, and not just part of the existing `redundant_guards.rs` test? Typically we have a single test file for lints, and optionally a `mod issue0000 {}`, [like here](https://github.com/rust-lang/rust-clippy/blob/a2c1d565e576efb5f3abce367723711afe65c8cd/tests/ui/redundant_guards.rs#L205).

**Review by y21 — COMMENTED** [review]
One small nit, then it LGTM

File: tests/ui/redundant_guards_const_fn.rs (hunk 1 above)
Comment (not-elm) [reply tests/ui/redundant_guards_const_fn.rs]: I created mod issue12243 in `redundant_guards.rs` and moved the test cases there.

**Review by y21 — APPROVED** [review]

**Comment by y21** [comment]
Looks great, thanks!

@bors r+
