### PR TITLE
Fix false positive in module_name_repetitions lint

### LINKED ISSUE #3892: No location reported for `module_name_repetitions`
Hi,

Clippy fails to give a location for `module_name_repetitions` in some cases. It looks like it's when an attribute matches the module name. Here's the steps to reproduce:

```
cargo new --lib clippy-test
cd clippy-test
```

Change the module inside `src/lib.rs` from `tests` to `test`:

```
#[cfg(test)]
mod test {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

Then run `cargo clippy --tests -- -D clippy::pedantic`, which outputs:

```
    Checking clippy-test v0.1.0 (/some_path/clippy-test)
error: item name starts with its containing module's name
  |
  = note: `-D clippy::module-name-repetitions` implied by `-D clippy::pedantic`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#module_name_repetitions

error: aborting due to previous error

error: Could not compile `clippy-test`.

To learn more, run the command again with --verbose.

```

Regards,

Simon

Versions:

clippy 0.0.212 (1b89724 2019-01-15)
cargo 1.33.0 (f099fe94b 2019-02-12)

### PR DESCRIPTION
**Pull request by phansch**
This lint was triggering on modules inside expanded attrs, like
for example `#[cfg(test)]` and possibly more.

It was not reporting a location in #3892 because `span.lo()` and `span.hi()` both were 0.

Fixes #3892

changelog: Fix false positive in `module_name_repetitions` lint

### CODE REVIEW

File: tests/ui/module_name_repetitions.rs [hunk 1]
```diff
@@ -1,3 +1,5 @@
+// compile-flags: --test
```
Comment (phansch) [inline tests/ui/module_name_repetitions.rs]: I couldn't find another attribute that caused this issue, that's why the `--test` is included here.
