### PR TITLE
Do not trigger redundant_closure for non-function types

### LINKED ISSUE #3898: redundant closure lint fails for FnMut where FnOnce is expected
This compiles ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7e067bffb234f1b39857d6dd986e1313)):

```rust
pub fn bar(mut x: Box<dyn FnMut()>) {
    foo(|| x())
}

pub fn foo<T: FnOnce()>(_: T) {}
```

but clippy suggests:

```
warning: redundant closure found
 --> src/lib.rs:2:9
  |
2 |     foo(|| x())
  |         ^^^^^^ help: remove closure as shown: `x`
  |
  = note: #[warn(clippy::redundant_closure)] on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure
```

which fails to compile with ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bd910962f25b592909b97a16c5198686)):

```
error[E0277]: expected a `std::ops::FnOnce<()>` closure, found `std::boxed::Box<dyn std::ops::FnMut()>`
 --> src/lib.rs:2:5
  |
2 |     foo(x)
  |     ^^^ expected an `FnOnce<()>` closure, found `std::boxed::Box<dyn std::ops::FnMut()>`
  |
  = help: the trait `std::ops::FnOnce<()>` is not implemented for `std::boxed::Box<dyn std::ops::FnMut()>`
  = note: wrap the `std::boxed::Box<dyn std::ops::FnMut()>` in a closure with no arguments: `|| { /* code */ }
note: required by `foo`
 --> src/lib.rs:5:1
  |
5 | pub fn foo<T: FnOnce()>(_: T) {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by g-bartoszek**
fixes #3898

Added a check for the entity being called in the closure body to be a FnDef. This way lint does not trigger for ADTs (Box) but I'm not sure if it's correct and not too restrictive.

changelog: Fix false positive in `redundant_closure` pertaining to non-function types

### CODE REVIEW

File: clippy_lints/src/eta_reduction.rs [hunk 1]
```diff
@@ -65,6 +65,9 @@ fn check_closure(cx: &LateContext<'_, '_>, expr: &Expr) {
             if !(is_adjusted(cx, ex) || args.iter().any(|arg| is_adjusted(cx, arg)));
 
             let fn_ty = cx.tables.expr_ty(caller);
+
+            if let ty::FnDef(_, _) = fn_ty.sty;
```
Comment (Manishearth) [inline clippy_lints/src/eta_reduction.rs]: This should include `FnPtr` and `Closure`. 

Use `matches!` if it works here, otherwise you can move this check below to the `then` block as a `match`

**Comment by phansch** [comment]
Does this also fix https://github.com/rust-lang/rust-clippy/issues/1439? (No problem if it doesn't, just making sure)

**Comment by g-bartoszek** [comment]
@phansch The lint does not trigger for the original example (https://github.com/rust-lang/rust-clippy/issues/1439#issue-200535244). It does trigger for the "minimal repro" (https://github.com/rust-lang/rust-clippy/issues/1439#issuecomment-406806303) but the suggestion is correct in this case (there is no Box involved, just plain closure) so it seems that the answer is yes.

**Comment by phansch** [comment]
@bors r+

thanks!
