### PR TITLE
Fix `collapsible_if` FP on block stmt before expr

### LINKED ISSUE #14722: `collapsible_else_if` lint false positive
### Summary

There is a bug in the `collapsible_else_if` lint that shows an irrelevant warning about collapsing else if statements when it shouldn't.

### Lint Name

collapsible_else_if

### Reproducer

I tried this code:

```rust
fn main() {
    let x = if true {
        Some(1)
    } else {
        if true {
            println!("Some debug information");
        };
        None
    };
}
```

I saw this happen:

```
warning: this `else { if .. }` block can be collapsed
 --> src/main.rs:4:12
  |
4 |       } else {
  |  ____________^
5 | |         if true {
6 | |             println!("Some debug information");
7 | |         };
8 | |         None
9 | |     };
  | |_____^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_else_if
  = note: `#[warn(clippy::collapsible_else_if)]` on by default
help: collapse nested if block
  |
4 ~     } else if true {
5 +         println!("Some debug information");
6 ~     };
  |
```

I expected to see this happen:

No warning.

### Version

```text
rustc 1.88.0-nightly (b45dd71d1 2025-04-30)
binary: rustc
commit-hash: b45dd71d1824f176fba88f6c40467030a16afa2c
commit-date: 2025-04-30
host: aarch64-apple-darwin
release: 1.88.0-nightly
LLVM version: 20.1.2
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by profetia**
Closes rust-lang/rust-clippy#14722 

changelog: [`collapsible_if`] fix FP on block stmt before expr

### CODE REVIEW

**Comment by Alexendoo** [comment]
Nominating this to be in the same release as https://github.com/rust-lang/rust-clippy/pull/14481 if needed

**Comment by samueltardieu** [comment]
> Nominating this to be in the same release as #14481 if needed

Thanks, this was indeed introduced (and not caught by existing checks) during the conversion into a late lint.

File: clippy_lints/src/collapsible_if.rs [hunk 1]
```diff
@@ -202,13 +202,12 @@ fn block_starts_with_comment(cx: &LateContext<'_>, block: &Block<'_>) -> bool {
...
         [] => block.expr,
-        [stmt] => {
-            if let StmtKind::Semi(expr) = stmt.kind {
-                Some(expr)
-            } else {
-                None
-            }
-        },
+        [
+            Stmt {
```
Comment (samueltardieu) [inline clippy_lints/src/collapsible_if.rs:206]: I'm on a phone and can't easily check this for now, but don't we have a function in clippy utils to check for single statement (semi/expr) blocks?

Comment (profetia) [reply clippy_lints/src/collapsible_if.rs]: Thank you!

**Review by samueltardieu — CHANGES_REQUESTED** [review]
The fix looks complicated. It looks like there is a guard missing in `expr_block()`, adding it may be enough to fix the problem and would greatly simplify this PR:

```diff
     match block.stmts {
         [] => block.expr,
-        [stmt] => {
+        [stmt] if block.expr.is_none() => {
```

**Review by samueltardieu — APPROVED** [review]
LGTM, thanks

**Comment by flip1995** [comment]
Same as: https://github.com/rust-lang/rust-clippy/pull/14733#issuecomment-2863369355

The likelihood of a beta backport right after the release increases.

**Comment by flip1995** [comment]
https://github.com/rust-lang/rust/pull/142725
