### PR TITLE
Fix `derivable_impls` suggests wrongly on `derive_const`

### LINKED ISSUE #15493: Correct manual impl Default
### Summary

Clippy warns a manually implenented Default, while I think it's correct on both non-Nightly and Nightly compilers (on Nightly there's a better solution).

### Lint Name

derivable_impls

### Reproducer

I tried this code:

```rust
#![feature(const_trait_impl)]
#![feature(const_default)]
#![allow(dead_code)]

#[derive(Copy, Clone)]
#[repr(transparent)]
struct Foo(u64);

impl const Default for Foo {
    fn default() -> Self {
        Self(0)
    }
}

fn main() {
    const X: Foo = Foo::default();
}
```

But Clippy complains:

```rust
warning: this `impl` can be derived
  --> src\main.rs:9:1
   |
 9 | / impl const Default for Foo {
10 | |     fn default() -> Self {
11 | |         Self(0)
12 | |     }
13 | | }
   | |_^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls
   = note: `#[warn(clippy::derivable_impls)]` on by default
help: replace the manual implementation with a derive attribute
   |
 7 + #[derive(Default)]
 8 ~ struct Foo(u64);
   |
```

If I do that, the code doesn't compile anymore:

```rust
error[E0277]: the trait bound `Foo: const Default` is not satisfied
```

To make it compilable again on Nightly I need to use a derive_const:

```rust
#![feature(const_trait_impl)]
#![feature(const_default)]
#![feature(derive_const)]
#![allow(dead_code)]

#[derive(Copy, Clone)]
#[repr(transparent)]
#[derive_const(Default)]
struct Foo(u64);

fn main() {
    const X: Foo = Foo::default();
}
```

### Version

```text
rustc 1.91.0-nightly (898aff704 2025-08-14)
binary: rustc
commit-hash: 898aff704d6f0d00343f21d31b8b9bfac8e43007
commit-date: 2025-08-14
host: x86_64-pc-windows-gnu
release: 1.91.0-nightly
LLVM version: 21.1.0
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by profetia**
Closes rust-lang/rust-clippy#15493 
Closes rust-lang/rust-clippy#15536

changelog: [`derivable_impls`] fix wrong suggestions on `derive_const`

### CODE REVIEW

File: clippy_lints/src/derivable_impls.rs [hunk 1]
```diff
@@ -85,6 +85,17 @@ fn contains_trait_object(ty: Ty<'_>) -> bool {
...
 
+fn determine_derive_macro(cx: &LateContext<'_>, is_const: bool) -> Option<&'static str> {
+    if is_const {
+        if !cx.tcx.features().enabled(sym::derive_const) {
+            return None;
+        }
+        return Some("derive_const");
+    }
+    Some("derive")
+}
```
Comment (samueltardieu) [inline clippy_lints/src/derivable_impls.rs]: This can be made more concise:

```suggestion
    if is_const {
        cx.tcx.features().enabled(sym::derive_const).then_some("derive_const")
    } else {
        Some("derive")
    }
```

File: clippy_lints/src/derivable_impls.rs [hunk 2]
```diff
@@ -128,11 +140,15 @@ fn check_struct<'tcx>(
         _ => false,
```
Comment (samueltardieu) [inline clippy_lints/src/derivable_impls.rs]: Let's return early if we won't lint anyway:

```suggestion
        _ => return,
```

File: clippy_lints/src/derivable_impls.rs [hunk 3]
```diff
@@ -128,11 +140,15 @@ fn check_struct<'tcx>(
...
     };
 
+    let Some(derive_snippet) = determine_derive_macro(cx, is_const) else {
+        return;
+    };
+
     if should_emit {
```
Comment (samueltardieu) [inline clippy_lints/src/derivable_impls.rs]: Best check for the derive macro to use only when we know that we will emit the lint:

```suggestion
    if should_emit && let Some(derive_snippet) = determine_derive_macro(cx, is_const) {
```

File: tests/ui/derivable_impls_derive_const.fixed [hunk 4]
```diff
@@ -0,0 +1,25 @@
+#![allow(dead_code)]
+#![feature(const_trait_impl)]
+#![feature(const_default)]
+#![feature(derive_const)]
+
+mod issue15493 {
+    #[derive(Copy, Clone)]
+    #[repr(transparent)]
+    #[derive_const(Default)]
+struct Foo(u64);
```
Comment (samueltardieu) [inline tests/ui/derivable_impls_derive_const.fixed]: The indentation looks wrong here.

**Review by samueltardieu — CHANGES_REQUESTED** [review]
Thanks, some nits to make the code shorter, and an indentation problem.

r? samueltardieu

**Comment by profetia** [comment]
Also closes #15536

File: clippy_lints/src/derivable_impls.rs (hunk 1 above)
Comment (profetia) [reply clippy_lints/src/derivable_impls.rs]: Thank you!

**Review by samueltardieu — APPROVED** [review]
