### PR TITLE
Fix `manual_is_variant_and` condition generation

### LINKED ISSUE #15202: Incorrect suggestion by `manual_is_variant_and`
### Summary

Incorrect suggestion by `manual_is_variant_and`

### Reproducer

I tried this code:

```rust
#![deny(clippy::manual_is_variant_and)]

fn main() {
    let xs = [None, Some(b'_'), Some(b'1')];
    for x in xs {
        let a1 = dbg!(x.map(|b| b.is_ascii_digit()) != Some(true));
        let a2 = dbg!(x.is_none_or(|b| b.is_ascii_digit()));
        assert_eq!(a1, a2);
    }
}
```

```
error: called `.map() != Some()`
 --> src/main.rs:6:18
  |
6 |         let a1 = x.map(|b| b.is_ascii_digit()) != Some(true);
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use: `x.is_none_or(|b| b.is_ascii_digit())`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_is_variant_and
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![deny(clippy::manual_is_variant_and)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I expected to see this happen:

Instead, this happened:

```
   Compiling playground v0.0.1 (/playground)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.45s
     Running `target/debug/playground`
[src/main.rs:6:18] x.map(|b| b.is_ascii_digit()) != Some(true) = true
[src/main.rs:7:18] x.is_none_or(|b| b.is_ascii_digit()) = true
[src/main.rs:6:18] x.map(|b| b.is_ascii_digit()) != Some(true) = true
[src/main.rs:7:18] x.is_none_or(|b| b.is_ascii_digit()) = false

thread 'main' panicked at src/main.rs:8:9:
assertion `left == right` failed
  left: true
 right: false
```

### Version

```text
rustc 1.90.0-nightly (667787527 2025-07-02)
binary: rustc
commit-hash: 6677875279b560442a07a08d5119b4cd6b3c5593
commit-date: 2025-07-02
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.7
```

### Additional Labels

@rustbot label +I-suggestion-causes-bug

### PR DESCRIPTION
**Pull request by samueltardieu**
When comparing `x.map(func) == Some(bool_lit)`, the value of `bool_lit` was ignored, despite the fact that its value should determine the value of the proposed expression.

`func` can be either a closure or a path. For the latter, η-expansion will be used if needed to invert the result of the function call.

changelog: [`manual_is_variant_and`]: fix inverted suggestions that could lead to code with different semantics

Fixes rust-lang/rust-clippy#15202 

### Summary Notes

- [Beta-nomination](https://github.com/rust-lang/rust-clippy/pull/15206#issuecomment-3034006613) by [samueltardieu](https://github.com/samueltardieu)

*Managed by `@rustbot`—see [help](https://forge.rust-lang.org/triagebot/note.html) for details*

### CODE REVIEW

**Comment by samueltardieu** [comment]
@rustbot note Beta-nomination
@rustbot label +beta-nominated +I-suggestion-causes-bug

Those extensions to `manual_is_variant_and` were introduced in Rust 1.89, now in beta. They cause compilable suggestions with bogus semantics. It would be preferable that they don't reach the stable version.

**Comment by samueltardieu** [comment]
Lintcheck run shows one fixed diagnostic which would have caused a bug if applied as-is (in cargo sources).

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
It's pretty common for closure/function paths to be used and needing to be handled by clippy. We should maybe provide a `utils` function to handle it, no?

**Comment by samueltardieu** [comment]
> It's pretty common for closure/function paths to be used and needing to be handled by clippy. We should maybe provide a `utils` function to handle it, no?

Yes, probably, but usages may be different, for example here we need to invert the boolean result of the closure/function.

Btw, my latest push is only some cleanup to ease later maintenance, no change in functionality.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
> > It's pretty common for closure/function paths to be used and needing to be handled by clippy. We should maybe provide a `utils` function to handle it, no?
> 
> Yes, probably, but usages may be different, for example here we need to invert the boolean result of the closure/function.

Having a function to generate an enum closure/path would likely be a good first step and also likely to be useable everywhere. For the more specific parts, we can see afterwards.

**Comment by samueltardieu** [comment]
> Having a function to generate an enum closure/path would likely be a good first step and also likely to be useable everywhere. For the more specific parts, we can see afterwards.

An `Expr` variant for arbitrary expressions would also have to be added in addition to closure + path, as in:

```rust
fn make_func() -> impl Fn(u32) -> u32 {
    |x| x+1
}

fn main() {
    let a = Some(41);
    println!("{:?}", a.map(make_func()));
}
```

**Comment by samueltardieu** [comment]
Anyway, I agree with your proposal. However, I would like to see it implemented *after* this is merged, so that this can be backported to beta, rather than *before*, because the backport would be much more involved.

**Comment by GuillaumeGomez** [comment]
Not planning to do it right away. I plan to move your current enum, so I need this PR to be merge first. :3

File: clippy_lints/src/methods/manual_is_variant_and.rs [hunk 1]
```diff
@@ -62,54 +64,154 @@ pub(super) fn check(
...
+) {
+    let mut app = Applicability::MachineApplicable;
+    let recv = snippet_with_applicability(cx, recv.span, "_", &mut app);
+
+    let (invert_expr, method, invert_body) = match (flavor, op, in_some_or_ok) {
+        (Flavor::Option, Op::Eq, bool_cst) => (false, "is_some_and", !bool_cst),
+        (Flavor::Option, Op::Ne, bool_cst) => (false, "is_none_or", bool_cst),
+        (Flavor::Result, Op::Eq, bool_cst) => (false, "is_ok_and", !bool_cst),
+        (Flavor::Result, Op::Ne, bool_cst) => (true, "is_ok_and", !bool_cst),
+    };
```
Comment (y21) [inline clippy_lints/src/methods/manual_is_variant_and.rs]: Nit: since this `bool_cst` is never really matched and just rebound here, could use the variable directly in the tuple

```suggestion
    let (invert_expr, method, invert_body) = match (flavor, op) {
        (Flavor::Option, Op::Eq) => (false, "is_some_and", !in_some_or_ok),
        (Flavor::Option, Op::Ne) => (false, "is_none_or", in_some_or_ok),
        (Flavor::Result, Op::Eq) => (false, "is_ok_and", !in_some_or_ok),
        (Flavor::Result, Op::Ne) => (true, "is_ok_and", !in_some_or_ok),
    };
```

File: tests/ui/manual_is_variant_and.stderr [hunk 2]
```diff
@@ -126,5 +126,101 @@ error: called `map(<f>).unwrap_or_default()` on a `Result` value
...
+  --> tests/ui/manual_is_variant_and.rs:227:18
+   |
+LL |         let a1 = b.map(iad) != Ok(true);
+   |                  ^^^^^^^^^^^^^^^^^^^^^^ help: use: `!b.is_ok_and(iad)`
+
+error: called `.map() != Ok()`
+  --> tests/ui/manual_is_variant_and.rs:232:18
+   |
+LL |         let a1 = b.map(iad) != Ok(false);
+   |                  ^^^^^^^^^^^^^^^^^^^^^^^ help: use: `!b.is_ok_and(|x| !iad(x))`
```
Comment (y21) [inline tests/ui/manual_is_variant_and.stderr:223]: I have to say this case stretches the "readability" point of the lint's suggestion a little bit IMO 😄 This took me a bit to mentally parse and prove that it's equivalent. The error message of the lint is also kinda terse and doesn't add any extra information.

But, those are pre-existing issues I guess, so not something we have to figure out here

**Review by y21 — APPROVED** [review]

File: clippy_lints/src/methods/manual_is_variant_and.rs (hunk 1 above)
Comment (samueltardieu) [reply clippy_lints/src/methods/manual_is_variant_and.rs]: Thanks for catching this, this is due to several iterations on this lint. Done.

**Comment by samueltardieu** [comment]
@y21 I made the change you requested, is it ok to merge it so that it gets synced tomorrow? I'd like it to get a larger test base since it should be backported in beta before the release.

**Comment by y21** [comment]
Sorry for the wait, yeah looks good to me now 👍

**Comment by flip1995** [comment]
This is too big of a PR to backport to beta. Instead, in the beta backport PR I'll move this lint to nursery.

**Comment by samueltardieu** [comment]
> This is too big of a PR to backport to beta. Instead, in the beta backport PR I'll move this lint to nursery.

I understand, but this is unfortunate. Wouldn't it be possible to revert the problematic commit which introduced the problem instead, so that we don't put the whole lint into nursery?

That would be commit 763a7bd1

**Comment by flip1995** [comment]
I'll try. If the revert goes through cleanly, I'll do that instead.

**Comment by flip1995** [comment]
https://github.com/rust-lang/rust/pull/144742
