### PR TITLE
Do not trigger `redundant_pub_crate` in external macros

### LINKED ISSUE #10636: arithmetic_side_effects, redundant_pub_crate should not warn external macros
### Summary

arithmetic_side_effects and redundant_pub_crate currently warns on code generated by external macros (in my case `tokio::select!`).

### Lint Name

arithmetic_side_effects, redundant_pub_crate

### Reproducer

I tried this code:

```rust
#![deny(clippy::arithmetic_side_effects, clippy::redundant_pub_crate)]

extern crate tokio; // 1.27.0

#[tokio::main]
async fn main() {
    let (_, mut receiver) = tokio::sync::mpsc::channel(1);
    
    loop {
        tokio::select! {
            Some(()) = receiver.recv() => {}
            else => break,
        }
    }
}
```

I saw this happen:

```
error: pub(crate) enum inside private module
  --> src/main.rs:10:9
   |
10 | /         tokio::select! {
11 | |             Some(()) = receiver.recv() => {}
12 | |             else => break,
13 | |         }
   | |_________^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pub_crate
note: the lint level is defined here
  --> src/main.rs:1:42
   |
1  | #![deny(clippy::arithmetic_side_effects, clippy::redundant_pub_crate)]
   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: this error originates in the macro `$crate::select_priv_declare_output_enum` which comes from the expansion of the macro `tokio::select` (in Nightly builds, run with -Z macro-backtrace for more info)

error: pub(crate) type alias inside private module
  --> src/main.rs:10:9
   |
10 | /         tokio::select! {
11 | |             Some(()) = receiver.recv() => {}
12 | |             else => break,
13 | |         }
   | |_________^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pub_crate
   = note: this error originates in the macro `$crate::select_priv_declare_output_enum` which comes from the expansion of the macro `tokio::select` (in Nightly builds, run with -Z macro-backtrace for more info)

error: arithmetic operation that can potentially result in unexpected side-effects
  --> src/main.rs:10:9
   |
10 | /         tokio::select! {
11 | |             Some(()) = receiver.recv() => {}
12 | |             else => break,
13 | |         }
   | |_________^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#arithmetic_side_effects
note: the lint level is defined here
  --> src/main.rs:1:9
   |
1  | #![deny(clippy::arithmetic_side_effects, clippy::redundant_pub_crate)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: this error originates in the macro `$crate::select` which comes from the expansion of the macro `tokio::select` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `playground` (bin "playground") due to 3 previous errors
```

I expected to see this happen: compile without errors.

### Version

```text
rustc 1.68.2 (9eb3afe9e 2023-03-27)
binary: rustc
commit-hash: 9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0
commit-date: 2023-03-27
host: aarch64-apple-darwin
release: 1.68.2
LLVM version: 15.0.6
```

### Additional Labels

_No response_

### LINKED ISSUE #12213: Usage of `tokio::select!` triggers `redundant_pub_crate` (nursery)
### Summary

On nursery lint level, any usage of `tokio::select!` wrongly triggers the `redundant_pub_crate` lint.

### Lint Name

redundant_pub_crate

### Reproducer

I tried this code:

```rust
use std::future::Future;
use tokio::select;

pub async fn selects(number: impl Future<Output = i32>, boolean: impl Future<Output = bool>) {
    select! {
        n = number => {
            println!("A number: {n}");
        },
        b = boolean => {
            println!("A boolean: {b}");
        }
    }
}
```

I saw this happen:
```
  --> src\lib.rs:5:5
   |
5  | /     select! {
6  | |         n = number => {
7  | |             println!("A number: {n}");
8  | |         },
...  |
11 | |         }
12 | |     }
   | |_____^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pub_crate
   = note: `-W clippy::redundant-pub-crate` implied by `-W clippy::nursery`
   = help: to override `-W clippy::nursery` add `#[allow(clippy::redundant_pub_crate)]`
   = note: this warning originates in the macro `$crate::select_priv_declare_output_enum` which comes from the expansion of the macro `select` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I expected to see this happen: no lint triggered on `select!`.

### Version

```text
rustc 1.77.0-nightly (5d3d3479d 2024-01-23)
binary: rustc
commit-hash: 5d3d3479d774754856db2db3e439dfb88ef3c52f
commit-date: 2024-01-23
host: x86_64-pc-windows-msvc
release: 1.77.0-nightly
LLVM version: 17.0.6
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by samueltardieu**
Some widely used crates, such as `pin-project-lite`, make use of a `pub(crate)` construct in a private module inside a public macro. This makes unrelated project trigger the lint.

There is also an unfortunate situation for Clippy itself: when a new version of `pin-project-lite` or similar lint-trigerring crates is released, those lints which can be found in hundreds of occurrences in dependent crates will change, and appear as diffs in unrelated Clippy PR because the base lintcheck run will be cached with the ancient release of the crates. We currently have the situation [here](https://github.com/rust-lang/rust-clippy/actions/runs/12635410895?pr=13851#user-content-redundant-pub-crate-removed), which 219 lints removed and 219 lints added because of a `pin-project-lite` version change between runs, and the fact that `redundant_pub_crate` triggers on external macros.

Also:
- Fix #10636
- Fix #12213

changelog: [`redundant_pub_crate`]: do not trigger on external macros

### CODE REVIEW

**Comment by samueltardieu** [comment]
Wow, 244 instances of the lint removed in [the current PR lintcheck run](https://github.com/rust-lang/rust-clippy/actions/runs/12636434500?pr=13952#user-content-redundant-pub-crate-changed).

**Review by Centri3 — APPROVED** [review]

File: tests/ui/redundant_pub_crate.rs [hunk 1]
```diff
@@ -113,4 +114,8 @@ mod issue_8732 {
     pub(crate) use some_macro; // ok: macro exports are exempt
 }
 
+mod do_not_lint_in_external_macros {
+    external_macro_pub_crate::ext_macro!();
```
Comment (Centri3) [inline tests/ui/redundant_pub_crate.rs:118]: Oh actually, do note you can use the `external!` macro for this: `//@aux-build:proc_macros.rs`

Comment (samueltardieu) [reply tests/ui/redundant_pub_crate.rs]: Neat, I didn't know this. Done.
