### PR TITLE
Fix `literal_string_with_formatting_args` lint emitted when it should not

### LINKED ISSUE #13885: literal_string_with_formatting_args false positive on test
### Summary

See reproducer below. I can't reproduce this in playground because it doesn't run clippy with `--all-targets`.

### Lint Name

literal_string_with_formatting_args

### Reproducer

I tried this code:

```rust
pub fn parse(_: &str) -> Result<Vec<String>, String> {
    unimplemented!()
}

#[test]
fn test_parse() {
    assert!(parse(
        #[allow(clippy::literal_string_with_formatting_args)]
        "foo {:}"
    )
    .is_err());
}
```

I saw this happen:

```shell
$ cargo +nightly clippy --all-targets
warning: this looks like a formatting argument but it is not part of a formatting macro
 --> src/lib.rs:5:6
  |
5 |     #[test]
  |      ^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#literal_string_with_formatting_args
  = note: `#[warn(clippy::literal_string_with_formatting_args)]` on by default
```

I expected to see this happen:
No warnings.

### Version

```text
rustc 1.85.0-nightly (917bfa784 2024-12-26)
binary: rustc
commit-hash: 917bfa78478cbcc77406e5ea37b24c3eedefacf4
commit-date: 2024-12-26
host: aarch64-apple-darwin
release: 1.85.0-nightly
LLVM version: 19.1.6
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #13885.
Fixes https://github.com/rust-lang/rust-clippy/issues/14007.

Problem was that I forgot to check whether or not the `span` was a "real" one. Because if not, then it starts pointing to pretty much only wrong content, hence the problems we saw with clippy linting on `clippy.toml`.

changelog: Fix `literal_string_with_formatting_args` lint emitted when it should not 

r? @samueltardieu

### CODE REVIEW

File: tests/ui/literal_string_with_formatting_arg.rs [hunk 1]
```diff
@@ -1,6 +1,24 @@
...
+    assert!(
+        parse(
+            #[allow(clippy::literal_string_with_formatting_args)]
+            "foo {:}"
+        )
+        .is_err()
+    );
+    let value = 0;
+    assert!(format!("{value}").is_ascii());
+}
```
Comment (samueltardieu) [inline tests/ui/literal_string_with_formatting_arg.rs:20]: Could you also add another true positive test such as

```suggestion
    assert!("{value}".is_ascii());
}
```

so that we can check that the lint properly triggers in non-formatting-macro arguments?

**Review by samueltardieu — APPROVED** [review]
LGTM, with the addition of a non-formatting true positive macro test case.

You should reroll the dice as I don't have the privilege to approve this patch.

r?

**Comment by samueltardieu** [comment]
r? clippy

**Comment by profetia** [comment]
Can you check if [this case](https://github.com/rust-lang/rust-clippy/issues/13885#issuecomment-2565076770) works? I think just checking dummy is not enough, that is why I switched to checking the enclosing exprs in #13898

**Comment by samueltardieu** [comment]
> Can you check if [this case](https://github.com/rust-lang/rust-clippy/issues/13885#issuecomment-2565076770) works? I think just checking dummy is not enough, that is why I switched to checking the enclosing exprs in #13898

It still triggers for me indeed:

```
warning: this looks like a formatting argument but it is not part of a formatting macro
 --> {value}.rs:7:6
  |
7 |     dbg!("something");
  |      ^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#literal_string_with_formatting_args
  = note: `#[warn(clippy::literal_string_with_formatting_args)]` on by default
```

**Comment by y21** [comment]
Nominating for beta backport because the lint is on beta now and the false positive leads to pretty confusing warnings.

@rustbot label +beta-nominated

**Comment by GuillaumeGomez** [comment]
Changelog CI also passed. :)

File: tests/ui/{literal_string_with_formatting_args}.rs [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+// The `dbg` macro generates a literal with the name of the current file, so
+// we need to ensure the lint is not emitted in this case.
+
+#![crate_name = "foo"]
+#![allow(unused)]
+#![warn(clippy::literal_string_with_formatting_args)]
+
+fn another_bad() {
+    let literal_string_with_formatting_args = 0;
+    dbg!("something");
```
[the remark this answers is not in the document]
Comment (y21) [reply tests/ui/{literal_string_with_formatting_args}.rs:11]: Ah, I see what's happening. Clippy sets `-Zflatten_format_args=no`, which changes the default behavior of how format args are lowered and only *that* one has this non-macro span. Adding the flag makes it repro on godbolt and shows a root context span for the file name string.
```
Lit(
    Spanned {
        node: Str(
            "/app/example.rs",
            Cooked,
        ),
        span: /app/example.rs:2:5: 2:22 (#0),
    },
)
```
Maybe add to the comment that clippy sets this flag and only with that flag does it have a non-macro span which gets around the `from_expansion` check, in case anyone wants to look into this in the future and doesn't have to go down this rabbit hole?

[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply tests/ui/{literal_string_with_formatting_args}.rs:11]: I looked into it but couldn't figure out why it didn't work. Thanks a lot for the detailed explanations! Adding it as a comment.

File: clippy_lints/src/literal_string_with_formatting_args.rs [hunk 3]
```diff
@@ -95,7 +96,15 @@ impl LateLintPass<'_> for LiteralStringWithFormattingArg {
...
             };
+            let Some(snippet) = snippet_opt(cx, expr.span) else {
+                return;
+            };
             let fmt_str = symbol.as_str();
+            // If the literal has been generated by the macro, the snippet should not contain it,
+            // allowing us to skip it.
+            if !snippet.contains(fmt_str) {
+                return;
+            }
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply clippy_lints/src/literal_string_with_formatting_args.rs]: Not sure why `is_from_proc_macro` didn't work last time I tried but this time it behaves as expected, so switching back to it.

**Comment by samueltardieu** [comment]
As it is currently, this does not fix #14007.

**Comment by GuillaumeGomez** [comment]
Fixed #14007 as well.

**Comment by Alexendoo** [comment]
Removing the beta nomination in favour of https://github.com/rust-lang/rust-clippy/pull/14014 since backporting would no longer be urgent

File: clippy_lints/src/literal_string_with_formatting_args.rs [hunk 4]
```diff
@@ -124,7 +128,11 @@ impl LateLintPass<'_> for LiteralStringWithFormattingArg {
                     pos.start += diff_len;
                     pos.end += diff_len;
 
-                    let start = fmt_str[..pos.start].rfind('{').unwrap_or(pos.start);
+                    let mut start = pos.start;
+                    while start < fmt_str.len() && !fmt_str.is_char_boundary(start) {
+                        start += 1;
+                    }
+                    let start = fmt_str[..start].rfind('{').unwrap_or(start);
```
Comment (y21) [inline clippy_lints/src/literal_string_with_formatting_args.rs:135]: Is this the same as `fmt_str[..fmt_str.ceil_char_boundary(pos.start)].rfind('{')`?

Comment (y21) [reply clippy_lints/src/literal_string_with_formatting_args.rs:135]: For what it's worth, it looks like the format parser offsets all spans by 1 (presumably because it's relative to the `"` quote), so that's what causes the index to be in the middle of a character sometimes. Just doing `pos.start - 1` instead of `pos.start` on the old deleted line (to undo the parser's offset) should fix this too as far as I can tell, but this over-conservative approach should be fine too I guess

**Comment by y21** [comment]
I've been reading through the surrounding code to get a better understanding of this lint and (somewhat tangentially related to the ICE) I'm wondering why we continue parsing after encountering parser errors? It seems to be adding a fair amount of complexity (remapping the spans, reconstructing parsers) while at the same time I'm not sure if it really makes sense to lint strings that failed to parse in the first place. It feels unlikely that the user meant to write a format string if it can't parse as one anyway? Maybe there is a good reason for this though and I don't know about it!

**Comment by GuillaumeGomez** [comment]
We need to remap the spans at every `{` we encounter, whether or not it's valid. For example if you have `"{} bla {}"`, we still need to remap the spans after the first `{}`.

As for why continuing after an error, it's mainly because you can do typos and if this is the case, still expect formatting afterwards (like in `panic`) and not realizing that:

1. There is no formatting.
2. There is a typo.

Does my reasoning makes sense to you?

File: clippy_lints/src/literal_string_with_formatting_args.rs (hunk 4 above)
Comment (GuillaumeGomez) [reply clippy_lints/src/literal_string_with_formatting_args.rs:135]: I'd prefer to keep it over-conservative if you don't mind. :wink:

**Comment by GuillaumeGomez** [comment]
Is there anything else to be done here?

**Review by y21 — APPROVED** [review]

**Comment by larseggert** [comment]
Should this be fixed with 1.85.0? I still see this:
```
cargo clippy --all-targets --no-default-features -- -D warnings
...
error: this looks like a formatting argument but it is not part of a formatting macro
 --> /Users/lars/Documents/Code/neqo/.clippy.toml:2:68
  |
2 |     { path = "std::slice::from_raw_parts", reason = "see null_safe_slice" }
  |                                                                    ^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#literal_string_with_formatting_args
  = note: `-D clippy::literal-string-with-formatting-args` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(clippy::literal_string_with_formatting_args)]`

error: could not compile `neqo-transport` (lib test) due to 1 previous error
```
with https://github.com/mozilla/neqo. (Example: https://github.com/mozilla/neqo/actions/runs/13468547315/job/37638898254?pr=2444#step:6:512)

**Comment by y21** [comment]
*This* fix will be in 1.87.0. But there was another PR that downgraded this lint's category to nursery (#14014) which was backported and should be on stable, so you shouldn't really see this unless you explicitly enabled the lint.

Do you have something like `#![warn(clippy::literal_string_with_formatting_args)]` or `#![warn(clippy::nursery)]` in your crate?

**Comment by larseggert** [comment]
Yes, we have enabled `nursery`. Thanks for the pointer, will work around it!
