### PR TITLE
Fix #4033 search_is_some

### LINKED ISSUE #4033: search_is_some fixit hint suggests invalid code
`clippy 0.0.212 (9897442 2019-04-23)`

in this code
````rust
    // https://docs.rs/walkdir/2.2.7/walkdir/#example-skip-hidden-files-and-directories-on-unix
    fn is_git(entry: &walkdir::DirEntry) -> bool {
        entry
            .path()
            .components()
            .find(|&path_elm| path_elm == std::path::Component::Normal(OsStr::new(".git")))
            .is_some()
    }
````
clippy suggests:
````
warning: called `is_some()` after searching an `Iterator` with find. This is more succinctly expressed by calling `any()`.
   --> src/main.rs:352:9
    |
352 | /         entry
353 | |             .path()
354 | |             .components()
355 | |             .find(|&path_elm| path_elm == std::path::Component::Normal(OsStr::new(".git")))
356 | |             .is_some()
    | |______________________^
    |
    = note: #[warn(clippy::search_is_some)] on by default
    = note: replace `find(|&path_elm| path_elm == std::path::Component::Normal(OsStr::new(".git"))).is_some()` with `any(|&path_elm| path_elm == std::path::Component::Normal(OsStr::new(".git")))`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#search_is_some
````

if I apply the suggestion
````rust
    fn is_git(entry: &walkdir::DirEntry) -> bool {
        entry
            .path()
            .components()
            .any(|&path_elm| path_elm == std::path::Component::Normal(OsStr::new(".git")))
    }
````
the code no longer compiles
````
    Checking raca v0.1.0 (/home/matthias/vcs/github/raca)
error[E0308]: mismatched types
   --> src/main.rs:355:19
    |
355 |             .any(|&path_elm| path_elm == std::path::Component::Normal(OsStr::new(".git")))
    |                   ^^^^^^^^^ expected enum `std::path::Component`, found reference
    |
    = note: expected type `std::path::Component<'_>`
               found type `&_`
    = help: did you mean `path_elm: &std::path::Component<'_>`?

error: aborting due to previous error
````

The correct code is
````rust
.any(|path_elm| ...
````
instead of
````rust
.any(|&path_elm| ...
````

### PR DESCRIPTION
**Pull request by airt**
Fixes #4033.

Suggest `any(|x| ..)` instead of `any(|&x| ..)` for `find(|&x| ..).is_some()` (Lint [search_is_some](https://rust-lang.github.io/rust-clippy/master/index.html#search_is_some))

FnDecl of `find`:

```rust
fn find<P>(&mut self, mut p: P) -> Option<Self::Item> where
    P: FnMut(&Self::Item) -> bool
```

FnDecl of `any`:

```rust
fn any<F>(&mut self, mut f: F) -> bool where
    F: FnMut(Self::Item) -> bool
```

If match on `|&_|` in closure of `find`, only use `|_|` in the suggestion.

PS. It's the first time that I have used the `hir` API, please correct me if there is any mistake 😺

### CODE REVIEW

File: clippy_lints/src/methods/mod.rs [hunk 1]
```diff
@@ -1975,6 +1975,19 @@ fn lint_search_is_some<'a, 'tcx>(
         );
         let search_snippet = snippet(cx, search_args[1].span, "..");
         if search_snippet.lines().count() <= 1 {
+            // suggest `any(|x| ..)` instead of `any(|&x| ..)` for `find(|&x| ..).is_some()`
+            let any_search_snippet =
+                if_chain! {
+                    if search_method == "find";
+                    if let hir::ExprKind::Closure(_, _, body_id, ..) = search_args[1].node;
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: This may panic for `find` functions with 0 or 1 argument. I don't really know if this is possible at this point, but better save than sorry:
```suggestion
                    if let Some(arg) = search_args.get(1);
                    if let hir::ExprKind::Closure(_, _, body_id, ..) = arg.node;
```

File: clippy_lints/src/methods/mod.rs [hunk 2]
```diff
@@ -1975,6 +1975,19 @@ fn lint_search_is_some<'a, 'tcx>(
...
+                    let closure_body = cx.tcx.hir().body(body_id);
+                    if let hir::PatKind::Ref(..) = closure_body.arguments[0].pat.node;
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: Also here:
```suggestion
                    if let Some(arg) = closure_body.arguments.get(0);
                    if let hir::PatKind::Ref(..) = arg.pat.node;
```

**Comment by flip1995** [comment]
Also rustfmt. Everything else LGTM

File: clippy_lints/src/methods/mod.rs (hunk 1 above)
Comment (airt) [reply clippy_lints/src/methods/mod.rs]: Thank you 😸

We can ensure the caller of search is an Iterator, so the `search_args[1]` should be fine:

https://github.com/rust-lang/rust-clippy/blob/c3fde34fd53a6eed89dd30064b1985acf39f7f07/clippy_lints/src/methods/mod.rs#L1969-L1977

File: clippy_lints/src/methods/mod.rs (hunk 2 above)
Comment (airt) [reply clippy_lints/src/methods/mod.rs]: Fixed

**Comment by flip1995** [comment]
Thanks!

@bors r+
