### PR TITLE
Do not panic when analyzing the malformed origin of a format string

### LINKED ISSUE #10148: 'rustc' panicked at 'EscapeOnlyChar'
Hi everyone, 
It looks like I have unintendedly written code that breaks clippy in my `osrm_client` crate (repo here: https://github.com/xgillard/osrm_client).  The problem occured on my machine where I am using rust stable. If that helps, here are some more details on the exact config being used.
* OS: OSX Ventura
* cargo 1.66.0  (d65d197ad 2022-11-15)
* rustc 1.66.0  (69f9c33d7 2022-12-12)
* clippy 0.1.66 (69f9c33d 2022-12-12)

When I try to use clippy to lint my code, it breaks with the following backtrace:

```
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <clippy_utils::macros::FormatString>::new::{closure#2}
   3: rustc_lexer::unescape::unescape_literal::<<clippy_utils::macros::FormatString>::new::{closure#2}>
   4: <clippy_utils::macros::FormatString>::new
   5: <clippy_utils::macros::FormatArgsExpn>::parse
   6: <clippy_lints::format_args::FormatArgs as rustc_lint::passes::LateLintPass>::check_expr
   7: <rustc_lint::late::LateLintPassObjects as rustc_lint::passes::LateLintPass>::check_expr
   8: rustc_hir::intravisit::walk_expr::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
   9: rustc_hir::intravisit::walk_arm::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  10: rustc_hir::intravisit::walk_expr::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  11: rustc_hir::intravisit::walk_block::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  12: rustc_hir::intravisit::walk_expr::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  13: rustc_hir::intravisit::walk_body::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  14: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_body
  15: rustc_hir::intravisit::walk_impl_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  16: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_impl_item
  17: rustc_hir::intravisit::walk_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  18: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  19: rustc_hir::intravisit::walk_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  20: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  21: rustc_hir::intravisit::walk_item::<rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects>>
  22: <rustc_lint::late::LateContextAndPass<rustc_lint::late::LateLintPassObjects> as rustc_hir::intravisit::Visitor>::visit_nested_item
  23: rustc_lint::late::late_lint_pass_crate::<rustc_lint::late::LateLintPassObjects>
  24: rustc_lint::late::late_lint_crate::<rustc_lint::BuiltinCombinedLateLintPass>
  25: rustc_data_structures::sync::join::<rustc_lint::late::check_crate<rustc_lint::BuiltinCombinedLateLintPass, rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#0}, rustc_lint::late::check_crate<rustc_lint::BuiltinCombinedLateLintPass, rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}, (), ()>
  26: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  27: <core::panic::unwind_safe::AssertUnwindSafe<rustc_interface::passes::analysis::{closure#5}::{closure#1}> as core::ops::function::FnOnce<()>>::call_once
  28: <rustc_session::session::Session>::time::<(), rustc_interface::passes::analysis::{closure#5}>
  29: rustc_interface::passes::analysis
  30: <rustc_query_system::dep_graph::graph::DepGraph<rustc_middle::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle::ty::context::TyCtxt, (), core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  31: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::plumbing::QueryCtxt, rustc_query_system::query::caches::DefaultCache<(), core::result::Result<(), rustc_errors::ErrorGuaranteed>>>
  32: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::analysis, rustc_query_impl::plumbing::QueryCtxt>
  33: <rustc_interface::passes::QueryContext>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}::{closure#3}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
  34: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}::{closure#1}>
  35: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.66 (69f9c33d 2022-12-12)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `osrm_client`
```

### PR DESCRIPTION
**Pull request by samueltardieu**
Fixes #10148. This will trigger only when generating format strings while accepting weird things in a procedural macro and setting the span to something which is not a string.

changelog: none

### CODE REVIEW

**Comment by Alexendoo** [comment]
Thanks!

We have a nice utility for testing proc macro weirdness, you can add

```rust
// aux-build: proc_macro_with_span.rs

#[macro_use]
extern crate proc_macro_with_span;
```

to `tests/ui/format.rs` or a similar file, and test it with

```rust
with_span!(""something format!(""));
```

**Comment by samueltardieu** [comment]
> We have a nice utility for testing proc macro weirdness

Nice indeed! I've added a test, without even having to write a proc_macro, confirmed panicking before this patch.

File: tests/ui/format.rs [hunk 1]
```diff
@@ -89,4 +92,7 @@ fn main() {
     let _ = format!("{abc}");
     let xx = "xx";
     let _ = format!("{xx}");
+
+    // Issue #10148
+    println!(proc_macro_with_span::with_span!(""something ""));
```
Comment (Alexendoo) [inline tests/ui/format.rs:97]:
```suggestion
    println!(proc_macro_with_span::with_span!(""something format!("")));
```

Comment (Alexendoo) [reply tests/ui/format.rs:97]: Oh wait, println like that works too nevermind

**Review by Alexendoo — APPROVED** [review]

**Comment by Alexendoo** [comment]
Great, thanks again!

@bors r+
