### PR TITLE
Fixes shadow_same's false positive for #7915

### LINKED ISSUE #7915: `shadow_same` is just plain wrong in an async context
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=bb8b58e91b2a00d51cd67875ebce1da6

**Code**

```rust
#![deny(clippy::shadow_same)]

pub async fn foo(_a: i32) {
}
```

**Output**

```
error: `_a` is shadowed by itself in `_a
```

### PR DESCRIPTION
**Pull request by surechen**
Fix shadow_same's false positive for async function's params(Fixes #7915):

Example Code:
```rust
#![deny(clippy::shadow_same)]

pub async fn foo(_a: i32) {
}
```
Output:
```
error: `_a` is shadowed by itself in `_a
```

Hir:
```rust
pub async fn foo(_a: i32)
 ->
     /*impl Trait*/ #[lang = "from_generator"](move |mut _task_context|
                                                   {
                                                       let _a = _a;
                                                       { let _t = { }; _t }
                                                   })
```

Skip checking async function's params.

changelog: Fix shadow_same's false positive for async function's params

### CODE REVIEW

File: tests/ui/shadow.rs [hunk 1]
```diff
@@ -79,4 +79,10 @@ fn question_mark() -> Option<()> {
     None
 }
 
+pub async fn foo1(_a: i32) {}
+
+pub async fn foo2(_a: i32, _b: i64) {
+    let _b = _a;
```
Comment (giraffate) [inline tests/ui/shadow.rs:85]: I think this should be warned in `shadow_unrelated`.

**Review by giraffate — COMMENTED** [review]
It might be simpler to check `DesugaringKind`. This may help us:
https://github.com/rust-lang/rust-clippy/pull/7174.

**Comment by surechen** [comment]
> It might be simpler to check `DesugaringKind`. This may help us: #7174.
Thank you very much.  By checking [DesugaringKind] is more concise and more accurate than my method.

**Comment by giraffate** [comment]
@bors r+

It looks good, thanks!
