### PR TITLE
Skip `use_self` inside macro expansions of a `impl Self` block

### LINKED ISSUE #13092: `use_self` false positive on outer items
### Summary

`use_self` doesn't work with outer items and the suggestion fails to compile.

### Lint Name

use_self

### Reproducer

I tried this code:

```rust
#![warn(clippy::use_self)]

#[derive(Default)]
struct MyStruct {}

impl MyStruct {
    thread_local! {
        static SPECIAL: RefCell<MyStruct> = RefCell::default();
    }
}
```

This warns on use_self, but attempting to change the signature to RefCell<Self> causes:

```
can't use `Self` from outer item
refer to the type directly here instead (rustc E0401)
```

### Version

```text
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by tesuji**
changelog: [`use_self`] Skip if inside macro expansions of a `impl Self` block
Fixes #13092.
r? Alexendoo

### CODE REVIEW

File: clippy_lints/src/use_self.rs [hunk 1]
```diff
@@ -190,20 +191,23 @@ impl<'tcx> LateLintPass<'tcx> for UseSelf {
...
-        // we can use `cx.typeck_results.node_type(..)` to get the `ty::Ty` from a `hir::Ty`.
-        // However the `node_type()` method can *only* be called in bodies.
-        if let Some(&mut StackItem::Check { ref mut in_body, .. }) = self.stack.last_mut() {
-            *in_body = in_body.saturating_add(1);
+        // Checking const items of `impl Self` blocks in which `std::thread_local!` expands into.
+        // HACK: `std::thread_local_inner` sometimes clears `macro_backtrace` of types in `check_ty`.
+        // To work around this problem, and assume that `LateLintPass` walks recursively from
+        // `check_impl_item` into `check_ty`, `check_expr`,etc. We encode the state when we enter
+        // this const item of `thread_local!` macro. Just remember to remove this state again in
+        // `check_impl_item_post`.
```
Comment (Alexendoo) [inline clippy_lints/src/use_self.rs:199]: `thread_local_inner` isn't behaving uniquely here, regular `macro_rules` would exhibit the same behaviour so we should probably skip any impl item that's from an expansion. e.g.

```rust
macro_rules! macro_inner_item {
    ($ty:ty) => {
        fn foo(_: $ty) {
            fn inner(_: $ty) {}
        }
    };
}

struct MyStruct;

impl MyStruct {
    macro_inner_item!(MyStruct);
}
```

**Comment by tesuji** [comment]
Thank you for your insightful reviews!
Should be ready for another look.

File: clippy_lints/src/use_self.rs [hunk 2]
```diff
@@ -192,18 +198,9 @@ impl<'tcx> LateLintPass<'tcx> for UseSelf {
...
-    }
-
-    fn check_body_post(&mut self, _: &LateContext<'_>, _: &hir::Body<'_>) {
-        if let Some(&mut StackItem::Check { ref mut in_body, .. }) = self.stack.last_mut() {
-            *in_body = in_body.saturating_sub(1);
+    fn check_impl_item_post(&mut self, _: &LateContext<'_>, _: &hir::ImplItem<'_>) {
+        if let Some(StackItem::NoCheck) = self.stack.last() {
+            self.stack.pop();
         }
     }
```
Comment (Alexendoo) [inline clippy_lints/src/use_self.rs:205]: Sorry for the delay!

We'll need to also check `if impl_item.span.from_expansion()` here so that we only pop entries we added in `check_impl_item`

Without it we would run into

```rust
struct A;

impl A {
    fn a() {
        struct B;

        impl Iterator for &B { // pushes a NoCheck
            type Item = A; // Pops the NoCheck
        
            fn next(&mut self) -> Option<A> { // Lints A -> Self
                Some(A)
            }
        }
    }
}
```

Could you add a test for this too

File: clippy_lints/src/use_self.rs [hunk 3]
```diff
@@ -137,6 +135,14 @@ impl<'tcx> LateLintPass<'tcx> for UseSelf {
...
 
     fn check_impl_item(&mut self, cx: &LateContext<'_>, impl_item: &hir::ImplItem<'_>) {
+        // Checking items of `impl Self` blocks in which macro expands into.
+        // HACK: Nested macros sometimes clears `macro_backtrace` of types in `check_ty`.
+        // To work around this problem, we check if this impl_item is from macro expansions.
+        // Just remember to remove this state again in `check_impl_item_post`.
```
Comment (Alexendoo) [inline clippy_lints/src/use_self.rs:141]: I'd say remove the `HACK`/`macro_backtrace` parts as macros are working as intended here, the issue isn't that a span's context is being cleared but that the same token is being used in two different contexts

File: clippy_lints/src/use_self.rs (hunk 2 above)
Comment (Alexendoo) [reply clippy_lints/src/use_self.rs]: Anywhere in `tests/ui/use_self.rs` would be fine

Comment (tesuji) [reply clippy_lints/src/use_self.rs]: Done.

**Review by Alexendoo — APPROVED** [review]
Thanks! Looks good to go with a rebase

**Review by Alexendoo — APPROVED** [review]
Thank you!
