### PR TITLE
tabs_in_doc_comments: Fix ICE due to char indexing

### LINKED ISSUE #5835: ICE: Clippy panics, during constructing a span in `TabsInDocComments::check_attribute`
env

- clippy: `clippy 0.0.212 (5c1f21c 2020-07-13)`
- rustc : `rustc 1.45.0 (5c1f21c3b 2020-07-13)`
- os:  `Mint 18.3 sylvia`

```bash
 $ cargo clippy --all-targets --all-features -- -D warnings
    Checking rtb-rust v0.1.0 (/home/hello/rtb-rust)
thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', src/librustc_span/source_map.rs:906:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (5c1f21c 2020-07-13)

thread 'rustc' panicked at 'assertion failed: bpos.to_u32() >= mbc.pos.to_u32() + mbc.bytes as u32', src/librustc_span/source_map.rs:906:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (5c1f21c 2020-07-13)

error: could not compile `rtb-rust`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### PR DESCRIPTION
**Pull request by phansch**
This is a quick-fix for an ICE in `tabs_in_doc_comments`. The problem
was that we we're indexing into possibly multi-byte characters, such as '位'.

More specifically `get_chunks_of_tabs` was returning indices into
multi-byte characters. Those were passed on to a `Span` creation that
then caused the ICE.

This fix makes sure that we don't return indices that point inside a
multi-byte character. *However*, we are still iterating over unicode
codepoints, not grapheme clusters. So a seemingly single character like y̆ ,
which actually consists of two codepoints, will probably still cause
incorrect spans in the output. But I don't think we handle those cases
anywhere in Clippy currently?

Fixes #5835
 
changelog: Fix ICE in `tabs_in_doc_comments`

### CODE REVIEW

**Comment by phansch** [comment]
Oh, I just realized that we _do_ use [unicode_normalization](https://github.com/unicode-rs/unicode-normalization) in Clippy, so I may just try and fix the grapheme handling as well.

File: clippy_lints/src/tabs_in_doc_comments.rs [hunk 1]
```diff
@@ -104,30 +104,29 @@ fn get_chunks_of_tabs(the_str: &str) -> Vec<(u32, u32)> {
     // tracker to decide if the last group of tabs is not closed by a non-tab character
     let mut is_active = false;
 
-    let chars_array: Vec<_> = the_str.chars().collect();
+    let char_indices: Vec<_> = the_str.char_indices().collect();
 
-    if chars_array == vec!['\t'] {
+    if char_indices.len() == 1 && char_indices.first().unwrap().1 == '\t' {
```
Comment (flip1995) [inline clippy_lints/src/tabs_in_doc_comments.rs:109]: Can you use pattern matching here?

```suggestion
    if let &[(_, '\t')] = &char_indices {
```

+/- compiler/type errors.

File: clippy_lints/src/tabs_in_doc_comments.rs [hunk 2]
```diff
@@ -137,7 +136,7 @@ fn get_chunks_of_tabs(the_str: &str) -> Vec<(u32, u32)> {
     if is_active {
         spans.push((
             current_start,
-            u32::try_from(the_str.chars().count()).expect(line_length_way_to_long),
+            u32::try_from(char_indices.last().unwrap().0 + 1).expect(line_length_way_to_long),
```
Comment (flip1995) [inline clippy_lints/src/tabs_in_doc_comments.rs:139]: Isn't this just

```suggestion
            u32::try_from(char_indices.len()).expect(line_length_way_to_long),
```

?

File: tests/ui/crashes/ice-5835.rs [hunk 3]
```diff
@@ -0,0 +1,8 @@
+#![rustfmt::skip]
+
+pub struct Foo {
+    /// 位
```
Comment (flip1995) [inline tests/ui/crashes/ice-5835.rs:4]: I would add a comment here for people like me who's editor auto-remove trailing whitespaces.

```suggestion
    /// 位	
    ///   ^ Don't remove this tab character!
```

File: tests/ui/crashes/ice-5835.rs [hunk 4]
```diff
@@ -0,0 +1,8 @@
+#![rustfmt::skip]
+
```
Comment (flip1995) [inline tests/ui/crashes/ice-5835.rs:2]:
```suggestion
#[rustfmt::skip]
```

To get rid of the rustc error.

**Comment by flip1995** [comment]
r? @flip1995 

Since highfive didn't assign anyone.

**Comment by flip1995** [comment]
> But I don't think we handle those cases anywhere in Clippy currently?

I don't think so, no. But doesn't this lint only produce spans for whitespaces? There shouldn't be many problems with wrong spans, I think.

File: clippy_lints/src/tabs_in_doc_comments.rs (hunk 2 above)
Comment (phansch) [reply clippy_lints/src/tabs_in_doc_comments.rs:139]: I don't think so. [char_indicies](https://doc.rust-lang.org/std/primitive.str.html#method.char_indices) is an iterator over tuples with `(byte position, char)` and using the length of the iterator would produce the same result as the previous code. The suggestion would only work if all characters are 1-byte characters.

File: clippy_lints/src/tabs_in_doc_comments.rs (hunk 1 above)
Comment (phansch) [reply clippy_lints/src/tabs_in_doc_comments.rs:109]: Yes, that works! :exploding_head:

File: clippy_lints/src/tabs_in_doc_comments.rs (hunk 2 above)
Comment (flip1995) [reply clippy_lints/src/tabs_in_doc_comments.rs:139]: Ah can you add a comment to that line than, that the first part is the byte position and not the character index? Otherwise r=me

**Comment by flip1995** [comment]
> Ah can you add a comment to that line than, that the first part is the byte position and not the character index? Otherwise r=me

Since comments on discussions often get lost ^ https://github.com/rust-lang/rust-clippy/pull/7039#discussion_r611055242

**Comment by phansch** [comment]
> Since comments on discussions often get lost
Yep, totally missed that :sweat_smile: 

@bors r=flip1995
