### PR TITLE
Fix derivable impl false positives

### LINKED ISSUE #7654: derivable_impls false positive on impl with doc comment
```rust
pub struct Color {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}

/// `#000000`
impl Default for Color {
    fn default() -> Self {
        Color { r: 0, g: 0, b: 0 }
    }
}
```

```console
$ cargo clippy

warning: this `impl` can be derived
  --> src/main.rs:8:1
   |
8  | / impl Default for Color {
9  | |     fn default() -> Self {
10 | |         Color { r: 0, g: 0, b: 0 }
11 | |     }
12 | | }
   | |_^
   |
   = note: `#[warn(clippy::derivable_impls)]` on by default
   = help: try annotating `Color` with `#[derive(Default)]`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls
```

Clippy's suggestion is not appropriate in this case because the impl carries documentation, which is not substitutable by a derived impl.

Screenshot from 2021-09-09 19-14-34

@HKalbasi @camsteffen

### Meta

**Rust version (`rustc -Vv`):**
```
rustc 1.57.0-nightly (497ee321a 2021-09-09)
binary: rustc
commit-hash: 497ee321af3b8496eaccd7af7b437f18bab81abf
commit-date: 2021-09-09
host: x86_64-unknown-linux-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```

### LINKED ISSUE #7655: derivable_impls false positive on nongeneric impl
```rust
pub struct Collection<T> {
    v: Vec<T>,
}

impl Default for Collection<String> {
    fn default() -> Self {
        Collection {
            v: Vec::new(),
        }
    }
}
```

```console
$ cargo clippy

warning: this `impl` can be derived
  --> src/main.rs:5:1
   |
5  | / impl Default for Collection<String> {
6  | |     fn default() -> Self {
7  | |         Collection {
8  | |             v: Vec::new(),
9  | |         }
10 | |     }
11 | | }
   | |_^
   |
   = note: `#[warn(clippy::derivable_impls)]` on by default
   = help: try annotating `Collection` with `#[derive(Default)]`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls
```

Clippy's suggestion is **not** equivalent to the handwritten impl. It is more generic which may not be desirable.

```rust
fn main() {
    let _ = Collection::default(); // works fine with handwritten Default
}
```

ambiguity with derived default but not handwritten default:

```console
error[E0282]: type annotations needed for `Collection<T>`
 --> src/main.rs:7:13
  |
7 |     let _ = Collection::default();
  |         -   ^^^^^^^^^^ cannot infer type for type parameter `T` declared on the struct `Collection`
  |         |
  |         consider giving this pattern the explicit type `Collection<T>`, where the type parameter `T` is specified
```

@HKalbasi @camsteffen

### Meta

**Rust version (`rustc -Vv`):**
```
rustc 1.57.0-nightly (497ee321a 2021-09-09)
binary: rustc
commit-hash: 497ee321af3b8496eaccd7af7b437f18bab81abf
commit-date: 2021-09-09
host: x86_64-unknown-linux-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```

### PR DESCRIPTION
**Pull request by HKalbasi**
fix #7654
fix #7655 

changelog: none (not released)

### CODE REVIEW

File: clippy_lints/src/derivable_impls.rs [hunk 1]
```diff
@@ -81,9 +81,18 @@ impl<'tcx> LateLintPass<'tcx> for DerivableImpls {
             if let Body { value: func_expr, .. } = cx.tcx.hir().body(*b);
             if let Some(adt_def) = cx.tcx.type_of(item.def_id).ty_adt_def();
             then {
-                if cx.tcx.type_of(item.def_id).definitely_has_param_types_or_consts(cx.tcx) {
+                if attrs.iter().any(|attr| attr.doc_str().is_some()) {
```
Comment (camsteffen) [inline clippy_lints/src/derivable_impls.rs:84]: Should also check for docs on the function.

**Comment by camsteffen** [comment]
Thanks! @bors r+
