### PR TITLE
Fix Deprecated lints don't expand

### LINKED ISSUE #4748: Lint docs: Deprecated lints don't expand
reported in Discord by @evanjs: Deprecated lints in the docs don't expand:  
https://rust-lang.github.io/rust-clippy/master/#misaligned_transmute

This is _probably_ because the doc comments need to be moved above the `pub LINT_NAME` line so that the lintlib.py script picks them up again.

### PR DESCRIPTION
**Pull request by evanjs**
### fixes #4748

Unable to `cargo test` locally (I'm on NixOS, and keep getting errors that are similar to those #4714 might solve) but I have verified that all deprecated lints can now be expanded like other lints.

changelog: Show deprecated lints in lint documentation again

### CODE REVIEW

File: clippy_lints/src/deprecated_lints.rs [hunk 1]
```diff
@@ -4,85 +4,85 @@ macro_rules! declare_deprecated_lint {
     }
 }
 
+declare_deprecated_lint! {
 /// **What it does:** Nothing. This lint has been deprecated.
```
Comment (phansch) [inline clippy_lints/src/deprecated_lints.rs]: Could you also indent the doc comments so that they're aligned with `pub LINT_NAME`?

**Comment by evanjs** [comment]
Thanks!  Didn't even think about the indents.  Derp.

Some of the doc-comments now barely exceed 80 characters, but I wasn't sure of any line-break conventions, so I left those alone.

**Comment by evanjs** [comment]
Pardon the noise.  That's what I get for having multiple `clippy` repos on the same machine.

Checked against the live site and all the lints seem to be present and expandable.
