### PR TITLE
Fix indentation of website code snippets

### LINKED ISSUE #13568: website: lint list: no indentation in code snippets
### Summary

https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/items_after_statements.rs#L17

Image

https://rust-lang.github.io/rust-clippy/master/index.html#/items_aft

### PR DESCRIPTION
**Pull request by Alexendoo**
Fixes #13568

Follow up to #13359, I didn't catch that it swapped the `strip_prefix` out for a `trim` but they aren't interchangeable here

changelog: none

### CODE REVIEW

File: clippy_config/src/conf.rs [hunk 1]
```diff
@@ -102,7 +102,9 @@ pub fn sanitize_explanation(raw_docs: &str) -> String {
     // Remove tags and hidden code:
     let mut explanation = String::with_capacity(128);
     let mut in_code = false;
-    for line in raw_docs.lines().map(str::trim) {
+    for line in raw_docs.lines() {
+        let line = line.strip_prefix(' ').unwrap_or(line);
```
Comment (GuillaumeGomez) [inline clippy_config/src/conf.rs:106]: The indent will still be removed with this change.

**Comment by GuillaumeGomez** [comment]
Funnily enough, we worked on the same problem. I opened https://github.com/rust-lang/rust-clippy/pull/13596 to fix it. However, I think this PR is not fixing since it still trims the indent if there is some.

File: clippy_config/src/conf.rs (hunk 1 above)
Comment (Alexendoo) [reply clippy_config/src/conf.rs:106]: It removes the single space `///[here]text`, strip_prefix does not remove multiple elements

Comment (GuillaumeGomez) [reply clippy_config/src/conf.rs:106]: Arf indeed, thought it was stripping as long as it found the character. But then it creates an unbalance in case you have no whitespace character at the beginning of all lines (for whatever reason) and you then have a block.

Comment (Centri3) [reply clippy_config/src/conf.rs:106]: Yeah though this is exactly how the procedural macro did it as well. I think this (there being no space) is a non-issue overall but if this was already fixed in your PR I think that's a better way of doing it, afaik both rustfmt and clippy never catch this likely typo.

Comment (GuillaumeGomez) [reply clippy_config/src/conf.rs:106]: Which procedural macro?

Also, I think it's about handling the fact that most of the time, you write code after a whitespace  (`/// bla` instead of `///bla`). It's handled in rustdoc by finding out what's the minimum indent and then stripping according to that. Hum, might be worth to do that actually. Gonna update my PR.

Comment (Centri3) [reply clippy_config/src/conf.rs:106]: In the prior PR, `declare_clippy_lint` was turned from a procedural macro into a declarative macro. It had the same logic before as this PR has

Comment (Centri3) [reply clippy_config/src/conf.rs:106]: Ah - didn't realize it'd leave a leading space. The issue was about it being unintentional, and hard to spot, rather than a style choice

Comment (flip1995) [reply clippy_config/src/conf.rs:106]: > Hum, might be worth to do that actually. Gonna update my PR.

I don't think this is worth the effort/code. This is just to generate the Clippy documentation from the lint documentation in the Clippy code base. This code doesn't have to handle all possible doc writing styles people come up with, like `rustdoc` does.

**Review by flip1995 — APPROVED** [review]
LGTM. @Centri3 I'll let you r+ as the assignee if you're also happy with the PR :)

File: clippy_config/src/conf.rs (hunk 1 above)
Comment (Alexendoo) [reply clippy_config/src/conf.rs:106]: Yeah we can't reuse the `fn`s rustdoc uses here unlike for our lints since we only get them as strings, but I think it's fine to assume our docs are reasonably formatted

**Review by Centri3 — APPROVED** [review]

**Comment by Centri3** [comment]
Would approve a way to either catch/fix wrongly formatted lints. It's a reasonable thing to ignore though. @bors r+
