### PR TITLE
Fixes [`trait_duplication_in_bounds`] false positives

### LINKED ISSUE #8771: type_repetition_in_bounds + trait_duplication_in_bounds false positive on signature containing double impl Trait
### Summary

Clippy makes a suggestion to write `impl Trait: Trait + Trait` which does not make sense.

### Lint Name

type_repetition_in_bounds and trait_duplication_in_bounds

### Reproducer

```rust
pub trait Trait {}

pub fn f(_a: impl Trait, _b: impl Trait) {}
```

```console
error: this type has already been used as a bound predicate
 --> src/main.rs:3:35
  |
3 | pub fn f(_a: impl Trait, _b: impl Trait) {}
  |                                   ^^^^^
  |
  = note: `-D clippy::type-repetition-in-bounds` implied by `-D clippy::pedantic`
  = help: consider combining the bounds: `impl Trait: Trait + Trait`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#type_repetition_in_bounds

error: this trait bound is already specified in the where clause
 --> src/main.rs:3:19
  |
3 | pub fn f(_a: impl Trait, _b: impl Trait) {}
  |                   ^^^^^
  |
  = note: `-D clippy::trait-duplication-in-bounds` implied by `-D clippy::pedantic`
  = help: consider removing this trait bound
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#trait_duplication_in_bounds
```

### Version

```text
rustc 1.62.0-nightly (7c4b47696 2022-04-30)
binary: rustc
commit-hash: 7c4b47696907d64eff5621a64eb3c6e795a9ec77
commit-date: 2022-04-30
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

### Additional Labels

_No response_

### LINKED ISSUE #9076: `trait_duplication_in_bounds` false positive for complex trait bounds
### Summary

When having complex trait bounds `trait_duplication_in_bounds` warns incorrectly

### Lint Name

trait_duplication_in_bounds

### Reproducer

I tried [this code](https://github.com/tremor-rs/tremor-runtime/blob/main/tremor-influx/src/decoder.rs#L31-L73):

```rust
fn parse_fields<'input, V>(total_idx: usize, mut input: &'input str) -> Result<(V, usize)>
where
    V: Value + Mutable + ValueAccess + Builder<'input> + 'input + std::fmt::Debug,
    <V as ValueAccess>::Key: From<Cow<'input, str>>,
    <V as ValueAccess>::Target: From<V>,
{
    let mut offset = 0;
    let mut res = V::object_with_capacity(16);
    loop {
        let (key, idx1) = parse_to(total_idx + offset, input, |c| c == '=')?;
        input = get_rest(input, idx1 + 1)?;
        offset += idx1 + 1;
        let (val, c, idx2): (V, _, _) = parse_value(total_idx + offset, input)?;
        input = get_rest(input, idx2 + 1)?;
        offset += idx2 + 1;

        match c {
            Some(',') => {
                cant_error!(res.insert(key, val));
            }
            Some(' ') | None => {
                cant_error!(res.insert(key, val));
                return Ok((res, offset));
            }
            _ => return Err(Error::InvalidFields(total_idx + offset)),
        };
    }
}
```

I saw this happen:

```
   --> tremor-influx/src/decoder.rs:202:30
    |
202 |     <V as ValueAccess>::Key: From<Cow<'input, str>>,
    |                              ^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider removing this trait bound
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#trait_duplication_in_bounds
```

I expected to see this happen:

No error

### Version

```text
rustc 1.62.0 (a8314ef7d 2022-06-27)
binary: rustc
commit-hash: a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
commit-date: 2022-06-27
host: x86_64-unknown-linux-gnu
release: 1.62.0
LLVM version: 14.0.5
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by aldhsu**
Fixes #9076 #9151 #8757.
Partially fixes #8771.

changelog: [`trait_duplication_in_bounds`]: Reduce number of false positives.

### CODE REVIEW

**Comment by flip1995** [comment]
Assigning this to me, since I reviewed the last PR. I pormise that it won't take me 2 months this time!

r? @flip1995

File: clippy_lints/src/trait_bounds.rs [hunk 1]
```diff
@@ -238,31 +238,45 @@ fn check_trait_bound_duplication(cx: &LateContext<'_>, gen: &'_ Generics<'_>) {
         return;
     }
 
-    let mut map = FxHashMap::<_, Vec<_>>::default();
-    for predicate in gen.predicates {
+    let where_predicates = gen
+        .predicates
+        .iter()
+        .filter_map(|pred| {
```
Comment (flip1995) [inline clippy_lints/src/trait_bounds.rs:244]: Please add a comment what this is actually filtering for. You can write example code in the comment and point to the parts this is looking for, like it is done for spans in error messages.

It may also be worth to define this `if_chain` in a closure above this `filter_map` and then use it here.

**Review by flip1995 — COMMENTED** [review]
Early review. I still have to look through the tests, but the impl changes LGTM overall.

File: clippy_lints/src/trait_bounds.rs (hunk 1 above)
Comment (aldhsu) [reply clippy_lints/src/trait_bounds.rs:244]: Thanks for having a look @flip1995! Is this the only thing you want me to address?

Comment (aldhsu) [reply clippy_lints/src/trait_bounds.rs:244]: > It may also be worth to define this if_chain in a closure above this filter_map and then use it here.
Oof. I tried this the lifetimes were beyond me. Any tips or should I just go with the comment?

Comment (aldhsu) [reply clippy_lints/src/trait_bounds.rs:251]: I've added a comment on what is collected. Let me know if it sufficent. I made some small changes to make it more consistent with what currently exists as well.

**Comment by flip1995** [comment]
Thanks! This was the only thing for now. The comments added are great! I now have to go through the tests, but I don't expect that there's anything left for you to do :+1:

**Comment by aldhsu** [comment]
@flip1995 I worked on a refactor to lint in one pass [0cf2864](https://github.com/rust-lang/rust-clippy/pull/9167/commits/0cf2864a2dc816190f33f62fc16153a77d5312cc). I thought it would be harder than it turned out to be. I've added it to this PR. I'm happy to split it to a separate PR if you prefer.

**Review by flip1995 — APPROVED** [review]
Awesome work, thanks! Now I wonder if I had waited even longer with my review, would you fix all of Clippy? :thinking: :stuck_out_tongue:

**Comment by flip1995** [comment]
Maybe in another PR :D


@bors r+
