### PR TITLE
Fix `items_after_test_module`: Ignore imported modules

### LINKED ISSUE #10713: items_after_test_module disagrees with widespread practice
### Summary

```rust
mod bar;
mod foo;

#[cfg(test)]
mod tests;

use bar::Trait;

pub fn fun() {}
```

I believe clippy should not dislike this code. Declaring modules at the top of the file is extremely common practice. People disagree on whether `mod` goes before or after `use`, but both of those ways are way more common than putting `mod` last in a file.

### Lint Name

items_after_test_module

### Reproducer

```rust
// src/lib.rs

#[cfg(test)]
mod tests;

pub fn f() {}
```

```rust
// src/tests.rs (empty)
```

```console
$ cargo clippy --tests

warning: items were found after the testing module
 --> src/lib.rs:2:1
  |
2 | / mod tests;
3 | |
4 | | pub fn f() {}
  | |_____________^
  |
  = help: move the items to before the testing module was defined
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_test_module
  = note: `#[warn(clippy::items_after_test_module)]` on by default
```

### Version

```text
rustc 1.71.0-nightly (f5559e338 2023-04-24)
binary: rustc
commit-hash: f5559e338256f17ada6d82b429acc2dbd8facc9c
commit-date: 2023-04-24
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by blyxyas**
Fixes #10713. It does a little bit of dark magic, but intention is what really counts.
changelog:[`items_after_test_module`]: Ignore imported modules (`mod foo;`) with no body.

### CODE REVIEW

File: tests/ui/items_after_test_module/imported_module.rs
Comment (Alexendoo) [inline tests/ui/items_after_test_module/imported_module.rs:1]: You can create a test in `ui-cargo` rather than `ui` for this, that way the module isn't being itself compiled as a test

Comment (Alexendoo) [reply tests/ui/items_after_test_module/imported_module.rs:1]: That or put the module in `auxiliary` and import it with `#[path = "auxiliary/tests.rs"] mod tests;`

File: clippy_lints/src/items_after_test_module.rs [hunk 1]
```diff
@@ -64,20 +64,21 @@ impl LateLintPass<'_> for ItemsAfterTestModule {
...
+					if_chain! {
+						if attr.has_name(sym::cfg);
                         if let Some(mitems) = attr.meta_item_list();
                         if let [mitem] = &*mitems;
                         if mitem.has_name(sym::test);
                         then {
-                            was_test_mod_visited = true;
-                            test_mod_span = Some(item.span);
+							was_test_mod_visited = true;
+                            test_mod_span = Some(module.spans.inner_span.with_lo(item.span.lo()));
```
Comment (Alexendoo) [inline clippy_lints/src/items_after_test_module.rs:77]: What difference does this make?

Comment (blyxyas) [reply clippy_lints/src/items_after_test_module.rs]: It was just a test for debugging that I forgot to remove

File: tests/ui/items_after_test_module/imported_module.rs
Comment (blyxyas) [reply tests/ui/items_after_test_module/imported_module.rs:1]: Fixed

File: tests/ui/items_after_test_module/imported_module.rs [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+
+fn should_not_lint() {}
+
+#[path = "auxiliary/tests.rs"]
+#[cfg(test)]
+mod tests; // Should not lint
+
+fn should_lint() {}
+
+const SHOULD_ALSO_LINT: usize = 1;
```
Comment (Alexendoo) [inline tests/ui/items_after_test_module/imported_module.rs:15]: These could do with a rename

File: tests/ui/items_after_test_module/imported_module.stderr
Comment (Alexendoo) [inline tests/ui/items_after_test_module/imported_module.stderr:1]: Empty stderrs can be removed

**Review by Alexendoo — APPROVED** [review]

**Comment by Alexendoo** [comment]
Thanks!

@bors r+
