### PR TITLE
Fix `collapsible_else_if` FP on conditionally compiled stmt

### LINKED ISSUE #14799: collapsible_else_if disregard platform code in else branch
### Summary

Without much context, I have the following code:

```rs
if connectivity.is_offline() {
    NextTunnelState::SameState(self)
} else {
    #[cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]
    Self::reset_dns(shared_state).await;

    if self.reconnect {
        NextTunnelState::NewState(ConnectingState::enter(0, self.selected_gateways, shared_state).await)
    } else {
        NextTunnelState::NewState(DisconnectedState::enter(None, shared_state).await)
    }
}
```

When compiling for `aarch64-apple-ios`, clippy suggests to collapse the else block disregarding the platform code:

```
warning: this `else { if .. }` block can be collapsed
   --> crates/nym-vpn-lib/src/tunnel_state_machine/states/offline_state.rs:143:24
    |
143 |                   } else {
    |  ________________________^
144 | |                     #[cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]
145 | |                     Self::reset_dns(shared_state).await;
...   |
152 | |                 }
    | |_________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_else_if
    = note: `#[warn(clippy::collapsible_else_if)]` on by default
help: collapse nested if block
    |
143 ~                 } else if self.reconnect {
144 +                     NextTunnelState::NewState(ConnectingState::enter(0, self.selected_gateways, shared_state).await)
145 +                 } else {
146 +                     NextTunnelState::NewState(DisconnectedState::enter(None, shared_state).await)
147 +                 }
```

Which would result into code duplication which I am trying to avoid. (I do not mind nested if)

### Lint Name

_No response_

### Reproducer

I tried this code:

```rust
<code>
```

I saw this happen:

```
<output>
```

I expected to see this happen:

### Version

```text

```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by profetia**
Closes rust-lang/rust-clippy#14799 

changelog: [`collapsible_else_if`] fix FP on conditionally compiled stmt

### CODE REVIEW

File: clippy_lints/src/collapsible_if.rs [hunk 1]
```diff
@@ -198,6 +204,12 @@ fn block_starts_with_comment(cx: &LateContext<'_>, block: &Block<'_>) -> bool {
     trimmed_block_text.starts_with("//") || trimmed_block_text.starts_with("/*")
 }
 
+fn span_not_contain_stmt(cx: &LateContext<'_>, span: Span) -> bool {
+    matches!(snippet_opt(cx, span), Some(text) if tokenize_with_text(&text[1..]).all(|(token, _, _)| {
+        matches!(token, TokenKind::LineComment { .. } | TokenKind::BlockComment { .. } | TokenKind::Whitespace)
+    }))
+}
+
```
Comment (samueltardieu) [inline clippy_lints/src/collapsible_if.rs:212]: Could you please:
- use `span.get_source_text(cx)` to avoid allocating a string with the span content instead of `snippet_opt(cx, span)`
- move this function to `clippy_utils` (after `span_contains_comment`) with the following signature: `pub fn span_contains_non_comment(cx: &impl source::HasSession, span: Span) -> bool`
- add documentation

**Review by samueltardieu — CHANGES_REQUESTED** [review]

**Comment by samueltardieu** [comment]
r? samueltardieu

**Review by samueltardieu — CHANGES_REQUESTED** [review]
After more thinking about it, I think we can do much better, fix more problems, and create a useful utility function that can be used by other lints in similar situations.

I noticed that we parse the beginning of the block two times: once to look for comments, and once to look for auto-removed code. This is not efficient, and we could have a function in `clippy_utils` that checks for both at the same time, or even one that allows comments but detects significant content:

```rust
/// Checks whether a given span has any significant token. A significant token is a non-whitespace
/// token, including comments unless `skip_comments` is set.
/// This is useful to determine if there are any actual code tokens in the span that are omitted in
/// the late pass, such as platform-specific code.
pub fn span_contains_non_whitespace(cx: &impl source::HasSession, span: Span, skip_comments: bool) -> bool {
    matches!(span.get_source_text(cx), Some(snippet) if tokenize_with_text(&snippet).any(|(token, _, _)|
        match token {
            TokenKind::Whitespace => false,
            TokenKind::BlockComment { .. } | TokenKind::LineComment { .. } => !skip_comments,
            _ => true,
        }
    ))
}
```

(that would supersede `span_contains_no_comment()` which can be removed) 

This will be particularly useful in `collapsible_if.rs` as:

- `collapsible_if_if` suffers the same problem about conditionally compiled statements
- `collapsible_if_if` has an option `lint_commented_code` which triggers the lint even in the presence of commented code
- `collapsible_else_if` would benefit from using the same option

If you create this method on `CollapsibleIf`:

```rust
    // Check that nothing significant can be found but whitespaces between the initial `{` of `block`
    // and the beginning of `stop_at`.
    fn block_starts_with_significant_tokens(
        &self,
        cx: &LateContext<'_>,
        block: &Block<'_>,
        stop_at: &Expr<'_>,
    ) -> bool {
        let span = block.span.split_at(1).1.until(stop_at.span);
        span_contains_non_whitespace(cx, span, self.lint_commented_code)
    }
```

then you can add a `&self` parameter to `check_collapsible_else_if()`, and call `            && !self.block_starts_with_significant_tokens(cx, else_block, else_)`. `check_collapsible_if_if()` can get a similar `&& !self.block_starts_with_significant_tokens(cx, then, inner)`. This way, the `block_starts_with_comment` function can be removed as it is no longer useful.

Also, you would need to:

- register `lint_commented_code` as being an option of `collapsible_else_if` as well
- create test code for `collapsible_else_if` in `ui-toml` with this option enabled – you might be able to share code with `collapsible_if_if`, which already tests for this
- add test code for `collapsible_if_if` to ensure that `#[cfg(…)]` blocks prevent the lint from triggering as expected

All this started from your initial PR, which made me think more about it.

What do you think?

File: clippy_config/src/conf.rs [hunk 2]
```diff
@@ -645,6 +645,10 @@ define_Conf! {
     /// that would be collapsed.
     #[lints(collapsible_if)]
     lint_commented_code: bool = false,
+    /// Whether collapsible `else if` chains are linted if they contain comments inside the parts
+    /// that would be collapsed.
+    #[lints(collapsible_else_if)]
+    lint_commented_else_if: bool = false,
```
Comment (samueltardieu) [inline clippy_config/src/conf.rs:651]: You should reuse the same option, `lint_commented_code`, there is no good reason to separate them.

**Review by samueltardieu — CHANGES_REQUESTED** [review]
This looks good to me, except that this should be the same option which applies to both lints, no need to make a new configuration option.

File: clippy_config/src/conf.rs (hunk 2 above)
Comment (profetia) [reply clippy_config/src/conf.rs]: Fair. Thank you!

**Comment by samueltardieu** [comment]
Just to make sure: if `lint_commented_code` is enabled, will the comments be preserved, as they are in the `collapsible_if` case? It looks like you applied the lint manually to Clippy sources, would an automatic fix have been ok too? 

The `lint_commented_code` option always to propose a fix in case comments are present, but should never remove the comments.

**Comment by samueltardieu** [comment]
(since you didn't mark the PR as ready, maybe it is not ready for review yet and this part will be changed later)

**Comment by profetia** [comment]
Fixed. The comments will now be kept similar to `collapsible_if`.

File: clippy_lints/src/undocumented_unsafe_blocks.rs [hunk 3]
```diff
@@ -606,32 +606,31 @@ fn span_from_macro_expansion_has_safety_comment(cx: &LateContext<'_>, span: Span
...
-                    None => HasSafetyComment::No,
-                }
-            } else {
-                HasSafetyComment::No
+    } else
+    // From a macro expansion. Get the text from the start of the macro declaration to start of the
+    // unsafe block.
+    //     macro_rules! foo { () => { stuff }; (x) => { unsafe { stuff } }; }
+    //     ^--------------------------------------------^
+    if let Ok(unsafe_line) = source_map.lookup_line(span.lo())
```
Comment (samueltardieu) [inline clippy_lints/src/undocumented_unsafe_blocks.rs]: I find the `else` much too far from the `if` where they are multi-lines comments. Could you make the lint suggest something like this instead, where the `else if` appears clearly?

```rust
   }
    // From a macro expansion. Get the text from the start of the macro declaration to start of the
    // unsafe block.
    //     macro_rules! foo { () => { stuff }; (x) => { unsafe { stuff } }; }
    //     ^--------------------------------------------^
    else if let Ok(unsafe_line) = source_map.lookup_line(span.lo())
```

If you disagree that this is beneficial, please open a Zulip thread so that people can weight in.

**Review by samueltardieu — CHANGES_REQUESTED** [review]

File: clippy_lints/src/undocumented_unsafe_blocks.rs (hunk 3 above)
Comment (samueltardieu) [reply clippy_lints/src/undocumented_unsafe_blocks.rs]: And also, don't forget to update the `lints` attribute for `lint_commented_code` in `clippy_config/src/conf.rs` and update the config metadata.

Comment (profetia) [reply clippy_lints/src/undocumented_unsafe_blocks.rs]: LGTM. I've updated it accordingly. Thank you!
