### PR TITLE
Fixes a case where `collapsible_match` suggested a transformation that changes runtime behavior.

### LINKED ISSUE #16875: `collapsible_match` suggestion change meaning
### Summary

Code in the form `pattern => {if test {…}}` is suggested to be simplified as `pattern if test => {…}` but the meaning is different: if the pattern match but not the test, no other pattern are checked in the original code, but other patterns are checked in the suggestion.

### Lint Name

collapsible_match

### Reproducer

Corrected code should have the same result as the original code, here is an example showing it is false:

```rust
fn check(a: Option<&str>, b: i32) -> i32 {
    let mut res = 0;
    match a {
        Some(_) => {
            if b == 0 {
                res = 1
            }
        }
        _ if b == 1 => res = 2,
        _ => {}
    }
    res
}

fn check_clippy_suggestion(a: Option<&str>, b: i32) -> i32 {
    let mut res = 0;
    match a {
        Some(_) if b == 0 => res = 1,
        _ if b == 1 => res = 2,
        _ => {}
    }
    res
}

fn main() {
    assert_eq!(check(Some(""), 1), check_clippy_suggestion(Some(""), 1));
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=c5e9555641490ea06f6588cd501e1233

### Version

```text
rustc 1.95.0 (59807616e 2026-04-14)
binary: rustc
commit-hash: 59807616e1fa2540724bfbac14d7976d7e4a3860
commit-date: 2026-04-14
host: x86_64-unknown-linux-gnu
release: 1.95.0
LLVM version: 22.1.2
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by Souradip121**
Closes rust-lang/rust-clippy#16875

### What was wrong

The lint suggested collapsing `pattern => { if test { body } }` into `pattern if test => { body }`. These are not equivalent. In the original, once `pattern` matches, the match exits regardless of `test`. In the suggestion, a failing guard allows fall-through to subsequent arms, which can match values that previously never reached them.

```rust
// Before (original)
match a {
    Some(_) => {
        if b == 0 { res = 1 }
    }
    _ if b == 1 => res = 2,  // unreachable when a is Some(_)
    _ => {}
}

// After (suggestion — WRONG, changes behavior)
match a {
    Some(_) if b == 0 => res = 1,
    _ if b == 1 => res = 2,  // now reachable when a is Some(_) and b != 0
    _ => {}
}
```

### Fix

The `if`-guard collapsing is only safe when there are no non-wildcard arms between the current arm and the wildcard arm. The fix adds a check that all arms after the current one are "wild-like" (a bare `_`, a binding, or `None`, all without guards) before suggesting the transformation.

As a side effect, three `#[expect(clippy::collapsible_match)]` suppressions in `clippy_lints/src/methods/mod.rs` are removed. They had been added to suppress this exact false positive and are no longer needed.

### Still lints correctly

When only wildcard arms follow, the transformation is safe and the lint still fires:

```rust
// This still lints — only `_ => {}` follows, fall-through is harmless
match a {
    Some(_) => {
        if b == 0 { res = 1 }  // triggers collapsible_match
    }
    _ => {}
}
```

changelog: [`collapsible_match`]: no longer suggests collapsing `pattern => { if test { body } }` into a match guard when non-wildcard arms follow, as this changes the semantics of the match.

### Summary Notes

- [Beta-nomination](https://github.com/rust-lang/rust-clippy/pull/16878#pullrequestreview-4134228149) by [samueltardieu](https://github.com/samueltardieu)

*Managed by `@rustbot`—see [help](https://forge.rust-lang.org/triagebot/note.html) for details*

### CODE REVIEW

File: clippy_lints/src/matches/collapsible_match.rs [hunk 1]
```diff
@@ -23,8 +23,19 @@ use super::{COLLAPSIBLE_MATCH, pat_contains_disallowed_or};
 
 pub(super) fn check_match<'tcx>(cx: &LateContext<'tcx>, expr: &'tcx Expr<'_>, arms: &'tcx [Arm<'_>], msrv: Msrv) {
     if let Some(els_arm) = arms.iter().rfind(|arm| arm_is_wild_like(cx, arm)) {
-        for arm in arms {
-            check_arm(cx, true, arm.pat, expr, arm.body, arm.guard, Some(els_arm.body), msrv);
+        for (idx, arm) in arms.iter().enumerate() {
+            let only_wildcards_after = arms[idx + 1..].iter().all(|a| arm_is_wild_like(cx, a));
```
Comment (samueltardieu) [inline clippy_lints/src/matches/collapsible_match.rs]: I think this would avoid a O(N²) situation in the presence of numerous arms:

```suggestion
        let last_non_wildcard = arms.iter().rposition(|arm| !arm_is_wild_like(cx, arm));
        for (idx, arm) in arms.iter().enumerate() {
            let only_wildcards_after = last_non_wildcard.is_none_or(|lnw| idx >= lnw);
```

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-clippy/16878/5800532ce08a453bb0eb60c4d6661500fc8c7b33..2e7b2ba1e1666a979c2fb2bc5cab5239d94f321e)*

**Review by samueltardieu — CHANGES_REQUESTED** [review]

File: clippy_lints/src/matches/collapsible_match.rs (hunk 1 above)
Comment (Souradip121) [reply clippy_lints/src/matches/collapsible_match.rs]: Yes, @samueltardieu you are right!

Comment (samueltardieu) [reply clippy_lints/src/matches/collapsible_match.rs]: A more proper fix would be to check for other arms that could match and are not wildcards, but that would be more difficult.

**Review by samueltardieu — APPROVED** [review]
@rustbot label +beta-nominated
@rustbot note Beta-nomination

This fixes a `I-suggestion-causes-bug` regression in 1.95. This could even be backported in a point release for 1.95.1.

Cc @flip1995 

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-clippy/16878/5800532ce08a453bb0eb60c4d6661500fc8c7b33..c7cadb6fe4470568caf975cfad94fa07b02bd531)*

**Comment by profetia** [comment]
Can you check if this also fixes #16716 and #16717? If not, can you borrow from #16749 to fix them? I'm thinking to put everything on this PR since it is beta nominated.

**Comment by Souradip121** [comment]
Alright @profetia checking right now.

**Comment by samueltardieu** [comment]
Please keep beta-nominated PR at minimal size, so that they are easy to review. Those PRs are merged very late into the beta cycle, almost right before the stable release, so they must be very very readable.

This one fixes a `I-suggestion-causes-bug` kind of problem which is more critical than `I-suggestion-causes-error`.

**Comment by samueltardieu** [comment]
> If not, can you borrow from #16749 to fix them? I'm thinking to put everything on this PR since it is beta nominated.

This is *not* a good idea.

**Comment by Souradip121** [comment]
@samueltardieu @profetia should I push the new commits or not :)

**Comment by samueltardieu** [comment]
> @samueltardieu @profetia should I push the new commits or not :)

Not in this PR.

**Comment by Souradip121** [comment]
@samueltardieu Alright, not doing it, kindly merge my PR then.

**Comment by samueltardieu** [comment]
Given that's it's beta-nominated and possibly considered for stable backporting, I want to let a second maintainer a chance to have a look to it first.

Ping @rust-lang/clippy

**Review by Manishearth — APPROVED** [review]

**Comment by profetia** [comment]
This PR now already fixes #16717. I will reopen https://github.com/rust-lang/rust-clippy/pull/16749 for #16716 solely, after it is merged.

**Comment by flip1995** [comment]
https://github.com/rust-lang/rust/pull/156793
