### PR TITLE
Fixes `manual_flatten` removes the useless if let

### LINKED ISSUE #14692: `manual_flatten` doesn't follow its suggestion to remove `if let` statement leading to broken code
### Summary

Clippy lint `manual_flatten` doesn't follow its own suggestion to remove `if let` statement leading to broken code.
Similar to #7514, but without references or slices.

### Reproducer

I tried this code:
```rust
fn main() {
    let results: Vec<Result<String, ()>> = vec![];

    for result in results {
        if let Ok(value) = result {
            println!("{value}");
        }
    }
}
```

I expected to see this happen:
```rust
for result in results.into_iter().flatten() {
    println!("{result}");
}
```

Instead, this happened:
```rust
for result in results.into_iter().flatten() {
    if let Ok(value) = result { // broken because result is now of type String
        println!("{value}");
    }
}
```

### Version

```text
rustc 1.86.0 (05f9846f8 2025-03-31)
binary: rustc
commit-hash: 05f9846f893b09a1be1fc8560e33fc3c815cfecb
commit-date: 2025-03-31
host: x86_64-pc-windows-msvc
release: 1.86.0
LLVM version: 19.1.7
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by donkomura**
Closes rust-lang/rust-clippy#14692

The suggestion of `manual_flatten` does not includes the replacement of `if let` so far despite of `.flatten()` suggestion.
This PR eliminates a redundant `if let`.

changelog: [`manual_flatten`] the suggestion removes `if let`

### CODE REVIEW

File: clippy_lints/src/loops/manual_flatten.rs [hunk 1]
```diff
@@ -54,20 +55,23 @@ pub(super) fn check<'tcx>(
...
+        let help_msg = "try `.flatten()` and remove the `if let` statement in the for loop";
 
-        // If suggestion is not a one-liner, it won't be shown inline within the error message. In that
-        // case, it will be shown in the extra `help` message at the end, which is why the first
-        // `help_msg` needs to refer to the correct relative position of the suggestion.
-        let help_msg = if sugg.contains('\n') {
-            "remove the `if let` statement in the for loop and then..."
-        } else {
-            "...and remove the `if let` statement in the for loop"
-        };
```
Comment (donkomura) [inline clippy_lints/src/loops/manual_flatten.rs:66]: The suggestion always have multiple lines, so we can become the help message simplify.
(or should we suggest the one-liner and separate the suggestion that includes removing `if let`?)

**Review by samueltardieu — CHANGES_REQUESTED** [review]
If this is supposed to now be auto-fixable, then `//@no-rustfix` should be removed from the test file.

However, the current suggestion don't appear to be valid unless the binding from the `Some()` or `Ok()` is a single identifier with the same name as the identifier from the `for` loop.

For example, given this code:

```rust
    for x in [Some(3)] {
        if let Some(y)  = x {
            println!("{y}");
        }
    }
```

the suggestion will not compile:

```rust
    for x in [Some(3)].into_iter().flatten() {
        println!("{y}");
    }
```

File: tests/ui/manual_flatten.stderr [hunk 2]
```diff
@@ -37,145 +37,169 @@ LL | |         };
...
    |
 LL | /         if let Some(m) = n {
 LL | |             println!("{}", m);
 LL | |         }
    | |_________^
+help: try
+   |
+LL ~     for m in z.flatten() {
+LL +         println!("{}", m);
+LL +     }
```
Comment (donkomura) [inline tests/ui/manual_flatten.stderr:126]: I'd fixed it to out valid code.

File: clippy_lints/src/loops/manual_flatten.rs [hunk 3]
```diff
@@ -54,20 +55,35 @@ pub(super) fn check<'tcx>(
...
-            "remove the `if let` statement in the for loop and then..."
+        let pat_snippet = if let_pats.is_empty() {
+            "_".to_string()
         } else {
-            "...and remove the `if let` statement in the for loop"
+            snippet_with_applicability(
+                cx,
+                let_pats.first().unwrap().span.source_callsite(),
+                "_",
+                &mut applicability,
```
Comment (samueltardieu) [inline clippy_lints/src/loops/manual_flatten.rs:67]: Shouldn't you initialize `applicability` with `MachineApplicable` if the suggestion is complete?

**Comment by donkomura** [comment]
Thank you for pointing that out. I made corrections to prevent the macro from triggering a lint. I also adjusted the Applicability.

**Review by samueltardieu — COMMENTED** [review]
This looks good to me, could you squash the commits?

**Comment by donkomura** [comment]
I'm sorry for the late reply. I've squashed the commits including a bit fix.

**Review by samueltardieu — APPROVED** [review]

**Comment by samueltardieu** [comment]
Thanks
