### PR TITLE
Fixing FPs for the `branches_sharing_code` lint

### LINKED ISSUE #7053: False positive branches_sharing_code: different inferred type
```rust
fn main() {
    if true {
        let mut v = Vec::new();
        v.push(0);
    } else {
        let mut v = Vec::new();
        v.push("");
    };
}
```

```console
$ cargo clippy
warning: all if blocks contain the same code at the start
 --> src/main.rs:2:5
  |
2 | /     if true {
3 | |         let mut v = Vec::new();
  | |_______________________________^
  |
  = note: `#[warn(clippy::branches_sharing_code)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#branches_sharing_code
help: consider moving the start statements out like this
  |
2 |     let mut v = Vec::new();
3 |     if true {
  |
```

Clippy's preferred code is the following, which does not compile.

```rust
fn main() {
    let mut v = Vec::new();
    if true {
        v.push(0);
    } else {
        v.push("");
    };
}
```

```console
error[E0308]: mismatched types
 --> src/main.rs:6:16
  |
6 |         v.push("");
  |                ^^ expected integer, found `&str`
```

### Meta

- `cargo clippy -V`: clippy 0.1.53 (2e495d2 2021-04-08)
- `rustc -Vv`:
  ```
  rustc 1.53.0-nightly (2e495d2e8 2021-04-08)
  binary: rustc
  commit-hash: 2e495d2e845cf27740e3665f718acfd3aa17253e
  commit-date: 2021-04-08
  host: x86_64-unknown-linux-gnu
  release: 1.53.0-nightly
  LLVM version: 12.0.0
  ```

Mentioning @xFrednet @phansch #6463

### LINKED ISSUE #7054: False positive branches_sharing_code: trailing expression in else of if-let
```rust
fn main() {
    let string;
    let _x = if let true = true {
        ""
    } else if true {
        string = "x".to_owned();
        &string
    } else {
        string = "y".to_owned();
        &string
    };
}
```

```console
$ cargo clippy
warning: all if blocks contain the same code at the end
  --> src/main.rs:10:5
   |
10 | /         &string
11 | |     };
   | |_____^
   |
   = note: `#[warn(clippy::branches_sharing_code)]` on by default
   = note: The end suggestion probably needs some adjustments to use the expression result correctly
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#branches_sharing_code
help: consider moving the end statements out like this
   |
10 |     }
11 |     &string;
   |
```

Clippy's preferred code is the following, which does not compile.

```rust
fn main() {
    let string;
    let _x = if let true = true {
        ""
    } else if true {
        string = "x".to_owned();
    } else {
        string = "y".to_owned();
    }
    &string;
}
```

```console
error[E0308]: `if` and `else` have incompatible types
 --> src/main.rs:5:12
  |
3 |        let _x = if let true = true {
  |   ______________-
4 |  |         ""
  |  |         -- expected because of this
5 |  |     } else if true {
  |  |____________^
6 | ||         string = "x".to_owned();
7 | ||     } else {
8 | ||         string = "y".to_owned();
9 | ||     }
  | ||     ^
  | ||_____|
  | |______`if` and `else` have incompatible types
  |        expected `&str`, found `()`
```

It's possible that clippy means the following, but I still consider this a false positive because I find the original code clearer than this.

```rust
fn main() {
    let string;
    let _x = if let true = true {
        ""
    } else {
        if true {
            string = "x".to_owned();
        } else {
            string = "y".to_owned();
        }
        &string
    };
}
```

### Meta

- `cargo clippy -V`: clippy 0.1.53 (2e495d2 2021-04-08)
- `rustc -Vv`:
  ```
  rustc 1.53.0-nightly (2e495d2e8 2021-04-08)
  binary: rustc
  commit-hash: 2e495d2e845cf27740e3665f718acfd3aa17253e
  commit-date: 2021-04-08
  host: x86_64-unknown-linux-gnu
  release: 1.53.0-nightly
  LLVM version: 12.0.0
  ```

Mentioning @xFrednet @phansch #6463

### PR DESCRIPTION
**Pull request by xFrednet**
Fixes #7053
Fixes #7054 
And an additional CSS adjustment to support dark mode for every inline code. It currently only works in paragraphs, which was an oversight on my part :sweat_smile:. [Current Example](https://rust-lang.github.io/rust-clippy/master/index.html#blacklisted_name)

This also includes ~50 lines of doc comments and is therefor not as big as the changes would indicate. :penguin:

---

changelog: none

All of these bugs were introduced in this dev version and are therefor not worth a change log entry.

r? @phansch 
cc: @camsteffen since you have a pretty good overview of the `SpanlessEq` implementation :upside_down_face:

### CODE REVIEW

File: clippy_utils/src/hir_utils.rs [hunk 1]
```diff
@@ -96,6 +129,21 @@ impl HirEqInterExpr<'_, '_, '_> {
     pub fn eq_stmt(&mut self, left: &Stmt<'_>, right: &Stmt<'_>) -> bool {
         match (&left.kind, &right.kind) {
             (&StmtKind::Local(ref l), &StmtKind::Local(ref r)) => {
+                // See `SpanlessEq::check_inferred_local_types` for an explication of this check
+                if_chain! {
+                    if l.ty.is_none() && r.ty.is_none();
```
Comment (camsteffen) [inline clippy_utils/src/hir_utils.rs:134]: I don't think you want this check. You could have a type specified but not fully specified `Vec<_>`.

File: clippy_utils/src/hir_utils.rs [hunk 2]
```diff
@@ -29,6 +30,30 @@ pub struct SpanlessEq<'a, 'tcx> {
...
+    /// ```
+    ///
+    /// Only comparing the first local definition would usually return that they are
+    /// equal, since they are identical. However, they are different due to the context
+    /// as they have different inferred types.
+    ///
+    /// This option enables or disables the specific check of the inferred type.
+    ///
+    /// Note: This check will only be done if `self.maybe_typeck_results` is `Some()`.
+    check_inferred_local_types: bool,
```
Comment (camsteffen) [inline clippy_utils/src/hir_utils.rs:56]: Any reason to not simply always do this?

File: clippy_utils/src/hir_utils.rs [hunk 3]
```diff
@@ -96,6 +129,21 @@ impl HirEqInterExpr<'_, '_, '_> {
     pub fn eq_stmt(&mut self, left: &Stmt<'_>, right: &Stmt<'_>) -> bool {
         match (&left.kind, &right.kind) {
             (&StmtKind::Local(ref l), &StmtKind::Local(ref r)) => {
+                // See `SpanlessEq::check_inferred_local_types` for an explication of this check
+                if_chain! {
+                    if l.ty.is_none() && r.ty.is_none();
+                    if self.inner.check_inferred_local_types;
+                    if let Some(tcx) = self.inner.maybe_typeck_results;
```
Comment (camsteffen) [inline clippy_utils/src/hir_utils.rs:136]:
```suggestion
                    if let Some(typeck) = self.inner.maybe_typeck_results;
```
`tcx` is usually `TyCtxt`, not `TypeckResults`.

File: clippy_utils/src/hir_utils.rs [hunk 4]
```diff
@@ -96,6 +129,21 @@ impl HirEqInterExpr<'_, '_, '_> {
...
+
+                    // Check the inferred types
+                    let l_ty = tcx.pat_ty(&l.pat);
+                    let r_ty = tcx.pat_ty(&r.pat);
+                    if l_ty != r_ty;
```
Comment (camsteffen) [inline clippy_utils/src/hir_utils.rs:141]:
```suggestion
                    if !TyS::same_type(l_ty, r_ty);
```

File: clippy_utils/src/lib.rs [hunk 5]
```diff
@@ -1195,13 +1195,29 @@ pub fn parent_node_is_if_expr(expr: &Expr<'_>, cx: &LateContext<'_>) -> bool {
...
+        let arm_parent_id = map.get_parent_node(arm.hir_id);
+        let arm_parent_node = map.get(arm_parent_id);
+        if let Node::Expr(expr) = arm_parent_node;
+        if let ExprKind::Match(_, _, MatchSource::IfLetDesugar { .. }) = expr.kind;
+        then {
+            return true;
+        }
+    }
+
+    false
```
Comment (camsteffen) [inline clippy_utils/src/lib.rs:1220]: I think this can be removed and use `is_else_clause`

File: clippy_utils/src/hir_utils.rs (hunk 1 above)
Comment (xFrednet) [reply clippy_utils/src/hir_utils.rs:134]: True, I've missed that :+1:

File: clippy_utils/src/hir_utils.rs (hunk 2 above)
Comment (xFrednet) [reply clippy_utils/src/hir_utils.rs:56]: This lint is currently the only chase where equality is evaluated on a per statement level, the other use cases inspect the entire context and catch such cases without the need of this additional check. So, we could check this every time, but it's often unnecessary and might alter the result of some evaluations as `let vec = Vec::new()` == `let vec = Vec::new()` would not always be the same anymore.

File: clippy_utils/src/lib.rs (hunk 5 above)
Comment (xFrednet) [reply clippy_utils/src/lib.rs:1220]: Oh, then it seems like there are two functions for the same purpose^^. I'll remove this one and replace the references with `is_else_clause`. That's a very good catch. Thank you! :upside_down_face:

File: clippy_utils/src/hir_utils.rs (hunk 2 above)
Comment (camsteffen) [reply clippy_utils/src/hir_utils.rs:56]: I think it is not unlikely that this will fix other false positives. So I think its most safe (and simple) to just always have the check.

File: clippy_lints/src/copies.rs [hunk 6]
```diff
@@ -290,6 +290,14 @@ fn lint_same_then_else<'tcx>(
     }
 }
 
+/// The return tuple is structured as follows:
+/// 1. The amount of equal statements from the start
+/// 2. The amount of equal statements from the end
+/// 3. An indication if the block expressions are the same. This will also be true if both are
+/// `None`
```
Comment (flip1995) [inline clippy_lints/src/copies.rs:297]: Why not creating a struct for this? If you have to explain the return type it should probably be a struct.

File: clippy_utils/src/hir_utils.rs (hunk 2 above)
Comment (xFrednet) [reply clippy_utils/src/hir_utils.rs]: Fair point, I've removed the configuration and all test still pass :)

File: clippy_lints/src/copies.rs (hunk 6 above)
Comment (xFrednet) [reply clippy_lints/src/copies.rs]: Good point, I'm sometimes not used to the Rust way when it comes to this ^^. The function now returns a struct which seems way cleaner :)

**Review by flip1995 — APPROVED** [review]
LGTM. If @camsteffen doesn't have any objections, this is ready to merge :+1:

**Review by camsteffen — APPROVED** [review]
All good!
