### PR TITLE
[`unused_async`]: don't lint if function is part of a trait

### LINKED ISSUE #10459: `unused_async` false positive with `async_fn_in_trait`
### Summary

`async_fn_in_trait` triggers `unused_async` when an implementation doesn't `.await` in the body, and suggests to remove the `async`. This produces broken code, as `async` is required by the trait definition.

### Lint Name

unused_async

### Reproducer

I tried this code:

```rust
#![allow(incomplete_features)]
#![feature(async_fn_in_trait)]
#![warn(clippy::unused_async)]

trait HasAsyncMethod {
    async fn do_something() -> u32;
}

impl HasAsyncMethod for () {
    async fn do_something() -> u32 {
        1
    }
}
```

[playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e3a2765c6e35061985668dfcee75f7c7)

### Version

```text
rustc 1.69.0-nightly (31f858d9a 2023-02-28)
binary: rustc
commit-hash: 31f858d9a511f24fedb8ed997b28304fec809630
commit-date: 2023-02-28
host: x86_64-unknown-linux-gnu
release: 1.69.0-nightly
LLVM version: 15.0.7
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by y21**
Fixes #10459.

We shouldn't lint if the function is part of a trait, because the user won't be able to easily remove the `async`, as this will then not match with the function signature in the trait definition

changelog: [`unused_async`]: don't lint if function is part of a trait

### CODE REVIEW

File: clippy_lints/src/unused_async.rs [hunk 1]
```diff
@@ -81,6 +81,20 @@ impl<'a, 'tcx> Visitor<'tcx> for AsyncFnVisitor<'a, 'tcx> {
     }
 }
 
+/// Checks if the `def_id` belongs to a function and that function is part of a trait impl,
+/// in which case we shouldn't lint because `async` is part of the trait definition and therefore
+/// can't be removed.
+fn is_in_trait_impl(cx: &LateContext<'_>, def_id: LocalDefId) -> bool {
```
Comment (Manishearth) [inline clippy_lints/src/unused_async.rs:87]: issue: this should be in utils somewhere. there's also a chance we already have it

(@Centri3 got opinions where?)

**Review by Manishearth — CHANGES_REQUESTED** [review]

File: clippy_lints/src/unused_async.rs (hunk 1 above)
Comment (Centri3) [reply clippy_lints/src/unused_async.rs:87]: I don't think we already have it, we have some for `MethodCall`s and such but not `DefId`s themselves

I think just the top-level `clippy_utils` is fine. The other `is_trait_method` function is there too. We could probably rename this to `is_def_id_trait_method` or something for consistency's sake.

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
@bors r+

thanks!
