### PR TITLE
Fix lint_single_char_pattern on raw string literal

### LINKED ISSUE #4356: lint_single_char_pattern shows extra quotation mark and number sign with raw string literal
## Problem

With the following code,

```rust
fn main() {
    for s in "try using a char instead".split(r"a") {
        println!("{}", s);
    }

    for s in "try using a char instead".split(r#"a"#) {
        println!("{}", s);
    }
}
```

clippy shows invalid char literals: `'"a'` and `'#"a"'` .

```
warning: single-character string constant used as pattern
 --> src\main.rs:2:47
  |
2 |     for s in "try using a char instead".split(r"a") {
  |                                               ^^^^ help: try using a char instead: `'"a'`
  |
  = note: #[warn(clippy::single_char_pattern)] on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern

warning: single-character string constant used as pattern
 --> src\main.rs:6:47
  |
6 |     for s in "try using a char instead".split(r#"a"#) {
  |                                               ^^^^^^ help: try using a char instead: `'#"a"'`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern
```

## Clippy version
```
clippy 0.0.212 (082cfa79 2019-06-07)
```

### PR DESCRIPTION
**Pull request by lzutao**
Closes #4356
changelog: Handle raw string literal on `single_char_literal` lint.

### CODE REVIEW

File: tests/ui/single_char_pattern.rs [hunk 1]
```diff
@@ -53,4 +53,8 @@ fn main() {
     // Issue #3204
     const S: &str = "#";
     x.find(S);
+
+    // Raw string
+    x.split(r"a");
+    x.split(r#"a"#);
```
Comment (phansch) [inline tests/ui/single_char_pattern.rs]: Just to be sure, could you also add these tests:

```rust
x.split(r###"a"###);
x.split(r###"\'"###);
x.split(r###"#"###);
```

If it works, then r=me

File: tests/ui/single_char_pattern.stderr [hunk 2]
```diff
@@ -132,5 +132,35 @@ error: single-character string constant used as pattern
...
+  --> $DIR/single_char_pattern.rs:60:13
+   |
+LL |     x.split(r###"a"###);
+   |             ^^^^^^^^^^ help: try using a char instead: `'a'`
+
+error: single-character string constant used as pattern
+  --> $DIR/single_char_pattern.rs:61:13
+   |
+LL |     x.split(r###"'"###);
+   |             ^^^^^^^^^^ help: try using a char instead: `'/''`
```
Comment (lzutao) [inline tests/ui/single_char_pattern.stderr]: I wonder why the suggestion is not `` `'\''` ``. It seems really awkward.

Comment (phansch) [reply tests/ui/single_char_pattern.stderr]: I think that might be caused by some `compiletest-rs` normalization of the output. The same happens with other suggestions
