### PR TITLE
`unnecessary_to_owned`: don't call `iter()` on a temporary object

### LINKED ISSUE #14242: `unnecessary_to_owned` in conjunction with reference counted slices and iterators
### Summary

When trying to return an iterator over values in an `Rc<[T]>` that is owned by the function by first converting it to a `Vec`, the `unnecessary_to_owned` lint gets triggered. Clippy also suggested a "fix" which wouldn't compile.

error from clippy's suggested code:
```
error[E0716]: temporary value dropped while borrowed
  --> src/main.rs:13:5
   |
13 |       rc_slice_provider()
   |       -^^^^^^^^^^^^^^^^^^
   |       |
   |  _____creates a temporary value which is freed while still in use
   | |
14 | |         .iter()
15 | |         .copied()
   | |_________________- opaque type requires that borrow lasts for `'static`
16 |   }
   |   - temporary value is freed at the end of this statement
```

### Lint Name

unnecessary_to_owned

### Reproducer

I tried this code:

```rust
#![deny(clippy::unnecessary_to_owned)]

use std::rc::Rc;

#[derive(Copy, Clone)]
struct Foo;

fn rc_slice_provider() -> Rc<[Foo]> {
    Rc::from([Foo])
}

fn iterator_provider() -> impl Iterator<Item = Foo> {
    rc_slice_provider()
        .to_vec() // can't return a reference since the rc is owned by the function
        .into_iter()
}
```

I saw this happen:

```
error: unnecessary use of `to_vec`
  --> src/main.rs:13:5
   |
13 | /     rc_slice_provider()
14 | |         .to_vec() // can't return a reference since the rc is owned by the function
15 | |         .into_iter()
   | |____________________^ help: use: `rc_slice_provider().iter().copied()`
   |
```

I expected to see this happen:

Nothing I suppose. (You could technically create a user-defined iterator that takes ownership of the rc to avoid the reallocation so I guess the lint is somewhat warranted)

### Version

```text
example ran in playground but here is my local:

rustc 1.84.1 (e71f9a9a9 2025-01-27)
binary: rustc
commit-hash: e71f9a9a98b0faf423844bf0ba7438f29dc27d58
commit-date: 2025-01-27
host: aarch64-apple-darwin
release: 1.84.1
LLVM version: 19.1.5
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by lapla-cogito**
fix #14242 

changelog: [`unnecessary_to_owned`]: don't call `iter` on a temporary object

### CODE REVIEW

File: clippy_lints/src/methods/unnecessary_to_owned.rs [hunk 1]
```diff
@@ -219,6 +219,8 @@ fn check_into_iter_call_arg(
         && let Some(receiver_snippet) = receiver.span.get_source_text(cx)
         // If the receiver is a `Cow`, we can't remove the `into_owned` generally, see https://github.com/rust-lang/rust-clippy/issues/13624.
         && !is_type_diagnostic_item(cx, cx.typeck_results().expr_ty(receiver), sym::Cow)
+        // Calling `iter()` on a temporary object can lead to false positives. #14242
+        && !matches!(receiver.kind, ExprKind::Call(..) | ExprKind::Struct(..) | ExprKind::Tup(..))
```
Comment (samueltardieu) [inline clippy_lints/src/methods/unnecessary_to_owned.rs:223]: Out of curiosity, how did you choose this expression? What about `ExprKind::Union` for example?

Comment (lapla-cogito) [reply clippy_lints/src/methods/unnecessary_to_owned.rs:223]: Are you talking about `ItemKind::Union`? Anyway, I chose these by looking at the members of `ExprKind` but please let me know if I am over or under.

Comment (samueltardieu) [reply clippy_lints/src/methods/unnecessary_to_owned.rs:223]: I am just curious, as I haven't seen tests for `Struct` for example. What about blocks, or binary operations, can't they create temporaries as well (since they can be overloaded), or casts? I was wondering if there wasn't another better heuristic for what you're trying to achieve.

Comment (Centri3) [reply clippy_lints/src/methods/unnecessary_to_owned.rs:223]: You should probably use the [criteria rustc uses](https://github.com/rust-lang/rust/blob/3ed2a10d173d6c2e0232776af338ca7d080b1cd4/compiler/rustc_hir_typeck/src/expr.rs#L482-L499).

File: clippy_lints/src/methods/unnecessary_to_owned.rs [hunk 2]
```diff
@@ -219,6 +219,8 @@ fn check_into_iter_call_arg(
         && let Some(receiver_snippet) = receiver.span.get_source_text(cx)
         // If the receiver is a `Cow`, we can't remove the `into_owned` generally, see https://github.com/rust-lang/rust-clippy/issues/13624.
         && !is_type_diagnostic_item(cx, cx.typeck_results().expr_ty(receiver), sym::Cow)
+        // Calling `iter()` on a temporary object can lead to false positives. #14242
+        && receiver.is_place_expr(|base| cx.typeck_results().adjustments().get(base.hir_id).is_some())
```
Comment (Centri3) [inline clippy_lints/src/methods/unnecessary_to_owned.rs:223]: At this point, let's make this a utils function and replace it everywhere else it's used. Ideally in a separate commit

Note this is missing the `Deref` part! It should be close enough...? But maybe too strict. Is there a reason any adjustment is ok?

Comment (lapla-cogito) [reply clippy_lints/src/methods/unnecessary_to_owned.rs:223]: Do you intend something like this?
```rust
receiver.is_place_expr(|base| cx.typeck_results().adjustments().get(base.hir_id)
        .is_some_and(|x| x.iter().any(|adj| matches!(adj.kind, Adjust::Deref(_)))))
```
I think adding the `Deref` restriction here causes some cases that should trigger this lint to be false negatives. There are such cases in the current test file like [here](https://github.com/rust-lang/rust-clippy/blob/6651fac315468de7da88499151729f83bd5e0cf0/tests/ui/unnecessary_to_owned.rs#L197-L198). Is the `Deref` part necessary? (I think it's unnecessary.)

Comment (Centri3) [reply clippy_lints/src/methods/unnecessary_to_owned.rs:223]: I'll look closer but it's about having the exact same check as rustc does

Comment (Centri3) [reply clippy_lints/src/methods/unnecessary_to_owned.rs:223]: So there aren't any FNs as well as no FPs (compile errors)

Comment (lapla-cogito) [reply clippy_lints/src/methods/unnecessary_to_owned.rs:223]: > there aren't any FNs as well as no FPs

I agree with this, but I wonder if there are cases where eliminating the `Deref` check would result in FPs.

Comment (Centri3) [reply clippy_lints/src/methods/unnecessary_to_owned.rs:223]: Looking closer, this is actually making it more permissive and allowing erroneous code past. The `Deref` part is specifically to only allow raw borrows *if* there is a dereference adjustment. By doing this, anything else (including no adjustments) is considered "legal", too, but not by rustc.

Whether or not you'd actually find code like this, idk. Adjustments are from autoderef or converting `!` to any type.

Comment (lapla-cogito) [reply clippy_lints/src/methods/unnecessary_to_owned.rs]: Thanks, I added a helper function and implemented the main purpose of this patch.

File: clippy_utils/src/lib.rs [hunk 3]
```diff
@@ -2331,6 +2331,16 @@ pub fn is_expr_final_block_expr(tcx: TyCtxt<'_>, expr: &Expr<'_>) -> bool {
     matches!(tcx.parent_hir_node(expr.hir_id), Node::Block(..))
 }
 
+/// Checks if the expression is a temporary value.
+pub fn is_expr_temporary_value(cx: &LateContext<'_>, expr: &Expr<'_>) -> bool {
+    expr.is_place_expr(|base| {
```
Comment (Centri3) [inline clippy_utils/src/lib.rs:2336]: I think noting that this is the exact same code rustc uses would be helpful for people viewing this later. My main idea is that this looks a bit like a (maybe incorrect) heuristic at first, vs just copying the code, and this change can clear up that hypothetical confusion.

After that, I'll merge this quickly

Comment (lapla-cogito) [reply clippy_utils/src/lib.rs:2338]: Done.

File: clippy_utils/src/lib.rs [hunk 4]
```diff
@@ -2331,6 +2331,18 @@ pub fn is_expr_final_block_expr(tcx: TyCtxt<'_>, expr: &Expr<'_>) -> bool {
     matches!(tcx.parent_hir_node(expr.hir_id), Node::Block(..))
 }
 
+/// Checks if the expression is a temporary value.
+// This logic is the same as the one used in rustc's `check_named_place_expr function`.
+// https://github.com/rust-lang/rust/blob/3ed2a10d173d6c2e0232776af338ca7d080b1cd4/compiler/rustc_hir_typeck/src/expr.rs#L482-L499
+pub fn is_expr_temporary_value(cx: &LateContext<'_>, expr: &Expr<'_>) -> bool {
+    expr.is_place_expr(|base| {
```
Comment (Centri3) [inline clippy_utils/src/lib.rs:2338]: This is currently checking that this is *not* a temporary value
```suggestion
    !expr.is_place_expr(|base| {
```

Comment (lapla-cogito) [reply clippy_utils/src/lib.rs]: Ah, sorry for that. Now fixed.
