### PR TITLE
Fix `for_kv_map` FN when using `iter` and `iter_mut`

### LINKED ISSUE #16822: `for_kv_map` false negative when using iter
### Summary

The lint is not triggered when iterating over a `HashMap` with `iter{_mut}` and destructuring the key as `_`, even though only the values are used.

### Lint Name

`for_kv_map`

### Reproducer

I tried this code:

```rust
pub fn m1(mut x: HashMap<usize, usize>) {
    for (_, v) in x.iter_mut() {
        black_box(v);
    }
}
```

https://rust.godbolt.org/z/qshMWz8xr

I expected to see this happen:

```log
warning: you seem to want to iterate on a map's values
  --> <source>:6:19
   |
13 |     for (_, v) in x.iter_mut() {
   |                   ^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.94.0/index.html#for_kv_map
   = note: `#[warn(clippy::for_kv_map)]` on by default
help: use the corresponding method
   |
13 -     for (_, y) in x.iter_mut() {
13 +     for v in x.values_mut() {
   |
```

Instead, this happened:

No warning emitted.

### Version

```text
nightly
```

### PR DESCRIPTION
**Pull request by profetia**
Closes rust-lang/rust-clippy#16822 

changelog: [`for_kv_map`] fix FN when using `iter` and `iter_mut`

### CODE REVIEW

**Comment by xtqqczze** [comment]
There's also the case of destructuring the value as `_`: https://github.com/rust-lang/rust-clippy/issues/16822#issuecomment-4225539744

**Comment by profetia** [comment]
Added into the test cases.

File: clippy_lints/src/loops/for_kv_map.rs [hunk 1]
```diff
@@ -23,7 +23,17 @@ pub(super) fn check<'tcx>(
...
         let arg_span = arg.span;
-        let (new_pat_span, kind, ty, mutbl) = match *cx.typeck_results().expr_ty(arg).kind() {
+        let (arg, arg_ty) = match arg.kind {
+            ExprKind::AddrOf(BorrowKind::Ref, _, expr) => (expr, cx.typeck_results().expr_ty(arg)),
+            ExprKind::MethodCall(path, receiver, [], ..)
+                if path.ident.name == sym::iter || path.ident.name == sym::iter_mut =>
+            {
+                (receiver, cx.typeck_results().expr_ty_adjusted(receiver))
+            },
+            _ => (arg, cx.typeck_results().expr_ty(arg)),
```
Comment (ada4a) [inline clippy_lints/src/loops/for_kv_map.rs:35]: *[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust-clippy/16830/46a80c238f73e2b36c72ae32a0bbe407177ecbe2..bd10abe991bd424da5cab470406f53be52b7bfc1)*

Could you please add some comments to this? Something like:
```suggestion
        let (arg, arg_ty) = match arg.kind {
            // `for x in &expr` or `for x in &mut expr`
            ExprKind::AddrOf(BorrowKind::Ref, _, expr) => (expr, cx.typeck_results().expr_ty(arg)),
            // `for x in receiver.iter()` or `for x in receiver.iter_mut()`
            ExprKind::MethodCall(path, receiver, [], ..)
                if path.ident.name == sym::iter || path.ident.name == sym::iter_mut =>
            {
                // (why does this use the adjusted type?)
                (receiver, cx.typeck_results().expr_ty_adjusted(receiver))
            },
            // (what does this one match?)
            _ => (arg, cx.typeck_results().expr_ty(arg)),
```

**Review by ada4a — CHANGES_REQUESTED** [review]

File: clippy_lints/src/loops/for_kv_map.rs (hunk 1 above)
Comment (profetia) [reply clippy_lints/src/loops/for_kv_map.rs:35]: The method call uses adjusted type because `.iter()` / `.iter_mut()` may introduce auto deference. For the last one, I just leave it as is in the original implementation.

**Comment by Jarcho** [comment]
r? ada4a

Since you've already looked at this.

File: clippy_lints/src/loops/for_kv_map.rs (hunk 1 above)
Comment (ada4a) [reply clippy_lints/src/loops/for_kv_map.rs:36]: > The method call uses adjusted type because `.iter()` / `.iter_mut()` may introduce auto deference.

Could you please add that as a comment?

Comment (profetia) [reply clippy_lints/src/loops/for_kv_map.rs:36]: Added.

**Comment by ada4a** [comment]
Thanks a lot:)

**Review by ada4a — APPROVED** [review]
