### PR TITLE
[`redundant_closure`] Fix suggestion causes error for `impl FnMut`

### LINKED ISSUE #9369: redundant_closure lint incorrectly emitted when using a `FnMut` as a `FnOnce`
### Summary

When passing a `FnMut` closure to a function that expects a `FnOnce`, you must wrap it in a new closure to avoid moving the original. Clippy incorrectly emits a redundant_closure lint when doing this.

### Lint Name

redundant_closure

### Reproducer

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9e821a26232ffb0e3cf5f90511c56c6b

```rust
pub fn ok_or_else<T, E>(mut f: impl FnMut() -> E)
    -> impl FnMut(Option<T>) -> Result<T, E>
{
    move |opt| opt.ok_or_else(|| f())
}
```

I saw this happen:

```text
warning: redundant closure
 --> src/lib.rs:4:31
  |
4 |     move |opt| opt.ok_or_else(|| f())
  |                               ^^^^^^ help: replace the closure with the function itself: `f`
  |
  = note: `#[warn(clippy::redundant_closure)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure
```

Following clippy's advice causes:
```text
error[[E0507]](https://doc.rust-lang.org/stable/error-index.html#E0507): cannot move out of `f`, a captured variable in an `FnMut` closure
 --> src/lib.rs:4:31
  |
1 | pub fn ok_or_else<T, E>(mut f: impl FnMut() -> E)
  |                         ----- captured outer variable
...
4 |     move |opt| opt.ok_or_else(f)
  |     ----------                ^ move occurs because `f` has type `impl FnMut() -> E`, which does not implement the `Copy` trait
  |     |
  |     captured by this `FnMut` closure
```

### Version

```text
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by evantypanski**
Fixes #9369 

changelog: [`redundant_closure`] Fix suggestion causes error with `impl FnMut` types

### CODE REVIEW

File: tests/ui/eta.rs [hunk 1]
```diff
@@ -303,3 +303,14 @@ fn not_general_enough() {
...
+// https://github.com/rust-lang/rust-clippy/issues/9369
+pub fn mutable_impl_fn_mut(mut f: impl FnMut()) {
+    fn takes_fn_mut(_: impl FnMut()) {}
+    takes_fn_mut(|| f());
+
+    fn takes_fn_once(_: impl FnOnce()) {}
+    takes_fn_once(|| f());
+
+    f();
+}
```
Comment (Alexendoo) [inline tests/ui/eta.rs:316]: Would be good to add a test where `f()` only appears once, like in the original issue

File: clippy_lints/src/eta_reduction.rs [hunk 2]
```diff
@@ -122,15 +122,11 @@ impl<'tcx> LateLintPass<'tcx> for EtaReduction {
...
                     if let Some(mut snippet) = snippet_opt(cx, callee.span) {
-                        if_chain! {
-                            if let ty::Closure(_, substs) = callee_ty.peel_refs().kind();
-                            if substs.as_closure().kind() == ClosureKind::FnMut;
-                            if path_to_local(callee).map_or(false, |l| local_used_after_expr(cx, l, expr));
-
-                            then {
+                        if let Some(fn_mut_id) = cx.tcx.lang_items().fn_mut_trait() &&
+                            implements_trait(cx, callee_ty.peel_refs(), fn_mut_id, &[]) &&
+                            path_to_local(callee).map_or(false, |l| local_used_after_expr(cx, l, expr)) {
```
Comment (Alexendoo) [inline clippy_lints/src/eta_reduction.rs:127]: style nit:

```suggestion
                        if let Some(fn_mut_id) = cx.tcx.lang_items().fn_mut_trait()
                            && implements_trait(cx, callee_ty.peel_refs(), fn_mut_id, &[])
                            && path_to_local(callee).map_or(false, |l| local_used_after_expr(cx, l, expr))
                        {
```

**Review by Alexendoo — APPROVED** [review]

**Comment by Alexendoo** [comment]
Great, thanks!

@bors r+
