### PR TITLE
auto-fix `if_not_else`

### LINKED ISSUE #13411: auto-fix `if_not_else`
### Description

> [!note]
> I'm unsure if this is a bug-report or feature-request

`cargo clippy --fix` should swap the 2 blocks

### Version

1.81.0

> I'm sorry, I'm not using the device that has the tool-chain installed

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by lapla-cogito**
fix #13411 

The `if_not_else` lint can be fixed automatically, but the issue above reports that there is no implementation to do so. Therefore, this PR implements it.

----

changelog: [`if_not_else`]: make suggestions for modified code

### CODE REVIEW

**Comment by lapla-cogito** [comment]
r? clippy

**Comment by llogiq** [comment]
I'd like to see more test cases involving comments and annotations, just to be sure the suggestion reproduces them faithfully.

**Comment by lapla-cogito** [comment]
@llogiq I added several test cases in https://github.com/rust-lang/rust-clippy/pull/13809/commits/887aa269b6657d53d4d074b6b34ad417fef1e271.

File: tests/ui/if_not_else.rs [hunk 1]
```diff
@@ -28,4 +28,46 @@ fn main() {
...
+        if foo() {
+            println!("foo");
+        } else if bla() {
+            println!("bla");
+        } else {
+            println!("both false");
+        }
+    } else {
+        println!("both true");
+    }
```
Comment (lapla-cogito) [inline tests/ui/if_not_else.rs:46]: Considering the following code, which is similar in structure to this one, except that the parts to be linted are nested:
```rust
if !(foo() && bla()) {
    if !foo() {
        println!("not foo");
    } else {
        println!("some output");
    }
} else {
    println!("both true");
}
```
Then, when I run `cargo bless`, I get a `cannot replace slice of data that was already replaced` error. But I don't think this is a problem since `rustfix` will apply the first fix and ignore the subsequent when put to practical use.

**Comment by llogiq** [comment]
Thank you!
