### PR TITLE
Fix infinite loop in `cast_sign_loss` when peeling unwrap method calls

### LINKED ISSUE #12506: Clippy hangs on `.unwrap().unwrap() as usize` on nightly
### Summary

When running `cargo clippy` on a library with the following code using rust nightly, it hangs and never completes. The clippy process CPU usage is at 100% of a core while it's running.

If anyone has a better title, please update it since I'm not sure exactly what's causing the bug.

### Reproducer

```rust
fn _foo() -> usize {
    let bar: Result<Option<i64>, u32> = Ok(Some(10));
    bar.unwrap().unwrap() as usize
}
```

It hangs with the output:

```text
    Checking clippy-bug v0.1.0 (/tmp/clippy-bug)
    Building [                             ] 0/1: clippy-bug
```

(I've waited 5 minutes, so I'm assuming it would hang forever.)

### Version

```text
rustc 1.79.0-nightly (eb45c8444 2024-03-17)
binary: rustc
commit-hash: eb45c844407968ea54df0d9870ebce9e3235b706
commit-date: 2024-03-17
host: x86_64-unknown-linux-gnu
release: 1.79.0-nightly
LLVM version: 18.1.2
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by y21**
Fixes #12506

The lint wants to peel method calls but didn't actually reassign the expression, leading to an infinite loop.

----

changelog: Fix infinite loop in [`cast_sign_loss`] when having two chained `.unwrap()` calls

### CODE REVIEW

File: clippy_lints/src/casts/cast_sign_loss.rs [hunk 1]
```diff
@@ -134,11 +134,12 @@ fn expr_sign<'cx>(cx: &LateContext<'cx>, expr: &Expr<'_>, ty: impl Into<Option<T
         // Peel unwrap(), expect(), etc.
         while let Some(&found_name) = METHODS_UNWRAP.iter().find(|&name| &method_name == name)
             && let Some(arglist) = method_chain_args(expr, &[found_name])
```
Comment (y21) [inline clippy_lints/src/casts/cast_sign_loss.rs:136]: actually now that I'm taking a closer look at the lint code, this `method_chain_args` call seems redundant? It doesn't really seem to do anything in this context, except for returning the expression back that was passed in, as far as I can tell.
The line right above it already checks that it's a call to one of the unwrap family of methods.

I removed it locally and the tests are still passing, would be good to have someone else look over this before I actually remove it tho, maybe it's relevant for something else

Comment (llogiq) [reply clippy_lints/src/casts/cast_sign_loss.rs:136]: The only additional check it does is whether the method path or any of the rags come from a macro/expansion. If so, the call will return None.

**Comment by llogiq** [comment]
Thank you!

@bors r+

**Comment by samueltardieu** [comment]
@llogiq Any idea of what went wrong?

**Comment by y21** [comment]
Probably just a spurious ci error. That happened on another PR and retrying worked. But I also wanted to talk about that one method call first before merging while we're at it, and it looks like its waiting for that atm. I'd also be fine with just leaving it if we want this fixed asap

**Comment by y21** [comment]
Nominated for beta backport since the bug made it to beta and looks like something that people might accidentally run into

**Comment by stevenengler** [comment]
> Nominated for beta backport since the bug made it to beta and looks like something that people might accidentally run into

FWIW, here's the actual real-world code that caused me to open #12506:

```rust
fn page_size() -> usize {
    nix::unistd::sysconf(nix::unistd::SysconfVar::PAGE_SIZE)
        .unwrap()
        .unwrap() as usize
}
```

The lack of error checking is because we just use this in a test case.

**Comment by flip1995** [comment]
https://github.com/rust-lang/rust/pull/124369
