### PR TITLE
fix: `borrow_deref_ref` suggests wrongly when coerce to mut

### LINKED ISSUE #9905: borrow_deref_ref breaks code
### Summary

.

### Lint Name

borrow_deref_ref

### Reproducer

I tried this code:

```rust
fn main() {
    let x: &'static str = "x";

    {
        let y = "y".to_string();
        let ref mut x = &*x;
        *x = &*y;
    }

    assert_eq!(x, "x");
}
```

I saw this happen:
`cargo clippy --fix -- -Aclippy::all -Wclippy::borrow_deref_ref`
```
after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0596]: cannot borrow `x` as mutable, as it is not declared as mutable
 --> src/main.rs:6:13
  |
2 |     let x: &'static str = "x";
  |         - help: consider changing this to be mutable: `mut x`
...
6 |         let ref mut x = x;
  |             ^^^^^^^^^ cannot borrow as mutable

error[E0597]: `y` does not live long enough
 --> src/main.rs:7:16
  |
2 |     let x: &'static str = "x";
  |            ------------ type annotation requires that `y` is borrowed for `'static`
...
7 |         *x = &*y;
  |                ^ borrowed value does not live long enough
8 |     }
  |     - `y` dropped here while still borrowed

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0596, E0597.
For more information about an error, try `rustc --explain E0596`.
Original diagnostics will follow.

warning: deref on an immutable reference
 --> src/main.rs:6:25
  |
6 |         let ref mut x = &*x;
  |                         ^^^ help: if you would like to reborrow, try removing `&*`: `x`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#borrow_deref_ref
  = note: requested on the command line with `-W clippy::borrow-deref-ref`

warning: `clpy` (bin "clpy" test) generated 1 warning (run `cargo fix --bin "clpy" --tests` to apply 1 suggestion)
warning: `clpy` (bin "clpy") generated 1 warning (1 duplicate)
    Finished dev [unoptimized + debuginfo] target(s) in 0.61s
```

I expected to see this happen:

### Version

```text
rustc 1.67.0-nightly (c5d82ed7a 2022-11-19)
binary: rustc
commit-hash: c5d82ed7a4ad94a538bb87e5016e7d5ce0bd434b
commit-date: 2022-11-19
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Additional Labels

_No response_

### LINKED ISSUE #11346: `borrow_deref_ref` suggestion breaks code
### Summary

When there is a method (not a freestanding function) that takes `self: &mut &Self` (or simply `&mut self` when `Self` is `&T`) and such a method is called on an immutable variable of the `&Self` type, a reborrow is required so that _a mutable reference to the copy of the original reference_ is taken.

The problem is that clippy flags such a reborrow as needless, when in reality, when removed, it causes a compilation error because it is not possible to take a mutable reference to an immutable variable.

### Lint Name

borrow_deref_ref

### Reproducer

This is the most minimal example I managed to write that reproduces the problem:

```rust
struct Struct;

impl Struct {
    fn foo(self: &mut &Self) {}
}

trait Trait {
   fn bar(&mut self) {}
}

impl Trait for &Struct {}

fn main() {
    let s = &Struct;

    (&*s).foo(); // warning: deref on an immutable reference
//  ^^^^^ help: if you would like to reborrow, try removing `&*`: `s`

    (&*s).bar(); // warning: deref on an immutable reference
//  ^^^^^ help: if you would like to reborrow, try removing `&*`: `s`
}
```

---

Note that if we remove the need to use the dot operator, the lint doesn't show up:
```rust
struct Struct;

fn foo(_: &mut &Struct) {}

fn main() {
    let s = &Struct;
    foo(&mut &*s) // no warning (reborrow still required)
}
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by profetia**
Closes #11346.
Partially fix #9905. The first case in this issue is a little tricky as the coerce does not happen in the borrowing.

changelog: [`borrow_deref_ref`]: fix wrong suggestions when coerce to mut

### CODE REVIEW

File: clippy_lints/src/borrow_deref_ref.rs [hunk 1]
```diff
@@ -73,6 +73,9 @@ impl<'tcx> LateLintPass<'tcx> for BorrowDerefRef {
                 }
             })
             && !is_from_proc_macro(cx, e)
+            && let e_ty = cx.typeck_results().expr_ty_adjusted(e)
+            // check if the reference is coercing to a mutable reference
+            && !matches!(e_ty.kind(), ty::Ref(_, _, Mutability::Mut))
```
Comment (samueltardieu) [inline clippy_lints/src/borrow_deref_ref.rs:78]: I think that if the deref target is mutable, the lint should trigger:

```suggestion
            && !(matches!(e_ty.kind(), ty::Ref(_, _, Mutability::Mut)) && !is_mutable(cx, deref_target))
```

This should help you lint things such as:

```rust
    (&*{s}).foo();
```

or like

```rust
    let mut s = &Struct;
    s.foo(); // To avoid a warning about `s` not needed to be mutable
    (&*s).foo();
```

Comment (profetia) [reply clippy_lints/src/borrow_deref_ref.rs]: Thanks!
