### PR TITLE
Fix unnecessary_lazy_eval suggestion applicability

### LINKED ISSUE #6240: `unnecessary_lazy_evaluations` suggestions cause type inferrence errors
I tried this code (https://github.com/rust-lang/rust/blob/0da6d42f297642a60f2640ec313b879b376b9ad8/compiler/rustc_trait_selection/src/traits/const_evaluatable.rs#L539):

```rust
    (|| {
        if let Some(a) = AbstractConst::new(tcx, a, a_substs)? {
            if let Some(b) = AbstractConst::new(tcx, b, b_substs)? {
                return Ok(try_unify(tcx, a, b));
            }
        }

        Ok(false)
    })()
    .unwrap_or_else(|ErrorReported| true)
```

I expected to see this happen: Not entirely sure ... maybe the lint shouldn't fire at all here, since there's an explicit type annotation for a unit struct?

Instead, this happened: Since `ErrorReported` is helping inferrence, inference breaks once it's gone.

```
error[E0282]: type annotations needed
   --> compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:539:26
    |
539 |         if let Some(a) = AbstractConst::new(tcx, a, a_substs)? {
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type

warning: unnecessary closure used to substitute value for `Result::Err`
   --> compiler/rustc_trait_selection/src/traits/const_evaluatable.rs:538:5
    |
538 | /     (|| {
539 | |         if let Some(a) = AbstractConst::new(tcx, a, a_substs)? {
540 | |             if let Some(b) = AbstractConst::new(tcx, b, b_substs)? {
541 | |                 return Ok(try_unify(tcx, a, b));
...   |
546 | |     })()
547 | |     .unwrap_or_else(|ErrorReported| true)
    | |_________________________________________^
    |
    = note: `#[warn(clippy::unnecessary_lazy_evaluations)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_lazy_evaluations
help: Use `unwrap_or` instead
    |
538 |     (|| {
539 |         if let Some(a) = AbstractConst::new(tcx, a, a_substs)? {
540 |             if let Some(b) = AbstractConst::new(tcx, b, b_substs)? {
541 |                 return Ok(try_unify(tcx, a, b));
542 |             }
543 |         }
```

### Meta

- `cargo clippy -V`: clippy 0.0.212 (ffa2e7a 2020-10-24)

### PR DESCRIPTION
**Pull request by camsteffen**
changelog: Fix unnecessary_lazy_eval suggestion applicability when breaking type inference

Fixes #6240

### CODE REVIEW

**Comment by llogiq** [comment]
I don't fully understand yet how the test is supposed to capture the difference in applicability. Wouldn't we need to have a `//run-rustfix` test for that?

**Comment by camsteffen** [comment]
Hmm I think you're right. The test doesn't verify that the lint is not machine applicable. But if I put the test case under `//run-rustfix`, the suggestion is applied in the `.fixed` file even though I have `Applicability::MaybeIncorrect`, and then the fixed file fails to compile. See the `async_yields_async` test which does the same except the suggestion does compile. Is this a shortcoming of the whole testing setup? What I did is consistent with tests `assign_ops2` and `bytecount`.

File: clippy_lints/src/methods/unnecessary_lazy_eval.rs [hunk 1]
```diff
@@ -32,6 +32,16 @@ pub(super) fn lint<'tcx>(
                 } else {
                     "unnecessary closure used to substitute value for `Result::Err`"
                 };
+                let applicability = if body
+                    .params
+                    .iter()
+                    .all(|param| matches!(param.pat.kind, hir::PatKind::Wild))
```
Comment (jyn514) [inline clippy_lints/src/methods/unnecessary_lazy_eval.rs:38]: slight enhancement: I think you could also mark it as machine-applicable if all the patterns are identifiers and the identifiers are never used in the function body. That would catch things like `.unwrap_or_else(|_err| 1)`.

Comment (camsteffen) [reply clippy_lints/src/methods/unnecessary_lazy_eval.rs:38]: It turns out bindings are already known to be unused since this is a guarded condition above. So I will just include `Binding` in this `matches!`.

**Comment by llogiq** [comment]
I don't have a good solution right now, but that shouldn't stop us. So... @bors r+
