### PR TITLE
Fix `[use_self]` false negative with on struct and tuple struct patterns

### LINKED ISSUE #8845: `use_self` false negative on tuple or struct enum variants
### Summary

`use_self` doesn't trigger for struct or tuple enum variants, only empty variants.

There are false negatives mentioned in the documention for [use_self](https://rust-lang.github.io/rust-clippy/master/index.html#use_self) but I couldn't find an issue tracking them. I don't know if these are the same known false negatives or not.

### Lint Name

use_self

### Reproducer

I tried this code:

```rust
#![warn(clippy::use_self)]
#![allow(unused)]

pub enum Something {
    Empty,
    Num(u8),
    TupleNums(u8, u8),
    StructNums { one: u8, two: u8 },
}

impl Something {
    const fn get_value(&self) -> u8 {
        match self {
            Something::Empty => 0,
            Something::Num(n) => *n,                      
            Something::TupleNums(n, _m) => *n,            
            Something::StructNums { one, two: _ } => *one,
        }                                                 
    }                                                     
}                                                         
```

I expected to see this happen:

I should get a warning for all four uses of `Something` in get_value.

Instead, this happened:

I only get a warning for `Something::Empty`. Once I update it to `Self::Empty` I get no more warnings.

### Version

```text
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

### PR DESCRIPTION
**Pull request by botahamec**
fixes #8845 

changelog: Triggered the warning for ``[`use_self`]`` on `TupleStruct` and `Struct` patterns, whereas currently it's only triggered for `Path` patterns

### CODE REVIEW

**Comment by Alexendoo** [comment]
👋

File: tests/ui/use_self.rs [hunk 1]
```diff
@@ -542,3 +542,42 @@ mod use_self_in_pat {
...
+
+    impl Something {
+        const fn get_value(&self) -> u8 {
+            match self {
+                Something::Num(n) => *n,
+                Something::TupleNums(n, _m) => *n,
+                Something::StructNums { one, two: _ } => *one,
+            }
+        }
+    }
```
Comment (Alexendoo) [inline tests/ui/use_self.rs:568]: Using the variants directly trigger the lint, suggesting to replace them all with `Self`:

```rust
fn imported_variants(&self) -> u8 {
    use Something::*;

    match self {
        Num(n) => *n,
        TupleNums(n, _m) => *n,
        StructNums { one, two: _ } => *one,
    }
}
```

Comment (Alexendoo) [reply tests/ui/use_self.rs:568]: Seems that's uncovering an existing bug, the first path segment is picked unconditionally 

```rust
enum Enum {
    A,
}

impl Enum {
    fn f(self) -> usize {
        match self {
            crate::Enum::A => 1,
        }
    }
}
```

```
warning: unnecessary structure name repetition
  --> t.rs:13:13
   |
13 |             crate::Enum::A => 1,
   |             ^^^^^ help: use the applicable keyword: `Self`
   |
```

You could check the `res` field of the `PathSegment`s to pick the right one

Comment (botahamec) [reply tests/ui/use_self.rs]: This was tricky. Using the `res` field on the `PathSegment`s doesn't seem to work. In the playground, I found that most of the `res` fields had errors, so I ended up using a workaround similar to what's done in the `check_expr` method. Luckily, the `lint_path_to_variant` function already exists. But, it's a bit hacky, and I did find that the name of the enum is correctly shown in the `res` fields. I made a version of the function which uses the `res` field, and is a bit less hacky, but it's also a bit less performant. I doubt anyone would notice the difference, but I left it unchanged for now.

**Comment by Alexendoo** [comment]
Thanks! Could you also squash the commits and then I think it'll be good to go

**Comment by botahamec** [comment]
@Alexendoo Should be good now

**Comment by xFrednet** [comment]
@Alexendoo when you're happy with this PR you can r+ it directly. And we no longer need a delegate for that :partying_face:

**Review by Alexendoo — APPROVED** [review]

**Comment by Alexendoo** [comment]
Well then. Guess the teams PR needs to happen for that yet 😄

**Comment by xFrednet** [comment]
*Talking in bors voice*

Thank you for the approval

@bors r=Alexendoo
