### PR TITLE
correct `single_match` lint suggestion

### LINKED ISSUE #12758: single_match: type are incompatible
### Summary

.

### Reproducer

I tried this code:
cargo clippy --fix 
```rust
fn test(s: &[u8]) {
    match &s[0..3] {
        b"hello" => {}
        _ => {}
    }
}

fn main() {}

```

I expected to see this happen:

Instead, this happened:
```
warning: function `test` is never used
 --> src/main.rs:1:4
  |
1 | fn test(s: &[u8]) {
  |    ^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: you seem to be trying to use `match` for an equality check. Consider using `if`
 --> src/main.rs:2:5
  |
2 | /     match &s[0..3] {
3 | |         b"hello" => {}
4 | |         _ => {}
5 | |     }
  | |_____^ help: try: `if s[0..3] == b"hello" {}`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_match
  = note: `#[warn(clippy::single_match)]` on by default

warning: `lint` (bin "lint" test) generated 2 warnings (run `cargo clippy --fix --bin "lint" --tests` to apply 1 suggestion)
warning: failed to automatically apply fixes suggested by rustc to crate `lint`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust-clippy/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0277]: can't compare `[u8]` with `&[u8; 5]`
 --> src/main.rs:2:16
  |
2 |     if s[0..3] == b"hello" {}
  |                ^^ no implementation for `[u8] == &[u8; 5]`
  |
  = help: the trait `std::cmp::PartialEq<&[u8; 5]>` is not implemented for `[u8]`
help: consider dereferencing here
  |
2 |     if s[0..3] == *b"hello" {}
  |                   +
```

### Version

```text
rustc 1.80.0-nightly (79734f1db 2024-05-02)
binary: rustc
commit-hash: 79734f1db8dbe322192dea32c0f6b80ab14c4c1d
commit-date: 2024-05-02
host: x86_64-unknown-linux-gnu
release: 1.80.0-nightly
LLVM version: 18.1.4
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by lapla-cogito**
fix #12758

The `single_match` lint makes incorrect suggestions when comparing with byte string literals. There seems to be an issue with the logic that calculates the number of refs when creating suggestions.

changelog: [`single_match`]: No longer make incorrect suggestions when comparing with byte string literals.

### CODE REVIEW

File: clippy_lints/src/matches/single_match.rs [hunk 1]
```diff
@@ -129,7 +129,7 @@ fn report_single_pattern(cx: &LateContext<'_>, ex: &Expr<'_>, arm: &Arm<'_>, exp
             PatKind::Lit(Expr {
                 kind: ExprKind::Lit(lit),
                 ..
-            }) if lit.node.is_str() => pat_ref_count + 1,
+            }) if lit.node.is_str() | lit.node.is_bytestr() => pat_ref_count + 1,
```
Comment (alex-semenyuk) [inline clippy_lints/src/matches/single_match.rs:132]: Is it intentionally `|` instead of `||` here?

Comment (lapla-cogito) [reply clippy_lints/src/matches/single_match.rs]: sorry for the typo... https://github.com/rust-lang/rust-clippy/pull/13824/commits/7886fee6d9066375ed9eeb7c538381f69c1146e7

**Review by blyxyas — APPROVED** [review]
LGTM, thanks! :heart:

**Comment by blyxyas** [comment]
@lapla-cogito, It seems that there's a merge conflict :cactus:

**Comment by lapla-cogito** [comment]
@blyxyas
Seems to be resolved now.
