### PR TITLE
Fix `needless_for_each` suggests wrongly when closure has no braces

### LINKED ISSUE #14734: Missing `{ … }` for `needless_for_each`
### Summary

Clippy forgot about the `{}` for the suggestions.

### Reproducer

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=3dedb348e9d9b077d3bcaa43ff1bc346

```rs
const LANGUAGE_ROWS: [u8; 0] = [];

#[warn(clippy::needless_for_each)]
fn main() {
    let mut v = vec![];
    LANGUAGE_ROWS.iter().for_each(|x| _ = v.push(x));
}
```
```
    Checking playground v0.0.1 (/playground)
warning: needless use of `for_each`
 --> src/main.rs:6:5
  |
6 |     LANGUAGE_ROWS.iter().for_each(|x| _ = v.push(x));
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `for x in LANGUAGE_ROWS.iter() _ = v.push(x)`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_for_each
note: the lint level is defined here
 --> src/main.rs:3:8
  |
3 | #[warn(clippy::needless_for_each)]
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: this let-binding has unit value
 --> src/main.rs:6:39
  |
6 |     LANGUAGE_ROWS.iter().for_each(|x| _ = v.push(x));
  |                                       ^^^^^^^^^^^^^ help: omit the `let` binding: `v.push(x);`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_unit_value
  = note: `#[warn(clippy::let_unit_value)]` on by default

warning: `playground` (bin "playground") generated 2 warnings (run `cargo clippy --fix --bin "playground"` to apply 2 suggestions)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.75s
```

### Version

```text
rustc 1.86.0 (05f9846f8 2025-03-31)
binary: rustc
commit-hash: 05f9846f893b09a1be1fc8560e33fc3c815cfecb
commit-date: 2025-03-31
host: x86_64-unknown-linux-gnu
release: 1.86.0
LLVM version: 19.1.7
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by profetia**
Closes rust-lang/rust-clippy#14734 

changelog: [`needless_for_each`] wrong suggestions when closure has no braces

### CODE REVIEW

File: clippy_lints/src/needless_for_each.rs [hunk 1]
```diff
@@ -103,7 +103,14 @@ impl<'tcx> LateLintPass<'tcx> for NeedlessForEach {
                 "for {} in {} {}",
                 snippet_with_applicability(cx, body.params[0].pat.span, "..", &mut applicability),
                 snippet_with_applicability(cx, for_each_recv.span, "..", &mut applicability),
-                snippet_with_applicability(cx, body.value.span, "..", &mut applicability),
+                if let ExprKind::Block(block, _) = body.value.kind
+                    && let block_sugg = snippet_with_applicability(cx, block.span, "..", &mut applicability)
```
Comment (blyxyas) [inline clippy_lints/src/needless_for_each.rs:107]: Trying to optimize this, turns out that this information is encoded into the HIR, no need to check with snippets (yay :partying_face:)

Without braces: `block.stmts` is a single `Let`,
With braces: `block.stmts` is empty, and `block.expr` is an inner `ExprKind::Block`

I'm not sure how robust is this, we should probably do some more testing, but pattern matching this way is way faster than adquiring a snippet, so I think it's well worth the try.

What do you think?

Comment (profetia) [reply clippy_lints/src/needless_for_each.rs]: Good idea! Thank you!

File: clippy_lints/src/needless_for_each.rs [hunk 2]
```diff
@@ -116,6 +126,20 @@ impl<'tcx> LateLintPass<'tcx> for NeedlessForEach {
     }
 }
 
+/// Check if the block is a desugared `_ = expr` statement.
+fn is_let_desugar(block: &Block<'_>) -> bool {
+    matches!(
+        block,
+        Block {
+            stmts: [Stmt {
+                kind: StmtKind::Let(_),
```
Comment (blyxyas) [inline clippy_lints/src/needless_for_each.rs:135]: Sorry for the misunderstanding, I think that only in the original test case is a Let. I suppose that if instead of the internal block being "_ = 0" it was a function call, it would be different.

So instead of looking for a Let, this would be a wildcard (this could also be tested)

Comment (profetia) [reply clippy_lints/src/needless_for_each.rs:135]: This lint does not work on such cases, so it is fine here. I can make it work on this case if you find it appropriate.
```rust
rows.iter().for_each(|x| do_something(x))
```

**Comment by profetia** [comment]
Squashed.
