### PR TITLE
fix: incorrect suggestions when `.then` and `.then_some` is used

### LINKED ISSUE #11910: Clippy fails to auto-fix `search_is_some` issue when `.then_some()` is used
### Summary

When `clippy` attempted to auto-fix an instance of [`search_is_some`](https://rust-lang.github.io/rust-clippy/master/index.html#search_is_some), there was a compiler error. 

The use of `.any()` is followed by `.then_some(...)` so it needs to add parentheses around the part it's negating with `!` rather than attempting to negate the entire expression (you can't 'negate' `Option<T>`).

### Reproducer

I tried this code:

```rust
impl Game {
    pub fn is_valid(&self, max_red: u32, max_green: u32, max_blue: u32) -> Option<u32> {
        self.turns
            .iter()
            .find(|t| !t.is_valid(max_green, max_blue, max_red))
            .is_none()
            .then_some(self.id)
    }
}
```

I expected to see this happen:

```rust
impl Game {
    pub fn is_valid(&self, max_red: u32, max_green: u32, max_blue: u32) -> Option<u32> {
        (!self
            .turns
            .iter()
            .any(|t| !t.is_valid(max_green, max_blue, max_red)))
        .then_some(self.id)
    }
}
```

Instead, this happened:

```
The following errors were reported:
error[E0600]: cannot apply unary operator `!` to type `std::option::Option<u32>`
  --> src/day2/part1.rs:80:9
   |
80 | /         !self.turns
81 | |             .iter().any(|t| !t.is_valid(max_green, max_blue, max_red))
82 | |             .then_some(self.id)
   | |_______________________________^ cannot apply unary operator `!`

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0600`.
```

### Version

```text
rustc 1.76.0-nightly (8c2b57721 2023-12-01)
binary: rustc
commit-hash: 8c2b57721728233e074db69d93517614de338055
commit-date: 2023-12-01
host: x86_64-apple-darwin
release: 1.76.0-nightly
LLVM version: 17.0.5
```

### Additional Labels

@rustbot labels +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by yuxqiu**
fixes #11910 

In the current implementation of `search_is_some`, if a `.is_none` call is followed by a `.then` or `.then_some` call, the generated `!` will incorrectly negate the values returned by the `then` and `.then_some` calls. To fix this, we need to add parentheses to the generated suggestions when appropriate.

changelog: [`search_is_some`]: add parenthesis to suggestions when appropriate

### CODE REVIEW

File: clippy_lints/src/methods/search_is_some.rs [hunk 1]
```diff
@@ -142,3 +156,12 @@ pub(super) fn check<'tcx>(
         }
     }
 }
+
+fn is_receiver_of_method_call(cx: &LateContext<'_>, expr: &hir::Expr<'_>) -> bool {
```
Comment (Manishearth) [inline clippy_lints/src/methods/search_is_some.rs:160]: nit: This should go in `utils/` somewhere (and get some documentation)


And it's possible we already have something like this in utils?

Comment (y21) [reply clippy_lints/src/methods/search_is_some.rs:160]: Shouldn't this also actually check that the receiver hir id matches `expr.hir_id`? Otherwise this can return true for something like `foo.bar(expr)` (the parent of `expr` is a method call because it's an argument, but `expr` is not the receiver).

(Also I wonder if this sort of check would be better done by checking if `expr.precedence() > PREC_PREFIX` ? Method calls aren't the only expressions where parentheses are necessary, I think. Field and index expressions also have higher precedence than `!`)

Comment (Manishearth) [reply clippy_lints/src/methods/search_is_some.rs:160]: Yeah, I hadn't even looked at the implementation.

Checking precedence sounds great!

Comment (yuxqiu) [reply clippy_lints/src/methods/search_is_some.rs:160]: > Shouldn't this also actually check that the receiver hir id matches `expr.hir_id`? Otherwise this can return true for something like `foo.bar(expr)` (the parent of `expr` is a method call because it's an argument, but `expr` is not the receiver).
> 
> (Also I wonder if this sort of check would be better done by checking if `expr.precedence() > PREC_PREFIX` ? Method calls aren't the only expressions where parentheses are necessary, I think. Field and index expressions also have higher precedence than `!`)

Thanks for the heads up! I've updated the code to check that the receiver's hir_id matches the expr's hir_id.

Comment (yuxqiu) [reply clippy_lints/src/methods/search_is_some.rs:160]: Regarding checking the precedence, I have a concern in this case because if we directly check `expr.precedence().order() > PREC_PREFIX` it will always return `true` because `expr` is a `MethodCall` and therefore has `ExprPrecedence::. MethodCall` precedence, which is greater than `PREC_PREFIX`. This means that we will always add a parenthesis to the generated suggestions.

I wonder if it would be better to just create separate cases for these (field access, index access, method call) when checking parent expression.

Comment (yuxqiu) [reply clippy_lints/src/methods/search_is_some.rs:160]: > nit: This should go in `utils/` somewhere (and get some documentation)
> 
> And it's possible we already have something like this in utils? (cc @Alexendoo @blyxyas who might remember)

Sounds good! I can put it in `utils` after we've come to a conclusion of how to implement it.

Comment (y21) [reply clippy_lints/src/methods/search_is_some.rs:160]: > Regarding checking the precedence, I have a concern in this case because if we directly check `expr.precedence().order() > PREC_PREFIX` it will always return `true` because `expr` is a `MethodCall` and therefore has `ExprPrecedence::. MethodCall` precedence, which is greater than `PREC_PREFIX`. This means that we will always add a parenthesis to the generated suggestions.

I meant checking the precedence of the parent expression, which shouldn't always be a method call. For `...find().is_none() && true` the parent is the `&&` expression with a precedence lower than `!` which wouldn't need parentheses (or there might not be a parent expression at all, in which case we also don't need parentheses)

> I wonder if it would be better to just create separate cases for these (field access, index access, method call) when checking parent expression.

On second thought, it probably might be fine. I realized that field and index expressions don't really make sense in this context: there's no way to index into a bool or access any fields, and a bool can't be called either. I think the only type of expression with a higher precedence than `!` that makes sense in this context are method calls.

Comment (yuxqiu) [reply clippy_lints/src/methods/search_is_some.rs:160]: > I meant checking the precedence of the parent expression, which shouldn't always be a method call. For `...find().is_none() && true` the parent is the `&&` expression with a precedence lower than `!` which wouldn't need parentheses (or there might not be a parent expression at all, in which case we also don't need parentheses)

In the case of `foo.bar(expr)`, it doesn't seem to work. As you mentioned, the parent expression of `expr` is a `MethodCall`, which has a higher precedence than `PREC_PREFIX`. Therefore, it seems that we still need to create a separate case for this.

> On second thought, it probably might be fine as is. I realized that field and index expressions don't really make sense in this context: there's no way to index into a bool or access any fields, and a bool can't be called either. I think the only type of expression with a higher precedence than `!` that makes sense in this context are method calls, so the current way of checking it would already cover all cases

Yes, I was thinking about this yesterday. But since Manishearth mentioned yesterday that this function should be in `utils/`, I was thinking that maybe we should implement a generic version of this method.

**Comment by xFrednet** [comment]
Manish is currently pretty busy @ARandomDev99, would you mind giving this a prereview?

File: clippy_lints/src/methods/search_is_some.rs [hunk 2]
```diff
@@ -127,13 +136,18 @@ pub(super) fn check<'tcx>(
                     let string = snippet(cx, search_recv.span, "..");
                     let mut applicability = Applicability::MachineApplicable;
                     let find_arg = snippet_with_applicability(cx, search_arg.span, "..", &mut applicability);
+                    let sugg = if is_receiver_of_method_call(cx, expr) {
+                        format!("(!{string}.contains({find_arg}))")
+                    } else {
+                        format!("!{string}.contains({find_arg})")
+                    };
```
Comment (ARandomDev99) [inline clippy_lints/src/methods/search_is_some.rs:143]: It is a good idea to add tests for this as well, even though it's straightforward.

File: clippy_lints/src/methods/search_is_some.rs (hunk 1 above)
Comment (xFrednet) [reply clippy_lints/src/methods/search_is_some.rs:160]: If we move it into utils, I agree that it should be more generic.

Since the PR has been open so long, I would be okay with merging this with a simpler version and leaving the generic version as a future TODO

File: clippy_lints/src/methods/search_is_some.rs (hunk 2 above)
Comment (yuxqiu) [reply clippy_lints/src/methods/search_is_some.rs:143]: Thank you! I've added more test cases.

**Review by ARandomDev99 — APPROVED** [review]

**Comment by xFrednet** [comment]
This PR is on my todo list for this week.

@ARandomDev99 thank you for the review :heart:

**Review by xFrednet — APPROVED** [review]

**Comment by xFrednet** [comment]
This implementation looks good to me. I like the idea of @Manishearth to have a general util method for this, but that is out of the scope of this PR IMO. Also, since it has been open for such a long time, I'll merge it as is, since the implementation looks good.

Thank you for the fix! :D

---

Let's see if the CI still passes.

@bors r=xFrednet,ARandomDev99
