### PR TITLE
Include async functions in the len_without_is_empty

### LINKED ISSUE #7232: len_without_is_empty triggers for async len methods, but does not accept async is_empty methods
The following will trigger the `len_without_is_empty` error:

```rust
impl Foo {
    pub async fn len(&self) -> usize { ... }
    pub async fn is_empty(&self) -> bool { ... }
}
```

It probably shouldn't expect the exact signature `fn(&self) -> bool`.

### PR DESCRIPTION
**Pull request by mladedav**
fixes #7232

Changes done to the functionality:

Allowing different error types for the functions was disallowed. So the following was linted before but is not after this change
```
impl Foo {
    pub len(&self) -> Result<usize, Error1> { todo!(); }
    pub is_empty(&self) -> Result<bool, Error2> { todo!(); }
}
```

---

changelog: Enhancement: [`len_without_is_empty`]: Now also detects `async` functions
[#10359](https://github.com/rust-lang/rust-clippy/pull/10359)

### CODE REVIEW

**Comment by llogiq** [comment]
fmt and dogfood are still failing; those should be easy to fix.

@rustbot author

**Comment by mladedav** [comment]
The tests are fixed now, hope everything looks fine

@llogiq

File: clippy_lints/src/len_zero.rs [hunk 1]
```diff
@@ -251,33 +252,133 @@ fn check_trait_items(cx: &LateContext<'_>, visited_trait: &Item<'_>, trait_items
...
-fn parse_len_output<'tcx>(cx: &LateContext<'_>, sig: FnSig<'tcx>) -> Option<LenOutput<'tcx>> {
+
+fn extract_future_output<'tcx>(cx: &LateContext<'tcx>, ty: Ty<'tcx>) -> Option<&'tcx PathSegment<'tcx>> {
+    if let ty::Alias(_, alias_ty) = ty.kind() {
+        let def_id = alias_ty.def_id;
+        let hir_map = cx.tcx.hir();
+        let item = hir_map.get_if_local(def_id);
+        let item = item.unwrap();
+
+        if let Node::Item(item) = item {
```
Comment (samueltardieu) [inline clippy_lints/src/len_zero.rs:268]: or could use a unique `if let …` here since you are really matching deeper and deeper with one possible pattern.

File: clippy_lints/src/len_zero.rs [hunk 2]
```diff
@@ -251,33 +252,133 @@ fn check_trait_items(cx: &LateContext<'_>, visited_trait: &Item<'_>, trait_items
...
+            return Some(LenOutput::Integral);
+        }
+
+        if let Res::Def(_, def_id) = res {
+            if cx.tcx.is_diagnostic_item(sym::Option, def_id) {
+                if is_first_generic_integral(segment) {
+                    return Some(LenOutput::Option(def_id));
+                }
+
+                return Some(LenOutput::Option(def_id));
```
[the remark this answers is not in the document]
Comment (mladedav) [reply clippy_lints/src/len_zero.rs:346]: Sorry, this is a bug. `is_first_generic_integral` checks that `len()` returns `Option<T>` where T is an integral type. This should ignore things like `pub fn len() -> Option<String>` because that's what happens for the sync version.

I've added a test for this.

File: clippy_lints/src/len_zero.rs (hunk 1 above)
Comment (mladedav) [reply clippy_lints/src/len_zero.rs:268]: I rewrote this with an if let without nesting. However, it can't be a unique `if let` since at times I want to check some bounds before indexing into an array.

I have collapsed the chains as much as possible though. I personally don't like that much (e.g. I'd rather split
```
        let Some(Node::Item(Item { kind: ItemKind::OpaqueTy(opaque), .. })) = cx.tcx.hir().get_if_local(alias_ty.def_id) &&
        ...
```
into
```
        let Some(Node::Item(item)) = cx.tcx.hir().get_if_local(alias_ty.def_id) &&
        let Item { kind: ItemKind::OpaqueTy(opaque), .. } = item &&
        ...
```
but if you prefer it like this I have no issue with that.

**Comment by mladedav** [comment]
@llogiq

Hi, do you think you will have some time for this PR? I'd like to finish this soI don't forget about it.

File: clippy_lints/src/len_zero.rs [hunk 3]
```diff
@@ -251,33 +252,133 @@ fn check_trait_items(cx: &LateContext<'_>, visited_trait: &Item<'_>, trait_items
...
+enum LenOutput {
     Integral,
     Option(DefId),
-    Result(DefId, Ty<'tcx>),
+    Result(DefId),
 }
-fn parse_len_output<'tcx>(cx: &LateContext<'_>, sig: FnSig<'tcx>) -> Option<LenOutput<'tcx>> {
+
+fn extract_future_output<'tcx>(cx: &LateContext<'tcx>, ty: Ty<'tcx>) -> Option<&'tcx PathSegment<'tcx>> {
+    if let ty::Alias(_, alias_ty) = ty.kind() {
```
[the remark this answers is not in the document]
Comment (llogiq) [reply clippy_lints/src/len_zero.rs]: Nowadays we can even use let chains.

File: clippy_lints/src/len_zero.rs [hunk 4]
```diff
@@ -251,33 +252,98 @@ fn check_trait_items(cx: &LateContext<'_>, visited_trait: &Item<'_>, trait_items
...
 
-impl<'tcx> LenOutput<'tcx> {
-    fn matches_is_empty_output(self, ty: Ty<'tcx>) -> bool {
+impl LenOutput {
+    fn matches_is_empty_output<'tcx>(self, cx: &LateContext<'tcx>, ty: Ty<'tcx>) -> bool {
+        if let Some(segment) = extract_future_output(cx, ty) {
+            return match (self, segment.res) {
+                (_, Res::PrimTy(PrimTy::Bool)) => true,
+                (Self::Option(_), Res::Def(_, def_id)) if cx.tcx.is_diagnostic_item(sym::Option, def_id) => true,
+                (Self::Result(_), Res::Def(_, def_id)) if cx.tcx.is_diagnostic_item(sym::Result, def_id) => true,
```
Comment (llogiq) [inline clippy_lints/src/len_zero.rs:338]:
```suggestion
                (Self::Option(_), Res::Def(_, def_id)) => cx.tcx.is_diagnostic_item(sym::Option, def_id),
                (Self::Result(_), Res::Def(_, def_id)) => cx.tcx.is_diagnostic_item(sym::Result, def_id),
```
I think we don't need guards here.

**Review by llogiq — APPROVED** [review]
r=me after rebase

**Comment by mladedav** [comment]
r= @llogiq
