### PR TITLE
`comparison_to_empty`: peel derefs in suggestions

### LINKED ISSUE #9958: Clippy lint "comparison to empty" fails to apply fix when reference is used
I tried this code:

```rust
fn main() {
    let s = "Hello World!";
    let s1 = &s;
    println!("{}", *s1 != "");
}
```

I expected to see this happen: Clippy applies fix successfully

Instead, this happened: 

Clippy fails to automatically apply fix

<details><summary>Output</summary>
<p>

```
> cargo clippy --fix
    Checking clippy_bug v0.1.0 (/home/mdgaziur001/clippy_bug)
warning: failed to automatically apply fixes suggested by rustc to crate `clippy_bug`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0614]: type `bool` cannot be dereferenced
 --> src/main.rs:4:20
  |
4 |     println!("{}", *s1.is_empty());
  |                    ^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0614`.
Original diagnostics will follow.

warning: comparison to empty slice
 --> src/main.rs:4:20
  |
4 |     println!("{}", *s1 == "");
  |                    ^^^^^^^^^ help: using `is_empty` is clearer and more explicit: `*s1.is_empty()`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#comparison_to_empty
  = note: `#[warn(clippy::comparison_to_empty)]` on by default

warning: `clippy_bug` (bin "clippy_bug") generated 1 warning (run `cargo fix --bin "clippy_bug"` to apply 1 suggestion)
warning: `clippy_bug` (bin "clippy_bug" test) generated 1 warning (1 duplicate)
    Finished dev [unoptimized + debuginfo] target(s) in 1.20s
```
</p>
</details>

### Meta

`rustc --version --verbose`:

Stable:

```
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-unknown-linux-gnu
release: 1.65.0
LLVM version: 15.0.0
```

Beta:

```
rustc 1.66.0-beta.2 (0040709e3 2022-11-20)
binary: rustc
commit-hash: 0040709e39bfa159d099ee14628ad4ac72f91406
commit-date: 2022-11-20
host: x86_64-unknown-linux-gnu
release: 1.66.0-beta.2
LLVM version: 15.0.2
```

Nightly:

```
rustc 1.66.0-beta.2 (0040709e3 2022-11-20)
binary: rustc
commit-hash: 0040709e39bfa159d099ee14628ad4ac72f91406
commit-date: 2022-11-20
host: x86_64-unknown-linux-gnu
release: 1.66.0-beta.2
LLVM version: 15.0.2
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by mdgaziur**
This PR fixes #9958. In order to fix the issue, the lint will now peel reference operators and enclose the expression with parentheses when necessary.

changelog: [`comparison_to_empty`]: Peel deref operators in suggestions when necessary

### CODE REVIEW

File: clippy_lints/src/len_zero.rs [hunk 1]
```diff
@@ -425,8 +425,12 @@ fn check_len(
     }
 }
 
-fn check_empty_expr(cx: &LateContext<'_>, span: Span, lit1: &Expr<'_>, lit2: &Expr<'_>, op: &str) {
+fn check_empty_expr(cx: &LateContext<'_>, span: Span, mut lit1: &Expr<'_>, lit2: &Expr<'_>, op: &str) {
     if (is_empty_array(lit2) || is_empty_string(lit2)) && has_is_empty(cx, lit1) {
+        if let ExprKind::Unary(UnOp::Deref, expr) = lit1.kind {
+            lit1 = expr;
+        }
```
Comment (dswij) [inline clippy_lints/src/len_zero.rs:432]: I think this only covers 1 deref, so 2 derefs or more wouldn't be covered, i.e.

```rust
    let s = "Hello, world!";
    let s1 = &&s;
    println!("{}", **s1 == "");
```

File: tests/ui/len_zero.rs [hunk 2]
```diff
@@ -64,6 +64,10 @@ fn main() {
 
     if "".len() == 0 {}
 
+    let s = "Hello, world!";
+    let s1 = &s;
+    println!("{}", *s1 == "");
+
```
Comment (dswij) [inline tests/ui/len_zero.rs:70]: Let's also add a case for multiple derefs in the test.

**Review by dswij — CHANGES_REQUESTED** [review]
Thanks for the PR, and welcome to Clippy!

Note that for the changelog, it's user-facing changelog. So we'd expect a short explanation of the change itself, rather than pointing it to an issue number/link. Could you help to change that?

Other than that, it's just a small comment on the change itself, and it should be good to go

File: clippy_lints/src/len_zero.rs (hunk 1 above)
Comment (mdgaziur) [reply clippy_lints/src/len_zero.rs:432]: I think getting the expression that is deref'd in a loop can be a solution

Comment (dswij) [reply clippy_lints/src/len_zero.rs:432]: That's one way to do it, but we have a util function that derefs expr

https://github.com/rust-lang/rust-clippy/blob/3cf2c17e53d115bd8c233a268c0d0ff0fbb2395e/clippy_utils/src/lib.rs#L2276-L2287

Maybe we can use that instead

Comment (mdgaziur) [reply clippy_lints/src/len_zero.rs:432]: Another thing I noticed is that, parentheses aren't removed. So, something like the following:
```rs
**(s1) == ""
```
will become:
```rs
(s1).is_empty()
```
Is there any way to remove these redundant parentheses?

Comment (dswij) [reply clippy_lints/src/len_zero.rs]: We have another util to build suggestions, but it needs a little bit more digging:

https://github.com/rust-lang/rust-clippy/blob/78589ffad2c973f7863fdabc2df6e8ab2b54110f/clippy_utils/src/sugg.rs

IIRC, you can remove parentheses with this.

Comment (mdgaziur) [reply clippy_lints/src/len_zero.rs]: Can you tell me what `default` parameter in `Sugg::hir_with_applicability` does?

Comment (mdgaziur) [reply clippy_lints/src/len_zero.rs]: I found out that other lints don't remove the parentheses. Is this ok if I ignore parentheses?
AFAIK, the util you've suggested directly takes snippet from source code and has no method to remove unnecessary parentheses.

Comment (dswij) [reply clippy_lints/src/len_zero.rs]: I think it depends on the lint whether it will suggest removing the parentheses or not. Ideally, we'd have the parentheses removed.

But it's fine if we merge it without removing it in this PR, since the change is already an improvement as it is.

Let me know if you decide not to include the parentheses change in this PR.

Comment (mdgaziur) [reply clippy_lints/src/len_zero.rs]: I think we can ignore parentheses now. Maybe this can be done in future?

**Comment by dswij** [comment]
Thanks for this! @bors r+
