### PR TITLE
Fix redundant_pattern_matching lint

### LINKED ISSUE #5504: FP redundant_pattern_matching: try! macro
This code from serde
````rust
        fn visit_map<M>(self, mut access: M) -> Result<(), M::Error>
        where
            M: MapAccess<'de>,
        {
            while let Some(_) = try!(access.next_entry::<IgnoredAny, IgnoredAny>()) {}
            Ok(())
        }
````

caused the warning
````
warning: redundant pattern matching, consider using `is_some()`
    --> serde/src/private/de.rs:2475:23
     |
2475 |             while let Some(_) = try!(access.next_entry::<IgnoredAny, IgnoredAny>()) {}
     |                       ^^^^^^^   --------------------------------------------------- help: try this: `while _.is_some()`
     |
````

`_.is_some()` does not look like it is going to work :smile: 

`clippy 0.0.212 (891e1a8 2020-04-18)`

### PR DESCRIPTION
**Pull request by alex-700**
fixes #5504 

changelog: Fix suggestion in `redundant_pattern_matching` for macros.

### CODE REVIEW

**Comment by alex-700** [comment]
github was unavailable, so smb need to retry. Hm, interesting, do I have rights to do it.
@bors retry

**Comment by phansch** [comment]
Let's try again =)

@bors retry

File: clippy_lints/src/redundant_pattern_matching.rs [hunk 1]
```diff
@@ -103,14 +103,21 @@ fn find_sugg_for_if_let<'a, 'tcx>(
         arms[0].pat.span,
         &format!("redundant pattern matching, consider using `{}`", good_method),
         |diag| {
-            // in the case of WhileLetDesugar expr.span == op.span incorrectly.
-            // this is a workaround to restore true value of expr.span
-            let expr_span = expr.span.to(arms[1].span);
-            let span = expr_span.until(op.span.shrink_to_hi());
+            // while let ... = ... { ... }
+            // ^^^^^^^^^^^^^^^^^^^^^^^^^^^
+            let expr_span = arms[1].pat.span;
```
Comment (flip1995) [inline clippy_lints/src/redundant_pattern_matching.rs:108]: Wait, what? I don't trust this at all. There is no test for `if let ... {} else if let {}`. I think this could break.

Comment (alex-700) [reply clippy_lints/src/redundant_pattern_matching.rs:108]: > I think this could break.

I don't think so. I'll add this test.

Comment (alex-700) [reply clippy_lints/src/redundant_pattern_matching.rs:108]: done

**Comment by flip1995** [comment]
https://github.com/rust-lang/rust/pull/71494

**Comment by flip1995** [comment]
@alex-700 The `expr.span` should now be as expected, can you change the code accordingly? (you may have to update your master toolchain locally)

**Comment by flip1995** [comment]
Now that suggestion building looks more trustworthy and stable. Thanks! :)

@bors r+
