### PR TITLE
Fix suspicious_map false positives

### LINKED ISSUE #5253: suspicious_map oddity
````rust
fn count_and_sum(numbers: &Vec<u32>) -> (usize, u32)   {
	let mut sum: u32 = 0;
	let count = numbers.iter().map(|n| sum += n).count();

	(count, sum)
}
````

In this example, we use `map` to process all values and do something with them that involves another mutable variable or function, in the end, we use `count()` to get the total number of items processed.

The lint explanation says 
```
Maybe map was confused with filter. If the map call is intentional, this should be rewritten. Or, if you intend to drive the iterator to completion, you can just use for_each instead.
```
But a filter is not useful here. Using `for_each` is out of option since `for_each().count()` does not work since `for_each()` does not return anything.

I'm not sure if `inspect()` is the right choice here, at least it is not noted in the lints description.

### PR DESCRIPTION
**Pull request by camsteffen**
changelog: Fix suspicious_map false positives

Fixes #5253
Replaces #5375

### CODE REVIEW

File: clippy_lints/src/methods/mod.rs [hunk 1]
```diff
@@ -1709,7 +1709,7 @@ impl<'tcx> LateLintPass<'tcx> for Methods {
                 unnecessary_filter_map::lint(cx, expr, arg_lists[0]);
                 filter_map_identity::check(cx, expr, arg_lists[0], method_spans[0]);
             },
-            ["count", "map"] => lint_suspicious_map(cx, expr),
+            ["count", "map"] => lint_suspicious_map(cx, expr, &arg_lists[1][1]),
```
Comment (Y-Nak) [inline clippy_lints/src/methods/mod.rs:1712]: This causes ICE when the below is input
```rust
struct Foo {}
impl Foo {
    fn map(&self) -> Bar {
        Bar {}
    }
}

struct Bar {}
impl Bar {
    fn count(&self) -> usize {
        13
    }
}

fn ice() {
    let foo = Foo {};
    let _ = foo.map().count();
}
```
though this is a really rare case.

**Review by Y-Nak — COMMENTED** [review]
LGTM other than the ICE.

**Comment by camsteffen** [comment]
* Rebased (including methods mod refactor)
* Check arg counts
* Ensure `map` is `Iterator` method

File: clippy_utils/src/lib.rs [hunk 2]
```diff
@@ -138,6 +138,62 @@ pub fn differing_macro_contexts(lhs: Span, rhs: Span) -> bool {
...
+///
+/// // or...
+/// let abc = 1;
+/// let def = abc + 2;
+/// //        ^^^^^^^ output
+/// dbg!(def)
+/// //   ^^^ input
+/// ```
+pub fn expr_or_init<'a, 'b, 'tcx: 'b>(cx: &LateContext<'tcx>, mut expr: &'a Expr<'b>) -> &'a Expr<'b> {
+    while let Some(init) = path_to_local(expr)
```
Comment (Y-Nak) [inline clippy_utils/src/lib.rs:163]: Should `path_to_local` be called in `find_binding_init`? Otherwise, the example of `find_binding_init` doesn't work.
And I think this change would improve the usability of it.

Comment (Y-Nak) [reply clippy_utils/src/lib.rs:163]: Or it would be better to rewrite the example.

Comment (camsteffen) [reply clippy_utils/src/lib.rs:163]: You're right, the example was not correct. I changed the docs for `find_binding_init`.

**Review by Y-Nak — APPROVED** [review]
LGTM!
@flip1995 Ready for final review.

**Comment by flip1995** [comment]
Thanks! @Y-Nak great catch with the ICE, I probably would've missed that.

@bors r+
