### PR TITLE
Fix macro expansion in try_err lint

### LINKED ISSUE #4309: Broken lints sugesstion on `format!` macro
Maybe related to #3630.

### Example

```rust
fn foo(fail: bool) -> Result<i32, String> {
    if fail {
      Err(format!("failed {:?}", fail))?;
    }
    Ok(0)
}
```

### Expected Behavior

```rust
warning: returning an `Err(_)` with the `?` operator
 --> src/lib.rs:3:7
  |
3 |       Err(format!("failed {:?}", fail))?;
  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `return Err(format!("failed {:?}", fail))`
  |
  = note: `#[warn(clippy::try_err)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#try_err
```

### Current Behavior

```rust
warning: returning an `Err(_)` with the `?` operator
 --> src/lib.rs:3:7
  |
3 |       Err(format!("failed {:?}", fail))?;
  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `return Err($ crate :: fmt :: format (format_args ! ($ ($ arg) *)))`
  |
  = note: `#[warn(clippy::try_err)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#try_err
```

### `cargo clippy -V`
clippy 0.0.212 (dc69a5c 2019-07-27)

### PR DESCRIPTION
**Pull request by lzutao**
Fixes #4309

changelog: none

### CODE REVIEW

File: clippy_lints/src/try_err.rs [hunk 1]
```diff
@@ -67,10 +68,15 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TryErr {
 
             then {
                 let err_type = cx.tables.expr_ty(err_arg);
+                let span = if in_macro_or_desugar(err_arg.span) {
+                    span_to_outer_expn(err_arg.span)
```
Comment (flip1995) [inline clippy_lints/src/try_err.rs]: You could use `utils::snippet_with_macro_callsite` here (and `snippet` in the `else` block).

Comment (lzutao) [reply clippy_lints/src/try_err.rs]: Thanks. Done.

**Comment by flip1995** [comment]
Thanks!

@bors r+

---
Funfact: I actually also fixed this some days ago, but forgot to push it and open a PR. Woops 😄
