### PR TITLE
Fix `manual_let_else` FN when diverges on simple enum variant

### LINKED ISSUE #14598: `manual_let_else` not suggesting a fix for match statement
### Summary

An expected suggistion was not made

### Lint Name

manual_let_else

### Reproducer

I tried this code:

```rust
fn main(){
    assert!(bar().is_ok());
}

fn bar() -> Result<bool, &'static str> {
    let value = match foo() {
        Err(_) => return Err("abc"),
        Ok(value) => value,
    };

    Ok(value == 42)
}

#[allow(clippy::unnecessary_wraps)]
fn foo() -> Result<u32, &'static str>  {
    Ok(42)
}

```

I expected this suggestion for the `let value = ...` statement:

```rust
    let Ok(value) = foo() else {
        return Err("abc");
    };
```

Instead, there were no suggestions.

### Version

```text
rustc 1.86.0 (05f9846f8 2025-03-31)
binary: rustc
commit-hash: 05f9846f893b09a1be1fc8560e33fc3c815cfecb
commit-date: 2025-03-31
host: x86_64-unknown-linux-gnu
release: 1.86.0
LLVM version: 19.1.7
```

### PR DESCRIPTION
**Pull request by profetia**
Closes rust-lang/rust-clippy#14598 

Implemented checks for simple enum variants when checking if match arms are disjointed.

changelog: [`manual_let_else`] fix FN when diverges on simple enum variant

### CODE REVIEW

File: clippy_lints/src/manual_let_else.rs [hunk 1]
```diff
@@ -110,6 +113,22 @@ impl<'tcx> QuestionMark {
     }
 }
 
+/// Checks if the patterns of the arms are disjointed. Currently, we only support patterns of enum
+/// variants.
+///
+/// TODO: Support more complex patterns.
+fn is_arms_disjointed(cx: &LateContext<'_>, arm1: &Arm<'_>, arm2: &Arm<'_>) -> bool {
```
Comment (est31) [inline clippy_lints/src/manual_let_else.rs:120]: I think this will return `true` for a case like this (and it shouldn't):

```Rust
enum Foo<T> { Foo(T) }

let v = match Foo::Foo(Some(())) {
    Foo::Foo(Some(_)) => return,
    Foo::Foo(v) => v,
};
```

Comment (profetia) [reply clippy_lints/src/manual_let_else.rs:120]: Thank you!

**Review by dswij — APPROVED** [review]

**Comment by profetia** [comment]
Hmm.. Why isn't this PR merged automatically?

**Comment by samueltardieu** [comment]
The PR are never merged automatically in this repository, the assigned reviewer has to press the "Merge when ready" button.

**Comment by dswij** [comment]
Whoops yeah, I might've forgotten to click the merge button. :sweat_smile:

**Comment by nyurik** [comment]
thank you!
