### PR TITLE
Fix FP of `needless_range_loop` when meeting multidimensional array

### LINKED ISSUE #15068: `needless_range_loop` falsely emmitted with nested indexing
### Summary

Given that `i` is a `Range` iterator (and the likes), if both `vec1[i]` and `vec2[1][i]` exist, clippy would say that `i` is used to index `vec1` only, and suggest a loop over `vec1` instead of a `Range`.

### Lint Name

needless_range_loop

### Reproducer

I tried this code:

```rust
const COUNT: usize = 10;

fn main() {
    let a = vec![vec![0u8; COUNT]; COUNT]; // Must be 2+ dimensions!
    #[allow(clippy::useless_vec)] // irrelevant.
    let b = vec![0u8; COUNT];

    for i in 0..COUNT {
        let _ = a[1][i]; // Doing `a[i]` doesn't send the warning.
        let _ = b[i];
    }
}
```

I saw this happen:

```
the loop variable `i` is used to index `b`
for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
`#[warn(clippy::needless_range_loop)]` on by defaultclippy[needless_range_loop](rust-analyzer-diagnostics-view:/diagnostic%20message%20[0]?0#file:///home/Ryo/dev/rust/mcli/src/commands/clock/mod.rs)
mod.rs(164, 13): consider using an iterator and enumerate(): `(i, <item>)`, `b.iter().enumerate().take(COUNT)`
```

I expected to see this happen:

No warning. In my specific case, it was a `match` statement with 2 arms, one indexing `a` and another indexing `b`, so I only needed one of the arrays - the example isn't made like that to make it as simple as possible.

### Version

```text
rustc 1.87.0 (17067e9ac 2025-05-09)
binary: rustc
commit-hash: 17067e9ac6d7ecb70e50f92c1944e545188d2359
commit-date: 2025-05-09
host: x86_64-unknown-linux-gnu
release: 1.87.0
LLVM version: 20.1.1
```

### Additional Labels

@rustbot label +L-style

### PR DESCRIPTION
**Pull request by relaxcn**
Fixes  rust-lang/rust-clippy#15068

changelog: Fix [`needless_range_loop`] false positive and false negative when meeting multidimensional array

### CODE REVIEW

File: clippy_lints/src/loops/needless_range_loop.rs [hunk 1]
```diff
@@ -252,13 +252,31 @@ struct VarVisitor<'a, 'tcx> {
...
+            .filter(|&&idx| is_local_used(self.cx, idx, self.var))
+            .collect();
+
+        match used_idxs.len() {
+            0 => return true,
+            n if n > 1 => self.nonindex = true, // Optimize code like `a[i][i]`
+            _ => {},
+        }
+
+        let index_used_directly = used_idxs.iter().all(|idx| matches!(idx.kind, ExprKind::Path(_)));
```
Comment (Jarcho) [inline clippy_lints/src/loops/needless_range_loop.rs]: This whole thing can be done as:
```rust
let mut count = 0;
let mut used_directly = true;

peel_hir_expr_while(seq_expr, |e| {
  if let ExprKind::Index(e, idx, _) = e.kind {
    if is_local_used(self.cx, idx, self.var) {
      count += 1;
      used_directly |= matches!(idx.kind, ExprKind::Path(_));
    }
    Some(e)
  } else {
    None
  }
})
```

You'll have to handle the initial index, but this avoids allocating.

Comment (relaxcn) [reply clippy_lints/src/loops/needless_range_loop.rs]: Good idea!
Thank you, I don't know this useful function before.

File: clippy_lints/src/loops/needless_range_loop.rs [hunk 2]
```diff
@@ -320,7 +346,7 @@ impl<'tcx> Visitor<'tcx> for VarVisitor<'_, 'tcx> {
                 .and_then(|def_id| self.cx.tcx.trait_of_assoc(def_id))
             && ((meth.ident.name == sym::index && self.cx.tcx.lang_items().index_trait() == Some(trait_id))
                 || (meth.ident.name == sym::index_mut && self.cx.tcx.lang_items().index_mut_trait() == Some(trait_id)))
-            && !self.check(args_1, args_0, expr)
+                && !self.check(args_1, args_0, expr)
```
Comment (Jarcho) [inline clippy_lints/src/loops/needless_range_loop.rs]: nit: formatting error. The earlier comment causes rustfmt to give up. I would just delete it since it doesn't really say anything useful.

Comment (relaxcn) [reply clippy_lints/src/loops/needless_range_loop.rs]: Is it a bug in rustfmt?

Comment (Jarcho) [reply clippy_lints/src/loops/needless_range_loop.rs]: It doesn't handle comments inside an expression.

Comment (relaxcn) [reply clippy_lints/src/loops/needless_range_loop.rs]: Thank you for your explanation.

I have deleted the comment and performed fmt command.

**Review by Jarcho — APPROVED** [review]
Thank you.

**Comment by shionryuu** [comment]
This fix is a bit strange for the following code

```rust
        let mut ch = b'`';
        for i in 0..26 {
            let cnt = prefix[right][i] - prefix[left][i];
            if cnt > 0 && cnt < k {
                ch = b'a' + i as u8;
                break;
            }
        }
```

```text
error: the loop variable `i` is used to index `prefix`
  --> src/n0395_longest_substring_with_at_least_k_repeating_characters.rs:66:18
   |
66 |         for i in 0..26 {
   |                  ^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator and enumerate()
   |
66 -         for i in 0..26 {
66 +         for (i, <item>) in prefix.iter().enumerate().take(26) {
   |
```

**Comment by relaxcn** [comment]
Yes. It looks strange because the lint doesn't handle multidimensional array very well. This PR only enables it to detect the usage in non-first index.
So I think we need to consider a general methods to handle multi-dimensional arrays.
Sorry for the new bug, I will look at it later when I have more time or someone else could fix it.
