### PR TITLE
Make `approx_const` MSRV aware

### LINKED ISSUE #7623: `approx_const` not MSRV aware
Lint name: approx_const

I tried this code:

```rust
#![feature(custom_inner_attributes)]
#![clippy::msrv = "1.30.0"]

fn main() {
    let _log2_10 = 3.321928095f64; 
    let _log10_2 = 0.301029995f64;
}
```

I expected to see this happen:
No warnings. The `LOG2_10`  and `LOG10_2` consts where added in 1.43.

Instead, this happened:
```
error: approximate value of `f64::consts::LOG2_10` found. Consider using it directly
 --> src/main.rs:5:20
  |
5 |     let _log2_10 = 3.321928095f64; 
  |                    ^^^^^^^^^^^^^^
  |
  = note: `#[deny(clippy::approx_constant)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#approx_constant

error: approximate value of `f64::consts::LOG10_2` found. Consider using it directly
 --> src/main.rs:6:20
  |
6 |     let _log10_2 = 0.301029995f64;
  |                    ^^^^^^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#approx_constant
```

### PR DESCRIPTION
**Pull request by mikerite**
changelog: [`approx_const`]: Add MRSV checks for LOG10_2 and LOG2_10.

Fixes #7623

### CODE REVIEW

File: clippy_lints/src/approx_const.rs [hunk 1]
```diff
@@ -36,68 +38,83 @@ declare_clippy_lint! {
...
+                    span_lint(
+                        cx,
+                        APPROX_CONSTANT,
+                        e.span,
+                        &format!(
+                            "approximate value of `{}::consts::{}` found. \
+                             Consider using it directly",
+                            module, &name
+                        ),
+                    );
```
Comment (xFrednet) [inline clippy_lints/src/approx_const.rs:100]: This lint message already contains a help message. I would suggest using `span_lint_and_help` here instead.

File: clippy_lints/src/lib.rs [hunk 2]
```diff
@@ -1894,6 +1893,7 @@ pub fn register_plugins(store: &mut rustc_lint::LintStore, sess: &Session, conf:
     });
 
     let avoid_breaking_exported_api = conf.avoid_breaking_exported_api;
+    store.register_late_pass(move || Box::new(approx_const::ApproxConstant::new(msrv)));
```
Comment (xFrednet) [inline clippy_lints/src/lib.rs:1896]: Could you also add the lint name `APPROX_CONSTANT` to the `msrv` documentation to have it show up in the lint documentation?

https://github.com/rust-lang/rust-clippy/blob/a8c2c7b712c273f13258de8b87b233918d8726b9/clippy_lints/src/utils/conf.rs#L135-L138

**Review by xFrednet — COMMENTED** [review]
Thank you for the work, your changes already look excellent. I've just found two NITs that should be addressed before merging this :upside_down_face:

**Review by xFrednet — APPROVED** [review]
Looks good to me! Thank you very much for the quick changes :upside_down_face:
