### PR TITLE
Fix float_cmp false positive when comparing signum

### LINKED ISSUE #4248: float_cmp should not apply to results of signum()
Hello,

It seems to me that clippy should allow the results of two calls to `f{32, 64}::signum()` to be compared, e.g a contrived example:

```rust
fn signs_agree(f1: f64, f2: f64) -> bool {
   return f1.signum() == f2.signum()
}
```

results in:

```
error: strict comparison of f32 or f64
 --> src/main.rs:3:4
  |
3 |    f1.signum() == f2.signum()
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider comparing them within some error: `(f1.signum() - f2.signum()).abs() < error`
  |
  = note: #[deny(clippy::float_cmp)] on by default
note: std::f32::EPSILON and std::f64::EPSILON are available.
 --> src/main.rs:3:4
  |
3 |    f1.signum() == f2.signum()
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#float_cmp
```

### PR DESCRIPTION
**Pull request by jayhardee9**
fixes #4248

changelog: Fix float_cmp false positive when comparing signum

### CODE REVIEW

File: clippy_lints/src/misc.rs [hunk 1]
```diff
@@ -493,6 +499,25 @@ fn is_allowed<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, expr: &'tcx Expr) -> bool {
     }
 }
 
+// Return true if `expr` is the result of `signum()` invoked on a float value.
+fn is_signum(cx: &LateContext<'_, '_>, expr: &Expr) -> bool {
+    // The negation of a signum is still a signum
```
Comment (flip1995) [inline clippy_lints/src/misc.rs]: Nice, good catch!

Lint idea (for another PR):
```rust
// for
f1.signum() == -f2.signum()
// suggest
f1.signum() != f2.signum()
```

Same goes for `-sig==+sig` and `-sig==-sig` and the `!=` variants.

**Comment by flip1995** [comment]
Thanks!

@bors r+

File: clippy_lints/src/misc.rs (hunk 1 above)
Comment (jayhardee9) [reply clippy_lints/src/misc.rs]: Thanks! I'm not sure that's the best way to simplify `f1.signum() == -f2.signum()`, since if both `f1` and `f2` are 0, then also `f1.signum() == f2.signum() == 0`.

Comment (flip1995) [reply clippy_lints/src/misc.rs]: Oh your right, in this case we can't really lint this. Never mind then :D
