### PR TITLE
Dereference one less on search_is_some and make it auto-fixable

### LINKED ISSUE #4453: Wrong suggestion in search_is_some lint
It's pretty much the same as #4033. The closure argument of `any` needs one dereference less than the closure argument of `find`. 

```rust
fn main() {
    let vec = vec![1];
    let _ = vec.iter().find(|x| **x == 0).is_some();
    // let _ = vec.iter().any(|x| **x == 0); // <- this is suggested
    let _ = vec.iter().any(|x| *x == 0); // <- this should be suggested
}
``` 

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6a1ef5d4137c996d3ea4c7e4d7cf86f0)

_Originally posted by @BO41 in https://github.com/rust-lang/rust-clippy/pull/4436#discussion_r317351872_

### PR DESCRIPTION
**Pull request by BO41**
Fixes #4453

changelog: none

### CODE REVIEW

**Comment by BO41** [comment]
@flip1995 do you think this is enough, or is some logic required?
If so, could you mentor me?

I can make it autofixable :wink: 

How can I run doc tests? `cargo test --doc SEARCH_IS_SOME` doesn't work for me :/

**Comment by phansch** [comment]
> How can I run doc tests? cargo test --doc SEARCH_IS_SOME doesn't work for me :/
I think you'll first have to change to the `clippy_lints` directory for them to work.

File: clippy_lints/src/methods/mod.rs [hunk 1]
```diff
@@ -2367,14 +2367,18 @@ fn lint_search_is_some<'a, 'tcx>(
...
                 let closure_body = cx.tcx.hir().body(body_id);
                 if let Some(closure_arg) = closure_body.arguments.get(0);
-                if let hir::PatKind::Ref(..) = closure_arg.pat.node;
                 then {
-                    Some(search_snippet.replacen('&', "", 1))
+                    if let hir::PatKind::Ref(..) = closure_arg.pat.node {
+                        Some(search_snippet.replacen('&', "", 1).replacen("**", "*", 1))
+                    } else {
+                        Some(search_snippet.replacen("**", "*", 1))
+                    }
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: IIUC, the `search_snippet` is the whole closure in the `find` call. The `replacen` for the `|&_|` only works, because the closure is guaranteed to start with `|&_|`.

The deref has 3 problems: 
1. Not only the closure arg can be derefed: `(0..1).find(|x| **y == *x)`
2. It may be derefed only once or multiple times: `(0..1).find(|x| *x == 0).is_some()`
3. When the closure arg already has `PatKind::Ref`, then the amount of derefs must stay the same. (This is the easy case)

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dbf6bc1a804768b1d2e1aa3e12feaba8) for the three examples. (Please also add these as tests, if they don't exist yet.)

So to answer your question:

> do you think this is enough, or is some logic required?

There is some logic required. Since we currently only emit the suggestion, when the closure is a one-liner, I think it is save to say, that the closure arguments doesn't get shadowed. This means, you have to get the `Ident` of the closure arg and then replace every occurrence of `*<ident-name>` with `<ident-name>`.

---
To do it right, and also accounting for shadowing of the closure arg, we would have to write a visitor, that searches for occurrences of `Deref(<closure_arg>)` and then only replace these derefs. But I **really** don't think, that this is necessary.

**Comment by BO41** [comment]
I though this would be easier and the code better to understand. But it seems that I am not capable of fixing the issue :cry:

**Comment by flip1995** [comment]
Your not really far from the goal, and I'm happy to support you to achieve it!

- You already have the closure argument: `closure_arg`
- You only need to care about closure arguments, that are `PatKind::Lit(expr)`
- Get the `closure_arg_snip = snippet(expr)` (This is the name of the closure argument)
- Run `search_snippet.replace(&format!("*{}", closure_arg_snip), &closure_arg_snip)`

For test cases, see [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=578347a9f993b4d5ea6f76c823a457a3)

**Comment by BO41** [comment]
> I think you'll first have to change to the `clippy_lints` directory for them to work.

Thanks you. That worked :smiley:

**Comment by BO41** [comment]
@flip1995 thank you for the help :+1: 

Are you sure I need `closure_arg` and not the closure_body.value?
PatKind::Lit never finds a match

**Comment by flip1995** [comment]
Huh, I'm pretty sure that you need `closure_arg`. `body.value` is the actual body of the closure.

It should find a match for `_.find(|x| ..)`, except something else is meant by `PatKind::Lit`. What you can do to find out the correct `PatKind` for closures like this, is to add a `dbg!(closure_arg.node)` to the code and then look at the stderr output, when running the testcase: `TESTNAME=ui/<name_of_search_is_some_test_without_.rs> cargo +master uitest`

**Comment by BO41** [comment]
```
LL |     let _ = (0..1).find(|x| *x == 0).is_some();
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `any(|x| x == 0)`
```
it seems like the lint isn't very exact. This causes rust-fix to replace everything with just `any(...)`
```
let _ = any(|x| x == 0);
```

Or did I do something wrong?

**Comment by flip1995** [comment]
Rustfix always replaces the span you specify with the suggested code. You have to build the span by hand, since it does not exist in the way you need it. This shouldn't be a problem though. Just grep the `methods/mod.rs` file for `span.with_hi` to see how to do this.

**Comment by BO41** [comment]
> Rustfix always replaces the span you specify with the suggested code

so I should be able to replace `expr.span,` with a formatted `{0}({1}).is_some()`, right?

**Comment by flip1995** [comment]
No, because the `expr.span` is everything from the iterator expression (`(0..1).` in the example above, or e.g. `vec.iter().`) up to the call of `is_some()`. Or in other words, everything that is indicated by the `^`  in the error message.

You only want to replace the `find(..).is_some()` with `any(..)` though. That means you have to construct a span, that starts at `find...` and ends at `...some()`. You already have a span that ends at `...some()`: `expr.span`. Now you need a span that starts with `find...`.

---

I just looked up how to get this span, and saw, that it is not that easy (and not really easy to explain the changes that need to be made). So I decided to write a patch for you, that simplifies this. (I'll notify you once it's ready)

While looking into this, I found, that there already exists a function to get the name of the closure arg:
https://github.com/rust-lang/rust-clippy/blob/949b347f654f40ed7e4ab9dedb9e2c9b0a8c2133/clippy_lints/src/utils/mod.rs#L916-L922

You can just use this.

**Comment by flip1995** [comment]
Here's the patch: https://github.com/flip1995/rust-clippy/commits/method_calls_spans

You can look at the most recent commit on the branch on how to use the method spans.

**Comment by BO41** [comment]
almost worked

File: clippy_lints/src/methods/mod.rs [hunk 2]
```diff
@@ -1020,11 +1020,11 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for Methods {
             ["map", "find"] => lint_find_map(cx, expr, arg_lists[1], arg_lists[0]),
             ["flat_map", "filter"] => lint_filter_flat_map(cx, expr, arg_lists[1], arg_lists[0]),
             ["flat_map", "filter_map"] => lint_filter_map_flat_map(cx, expr, arg_lists[1], arg_lists[0]),
-            ["flat_map", ..] => lint_flat_map_identity(cx, expr, arg_lists[0]),
+            ["flat_map", ..] => lint_flat_map_identity(cx, expr, arg_lists[0], method_spans[0]),
             ["flatten", "map"] => lint_map_flatten(cx, expr, arg_lists[1]),
-            ["is_some", "find"] => lint_search_is_some(cx, expr, "find", arg_lists[1], arg_lists[0]),
-            ["is_some", "position"] => lint_search_is_some(cx, expr, "position", arg_lists[1], arg_lists[0]),
-            ["is_some", "rposition"] => lint_search_is_some(cx, expr, "rposition", arg_lists[1], arg_lists[0]),
+            ["is_some", "find"] => lint_search_is_some(cx, expr, "find", arg_lists[1], arg_lists[0], method_spans[0]),
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
            ["is_some", "find"] => lint_search_is_some(cx, expr, "find", arg_lists[1], arg_lists[0], method_spans[1]),
```

the method/span lists are sorted with the most recent call first.

Comment (flip1995) [reply clippy_lints/src/methods/mod.rs]: Bonus points if you add this to the documentation of the `utils::method_calls` function :smile:

Comment (BO41) [reply clippy_lints/src/methods/mod.rs]: the code suggestion is still wrong :man_shrugging:

**Comment by phansch** [comment]
Sorry about the merge conflict, let me know if I can help resolving it =)

**Comment by flip1995** [comment]
That was my fault in 6035b65, so I'd also resolve it for you, if need be.

**Comment by BO41** [comment]
I don't get what is going on.
Rebasing just broke my lint again 
2019-08-29-173031_556x75_scrot

Please fix it for me :)

File: clippy_lints/src/methods/mod.rs (hunk 2 above)
Comment (flip1995) [reply clippy_lints/src/methods/mod.rs]: The span is correct now and thanks for adding the note to the docs :tada:

The replacement of the suggestion doesn't work, for some reason. Also I don't think that the `tests/ui/methods.rs` file is ready that `run-rustfix` is possible. You can either leave this comment out or extract the tests for `search_is_some` in another file.

It would be great if you could use the `get_arg_name` function I mentioned [above](https://github.com/rust-lang/rust-clippy/pull/4454#issuecomment-525639427)

**Comment by flip1995** [comment]
Done :+1:

File: tests/ui/methods.stderr [hunk 3]
```diff
@@ -139,16 +139,27 @@ LL | |                    ).next();
...
    |
    = note: `-D clippy::search-is-some` implied by `-D warnings`
-   = note: replace `find(|&x| *x < 0).is_some()` with `any(|x| *x < 0)`
 
 error: called `is_some()` after searching an `Iterator` with find. This is more succinctly expressed by calling `any()`.
-  --> $DIR/methods.rs:268:13
+  --> $DIR/methods.rs:267:20
+   |
+LL |     let _ = (0..1).find(|x| **y == *x).is_some(); // one dereference less
+   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `any(|x| **y == *x)`
```
Comment (BO41) [inline tests/ui/methods.stderr]: this suggestion is still wrong

Comment (BO41) [reply tests/ui/methods.stderr]: as well as `any(|x| *x == 0)`

Comment (flip1995) [reply tests/ui/methods.stderr]: Yes, it seems that the replacement does not work.

Comment (BO41) [reply tests/ui/methods.stderr]: it worked at this point https://github.com/rust-lang/rust-clippy/pull/4454#issuecomment-524998966 
Some of the changes did break it again. But I don't understand the code enough to get it back working

Comment (flip1995) [reply tests/ui/methods.stderr]: Ah, I try to look into this, this evening. :+1:

File: clippy_lints/src/methods/mod.rs [hunk 4]
```diff
@@ -2386,31 +2393,34 @@ fn lint_search_is_some<'a, 'tcx>(
...
             let any_search_snippet = if_chain! {
                 if search_method == "find";
                 if let hir::ExprKind::Closure(_, _, body_id, ..) = search_args[1].node;
                 let closure_body = cx.tcx.hir().body(body_id);
                 if let Some(closure_arg) = closure_body.params.get(0);
                 if let hir::PatKind::Ref(..) = closure_arg.pat.node;
+                if let Some(name) = get_arg_name(&closure_arg.pat);
                 then {
-                    Some(search_snippet.replacen('&', "", 1))
+                    Some(search_snippet.replacen('&', "", 1).replace(&format!("*{}", name), &name.to_string()))
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: Ah found it: You only trigger this lint, when the `PatKind` is `Ref(..)`. Maybe my suggestion with `get_arg_name()` was a little bit misleading. What I had in mind was: First removing `if let PatKind::Ref ...` from the `if_chain!`. In the then block you can do following:
```rust
if let hir::PatKind::Ref(..) = closure_arg.pat.node {
    Some(search_snippet.replacen('&', "", 1))
} else if let Some(name) = get_arg_name(&closure_arg.pat) {
    Some(search_snippet.replace(&format!("*{}", name), &name.as_str()))
} else {
    None
}
```

**Comment by flip1995** [comment]
Could you add a test case where `x` is derefed multiple times:
```rust
let _ = vec.iter().find(|x| **x == 0).is_some();
```

File: clippy_lints/src/methods/mod.rs [hunk 5]
```diff
@@ -2386,31 +2393,39 @@ fn lint_search_is_some<'a, 'tcx>(
         let search_snippet = snippet(cx, search_args[1].span, "..");
         if search_snippet.lines().count() <= 1 {
             // suggest `any(|x| ..)` instead of `any(|&x| ..)` for `find(|&x| ..).is_some()`
+            // suggest `any(|..| *..)` instead of `any(|..| **..)` for `find(|..| **..).is_some()`
             let any_search_snippet = if_chain! {
                 if search_method == "find";
                 if let hir::ExprKind::Closure(_, _, body_id, ..) = search_args[1].node;
                 let closure_body = cx.tcx.hir().body(body_id);
                 if let Some(closure_arg) = closure_body.params.get(0);
                 if let hir::PatKind::Ref(..) = closure_arg.pat.node;
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: You also have to remove this line. After that, this should be ready to merge :tada:

**Comment by flip1995** [comment]
Ok one last change and a run of `./util/dev fmt` and this is ready to merge. Sorry that this was harder, than expected. I'm really bad when it comes to judging if an issue is a `good first issue` :smile:

**Comment by flip1995** [comment]
Thanks!

@bors r+
