### PR TITLE
compiletest: Disambiguate extern crate deps shared with the compiler

### LINKED ISSUE #4015: Tests failing with multiple matching crates for `serde`
https://github.com/rust-lang/rust/pull/60053 broke the Clippy tests. Specifically `tests/ui/serde.rs` fails with:

```
error[E0464]: multiple matching crates for `serde`
  --> $DIR/serde.rs:4:1
   |
LL | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^
   |
   = note: candidates:
           crate `serde`: /home/<user>/code/rust-clippy/target/debug/deps/libserde-3ec33c1c405dbd9a.rlib
           crate `serde`: /home/<user>/.rustup/toolchains/master/lib/rustlib/x86_64-unknown-linux-gnu/lib/libserde-4b8bb77bdaea80db.rlib

error[E0463]: can't find crate for `serde`
  --> $DIR/serde.rs:4:1
   |
LL | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0463`.
```

I'm not really sure how fix this. Maybe somewhere in compiletest-rs? The error still happens with a clean Rust master installation. Can we somehow ignore the sysroot serde?

cc https://github.com/laumann/compiletest-rs/issues/114, https://github.com/rust-lang/rust/issues/24853

### PR DESCRIPTION
**Pull request by Xanewok**
Fixes #4015.

changelog: Handle deps shared with the compiler in the internal compiletest suite

Attempts to fix the multiple matching crates error using the `--extern dep=path` disambiguation. This only includes `serde` at the moment because it's the only problematic dep right now (is inside Rust sysroot and pulled via `extern crate` in the test suite).

I'm not exactly sure this is the right approach (FWIW it fixes the issue locally), please do tell if this should be done differently.

### CODE REVIEW

**Comment by oli-obk** [comment]
Oh wow, this is cool. Although I think we should try to upstream stuff like this to compiletest-rs, we can play with it here until we have the kinks worked out.

You have a dogfood failure (basically make the entire thing one big `filter_map` instead of many methods).

File: tests/compile-test.rs [hunk 1]
```diff
@@ -46,9 +46,33 @@ fn config(mode: &str, dir: PathBuf) -> compiletest::Config {
...
+    // `--extern dep=path`.
+    // See https://github.com/rust-lang/rust-clippy/issues/4015.
+    let needs_disambiguation = ["serde"];
+    // This assumes that deps are compiled (they are for Cargo integration tests).
+    let deps = std::fs::read_dir(host_libs().join("deps")).unwrap();
+    let disambiguated = deps
+        .filter_map(|dep| dep.ok().map(|x| x.path()))
+        .filter(|path| path.file_name().is_some())
+        .filter_map(|path| {
+            let name = path.file_name().unwrap().to_string_lossy();
```
Comment (Xanewok) [inline tests/compile-test.rs]: Any idea how to avoid the `is_some()`/`unwrap()` dance?
I tried naively to do
```rust
filter_map(|path| path.file_name().map(move |name| (path, name)|)
```
before but then I get lifetime errors because I'm returning `(PathBuf, &OsStr)` which borrows from it; ideally I'd just borrow everything for the same lifetime and be done with it

Comment (oli-obk) [reply tests/compile-test.rs]: The problem is the fact that you are trying to make the references live across multiple `filter_*` calls. If you use a single call, it works out:

```rust
    let disambiguated = deps
        .filter_map(|dep| {
            let path = dep.ok()?.path();
            let name = path.file_name()?.to_string_lossy();
            // NOTE: This only handles a single dep
            // https://github.com/laumann/compiletest-rs/issues/101
            needs_disambiguation
                .iter()
                .find(|dep| name.starts_with(&format!("lib{}-", dep)))
                .map(|dep| format!("--extern {}={}", dep, path.display()))
        })
        .collect::<Vec<_>>();
```

Comment (Xanewok) [reply tests/compile-test.rs]: Ah, I forgot that question mark works at the closure boundaries! Nice, let me update this real quick
