### PR TITLE
fix: `redundant_clone` FP in overlapping lifetime

### LINKED ISSUE #13900: FP redundant-clone  impl trait
### Summary

.

### Lint Name

redundant-clone

### Reproducer

I tried this code:

```rust
use std::fmt::Display;

fn foo(f: impl Display + Clone) -> String {
    let g = f.clone();
    format!("{} + {}", f, g)
}

fn main() {
    let sum = foo("22".to_string());
    assert_eq!(sum, r"22 + 22");
}
```

I saw this happen:

```
warning: redundant clone
 --> src/main.rs:4:14
  |
4 |     let g = f.clone();
  |              ^^^^^^^^ help: remove this
  |
note: cloned value is neither consumed nor mutated
 --> src/main.rs:4:13
  |
4 |     let g = f.clone();
  |             ^^^^^^^^^
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone
  = note: requested on the command line with `-W clippy::redundant-clone`
```

this breaks the code:

```
error[E0382]: borrow of moved value: `f`
 --> src/main.rs:5:24
  |
3 | fn foo(f: impl Display + Clone) -> String {
  |        - move occurs because `f` has type `impl Display + Clone`, which does not implement the `Copy` trait
4 |     let g = f;
  |             - value moved here
5 |     format!("{} + {}", f, g)
  |                        ^ value borrowed here after move
  |
  = note: this error originates in the macro `$crate::__export::format_args` which comes from the expansion of the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider cloning the value if the performance cost is acceptable
  |
4 |     let g = f.clone();
  |              ++++++++
help: consider restricting opaque type `impl Display + Clone` with trait `Copy`
  |
3 | fn foo(f: impl Display + Clone + std::marker::Copy) -> String {
  |                                +++++++++++++++++++

error: aborting due to 1 previous error
```

### Version

```text
rustc 1.85.0-nightly (8742e0556 2024-12-28)
binary: rustc
commit-hash: 8742e0556dee3c64f7144de2fb2e88936418865a
commit-date: 2024-12-28
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.6
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by profetia**
fixes #13900 

changelog: [`redundant_clone`]: fix FP in overlapping lifetime

### CODE REVIEW

File: clippy_lints/src/redundant_clone.rs [hunk 1]
```diff
@@ -333,6 +343,8 @@ fn base_local_and_movability<'tcx>(
 struct CloneUsage {
     /// Whether the cloned value is used after the clone.
     cloned_used: bool,
+    /// The first location where the cloned value is used, if any.
+    cloned_use_loc: Option<mir::Location>,
```
Comment (samueltardieu) [inline clippy_lints/src/redundant_clone.rs:347]: Doesn't that make `cloned_used` redundant, according to the doc comments?

File: clippy_lints/src/redundant_clone.rs [hunk 2]
```diff
@@ -370,6 +383,7 @@ fn visit_clone_usage(cloned: mir::Local, clone: mir::Local, mir: &mir::Body<'_>,
     } else {
         CloneUsage {
             cloned_used: true,
+            cloned_use_loc: None,
```
Comment (samueltardieu) [inline clippy_lints/src/redundant_clone.rs:386]: And here, it looks like this is contradictory. Is the doc comment for `cloned_used` or `cloned_use_loc` wrong or incomplete?

Couldn't `cloned_used` be removed completely, as it seems to be set iff `cloned_consumed_or_mutated` is `true` or `cloned_use_loc` is `Some`.

Comment (profetia) [reply clippy_lints/src/redundant_clone.rs:386]: I leave it as is because I don't quite understand why `clone_used` is set `true` in the else branch. Anyway, I'll remove it and see what happens.

File: clippy_lints/src/redundant_clone.rs (hunk 1 above)
Comment (profetia) [reply clippy_lints/src/redundant_clone.rs]: Fixed

**Comment by profetia** [comment]
r? clippy

**Comment by profetia** [comment]
r? clippy

**Comment by profetia** [comment]
r? clippy

**Comment by profetia** [comment]
r? clippy

**Review by samueltardieu — CHANGES_REQUESTED** [review]
The following is a false positive and the suggestion will cause an error:

```rust
    let mut a = String::new();
    let mut b = String::new();
    for _ in 1..10 {
        b = a.clone();
    }
```

This shows in the lintcheck run.

File: clippy_lints/src/redundant_clone.rs [hunk 3]
```diff
@@ -368,7 +375,7 @@ fn visit_clone_usage(cloned: mir::Local, clone: mir::Local, mir: &mir::Body<'_>,
         }
     } else {
         CloneUsage {
-            cloned_used: true,
+            cloned_use_loc: Some(mir::Location::START), // Maybe used so we return a dummy value
```
Comment (samueltardieu) [inline clippy_lints/src/redundant_clone.rs:378]: Using a dummy value from another type is rarely a good idea, and there is a global movement in rustc code to not to that (currently on symbols on keywords).

Maybe an enumeration with three variants (`Unknown`, `Unused`, `Used(mir::Location)`) would make it clearer to follow what happens. What do you think?

**Review by samueltardieu — CHANGES_REQUESTED** [review]
Could you add the test case that would wrongly trigger the lint (the assignment in a loop) so that it can act as a non regression test?

File: clippy_lints/src/redundant_clone.rs (hunk 3 above)
Comment (profetia) [reply clippy_lints/src/redundant_clone.rs]: Good idea! Updated.

**Comment by samueltardieu** [comment]
Looks good, thanks!
