### PR TITLE
Fix `#[allow]` for `module_name_repetitions` & `single_component_path_imports`

### LINKED ISSUE #7511: Re-exports do not allow item-style allow(clippy::module_name_repetitions) attributes
Lint name: `module_name_repetitions`, `useless_attribute`.

I tried this code:

```rust
#![warn(clippy::all)]
#![warn(clippy::pedantic)]

extern crate regex; // 1.5.4

pub mod capture {
    pub use regex::CaptureNames;
}

pub mod split {
    #[allow(clippy::module_name_repetitions)]
    pub use regex::SplitN;
}

pub mod sub {
    #![allow(clippy::module_name_repetitions)]

    pub use regex::SubCaptureMatches;
}

fn main() {}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=773e01d26c21788a14417433d240e745

I expected to see this happen: Only the `CaptureNames` re-export triggers a lint warning.

Instead, this happened: `SplitN` triggers a useless attribute warning, which differs from the behavior of applying the `allow(clippy:: module_name_repetitions)` pragma to an item.

```
    Checking playground v0.0.1 (/playground)
warning: item name starts with its containing module's name
 --> src/main.rs:7:5
  |
7 |     pub use regex::CaptureNames;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/main.rs:2:9
  |
2 | #![warn(clippy::pedantic)]
  |         ^^^^^^^^^^^^^^^^
  = note: `#[warn(clippy::module_name_repetitions)]` implied by `#[warn(clippy::pedantic)]`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#module_name_repetitions

warning: useless lint attribute
  --> src/main.rs:11:5
   |
11 |     #[allow(clippy::module_name_repetitions)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: if you just forgot a `!`, use: `#![allow(clippy::module_name_repetitions)]`
   |
note: the lint level is defined here
  --> src/main.rs:1:9
   |
1  | #![warn(clippy::all)]
   |         ^^^^^^^^^^^
   = note: `#[warn(clippy::useless_attribute)]` implied by `#[warn(clippy::all)]`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_attribute

warning: `playground` (bin "playground") generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.53s
```

### Meta

Rust 1.54.0 in the playground.

### LINKED ISSUE #8768: Is it possible to allow `single_component_path_imports` for an individual `use`?
### Summary

I use `rstest_reuse`, which [requires](https://docs.rs/rstest_reuse/0.3.0/rstest_reuse/#cavelets) being `use`d at the top level of the crate because of how its macros work. The `single_component_path_imports` lint (correctly) flags this, but I need it to be that way, and I can't figure out how to allow that lint for just that one `use`. I can disable the offending lint globally with `#!allow`, but I'd rather not do that as it's generally a valid lint.

### Reproducer

I tried this code:

```rust
#[cfg(test)]
use rstest_reuse;
```

I saw this happen:

```
error: this import is redundant
   --> src/lib.rs:100:1
    |
100 | use rstest_reuse;
    | ^^^^^^^^^^^^^^^^^ help: remove it entirely
    |
note: the lint level is defined here
   --> src/lib.rs:86:5
    |
86  |     warnings
    |     ^^^^^^^^
    = note: `#[deny(clippy::single_component_path_imports)]` implied by `#[deny(warnings)]`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_component_path_imports
```

So I added an `allow`:

```rust
#[cfg(test)]
#[allow(clippy::single_component_path_imports)]
use rstest_reuse;
```

and now two lints are mad:

```
error: this import is redundant
   --> src/lib.rs:100:1
    |
100 | use rstest_reuse;
    | ^^^^^^^^^^^^^^^^^ help: remove it entirely
    |
note: the lint level is defined here
   --> src/lib.rs:86:5
    |
86  |     warnings
    |     ^^^^^^^^
    = note: `#[deny(clippy::single_component_path_imports)]` implied by `#[deny(warnings)]`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_component_path_imports

error: useless lint attribute
  --> src/lib.rs:99:1
   |
99 | #[allow(clippy::single_component_path_imports)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: if you just forgot a `!`, use: `#![allow(clippy::single_component_path_imports)]`
   |
   = note: `#[deny(clippy::useless_attribute)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_attribute
```

### Version

```text
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-apple-darwin
release: 1.60.0
LLVM version: 14.0.0
```

### Additional Labels

_No response_

### LINKED ISSUE #9401: `useless_attribute` does not permit `module_name_repetitions` on `use` statements
### Summary

With `#![warn(clippy::module_name_repetitions)]`, clippy will emit a lint warning when `pub use` items start with the same prefix as the module with the `pub use` statement. This lint can be suppressed by adding an `allow` pragma on the `use` statement. However, once adding the allow, clippy emits a deny-by-default lint for `useless_attribute`.

`useless_attribute` does not permit `module_name_repetitions` on `use` items per its docs: https://rust-lang.github.io/rust-clippy/master/index.html#useless_attribute. I believe `useless_attribute` should permit `module_name_repetitions` on `use` items.

### Lint Name

useless_attribute

### Reproducer

I tried this code:

```rust
#![warn(clippy::module_name_repetitions)]

pub mod convert {
    mod internal {
        pub enum ConvertOnError {
            Yes,
            No,
        }
        
        pub fn convert_type() {}
    }
    
    pub use internal::{ConvertOnError, convert_type};
}

fn main() {
    println!("Hello, world!");
}
```

I saw this happen:

```
    Checking playground v0.0.1 (/playground)
warning: item name starts with its containing module's name
  --> src/main.rs:13:24
   |
13 |     pub use internal::{ConvertOnError, convert_type};
   |                        ^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> src/main.rs:1:9
   |
1  | #![warn(clippy::module_name_repetitions)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#module_name_repetitions

warning: item name starts with its containing module's name
  --> src/main.rs:13:40
   |
13 |     pub use internal::{ConvertOnError, convert_type};
   |                                        ^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#module_name_repetitions

warning: `playground` (bin "playground") generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.58s
```

I tried to suppress the lint:

```rust
#![warn(clippy::module_name_repetitions)]

pub mod convert {
    mod internal {
        pub enum ConvertOnError {
            Yes,
            No,
        }
        
        pub fn convert_type() {}
    }
    
    #[allow(clippy::module_name_repetitions)]
    pub use internal::{ConvertOnError, convert_type};
}

fn main() {
    println!("Hello, world!");
}
```

and got this output:

```
    Checking playground v0.0.1 (/playground)
error: useless lint attribute
  --> src/main.rs:13:5
   |
13 |     #[allow(clippy::module_name_repetitions)]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: if you just forgot a `!`, use: `#![allow(clippy::module_name_repetitions)]`
   |
   = note: `#[deny(clippy::useless_attribute)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_attribute

error: could not compile `playground` due to previous error
```

Adding an additional suppression for `useless_attribute` results in the expected behavior:

```rust
#![warn(clippy::module_name_repetitions)]

pub mod convert {
    mod internal {
        pub enum ConvertOnError {
            Yes,
            No,
        }
        
        pub fn convert_type() {}
    }
    
    #[allow(clippy::module_name_repetitions)]
    #[allow(clippy::useless_attribute)] // clippy does not permit `clippy::module_name_repetitions` on `use` statements
    pub use internal::{ConvertOnError, convert_type};
}

fn main() {
    println!("Hello, world!");
}
```

and got this output: _no warnings_

### Version

```text
rustc 1.63.0 (4b91a6ea7 2022-08-08)
binary: rustc
commit-hash: 4b91a6ea7258a947e59c6522cd5898e7c0a6a88f
commit-date: 2022-08-08
host: x86_64-apple-darwin
release: 1.63.0
LLVM version: 14.0.5
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by Alexendoo**
Fixes #7511
Fixes #8768
Fixes #9401

`single_component_path_imports` needed some changes to the lint itself, it now buffers the found single component paths to emit in the equivalent `check_item`

changelog: Fix `#[allow(clippy::module_name_repetitions)]` and `#[allow(clippy::single_component_path_imports)]`

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

File: clippy_lints/src/single_component_path_imports.rs [hunk 1]
```diff
@@ -102,74 +84,126 @@ fn check_mod(cx: &EarlyContext<'_>, items: &[P<Item>]) {
...
-    imports_reused_with_self: &mut Vec<Symbol>,
-    single_use_usages: &mut Vec<(Symbol, Span, bool)>,
-    macros: &mut Vec<Symbol>,
-) {
-    if item.span.from_expansion() || item.vis.kind.is_pub() {
-        return;
-    }
+impl SingleComponentPathImports {
+    fn check_mod(&mut self, cx: &EarlyContext<'_>, items: &[P<Item>]) {
+        // keep track of imports reused with `self` keyword,
```
Comment (Manishearth) [inline clippy_lints/src/single_component_path_imports.rs:89]: nit: worth dropping a comment giving context as to why we're doing it this way

**Comment by Manishearth** [comment]
r=me after adding the comment

tricky fix!

**Comment by Alexendoo** [comment]
Thanks! I was thinking it would be an easy fix, just use `span_lint_hir`. Then I saw it was an early lint 😄

@bors r=Manishearth
