### PR TITLE
fix: `undocumented_unsafe_blocks` FP on trait/impl items

### LINKED ISSUE #11709: undocumented_unsafe_blocks doesn't detect safety comment above associated constant
### Summary

I make use of the `voladdress` crate which uses a pattern of "unsafe construction, safe use", but when I put a `VolAddress` in a constant clippy doesn't detect the safety comment I add above it.

### Reproducer

I tried this code:

```rust
#![warn(clippy::undocumented_unsafe_block)]

use voladdress::{Safe, VolAddress};

struct Control(u16);

impl Control {
    // SAFETY: this is safe
    const REGISTER: VolAddress<Self, Safe, Safe> = unsafe { VolAddress::new(0x0400_0204) };
}
```

I expected to see this happen:
no clippy warning

Instead, this happened:
a clippy warning

### Version

```text
rustc 1.75.0-nightly (1c05d50c8 2023-10-21)
binary: rustc
commit-hash: 1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07
commit-date: 2023-10-21
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.3
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by profetia**
fixes #11709

Continuation of #12672. r? @Alexendoo if you don't mind?

changelog: [`undocumented_unsafe_blocks`] fix FP on trait/impl items

### CODE REVIEW

**Comment by profetia** [comment]
r? clippy

File: tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.rs [hunk 1]
```diff
@@ -586,4 +586,45 @@ mod issue_11246 {
...
+    }
+}
+
+fn issue_13024() {
+    let mut just_a_simple_variable_with_a_very_long_name_that_has_seventy_eight_characters = 0;
+    let here_is_another_variable_with_long_name = 100;
+
+    // SAFETY: good
+    just_a_simple_variable_with_a_very_long_name_that_has_seventy_eight_characters =
+        unsafe { here_is_another_variable_with_long_name };
```
Comment (xFrednet) [inline tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.rs:627]: I love these variable names :D

**Review by xFrednet — APPROVED** [review]
LGTM, thank you for the update (And sorry for the delay with the review. :sweat_smile: )

---

Roses are red,
Violets are blue,
Safety comments,
For unsafe code

**Comment by profetia** [comment]
Looks like it is conflicted with the recent update on ui toml. Should be ok now, you may need to re-press the button though @xFrednet.

**Comment by xFrednet** [comment]
Thanks for the rebase!

I've checked the CI lintcheck output: https://github.com/rust-lang/rust-clippy/actions/runs/13364592312?pr=13888 and actually noticed a regression here: https://docs.rs/time/0.3.36/src/time/offset_date_time.rs.html#35. The linked code would now be linted while it wasn't before. Could you take a look at it and add a test?

**Comment by profetia** [comment]
@xFrednet Can you check it now? I fixed that one and we also got 9 cases REMOVED. How wiered that this one in `time-rs` does not exist initially.

**Review by xFrednet — APPROVED** [review]

**Comment by xFrednet** [comment]
This version looks good to me, could you rebase one last time?

Thank you for your patience while waiting on my review :sweat_smile:

**Comment by profetia** [comment]
> This version looks good to me, could you rebase one last time?
> 
> Thank you for your patience while waiting on my review 😅

Rebased

**Comment by xFrednet** [comment]
```rust
// Safety: The following poem is not complete
unsafe {
    Rose are red,
    Violets are blue
}
```

**Review by xFrednet — APPROVED** [review]
