### PR TITLE
Don't use `to_string` in impl Display

### LINKED ISSUE #3876: Correctness: no to_string in impl Display
I have recently been implementing some `Display` traits for my types and accidentally used `to_string()` of the type being implemented for. This of course resulted in a stack overflow. I think that this is always wrong and should be linted

### PR DESCRIPTION
**Pull request by chansuke**
fixes #3876

this PR is derived from [Toxyxer's implementation](https://github.com/rust-lang/rust-clippy/pull/5574).
changelog: add [`to_string_in_display`] lint

### CODE REVIEW

File: clippy_lints/src/to_string_in_display.rs [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    correctness,
+    "to_string method used while implementing Display trait"
+}
+
+declare_lint_pass!(ToStringInDisplay => [TO_STRING_IN_DISPLAY]);
+
+impl LateLintPass<'_> for ToStringInDisplay {
+    fn check_expr(&mut self, cx: &LateContext<'_>, expr: &Expr<'_>) {
+        let parent_id = cx.tcx.hir().get_parent_item(expr.hir_id);
+        let parent_node = cx.tcx.hir().find(parent_id);
```
Comment (flip1995) [inline clippy_lints/src/to_string_in_display.rs:50]: If you use the `check_item` + `check_item_post` methods, you can check more easily, if you are currently inside a `Display` implementation.

See the `clippy_lints::wildcard_imports` for a similar case, where these functions are used to determine, if weÄre currently inside a specific item.

File: tests/ui/to_string_in_display.stderr [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+LL | |     }
+   | |_____^
+   |
+   = note: `#[deny(clippy::inherent_to_string_shadow_display)]` on by default
+   = help: remove the inherent method from type `C`
+
+error: Using to_string in fmt::Display implementation might lead to infinite recursion
+  --> $DIR/to_string_in_display.rs:42:25
+   |
+LL |         write!(f, "{}", self.to_string())
```
Comment (flip1995) [inline tests/ui/to_string_in_display.stderr:23]: This should not trigger the lint, iff the `C::to_string`, instead of the `<C as ToString>::to_string` method is used. See my comment in: https://github.com/rust-lang/rust-clippy/pull/5574#issuecomment-625333045

File: tests/ui/to_string_in_display.stderr [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+
+error: type `C` implements inherent method `to_string(&self) -> String` which shadows the implementation of `Display`
+  --> $DIR/to_string_in_display.rs:35:5
+   |
+LL | /     pub fn to_string(&self) -> String {
+LL | |         "I am C".to_string()
+LL | |     }
+   | |_____^
+   |
+   = note: `#[deny(clippy::inherent_to_string_shadow_display)]` on by default
```
Comment (flip1995) [inline tests/ui/to_string_in_display.stderr:17]: Just allow this lint in this test file.

File: clippy_lints/src/to_string_in_display.rs (hunk 1 above)
Comment (chansuke) [reply clippy_lints/src/to_string_in_display.rs:50]: Thank you for the review & information. I will fix this.

File: tests/ui/to_string_in_display.stderr (hunk 2 above)
Comment (chansuke) [reply tests/ui/to_string_in_display.stderr:12]: @flip1995 I tried several utils but stuck to think of the solution to this case... Is there any way to get closer to a solution to this problem? Thanks.

Comment (flip1995) [reply tests/ui/to_string_in_display.stderr:12]: You have to check if the method is from the `ToString` trait. You can use code similar to
https://github.com/rust-lang/rust-clippy/blob/799eef691969c2f6ecf33359f0b1e1691a060648/clippy_lints/src/loops.rs#L545-L546

for this. 

- `next`  -> `to_string`
- `match_expr` -> `expr`
- `ITERATOR` -> `TO_STRING`

Comment (chansuke) [reply tests/ui/to_string_in_display.stderr:12]: Thank you for your suggestion. I will try this weekend.

File: clippy_lints/src/to_string_in_display.rs [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+            if ident.as_str() == "fmt";
+            if let ImplItemKind::Fn(FnSig {decl, ..}, _) = kind;
+            if let FnDecl{inputs, ..} = decl;
+            if let Ty {kind, ..} = &inputs[0];
+            if let TyKind::Rptr(_, MutTy {ty, ..}) = kind;
+            if let Ty {kind, ..} = ty;
+            if let TyKind::Path(QPath::Resolved(_, path)) = kind;
+            if let Path{res, ..} = path;
+            if let def::Res::SelfTy(Some(did), _) = res;
+            if match_def_path(cx, *did, &paths::DISPLAY_TRAIT);
```
Comment (flip1995) [inline clippy_lints/src/to_string_in_display.rs:67]: You can remove this whole code if you add:

```rust
fn is_display_impl(cx: ..., item: &Item<'_>) {
    if_chain! {
        if let ItemKind::Impl { of_trait: Some(trait_ref), .. } = item.kind;
        if let Some(did) = trait_ref.trait_def_id();
        if match_def_path(cx, did, &paths::DISPLAY_TRAIT);
        then {
            true
        } else {
            false
        }
    }
}

fn check_item(&mut self, cx: ..., item: &Item<'_>) {
    if is_display_impl(item) {
        self.in_display_impl = true;
    }
}

fn check_item_post(&mut self, cx: ..., item: &Item<'_>) {
    if is_display_impl(item) {
        self.in_display_impl = false;
    }
}
```

and then

```suggestion
            if self.in_display_impl;
```

File: clippy_lints/src/to_string_in_display.rs [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+impl LateLintPass<'_> for ToStringInDisplay {
+    fn check_expr(&mut self, cx: &LateContext<'_>, expr: &Expr<'_>) {
+        let parent_id = cx.tcx.hir().get_parent_item(expr.hir_id);
+        let parent_node = cx.tcx.hir().find(parent_id);
+
+        if_chain! {
+            if let ExprKind::MethodCall(ref path, _, _, _) = expr.kind;
+            if path.ident.name == sym!(to_string)
+                    && match_trait_method(cx, expr, &paths::TO_STRING);
+            if path.ident.as_str() == "to_string";
```
Comment (flip1995) [inline clippy_lints/src/to_string_in_display.rs:56]: You already check this above.

```suggestion
            if path.ident.name == sym!(to_string);
            if match_trait_method(cx, expr, &paths::TO_STRING);
```

File: clippy_lints/src/to_string_in_display.rs (hunk 4 above)
Comment (chansuke) [reply clippy_lints/src/to_string_in_display.rs]: I'm trying below code but returns `this if-then-else expression returns a bool literal` error. 

```
fn is_display_impl(cx: &LateContext<'_>, item: &Item<'_>) -> bool {
    if_chain! {
        if let ItemKind::Impl { of_trait: Some(trait_ref), .. } = &item.kind;
        if let Some(did) = trait_ref.trait_def_id();
        if match_def_path(cx, did, &paths::DISPLAY_TRAIT);
        then {
            true
        } else {
            false
        }
    }
}
```

File: clippy_lints/src/to_string_in_display.rs [hunk 6]
```diff
@@ -0,0 +1,104 @@
...
+fn is_display_impl(cx: &LateContext<'_>, item: &Item<'_>) -> bool {
+    if_chain! {
+        if let ItemKind::Impl { of_trait: Some(trait_ref), .. } = &item.kind;
+        if let Some(did) = trait_ref.trait_def_id();
+        if match_def_path(cx, did, &paths::DISPLAY_TRAIT);
+        then {
+            true
+        } else {
+            false
+        }
```
Comment (flip1995) [inline clippy_lints/src/to_string_in_display.rs:102]: Regarding the `clippy::needless_bool` lint triggering here: You can simplify this to:

```suggestion
        then {
            match_def_path(cx, did, &paths::DISPLAY_TRAIT)
        } else {
            false
        }
```

Clippy is great 😄

**Comment by flip1995** [comment]
Please also address the other two dogfood errors:

```
warning: unused variable: `parent_node`
  --> clippy_lints/src/to_string_in_display.rs:73:13
   |
73 |         let parent_node = cx.tcx.hir().find(parent_id);
   |             ^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_parent_node`
   |
   = note: `#[warn(unused_variables)]` on by default

error: usage of wildcard import
 --> clippy_lints/src/to_string_in_display.rs:3:5
  |
3 | use rustc_hir::*;
  |     ^^^^^^^^^^^^ help: try: `rustc_hir::{Expr, ExprKind, Item, ItemKind}`
  |
  = note: `-D clippy::wildcard-imports` implied by `-D clippy::pedantic`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#wildcard_imports
```

File: clippy_lints/src/to_string_in_display.rs (hunk 6 above)
Comment (chansuke) [reply clippy_lints/src/to_string_in_display.rs:102]: Thanks!!

**Comment by flip1995** [comment]
Thanks!

@bors r+

File: clippy_lints/src/to_string_in_display.rs [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+    /// struct Structure(i32);
+    /// impl fmt::Display for Structure {
+    ///     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+    ///         write!(f, "{}", self.0)
+    ///     }
+    /// }
+    /// ```
+    pub TO_STRING_IN_DISPLAY,
+    correctness,
+    "to_string method used while implementing Display trait"
```
Comment (lzutao) [inline clippy_lints/src/to_string_in_display.rs:42]:
```
"`to_string` method used while implementing `Display` trait"
```

File: clippy_lints/src/to_string_in_display.rs [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+            if path.ident.name == sym!(to_string);
+            if match_trait_method(cx, expr, &paths::TO_STRING);
+            if self.in_display_impl;
+
+            then {
+                span_lint(
+                    cx,
+                    TO_STRING_IN_DISPLAY,
+                    expr.span,
+                    "Using to_string in fmt::Display implementation might lead to infinite recursion",
```
Comment (lzutao) [inline clippy_lints/src/to_string_in_display.rs:83]: "using `to_string` in `fmt::Display` implementation might lead to infinite recursion",
