### PR TITLE
fix ICE by `u64::try_from(<u128>)`

### LINKED ISSUE #11426: ICE `shift too high: TryFromIntError(())`
### Summary

````rust
pub fn main() {
    (&42u8 >> 0xa9008fb6c9d81e42_0e25730562a601c8_u128) as usize;
}
````

### Version

```text
rustc 1.74.0-nightly (b2515fa74 2023-08-29)
binary: rustc
commit-hash: b2515fa741eea89b82a2c94048f934bbcbd3bd48
commit-date: 2023-08-29
host: x86_64-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.0
```

### Error output

<details><summary>Backtrace</summary>
  <p>

  ```
  warning: statement with no effect
 --> 3.rs:2:5
  |
2 |     (&42u8 >> 0xa9008fb6c9d81e42_0e25730562a601c8_u128) as usize;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#no_effect
  = note: `#[warn(clippy::no_effect)]` on by default

thread 'rustc' panicked at src/tools/clippy/clippy_lints/src/casts/cast_possible_truncation.rs:47:88:
shift too high: TryFromIntError(())
stack backtrace:
   0:     0x7fda0836316c - std::backtrace_rs::backtrace::libunwind::trace::h436c8e524cde9e19
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fda0836316c - std::backtrace_rs::backtrace::trace_unsynchronized::h23af15dda014f863
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fda0836316c - std::sys_common::backtrace::_print_fmt::h366b8b1240af736d
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fda0836316c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4c76a6c9a9d27949
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fda083c941c - core::fmt::rt::Argument::fmt::hdcec6912fddde237
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/core/src/fmt/rt.rs:138:9
   5:     0x7fda083c941c - core::fmt::write::h3c8408a9c1ca2b88
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/core/src/fmt/mod.rs:1094:21
   6:     0x7fda08355d7e - std::io::Write::write_fmt::h49f73e56bc6178eb
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/io/mod.rs:1714:15
   7:     0x7fda08362f54 - std::sys_common::backtrace::_print::hc978fdff27b3702f
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fda08362f54 - std::sys_common::backtrace::print::h6d8605d3f6a732cf
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fda0836604a - std::panicking::panic_hook_with_disk_dump::{{closure}}::h5ba21bec50652e99
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/panicking.rs:280:22
  10:     0x7fda08365d45 - std::panicking::panic_hook_with_disk_dump::h06e78b9adc4953c8
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/panicking.rs:314:9
  11:     0x7fda0b53b2a9 - <rustc_driver_impl[9c0b0eae858fb9ed]::install_ice_hook::{closure#0} as core[f4d78fc37b1271ab]::ops::function::FnOnce<(&core[f4d78fc37b1271ab]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7fda08366913 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h5e9d6c842a587ade
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/alloc/src/boxed.rs:2021:9
  13:     0x7fda08366913 - std::panicking::rust_panic_with_hook::h731d1fd1d7057f0e
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/panicking.rs:757:13
  14:     0x7fda08366681 - std::panicking::begin_panic_handler::{{closure}}::h6d854330c70238b5
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/panicking.rs:631:13
  15:     0x7fda08363696 - std::sys_common::backtrace::__rust_end_short_backtrace::hc13992967e8ee37d
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/sys_common/backtrace.rs:170:18
  16:     0x7fda083663c2 - rust_begin_unwind
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/panicking.rs:619:5
  17:     0x7fda083c57a5 - core::panicking::panic_fmt::h55890f00e6462e9a
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/core/src/panicking.rs:72:14
  18:     0x7fda083c5dca - core::result::unwrap_failed::h2d3e69bdfe72eb43
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/core/src/result.rs:1652:5
  19:     0x556dbc2e1fc3 - clippy_lints[32b6a0893c936af6]::casts::cast_possible_truncation::apply_reductions
  20:     0x556dbc2e2652 - clippy_lints[32b6a0893c936af6]::casts::cast_possible_truncation::check
  21:     0x556dbc335284 - <clippy_lints[32b6a0893c936af6]::casts::Casts as rustc_lint[7c029eba3f723c1c]::passes::LateLintPass>::check_expr
  22:     0x7fda0b93ce99 - <rustc_lint[7c029eba3f723c1c]::late::LateContextAndPass<rustc_lint[7c029eba3f723c1c]::late::RuntimeCombinedLateLintPass> as rustc_hir[c8736cc5ad551095]::intravisit::Visitor>::visit_expr::{closure#0}
  23:     0x7fda0b942c6b - rustc_hir[c8736cc5ad551095]::intravisit::walk_block::<rustc_lint[7c029eba3f723c1c]::late::LateContextAndPass<rustc_lint[7c029eba3f723c1c]::late::RuntimeCombinedLateLintPass>>
  24:     0x7fda0b93d7f8 - <rustc_lint[7c029eba3f723c1c]::late::LateContextAndPass<rustc_lint[7c029eba3f723c1c]::late::RuntimeCombinedLateLintPass> as rustc_hir[c8736cc5ad551095]::intravisit::Visitor>::visit_block
  25:     0x7fda0b93cead - <rustc_lint[7c029eba3f723c1c]::late::LateContextAndPass<rustc_lint[7c029eba3f723c1c]::late::RuntimeCombinedLateLintPass> as rustc_hir[c8736cc5ad551095]::intravisit::Visitor>::visit_expr::{closure#0}
  26:     0x7fda0b93cba9 - <rustc_lint[7c029eba3f723c1c]::late::LateContextAndPass<rustc_lint[7c029eba3f723c1c]::late::RuntimeCombinedLateLintPass> as rustc_hir[c8736cc5ad551095]::intravisit::Visitor>::visit_nested_body
  27:     0x7fda0b93d14c - <rustc_lint[7c029eba3f723c1c]::late::LateContextAndPass<rustc_lint[7c029eba3f723c1c]::late::RuntimeCombinedLateLintPass> as rustc_hir[c8736cc5ad551095]::intravisit::Visitor>::visit_fn
  28:     0x7fda0b946e9d - rustc_hir[c8736cc5ad551095]::intravisit::walk_item::<rustc_lint[7c029eba3f723c1c]::late::LateContextAndPass<rustc_lint[7c029eba3f723c1c]::late::RuntimeCombinedLateLintPass>>
  29:     0x7fda0b93ad7b - <rustc_lint[7c029eba3f723c1c]::late::LateContextAndPass<rustc_lint[7c029eba3f723c1c]::late::RuntimeCombinedLateLintPass> as rustc_hir[c8736cc5ad551095]::intravisit::Visitor>::visit_nested_item
  30:     0x7fda0b945c0a - rustc_hir[c8736cc5ad551095]::intravisit::walk_mod::<rustc_lint[7c029eba3f723c1c]::late::LateContextAndPass<rustc_lint[7c029eba3f723c1c]::late::RuntimeCombinedLateLintPass>>
  31:     0x7fda0abba7db - <rustc_session[227a7b0182a81de4]::session::Session>::time::<(), rustc_lint[7c029eba3f723c1c]::late::check_crate::{closure#0}::{closure#0}>
  32:     0x7fda0abb9f99 - <core[f4d78fc37b1271ab]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[86525c5fafa2c3a]::passes::analysis::{closure#6}::{closure#1}::{closure#2}> as core[f4d78fc37b1271ab]::ops::function::FnOnce<()>>::call_once
  33:     0x7fda0abb159f - <core[f4d78fc37b1271ab]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[86525c5fafa2c3a]::passes::analysis::{closure#6}::{closure#1}> as core[f4d78fc37b1271ab]::ops::function::FnOnce<()>>::call_once
  34:     0x7fda0a472aa8 - <rustc_session[227a7b0182a81de4]::session::Session>::time::<(), rustc_interface[86525c5fafa2c3a]::passes::analysis::{closure#6}>
  35:     0x7fda0a470e31 - rustc_interface[86525c5fafa2c3a]::passes::analysis
  36:     0x7fda0aa5572a - rustc_query_impl[75df7bf25f38779]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[75df7bf25f38779]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[6f8d83f57f417709]::query::erase::Erased<[u8; 1usize]>>
  37:     0x7fda0aa55719 - <rustc_query_impl[75df7bf25f38779]::query_impl::analysis::dynamic_query::{closure#2} as core[f4d78fc37b1271ab]::ops::function::FnOnce<(rustc_middle[6f8d83f57f417709]::ty::context::TyCtxt, ())>>::call_once
  38:     0x7fda0abdd8ca - rustc_query_system[9ff6dc27fa3386b9]::query::plumbing::try_execute_query::<rustc_query_impl[75df7bf25f38779]::DynamicConfig<rustc_query_system[9ff6dc27fa3386b9]::query::caches::SingleCache<rustc_middle[6f8d83f57f417709]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[75df7bf25f38779]::plumbing::QueryCtxt, false>
  39:     0x7fda0abdd649 - rustc_query_impl[75df7bf25f38779]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  40:     0x7fda0a84a8f6 - <rustc_middle[6f8d83f57f417709]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[9c0b0eae858fb9ed]::run_compiler::{closure#1}::{closure#2}::{closure#6}, core[f4d78fc37b1271ab]::result::Result<(), rustc_span[9b50d41fcb69953]::ErrorGuaranteed>>
  41:     0x7fda0a849d3d - <rustc_interface[86525c5fafa2c3a]::interface::Compiler>::enter::<rustc_driver_impl[9c0b0eae858fb9ed]::run_compiler::{closure#1}::{closure#2}, core[f4d78fc37b1271ab]::result::Result<core[f4d78fc37b1271ab]::option::Option<rustc_interface[86525c5fafa2c3a]::queries::Linker>, rustc_span[9b50d41fcb69953]::ErrorGuaranteed>>
  42:     0x7fda0a847058 - std[dba048ab42cdd2b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[86525c5fafa2c3a]::util::run_in_thread_pool_with_globals<rustc_interface[86525c5fafa2c3a]::interface::run_compiler<core[f4d78fc37b1271ab]::result::Result<(), rustc_span[9b50d41fcb69953]::ErrorGuaranteed>, rustc_driver_impl[9c0b0eae858fb9ed]::run_compiler::{closure#1}>::{closure#0}, core[f4d78fc37b1271ab]::result::Result<(), rustc_span[9b50d41fcb69953]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f4d78fc37b1271ab]::result::Result<(), rustc_span[9b50d41fcb69953]::ErrorGuaranteed>>
  43:     0x7fda0a8467ce - <<std[dba048ab42cdd2b]::thread::Builder>::spawn_unchecked_<rustc_interface[86525c5fafa2c3a]::util::run_in_thread_pool_with_globals<rustc_interface[86525c5fafa2c3a]::interface::run_compiler<core[f4d78fc37b1271ab]::result::Result<(), rustc_span[9b50d41fcb69953]::ErrorGuaranteed>, rustc_driver_impl[9c0b0eae858fb9ed]::run_compiler::{closure#1}>::{closure#0}, core[f4d78fc37b1271ab]::result::Result<(), rustc_span[9b50d41fcb69953]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f4d78fc37b1271ab]::result::Result<(), rustc_span[9b50d41fcb69953]::ErrorGuaranteed>>::{closure#1} as core[f4d78fc37b1271ab]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  44:     0x7fda08371375 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7334712f13dfb18e
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/alloc/src/boxed.rs:2007:9
  45:     0x7fda08371375 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcc12b515e1513e84
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/alloc/src/boxed.rs:2007:9
  46:     0x7fda08371375 - std::sys::unix::thread::Thread::new::thread_start::h103bf550e93c21c5
                               at /rustc/b2515fa741eea89b82a2c94048f934bbcbd3bd48/library/std/src/sys/unix/thread.rs:108:17
  47:     0x7fda07e8c9eb - <unknown>
  48:     0x7fda07f10ebc - <unknown>
  49:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

note: please attach the file at `/home/matthias/vcs/github/rust/tests/icemaker_omni/rustc-ice-2023-08-30T05:32:53.221250752Z-3237789.txt` to your bug report

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
note: Clippy version: clipp
  ```

  </p>
</details>

### PR DESCRIPTION
**Pull request by mojave2**
changelog: Fix the ICE in [`cast_possible_truncation`], when the `Shr` bits is larger than `u64::MAX`

fix #11426

### CODE REVIEW

File: clippy_lints/src/casts/cast_possible_truncation.rs [hunk 1]
```diff
@@ -43,8 +43,9 @@ fn apply_reductions(cx: &LateContext<'_>, nbits: u64, expr: &Expr<'_>, signed: b
             BinOpKind::Rem | BinOpKind::BitAnd => get_constant_bits(cx, right)
                 .unwrap_or(u64::max_value())
                 .min(apply_reductions(cx, nbits, left, signed)),
-            BinOpKind::Shr => apply_reductions(cx, nbits, left, signed)
-                .saturating_sub(constant_int(cx, right).map_or(0, |s| u64::try_from(s).expect("shift too high"))),
+            BinOpKind::Shr => apply_reductions(cx, nbits, left, signed).saturating_sub(
+                constant_int(cx, right).map_or(0, |s| u64::try_from(s.rem_euclid(u128::from(u64::MAX) + 1)).unwrap()),
```
Comment (Alexendoo) [inline clippy_lints/src/casts/cast_possible_truncation.rs:47]: This seems to be the same as `s as u64`

Comment (mojave2) [reply clippy_lints/src/casts/cast_possible_truncation.rs:47]: yeah, they're the same. The only benefit this way is to pass the dogfood test.

Comment (Alexendoo) [reply clippy_lints/src/casts/cast_possible_truncation.rs:47]: You can add an `#[allow]` if it triggers a lint, but it might be preferable to do something like `constant_int().and_then(|s| u64::try_from(s).ok()).unwrap_or(0)`

**Comment by Alexendoo** [comment]
Thanks! @bors r+

**Comment by blyxyas** [comment]
Spurious error.
@bors r=Alexendoo

**Comment by blyxyas** [comment]
This PR shouldn't even trigger the `remark` job -.-
Probably an infra bug

**Comment by Alexendoo** [comment]
The PR didn't, but the bors build will since it pushes to the `auto` branch. Looks like we need to update node, I'll get on that
