### PR TITLE
Fix check_infinite_loop (while_immutable_condition) by checking for break or return inside loop body

### LINKED ISSUE #4648: false positive on while_immutable_condition
Code:

```
pub fn skip_while<St, F, Fut>(stream: St, f: F) -> impl Stream<Item = St::Item>
where
    St: Stream,
    F: FnMut(&St::Item) -> Fut,
    Fut: Future<Output = bool>,
{
    let stream = Box::pin(stream);
    let should_skip = true;
    crate::stream::unfold(
        (stream, f, should_skip),
        |(mut stream, mut f, should_skip)| async move {
            while should_skip {
                if let Some(item) = next(&mut stream).await {
                    if f(&item).await {
                        continue;
                    } else {
                        return Some((item, (stream, f, /* should_skip */ false)));
                    }
                } else {
                    return None;
                }
            }
            if let Some(item) = next(&mut stream).await {
                Some((item, (stream, f, /* should_skip */ false)))
            } else {
                None
            }
        },
    )
}
```

Error:

```
error: Variable in the condition are not mutated in the loop body. This either leads to an infinite or to a never running loop.
   --> src/stream.rs:717:19
    |
717 |             while should_skip {
    |                   ^^^^^^^^^^^
    |
```

https://github.com/kpp/futures-async-combinators/blob/d8da69c9f3b4587a99ddf1e0e5545bcff81cf57c/src/stream.rs#L718

### PR DESCRIPTION
**Pull request by yerke**
changelog: Fix check_infinite_loop (while_immutable_condition) by checking for break or return inside loop body
fixes #4648

### CODE REVIEW

**Comment by yerke** [comment]
Next I will try to break this lint into 2 as suggested in https://github.com/rust-lang/rust-clippy/issues/4648#issuecomment-541019628

File: clippy_lints/src/loops.rs [hunk 1]
```diff
@@ -2363,8 +2363,8 @@ fn check_infinite_loop<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, cond: &'tcx Expr, e
             cx,
             WHILE_IMMUTABLE_CONDITION,
             cond.span,
-            "Variable in the condition are not mutated in the loop body. \
-             This either leads to an infinite or to a never running loop.",
+            "Variables in the condition are not mutated in the loop body. \
+             This may lead to an infinite or to a never running loop.",
```
Comment (flip1995) [inline clippy_lints/src/loops.rs]:
```suggestion
             This may lead to an infinite or to a never running loop",
```

Also lowercase `Variables`

File: clippy_lints/src/loops.rs [hunk 2]
```diff
@@ -2358,17 +2358,100 @@ fn check_infinite_loop<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, cond: &'tcx Expr, e
...
     };
     let mutable_static_in_cond = var_visitor.def_ids.iter().any(|(_, v)| *v);
-    if no_cond_variable_mutated && !mutable_static_in_cond {
+    let has_break_or_return = if let ExprKind::Block(ref block, _) = expr.kind {
+        match infinite_loop_block(block) {
+            InfiniteLoopResult::MayBreak => true,
+            InfiniteLoopResult::Otherwise => false,
+        }
+    } else {
+        panic!("Expected block here always!");
```
Comment (yerke) [inline clippy_lints/src/loops.rs]: I will remove that during clean up

File: clippy_lints/src/loops.rs [hunk 3]
```diff
@@ -2358,17 +2358,100 @@ fn check_infinite_loop<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, cond: &'tcx Expr, e
...
+        InfiniteLoopResult::Otherwise => second,
+    }
+}
+
+fn infinite_loop_expr(expr: &Expr) -> InfiniteLoopResult {
+    match expr.kind {
+        ExprKind::Ret(_) => {
+            InfiniteLoopResult::MayBreak
+        },
+        ExprKind::Break(_, _) => {
```
Comment (yerke) [inline clippy_lints/src/loops.rs]: I considered getting destination from `Break(d, ref e)`, but decided against it. Consider the following example similar to https://doc.rust-lang.org/rust-by-example/flow_control/loop/nested.html:
```
    'outer: while y > 10 {
        println!("Entered the outer loop");

        'inner: while x > 10 {
            println!("Entered the inner loop");

            // This breaks the outer loop
            break 'outer;
        }

        println!("This point will never be reached");
    }
```
If I check `main_loop_id` like in `never_loop_block`, the outer loop will pass the lint, but the inner loop will fail, since the `break` inside it points to outer label.
Please let me know if my reasoning is correct.

Comment (flip1995) [reply clippy_lints/src/loops.rs]: Sounds reasonable.

File: clippy_lints/src/loops.rs [hunk 4]
```diff
@@ -2358,17 +2358,100 @@ fn check_infinite_loop<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, cond: &'tcx Expr, e
...
+
+enum InfiniteLoopResult {
+    // Has break/return in the body of the loop
+    MayBreak,
+    Otherwise,
+}
+
+fn infinite_loop_expr_seq<'a, T: Iterator<Item = &'a Expr>>(es: &mut T) -> InfiniteLoopResult {
+    es.map(|e| infinite_loop_expr(e))
+        .fold(InfiniteLoopResult::Otherwise, infinite_loop_combine_seq)
```
Comment (flip1995) [inline clippy_lints/src/loops.rs]: This is more efficient:
```suggestion
        .find(|res| res == InfiniteLoopResult::MayBreak)
        .unwrap_or(InfiniteLoopResult::Otherwise)
```

(Requires `PartialEq` derive on the `InfiniteLoopResult` enum)

File: clippy_lints/src/loops.rs [hunk 5]
```diff
@@ -2358,17 +2358,100 @@ fn check_infinite_loop<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, cond: &'tcx Expr, e
...
+}
+
+fn infinite_loop_combine_seq(first: InfiniteLoopResult, second: InfiniteLoopResult) -> InfiniteLoopResult {
+    match first {
+        InfiniteLoopResult::MayBreak => first,
+        InfiniteLoopResult::Otherwise => second,
+    }
+}
+
+fn infinite_loop_expr(expr: &Expr) -> InfiniteLoopResult {
```
Comment (flip1995) [inline clippy_lints/src/loops.rs]: You should implement this as a `Visitor`. Then this would just be
```rust
fn visit_expr(&mut self, expr..) {
    if self.has_break {
        return;
    }
    match expr.kind {
        ExprKind::Return(_) | ExprKind::Break(..) => self.has_break = true,
        _ => {}
    }
   
    walk_expr(expr);
}
```

grep the clippy codebase for `intravisit` to find examples on how to write a visitor.

File: clippy_lints/src/loops.rs [hunk 6]
```diff
@@ -2367,17 +2367,50 @@ fn check_infinite_loop<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, cond: &'tcx Expr, e
...
+                return;
+            },
+            _ => {},
+        }
+
+        walk_expr(self, expr);
+    }
+
+    fn nested_visit_map<'this>(&'this mut self) -> NestedVisitorMap<'this, 'tcx> {
+        NestedVisitorMap::None
```
Comment (yerke) [inline clippy_lints/src/loops.rs]: Is this correct? I have not idea :(

File: clippy_lints/src/loops.rs [hunk 7]
```diff
@@ -2367,17 +2367,50 @@ fn check_infinite_loop<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, cond: &'tcx Expr, e
         return;
     };
     let mutable_static_in_cond = var_visitor.def_ids.iter().any(|(_, v)| *v);
-    if no_cond_variable_mutated && !mutable_static_in_cond {
+
+    let mut has_break_or_return_visitor = HasBreakOrReturnVisitor {
+        has_break_or_return: false,
+    };
+    walk_expr(&mut has_break_or_return_visitor, expr);
```
Comment (flip1995) [inline clippy_lints/src/loops.rs]:
```suggestion
    has_break_or_return_visitor.visit_expr(expr);
```

File: tests/ui/infinite_loop.rs [hunk 8]
```diff
@@ -177,6 +177,23 @@ impl Counter {
     }
 }
 
+fn while_loop_with_break_and_return() {
+    let y = 0;
+    while y < 10 {
```
Comment (flip1995) [inline tests/ui/infinite_loop.rs]: We still want to lint this until we split up the lints.

Comment (yerke) [reply tests/ui/infinite_loop.rs]: I am not sure I follow. Do you want me to ignore `has_break_or_return_visitor.has_break_or_return` until the other lint is done?

Comment (flip1995) [reply tests/ui/infinite_loop.rs]: Hmm... I read your comment
> Next I will try to break this lint into 2 as suggested in #4648 (comment)

like you want to do this in this PR. But if we should merge this PR as an intermediate fix for this lint, the current behavior is fine.

What I actually meant with this was, that this case should still get linted (but by another lint).

So you choose: Either, we can merge this PR as an intermediate fix or you can split up this lint in this PR.

Comment (yerke) [reply tests/ui/infinite_loop.rs]: Yes, let's merge this one, if you don't mind, and I will start working on the other lint in a separate PR. Thanks.

File: clippy_lints/src/loops.rs [hunk 9]
```diff
@@ -2367,17 +2367,50 @@ fn check_infinite_loop<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, cond: &'tcx Expr, e
...
+    if no_cond_variable_mutated && !mutable_static_in_cond && !has_break_or_return {
         span_lint(
             cx,
             WHILE_IMMUTABLE_CONDITION,
             cond.span,
-            "Variable in the condition are not mutated in the loop body. \
-             This either leads to an infinite or to a never running loop.",
+            "variables in the condition are not mutated in the loop body. \
+             This may lead to an infinite or to a never running loop",
         );
```
Comment (flip1995) [inline clippy_lints/src/loops.rs]: I still don't like, that we stop linting when the loop body contains a `return` or `break` statement. I have an idea how to solve this in this PR:

```rust
span_lint_and_then(
    cx,
    WHILE_IMMUTABLE_CONDITION,
    cond.span,
    "variables in the condition are not mutated in the loop body",
    |db| {
        db.note("this may lead to an infinite or to a never running loop");

        if has_break_or_return {
            db.note("this loop contains `return`s or `break`s");
            db.help("rewrite it as `if cond { loop { } }`");
        }
    },
);
```

That way, we get a better error message, but avoid false negatives:
```
error: variable in the condition are not mutated in the loop body
   --> src/stream.rs:717:19
    |
717 |             while should_skip {
    |                   ^^^^^^^^^^^
    |
    = note: this may lead to an infinite or to a never running loop
    = note: this loop contains `return`s or `break`s
    = help: rewrite it as `if cond { loop { } }`
```

**Comment by yerke** [comment]
@flip1995 Does it look like you wanted to see? Do I understand correctly that we probably don't need to split into another lint any more now?

BTW, I opened https://github.com/rust-lang/rust-clippy/issues/4835 as I am hitting the same issue as Travis CI. But the tests passed before I merged the latest master into my branch.

File: clippy_lints/src/loops.rs [hunk 10]
```diff
@@ -2367,17 +2367,57 @@ fn check_infinite_loop<'a, 'tcx>(cx: &LateContext<'a, 'tcx>, cond: &'tcx Expr, e
...
-        span_lint(
+        span_lint_and_then(
             cx,
             WHILE_IMMUTABLE_CONDITION,
             cond.span,
-            "Variable in the condition are not mutated in the loop body. \
-             This either leads to an infinite or to a never running loop.",
+            "variables in the condition are not mutated in the loop body",
+            |db| {
+                db.note("This may lead to an infinite or to a never running loop");
```
Comment (flip1995) [inline clippy_lints/src/loops.rs]: NIT:

```suggestion
                db.note("this may lead to an infinite or to a never running loop");
```

Comment (yerke) [reply clippy_lints/src/loops.rs]: Done

**Comment by yerke** [comment]
@flip1995 Updated with your suggested changes, and made sure `infinite_loop` test still works after https://github.com/rust-lang/rust-clippy/pull/4825 is merged in.
