### PR TITLE
[`needless_return`] Recursively remove unneeded semicolons

### LINKED ISSUE #8156: needless_return autofix does not remove semicolons when creating implicit returns, causing them to fail
### Summary

In some cases in functions using match statements where it would make a lot of sense to use a implicit return, when clippy attempts to autofix this, it does not correctly remove the semicolons necessary to crate a implicit return, or in some cases thinks it has not, but actuality has.

possibly useful:
- Rust edition: 2021
- no dependancies

also this is my first bug report here, so please give me feedback on it

### Reproducer

when writing a match expression in a function like
```rust
fn foo() -> u64 {
  match bar {
      80 => {
          return 10;
      }
      _ => {
          return 100;
      }
  };
}
```
for a function, clippy suggests to remove the return statements, (which it should). however, after running `cargo clippy --fix --broken-code`, 
it does fix the return, producing
```rust
fn foo() -> u64 {
  match bar {
      80 => {
          10
      }
      _ => {
          100
      }
  }
}
```
however it gives this error:
```
Checking clipy_err_test v0.1.0 ([path removed, contains personal info])
warning: failed to automatically apply fixes suggested by rustc to crate `clipy_err_test`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0308]: mismatched types
  --> src/main.rs:1:21
   |
1  | fn update_read() -> u128 {
   |    -----------      ^^^^ expected `u128`, found `()`
   |    |
   |    implicitly returns `()` as its body has no tail or `return` expression
...
10 |     };
   |      - help: consider removing this semicolon

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
Original diagnostics will follow.

       Fixed src/main.rs (1 fix)
    Finished dev [unoptimized + debuginfo] target(s) in 0.51s
```
even though the resulting code does not have a semicolon where it is pointing to.

By using a larger example, such as 
```rust
struct Test {
    foo: i8
}


fn update_read() -> u128 {
    let read: Result<Test, ()> = Ok(Test{foo:10});
    match read {
        Ok(stat) => {
            match stat.foo {
                10 => {
                    return 80;
                }
                _ => {
                    return 100;
                }
            };
        }
        Err(_) => {
            return 100;
        }
    };
}

fn main() {
    println!("{}", update_read());
}
```
however, it gives a similar error:
```
    Checking clipy_err_test v0.1.0 
warning: failed to automatically apply fixes suggested by rustc to crate `clipy_err_test`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0308]: `match` arms have incompatible types
  --> src/main.rs:20:13
   |
8  |       match read {
   |       ---------- `match` arms have incompatible types
9  |           Ok(stat) => {
10 | /             match stat.foo {
11 | |                 10 => {
12 | |                     80
13 | |                 }
...  |
16 | |                 }
17 | |             };
   | |              -
   | |              |
   | |______________help: consider removing this semicolon
   |                this is found to be of type `()`
...
20 |               100
   |               ^^^ expected `()`, found integer

error[E0308]: mismatched types
 --> src/main.rs:6:21
  |
6 | fn update_read() -> u128 {
  |    -----------      ^^^^ expected `u128`, found `()`
  |    |
  |    implicitly returns `()` as its body has no tail or `return` expression

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
Original diagnostics will follow.

error[E0308]: mismatched types
  --> src/main.rs:6:21
   |
6  | fn update_read() -> u128 {
   |    -----------      ^^^^ expected `u128`, found `()`
   |    |
   |    implicitly returns `()` as its body has no tail or `return` expression
...
22 |     };
   |      - help: consider removing this semicolon

For more information about this error, try `rustc --explain E0308`.
error: could not compile `clipy_err_test` due to previous error
warning: build failed, waiting for other jobs to finish...
warning: failed to automatically apply fixes suggested by rustc to crate `clipy_err_test`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0308]: mismatched types
  --> src/main.rs:6:21
   |
6  | fn update_read() -> u128 {
   |    -----------      ^^^^ expected `u128`, found `()`
   |    |
   |    implicitly returns `()` as its body has no tail or `return` expression
...
22 |     };
   |      - help: consider removing this semicolon

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
Original diagnostics will follow.

error: build failed
```
but this time produces code this is broken, shown here:
```rust
struct Test {
    foo: i8
}


fn update_read() -> u128 {
    let read: Result<Test, ()> = Ok(Test{foo:10});
    match read {
        Ok(stat) => {
            match stat.foo {
                10 => {
                    80
                }
                _ => {
                    100
                }
            }
        }
        Err(_) => {
            100
        }
    };
}

fn main() {
    println!("{}", update_read());
}
```
where there is a semicolon preventing the implicit return.

### Version

```text
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### LINKED ISSUE #8336: Extra semicolon after cargo clippy --fix
### Summary

you can access a reproducible example in this branch: [clippy-fix-error](https://github.com/tvallotton/models/tree/clippy-fix-error). It seems that clippy forgot to remove a semicolon but I'm not entirely sure. I ran `clippy --fix` from the `models/models` directory. 

### Version

```text
rustc 1.58.1 (db9d1b20b 2022-01-20)
binary: rustc
commit-hash: db9d1b20bba1968c1ec1fc49616d4742c1725b4b
commit-date: 2022-01-20
host: aarch64-apple-darwin
release: 1.58.1
LLVM version: 13.0.0
```

### Error output

<details><summary>Backtrace</summary>
  <p>

  ```
warning: `models` (lib) generated 46 warnings
warning: failed to automatically apply fixes suggested by rustc to crate `models`

after fixes were automatically applied the compiler reported errors within these files:

  * models/src/orm/mod.rs
  * models/src/private/scheduler/driver/migration.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see 
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0308]: mismatched types
   --> models/src/private/scheduler/driver/migration.rs:86:28
    |
86  |     pub fn commit(self) -> Result<Option<Report>> {
    |            ------          ^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found `()`
    |            |
    |            implicitly returns `()` as its body has no tail or `return` expression
...
104 |         };
    |          - help: consider removing this semicolon
    |
    = note:   expected enum `std::result::Result<std::option::Option<private::scheduler::driver::report::Report>, error::Error>`
            found unit type `()`

warning: unused import: `ConnectOptions`
  --> models/src/orm/mod.rs:12:5
   |
12 |     ConnectOptions,
   |     ^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0308`.
Original diagnostics will follow.
  ```

  </p>
</details>

### LINKED ISSUE #9192: `cargo clippy --fix` fails to fix unneeded return
Running `cargo clippy --fix` fails to fix the following code:

```rust
fn f() -> i32 {
    {
        return 0;
    };
}
```

It tries to convert the `return 0;` into an implicit return, but it fails to remove the semicolon on the following line, which causes the error.

<details><summary>Full Output</summary>
<p>

```
$ cargo clippy --fix
    Checking rustfmt-debug v0.1.0 (/home/seekr/Desktop/rustfmt-debug)
warning: failed to automatically apply fixes suggested by rustc to crate `rustfmt_debug`

after fixes were automatically applied the compiler reported errors within these files:

  * src/lib.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see 
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0308]: mismatched types
 --> src/lib.rs:1:15
  |
1 | pub fn f() -> i32 {
  |        -      ^^^ expected `i32`, found `()`
  |        |
  |        implicitly returns `()` as its body has no tail or `return` expression
...
4 |     };
  |      - help: remove this semicolon

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
Original diagnostics will follow.

warning: unneeded `return` statement
 --> src/lib.rs:3:9
  |
3 |         return 0;
  |         ^^^^^^^^^ help: remove `return`: `0`
  |
  = note: `#[warn(clippy::needless_return)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return

warning: `rustfmt-debug` (lib) generated 1 warning (1 duplicate)
warning: `rustfmt-debug` (lib test) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
```

</p>
</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (c2f428d2f 2022-07-14)
binary: rustc
commit-hash: c2f428d2f3340a0e7d995f4726223db91b93704c
commit-date: 2022-07-14
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### PR DESCRIPTION
**Pull request by kraktus**
fix #8336,
fix #8156,
fix https://github.com/rust-lang/rust-clippy/issues/7358,
fix #9192,
fix https://github.com/rust-lang/rust-clippy/issues/9503

changelog: [`needless_return`] Recursively remove unneeded semicolons

For now the suggestion about removing the semicolons are hidden because they would be very noisy and should be obvious if the user wants to apply the lint manually instead of using `--fix`. This could be an issue for beginner, but haven't found better way to display it.

### CODE REVIEW

File: clippy_lints/src/returns.rs [hunk 1]
```diff
@@ -139,62 +160,65 @@ impl<'tcx> LateLintPass<'tcx> for Return {
...
+            check_final_expr(cx, block_expr, semi_spans, RetReplacement::Empty);
+        } else if let Some(stmt) = block.stmts.iter().last() {
+            match stmt.kind {
+                StmtKind::Expr(expr) => {
+                    check_final_expr(cx, expr, semi_spans, RetReplacement::Empty);
+                },
+                StmtKind::Semi(semi_expr) => {
+                    let mut semi_spans_and_this_one = semi_spans;
+                    // we only want the span containing the semicolon so we can remove it later. From `entry.rs:382`
+                    semi_spans_and_this_one.push(stmt.span.trim_start(semi_expr.span).unwrap_or(DUMMY_SP));
```
Comment (llogiq) [inline clippy_lints/src/returns.rs:185]: Might be a good idea not to push DUMMY_SP here:

```suggestion
                    if let Some(semi_span) = stmt.span.trim_start(semi_expr.span) {
                        semi_spans_and_this_one.push(semi_span);
                    }
```

Comment (kraktus) [reply clippy_lints/src/returns.rs:185]: Normally the span of the Expr inside a statement should never be larger than the statement itself, but will change it's less error prone in case of futur refactor

**Comment by llogiq** [comment]
Sorry @flip1995 for stealing the review 😉

Thanks @kraktus!

@bors r+

**Comment by Mark-Simulacrum** [comment]
@llogiq can you re-approve this PR? We're fixing some bors missing events (which is why I closed/opened it etc); see https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/bors.20stuck.20for.20Miri.20and.20other.20tools.3F for some additional context.

**Comment by llogiq** [comment]
Sure!

@bors r+
