### PR TITLE
Fix false-positive `manual_unwrap_or` inside const fn

### LINKED ISSUE #6898: `manual_unwrap_or` should not trigger inside const fn
I tried this code:

```rust
const fn baz(x: Option<i32>) -> i32 {
    match x {
        Some(x) => x,
        None => 0
    }
}
```

I expected to see this happen: no lint error, beacuse `.unwrap_or` cannot be used inside a `const fn` yet.

Instead, this happened: `manual_unwrap_or` lint triggers.

### Meta

- `cargo clippy -V`: clippy 0.0.212 (cb75ad5 2021-02-10)
- `rustc -Vv`:
  ```
  rustc 1.50.0 (cb75ad5db 2021-02-10)
  binary: rustc
  commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
  commit-date: 2021-02-10
  host: x86_64-unknown-linux-gnu
  release: 1.50.0
  ```

### PR DESCRIPTION
**Pull request by MysteryJump**
Fixes #6898 

changelog:  Fix false-positive for manual_unwrap_or in const fn.

### CODE REVIEW

File: clippy_lints/src/manual_unwrap_or.rs [hunk 1]
```diff
@@ -44,11 +44,34 @@ declare_clippy_lint! {
...
+        span: Span,
+        _: HirId,
+    ) {
+        if in_external_macro(cx.sess(), span) {
             return;
         }
-        lint_manual_unwrap_or(cx, expr);
+        if_chain! {
+            if let FnKind::ItemFn(_, _, header, _) = kind;
+            if !header.is_const();
```
Comment (giraffate) [inline clippy_lints/src/manual_unwrap_or.rs:61]: I think it would be better to use `in_constant` in this case: <https://github.com/rust-lang/rust-clippy/blob/1a206fc4abae0b57a3f393481367cf3efca23586/clippy_utils/src/lib.rs#L199>

**Comment by Manishearth** [comment]
gonna r? @giraffate unless you want me to review this :)

**Review by giraffate — APPROVED** [review]
This looks good to me. Thanks!

**Comment by Manishearth** [comment]
@bors delegate=giraffate r=giraffate

oops, forgot delegate doesn't work that way, sorry @giraffate
