### PR TITLE
fix: `iter_cloned_collect` FP with custom `From`/`IntoIterator` impl

### LINKED ISSUE #9119: iter_cloned_collect false positive with custom From/IntoIterator impl
### Summary

When `FromIterator` is implemented for a type inside an another iterator, `.collect()`  is able to do run the inner iterator as well. Clippy doesn't recognize this case, and instead assumes that `.iter().cloned().collect()` to a `Vec<_>` always has the same resulting type than `to_vec()`.  This also occurs with `.iter().copied().collect()`.

### Lint Name

iter_cloned_collect and iter_cloned_collect

### Reproducer

I tried this code:

```rust
use std::iter;

#[derive(Clone)]
struct Example(u16);

impl iter::FromIterator<Example> for Vec<u8> {
    fn from_iter<T>(iter: T) -> Self
    where
        T: IntoIterator<Item = Example>,
    {
        iter.into_iter().flat_map(|e| e.0.to_le_bytes()).collect()
    }
}

fn main() {
    let examples = vec![Example(1), Example(0x1234)];
    let encoded: Vec<u8> = examples.iter().cloned().collect();
    assert_eq!(encoded, vec![0x01, 0x00, 0x34, 0x12]);
}

```

I saw this happen:

```
warning: called `iter().copied().collect()` on a slice to create a `Vec`. Calling `to_vec()` is both faster and more readable
  --> src/main.rs:17:36
   |
17 |     let encoded: Vec<u8> = examples.iter().copied().collect();
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `.to_vec()`
   |
   = note: `#[warn(clippy::iter_cloned_collect)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#iter_cloned_collect
```

I expected to see this happen:

No warning, as the `to_vec` cannot do the required conversion.

### Version

```text
rustc 1.62.0 (a8314ef7d 2022-06-27)
binary: rustc
commit-hash: a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
commit-date: 2022-06-27
host: x86_64-unknown-linux-gnu
release: 1.62.0
LLVM version: 14.0.5
```

### Additional Labels

@rustbot label +l-suggestion-causes-error

### PR DESCRIPTION
**Pull request by profetia**
Closes #9119

changelog: [`iter_cloned_collect`]: fix FP with custom `From`/`IntoIterator` impl

### CODE REVIEW

File: clippy_lints/src/methods/iter_cloned_collect.rs [hunk 1]
```diff
@@ -1,16 +1,22 @@
...
 
 pub(super) fn check<'tcx>(cx: &LateContext<'tcx>, method_name: &str, expr: &hir::Expr<'_>, recv: &'tcx hir::Expr<'_>) {
-    if is_type_diagnostic_item(cx, cx.typeck_results().expr_ty(expr), sym::Vec)
+    let expr_ty = cx.typeck_results().expr_ty(expr);
+    if is_type_diagnostic_item(cx, expr_ty, sym::Vec)
         && let Some(slice) = derefs_to_slice(cx, recv, cx.typeck_results().expr_ty(recv))
+        && let ty::Adt(_, args) = expr_ty.kind()
+        && let Some(vec_item_ty) = args.types().next()
+        && let Some(iter_item_ty) = get_iterator_item_ty(cx, cx.typeck_results().expr_ty(recv))
+        && vec_item_ty == iter_item_ty.peel_refs()
```
Comment (samueltardieu) [inline clippy_lints/src/methods/iter_cloned_collect.rs:19]: You know `expr` is a `Vec`, you can use `type_at()` on the args:

```suggestion
        && let Some(iter_item_ty) = get_iterator_item_ty(cx, cx.typeck_results().expr_ty(recv))
        && iter_item_ty.peel_refs() == args.type_at(0)
```

Comment (profetia) [reply clippy_lints/src/methods/iter_cloned_collect.rs]: Thank you!

**Comment by profetia** [comment]
r? clippy

File: clippy_lints/src/methods/iter_cloned_collect.rs [hunk 2]
```diff
@@ -1,16 +1,21 @@
...
 use super::ITER_CLONED_COLLECT;
 
 pub(super) fn check<'tcx>(cx: &LateContext<'tcx>, method_name: &str, expr: &hir::Expr<'_>, recv: &'tcx hir::Expr<'_>) {
-    if is_type_diagnostic_item(cx, cx.typeck_results().expr_ty(expr), sym::Vec)
+    let expr_ty = cx.typeck_results().expr_ty(expr);
+    if is_type_diagnostic_item(cx, expr_ty, sym::Vec)
         && let Some(slice) = derefs_to_slice(cx, recv, cx.typeck_results().expr_ty(recv))
+        && let ty::Adt(_, args) = expr_ty.kind()
+        && let Some(iter_item_ty) = get_iterator_item_ty(cx, cx.typeck_results().expr_ty(recv))
+        && iter_item_ty.peel_refs() == args.type_at(0)
```
Comment (samueltardieu) [inline clippy_lints/src/methods/iter_cloned_collect.rs:18]: You may end up peeling too many levels. For example, the following will be a false negative:

```rust
    let a = [&&String::new()];
    let v: Vec<&&String> = a.iter().cloned().collect();
```

I would have went with something like the following:

```suggestion
        && let ty::Ref(_, ty, _) = iter_item_ty.kind()
        && *ty == args.type_at(0)
```

**Review by samueltardieu — CHANGES_REQUESTED** [review]
@rustbot author

File: clippy_lints/src/methods/iter_cloned_collect.rs (hunk 2 above)
Comment (profetia) [reply clippy_lints/src/methods/iter_cloned_collect.rs]: Good point. Updated
