### PR TITLE
Fix match_same_arms to fail late

### LINKED ISSUE #4096: Make match_same_arms lint fail late
Currently the `match_same_arms` lint fails early. If we have code like this:
```rust
match a {
    Foo::A => 1,
    Foo::B => 1,
    Foo::C => 2,
    Foo::D => 2,
};
```
the lint first triggers on `Foo::A` and `Foo::B` and when this case is fixed it will trigger on `Foo::C` and `Foo::D`. This is especially annoying on big `match`es where there are multiple identical arms.

It would be nice if the lint would first collect all the identical tuples of arms and then warn on all of them at once, instead of failing early.

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=81c99a8499564bb2f8bdea11c42bfb70)

### PR DESCRIPTION
**Pull request by Urriel**
Changes:
- Add a function search_same_list which return a list of matched expressions
- Change the match_same_arms implementation behavior. It will lint each same arms found.

fixes #4096 

changelog: none

### CODE REVIEW

**Comment by Urriel** [comment]
Hello, I would like some feedback, especially for the tests. I have some tests failing and did not figure out yet out to fix them.

**Comment by flip1995** [comment]
Hey, thanks for the contribution! 

Have you looked at https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md#testing? It is described there how to update reference files (*.stderr files) and how to add tests.
If you have and tests are still failing, please push the tests+stderr files, so I can take a look at them.

**Comment by Urriel** [comment]
Thank you for the tips I did not pay attention to the doc folder. You guys did a good job making contributing trivial.

My last commit should add the right test and fix the test errors.

**Comment by flip1995** [comment]
> You guys did a good job making contributing trivial.

Happy to here that!

With your changes the first error doesn't get printed anymore. That's a regression we want to avoid. Could you look into that?

File: clippy_lints/src/copies.rs [hunk 1]
```diff
@@ -360,3 +364,36 @@ where
 
     None
 }
+
+fn search_same_list<T, Hash, Eq>(exprs: &[T], hash: Hash, eq: Eq) -> Option<Vec<(&T, &T)>>
```
Comment (pJunger) [inline clippy_lints/src/copies.rs]: Why return an Option here? Is there any more information than you get if the Vec is empty?

File: clippy_lints/src/copies.rs [hunk 2]
```diff
@@ -360,3 +364,36 @@ where
...
+where
+    Hash: Fn(&T) -> u64,
+    Eq: Fn(&T, &T) -> bool,
+{
+    let mut match_expr_list: Vec<(&T, &T)> = Vec::new();
+
```
Comment (pJunger) [inline clippy_lints/src/copies.rs]: Compared to the `search_same` implementation you dropped the 'common cases' check - is this intentional?

Comment (Urriel) [reply clippy_lints/src/copies.rs]: That's why I miss the first error case on the list. I'm trying to make a function out of it in order to not duplicate this code and use it in both methods.

File: clippy_lints/src/copies.rs (hunk 1 above)
Comment (Urriel) [reply clippy_lints/src/copies.rs]: I did not think of this. I'll make the proper arrangements.

**Comment by Urriel** [comment]
I have questions about the "unwrap" line 387. I am not sure its the right way to do it.
Also at the moment, we can see the expression found twice.

File: clippy_lints/src/copies.rs [hunk 3]
```diff
@@ -365,11 +375,18 @@ where
...
 }
 
-fn search_same_list<T, Hash, Eq>(exprs: &[T], hash: Hash, eq: Eq) -> Option<Vec<(&T, &T)>>
+fn search_same_list<T, Hash, Eq>(exprs: &[T], hash: Hash, eq: Eq) -> Vec<(&T, &T)>
 where
     Hash: Fn(&T) -> u64,
     Eq: Fn(&T, &T) -> bool,
 {
+
+    let matched_expr = search_common_cases(&exprs, &eq);
```
Comment (pJunger) [inline clippy_lints/src/copies.rs]: You could use `if let` to circumvent the use of `unwrap`.

```suggestion
    if let Some(expr) = search_common_cases(&exprs, &eq) {
        return vec![expr];
    }
```

File: clippy_lints/src/copies.rs [hunk 4]
```diff
@@ -185,7 +185,9 @@ fn lint_match_arms(cx: &LateContext<'_, '_>, expr: &Expr) {
         };
 
         let indexed_arms: Vec<(usize, &Arm)> = arms.iter().enumerate().collect();
-        if let Some((&(_, i), &(_, j))) = search_same(&indexed_arms, hash, eq) {
+        for match_expr in search_same_list(&indexed_arms, hash, eq) {
```
Comment (pJunger) [inline clippy_lints/src/copies.rs]: You could also destructure in the for loop to mirror the previous implementation & remove the next line.

```suggestion
for (&(_, i), &(_, j)) in search_same_list(&indexed_arms, hash, eq) {
```

File: clippy_lints/src/copies.rs [hunk 5]
```diff
@@ -323,20 +325,32 @@ where
...
         } else {
             None
-        };
+        }
+    } else {
+        None
+    }
+}
+
+fn search_same<T, Hash, Eq>(exprs: &[T], hash: Hash, eq: Eq) -> Option<(&T, &T)>
```
Comment (pJunger) [inline clippy_lints/src/copies.rs]: Do we even need this function anymore? Now it is used in the if-part of this lint.
Shouldn't search_same_List work there as well?

Comment (Urriel) [reply clippy_lints/src/copies.rs]: I did not want to refactor too much right away.

**Comment by Urriel** [comment]
@pJunger Thank you for your insight it helps a lot.

File: clippy_lints/src/copies.rs (hunk 5 above)
Comment (pJunger) [reply clippy_lints/src/copies.rs]: Got it! Do you want to add this to this commit later? Or maybe we could open an issue for this as well.

**Comment by pJunger** [comment]
You're welcome!

File: clippy_lints/src/copies.rs (hunk 5 above)
Comment (Urriel) [reply clippy_lints/src/copies.rs]: I am doing it right now, just checking again that everything works as intended.

Comment (Urriel) [reply clippy_lints/src/copies.rs]: Tests pass without changes in the if stderr.

Comment (pJunger) [reply clippy_lints/src/copies.rs]: Cool!
Although that just means, that there isn't a change in there that has multiple identical branches?

**Comment by Urriel** [comment]
Great !
Hope this little PR helps the cause.

**Comment by flip1995** [comment]
Thanks for the review @pJunger !

Now that `search_same` is removed you could rename the `search_same_list` function to `search_same`, since it does the same as before, just better. Thoughts?

Also (not really related to the issue, but while you're at it... 😄), could you change these `span_note`:
https://github.com/rust-lang/rust-clippy/blob/cbae9ed8731d7ad8a167e1a779a881812bf14197/clippy_lints/src/copies.rs#L212-L220
to [`span_help`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.DiagnosticBuilder.html#method.span_help) and use the span of the `pat`s instead of the body. The lint message should then look something like this:

```diff
 ...
+help: consider refactoring into `41 | 52`
-note: consider refactoring into `41 | 52`
   --> $DIR/match_same_arms.rs:115:15
    |
 LL |         41 => 2,
+   |         ^^
-   |               ^
```

And last but not least: Could you add a test where more than 2 match arms are the same:
```rust
match x {
    1 => 2,
    2 => 2,
    3 => 2, // 3rd time the same arm
    4 => 3,
}
```

**Comment by flip1995** [comment]
Thanks! You have to run `tests/ui/update-all-references.sh` again, since `tests/ui/matches.rs` fails now.

**Comment by pJunger** [comment]
Maybe also add a function to the if_same_then_else block with multiple branches?

```
if true {
    let foo = "";
    return Ok(&foo[0..]);
} else if false {
    let foo = "bar";
    return Ok(&foo[0..]);
} else if true {
    let foo = "";
    return Ok(&foo[0..]);
} else {
    let foo = "";
    return Ok(&foo[0..]);
}
```

**Comment by Urriel** [comment]
I hope this fix everything. I forgot to do a full uitest before commiting.

File: tests/ui/match_same_arms.rs [hunk 6]
```diff
@@ -124,6 +124,20 @@ fn match_same_arms() {
...
+    } else if false {
+        let foo = "bar";
+        return Ok(&foo[0..]);
+    } else if true {
+        let foo = "";
+        return Ok(&foo[0..]);
+    } else {
+        let foo = "";
+        return Ok(&foo[0..]);
+    }
```
Comment (pJunger) [inline tests/ui/match_same_arms.rs]: Oh I think this should go into `if_same_then_else.rs`.

Also: It does not find the duplicates here - what did I do wrong here?

Comment (Urriel) [reply tests/ui/match_same_arms.rs]: syntax error

File: tests/ui/match_same_arms.rs [hunk 7]
```diff
@@ -108,6 +108,36 @@ fn match_same_arms() {
...
+
+    let _ = match 42 {
+        1 => 2,
+        2 => 2, //~ ERROR 2rd matched arms have same body
+        3 => 2, //~ ERROR 3rd matched arms have same body
+        4 => 3,
+        _ => 0,
+    };
+
+    let try_it = if true {
```
Comment (flip1995) [inline tests/ui/match_same_arms.rs]: This test seems good now. Maybe:
```suggestion
    let _ = if true {
```

Can you move this test to the correct file?

Also you could change one `true` to `1 == 2` or something, to avoid the `clippy::ifs_same_cond` error.

File: tests/ui/match_same_arms.rs [hunk 8]
```diff
@@ -108,6 +108,36 @@ fn match_same_arms() {
...
+        42 => 1,
+        51 => 1, //~ ERROR match arms have same body
+        41 => 2,
+        52 => 2, //~ ERROR match arms have same body
+        _ => 0,
+    };
+
+    let _ = match 42 {
+        1 => 2,
+        2 => 2, //~ ERROR 2rd matched arms have same body
```
Comment (flip1995) [inline tests/ui/match_same_arms.rs]:
```suggestion
        2 => 2, //~ ERROR 2nd matched arms have same body
```

File: tests/ui/match_same_arms.rs (hunk 7 above)
Comment (Urriel) [reply tests/ui/match_same_arms.rs]: "1 == 2" condition throws me the same error for the clippy::ifs_same_cond error.

Comment (flip1995) [reply tests/ui/match_same_arms.rs]: Oh then the lint is too smart :D In that case, could you just allow that lint in the test file?

File: tests/ui/if_same_then_else.rs [hunk 9]
```diff
@@ -232,6 +232,20 @@ fn if_same_then_else() -> Result<&'static str, ()> {
         return Ok(&foo[0..]);
     }
 
+    if true {
+        let foo = "";
+        return Ok(&foo[0..]);
```
Comment (flip1995) [inline tests/ui/if_same_then_else.rs]: Shouldn't this `if` body get linted also?

Comment (Urriel) [reply tests/ui/if_same_then_else.rs]: it seems that the behavior for the if_arms lint is only targeted to the "then else" parts.
`lint_same_then_else`

**Comment by flip1995** [comment]
LGTM now.

2 Things left to do:
- run `cargo fmt --all`
- squash some of the commits

and this is good to go.

**Comment by Urriel** [comment]
I try to install rustfmt, but I get this errors:

'cargo-fmt' is not installed for the toolchain 'master'
toolchain 'master' does not support components

**Comment by flip1995** [comment]
Yeah, you can't really install components on the master toolchain.

For Clippy we use nightly rustfmt anyway (for this reason). So install rustfmt for nightly and then run `cargo +nightly fmt --all`

**Comment by Urriel** [comment]
That should cover it.
