### PR TITLE
consider mutability on useless_vec suggestions

### LINKED ISSUE #7035: useless_vec does not consider mutability
I tried this code:

```rust
fn on_mut_slice(_: &mut [u8]) {}
fn main() { 
    on_mut_slice(&mut vec![]);
}
```

I expected to see this happen:
clippy to suggest I could use a *mutable reference* to a slice.
e.g:
```
help: you can use a slice directly: `&mut []`
```
Instead, this happened:
clippy suggested I could use a slice, not mutable, so applying the suggestion results in code not compiling.
suggestion
```
help: you can use a slice directly: `&[]`
```
compiler error:
```
   |     on_mut_slice(&[]);
   |                  ^^^ types differ in mutability
```

### Meta

- `cargo clippy -V`: clippy 0.1.51 (2fd73fab 2021-03-23)
- `rustc -Vv`:
  ```
  rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-apple-darwin
release: 1.51.0
LLVM version: 11.0.1
  ```

### PR DESCRIPTION
**Pull request by horacimacias**
fixes #7035 

changelog: Now the suggested by `useless_vec` considers mutability to suggest either `&[]`, as before, or `&mut []` if the used reference is mutable.

### CODE REVIEW

**Comment by giraffate** [comment]
Thanks for your work, and welcome to Clippy!

Overall looks good. 
The test looks to fail because of formatting, so can you update on this? This document is helpful: <https://github.com/rust-lang/rust-clippy/blob/master/doc/adding_lints.md#running-rustfmt>.
Also, can you squash commits?

**Comment by horacimacias** [comment]
thanks!
I've formatted and squashed. 
I think it should be good now.

File: tests/ui/vec.rs [hunk 1]
```diff
@@ -22,28 +27,38 @@ impl Line {
...
     on_slice(&vec![1, 2]);
     on_slice(&[1, 2]);
+    on_mut_slice(&mut vec![1, 2]);
 
     on_slice(&vec![1, 2]);
     on_slice(&[1, 2]);
+    on_mut_slice(&mut vec![1, 2]);
     #[rustfmt::skip]
-    on_slice(&vec!(1, 2));
+        on_slice(&vec!(1, 2));
```
Comment (giraffate) [inline tests/ui/vec.rs:40]: Is this spaces what you intended?

**Review by giraffate — APPROVED** [review]
LGTM with nits

File: tests/ui/vec.rs (hunk 1 above)
Comment (horacimacias) [reply tests/ui/vec.rs]: ah sorry, didn't realise that and the skip flag was of course skipping this.
There was no particular reason for those spaces; I just pushed again without them.
thanks for the patience.

**Comment by giraffate** [comment]
@bors r+

Thanks!
