### PR TITLE
Fix: redundant_pattern_matching drop order

### LINKED ISSUE #5746: Some(_) is not equivalent to is_some()
I found a situation in which `if let Some(_) = func()` and `if func().is_some()` don't do the same thing. In particular, the latter deadlocks while the former doesn't. This is relevant for the redundant_pattern_matching lint. I replicated this behavior in debug and release mode with rustc 1.44.0.

[Here is the situation](https://github.com/josh65536/rust-is-some-deadlock/blob/master/src/main.rs)

### PR DESCRIPTION
**Pull request by Jarcho**
Fixes #5746

A note about the change in drop order is added when the scrutinee (or any temporary in the expression) isn't known to be safe to drop in any order (i.e. doesn't implement the `Drop` trait, or contain such a type). There is a whitelist for some `std` types, but it's incomplete. Currently just `Vec<_>`, `Box<_>`, `Rc<_>` and `Arc<_>`, but only if the contained type is also safe to drop in any order.

Another lint for when the drop order changes could be added as allowed by default, but the drop order requirement is pretty subtle in this case. I think the note added to the lint should be enough to make someone think before applying the change.

changelog: Added a note to `redundant_pattern_matching` when the change in drop order might matter

### CODE REVIEW

**Comment by giraffate** [comment]
The test seems to fail because `redundant_pattern_matching_result.stderr` file is too long. How about splitting the test file into two?

**Review by flip1995 — COMMENTED** [review]
I'm totally lost. I don't understand what any of this code does. Please add more (doc) comments to the functions better describing it.

The only thing I found reviewing this is that the ``get_temporary_tys`` may be better implemented by a visitor.

**Comment by giraffate** [comment]
ping from triage @Jarcho. Could you have any update on this?

**Comment by giraffate** [comment]
ping from triage @Jarcho. According to the triage procedure, I'm closing this because 2 weeks have passed with no activity. If you have more time to work on this, feel free to reopen this.

**Comment by Jarcho** [comment]
Great timing, I just went through and cleaned it up. I don't have the ability to re-open.

**Comment by giraffate** [comment]
@Jarcho Thanks! I reopened this.

File: clippy_lints/src/matches.rs [hunk 1]
```diff
@@ -1602,17 +1759,36 @@ mod redundant_pattern_match {
...
+            op_ty
+        } else {
+            inner_ty
+        };
+
+        // All temporaries created in the scrutinee expression are dropped at the same time as the
+        // scrutinee would be, so they have to be considered as well.
+        // e.g. in `if let Some(x) = foo.lock().unwrap().baz.as_ref() { .. }` the lock will be held
+        // for the duration if body.
+        let needs_drop = type_needs_ordered_drop(cx, check_ty) || temporaries_need_ordered_drop(cx, op);
```
Comment (flip1995) [inline clippy_lints/src/matches.rs:1790]: This check **has** to be somewhere in MIR already.  IIUC This is basically checking for this: https://doc.rust-lang.org/stable/reference/destructors.html#temporary-scopes

Am I correct, that you want to check for this behavior?

Comment (Jarcho) [reply clippy_lints/src/matches.rs:1790]: That is what I'm checking for. There should be some way, but I don't know how to link MIR to the expression it came from. It would be the better solution.

Comment (flip1995) [reply clippy_lints/src/matches.rs:1790]: I also am not experienced with the MIR. @oli-obk can you help out here, please?

Comment (oli-obk) [reply clippy_lints/src/matches.rs:1790]: The MIR indeed contains this information. But in order to leverage that information, the lint would need to be rewritten as a MIR lint, as it is nigh impossible to map between the HIR and the MIR. In the MIR all `Drop` invocations are explicit, so similarly to our "unnecessary clone lint", we can write a dataflow analysis on MIR that will tell us at any specific location in the MIR whether a specific local is going to be dropped by the time we reach that location.

Rewriting as a MIR lint should be done independently from any changes, as to not accidentally introduce changes.

**Comment by giraffate** [comment]
ping from triage @Jarcho. Could you have any update on this?

File: clippy_lints/src/matches.rs (hunk 1 above)
Comment (Jarcho) [reply clippy_lints/src/matches.rs:1790]: Given that the lint operates specifically on match expressions, and that we'd be looking specifically at the temporary values created in the scrutinee expression, is it fair to say that would be non-trivial to look for in the MIR?

Is there any way to use the code lowering the HIR into the MIR to find if there are any temporary values created by an expression which will need to subsequently be dropped?

Comment (Jarcho) [reply clippy_lints/src/matches.rs:1790]: @oli-obk can I get you to weigh in here one more time, please?

Comment (oli-obk) [reply clippy_lints/src/matches.rs:1790]: I don't see a good way to do this on the MIR at this time. The information is indeed available during HIR -> MIR lowering (well... in the THIR, which is between the two). The THIR is being heavily refactored at the moment and unsafety checking will be built on THIR. It may be reasonable to implement this analysis on THIR at that point, but not now.

So...

> is it fair to say that would be non-trivial to look for in the MIR?

yes

> Is there any way to use the code lowering the HIR into the MIR to find if there are any temporary values created by an expression which will need to subsequently be dropped?

Not yet. So proceeding with the PR as it is written seems good

Comment (Jarcho) [reply clippy_lints/src/matches.rs:1790]: Thank you.

**Comment by Jarcho** [comment]
@flip1995 Anything else to point out?

**Comment by flip1995** [comment]
I'll have to take another look at this PR.

File: clippy_lints/src/matches.rs [hunk 2]
```diff
@@ -1553,47 +1558,199 @@ where
...
 
+    // Check if the drop order for a type matters
+    fn type_needs_ordered_drop(cx: &LateContext<'tcx>, ty: Ty<'tcx>) -> bool {
+        if !ty.needs_drop(cx.tcx, cx.param_env) {
+            false
+        } else if cx
+            .tcx
+            .lang_items()
+            .drop_trait()
+            .map_or(false, |id| !implements_trait(cx, ty, id, &[]))
```
Comment (flip1995) [inline clippy_lints/src/matches.rs:1597]: IIUC `drop_trait()` only returns `None` if the `Drop` trait isn't defined. If the drop trait isn't defined, you can't implement it. So wouldn't it make sense to return `true` in the  default case of `map_or`?

File: clippy_lints/src/matches.rs [hunk 3]
```diff
@@ -1553,47 +1558,199 @@ where
...
                 _ => {},
             }
         }
     }
 
+    // Check if the drop order for a type matters
+    fn type_needs_ordered_drop(cx: &LateContext<'tcx>, ty: Ty<'tcx>) -> bool {
+        if !ty.needs_drop(cx.tcx, cx.param_env) {
+            false
+        } else if cx
```
Comment (flip1995) [inline clippy_lints/src/matches.rs:1593]: Why is `needs_drop` not enough here? The [documentation](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TyS.html#method.needs_drop) says:

> if it returns `false`, then `ty` definitely has no destructor (i.e., no drop glue).

Skimming the query code, it also checks ADT fields and so on.

**Review by flip1995 — COMMENTED** [review]
Implementation LGTM. I have 2 questions remaining.

File: clippy_lints/src/matches.rs (hunk 2 above)
Comment (Jarcho) [reply clippy_lints/src/matches.rs:1597]: That is correct.

File: clippy_lints/src/matches.rs (hunk 3 above)
Comment (Jarcho) [reply clippy_lints/src/matches.rs:1593]: It's not enough to determine whether drop order matters. The drop order for something `Vec` doesn't impact program correctness* and, by extension, neither would `(Vec, Vec)`. `needs_drop` is a good way to short circuit a search through all fields as the query would have already run for every type, and a good chunk of types don't actually need to be dropped.

The whole point of this change is to note that the suggested change is not correct in the case where drop order is being relied on. There's no way to handle this in the general case, but there are a few std types which implement drop only to deallocate memory. 

* I guess you could use `Vec` while implementing the allocator it uses, but that's a rather pathological case.

Comment (flip1995) [reply clippy_lints/src/matches.rs]: Thanks for clarifying this. Can you add this as a comment to the function, please?

**Review by flip1995 — APPROVED** [review]
LGTM. Needs a rebase and a comment on the `type_needs_ordered` drop with the explanation you provided in the discussion above.

**Comment by flip1995** [comment]
@bors r+

Thanks! Great job!
