### PR TITLE
`item_name_repetitions`: exclude enum variants with identical path components

### LINKED ISSUE #13637: `enum_variant_names` does not consider encapsulated type
Clippy is unhappy with this perfectly reasonable enum:

```rust
pub enum Error {
    RecvError(udp::RecvError),
    SendError(udp::SendError),
    BindError(udp::BindError),
    AddressFamilyUnavailable,
}
```

The lint `enum_variant_names` fires because `RecvError`, `SendError` and `BindError` variants are named like the type. That's the fundamental point of the lint, but it fails to consider information that'd be available to the linter: That that substring is also part of the encapsulated type.

I'm not well enough familiar with clippy to come up with code, but I'd like to suggest the following addition to the lint's rules:

> If the variant contains a single item, and any component of the contained item's path is identical to the variant's name, then the lint does not trigger.

By including the full path, it would even protect a hypothetical `enum Cbor { MiniCbor(minicbor::Something), SerdeCbor(serde_cbor::Something) }`; I can't tell how much going-out-of-the-way it would need to catch `SerdeCbor` to be justified by `serde_cbor`, so maybe a simpler version that just doesn't trigger on the real example above suffices.

### PR DESCRIPTION
**Pull request by aaron-ang**
fix rust-lang/rust-clippy#13637

As suggested in the PR above, we should not lint enum variants containing matching path names.

changelog: [`item_name_repetitions`]: exclude enum variants with identical path components

### CODE REVIEW

**Comment by aaron-ang** [comment]
r? clippy

File: clippy_lints/src/item_name_repetitions.rs [hunk 1]
```diff
@@ -202,22 +202,55 @@ impl ItemNameRepetitions {
...
             check_enum_start(cx, item_name, var);
             check_enum_end(cx, item_name, var);
         }
 
         Self::check_enum_common_affix(cx, item, def);
     }
 
+    // Exclude enum variants that contain a single item where any component
+    // of the contained item's path is identical to the variant's name.
+    fn filter_matching_enum_data<'a>(def: &'a EnumDef<'a>) -> Vec<&'a Variant<'a>> {
```
Comment (Manishearth) [inline clippy_lints/src/item_name_repetitions.rs:224]: issue: I don't think we should prefilter; we should instead perform this check in `check_enum_start` and `check_enum_end` _after_ we think we want to lint on it (so we perform this more expensive check later)

Comment (aaron-ang) [reply clippy_lints/src/item_name_repetitions.rs]: makes sense, I've made changes to reflec this
