### PR TITLE
Fix false positive for unit_arg lint

### LINKED ISSUE #6447: False positive for unit_arg when forwarding arguments
I tried this code:

```rust
trait Tr {
    type Args;
    fn do_it(args: Self::Args);
}

struct A;
impl Tr for A {
    type Args = ();
    fn do_it(_: Self::Args) {}
}

struct B;
impl Tr for B {
    type Args = <A as Tr>::Args;

    fn do_it(args: Self::Args) {
        A::do_it(args)
    }
}
```

I expected to see this happen: No lint trigger.

Instead, this happened:

```
warning: passing a unit value to a function
  --> src/lib.rs:17:9
   |
17 |         A::do_it(args)
   |         ^^^^^^^^^^^^^^
   |
   = note: `#[warn(clippy::unit_arg)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unit_arg
help: move the expression in front of the call and replace it with the unit literal `()`
   |
17 |         args;
18 |         A::do_it(())
   |
```

### Meta

- `cargo clippy -V`: clippy 0.0.212 (7eac88abb 2020-11-16)
- `rustc -Vv`:
  ```
  rustc 1.48.0 (7eac88abb 2020-11-16)
  binary: rustc
  commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
  commit-date: 2020-11-16
  host: x86_64-apple-darwin
  release: 1.48.0
  LLVM version: 11.0
  ```

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=00536070342bc4272bf55d028d065d03

### PR DESCRIPTION
**Pull request by mdm**
Fixes #6447 

To avoid false positives don't complain about unit args when they come from a path expression, e.g. a local variable.

**Note:** This is my first contribution to Clippy, so I might have messed up somewhere. Any feedback is welcome and I'm happy to work out any kinks.

---

changelog: Do not lint unit arguments when they come from a path expression.

### CODE REVIEW

**Comment by mdm** [comment]
I saw that the check for the size of the .stderr file failed. What would be the best way to resolve this?

**Comment by giraffate** [comment]
How about splitting the test file into two?

File: clippy_lints/src/types.rs [hunk 1]
```diff
@@ -955,7 +955,16 @@ impl<'tcx> LateLintPass<'tcx> for UnitArg {
                     .iter()
                     .filter(|arg| {
                         if is_unit(cx.typeck_results().expr_ty(arg)) && !is_unit_literal(arg) {
```
Comment (camsteffen) [inline clippy_lints/src/types.rs:957]: Can you check the `TypeFlags` to see if the type was resolved from a variable? Maybe `expr_ty(arg).needs_subst()`.

**Comment by Manishearth** [comment]
@camsteffen do you wanna handle review for this? I forgot this was in my queue.

@bors delegate=camsteffen

**Comment by camsteffen** [comment]
okay

File: clippy_lints/src/types.rs (hunk 1 above)
Comment (mdm) [reply clippy_lints/src/types.rs:957]: Sorry, for the slow response. I missed your comment regarding the type flags. Checking `needs_subst()` does not seem to have the desired effect. The following example passes linting with my implemention, but running `needs_subst()` on the type for the argument of `foo` returns `false`:
```
    let arg = if true {
        1;
    };
    foo(arg);
```
I'm not familiar with the compiler internals. I looked at the definition of the various type flags, but did not really understand many of them. Do you have any suggestions?

Comment (mdm) [reply clippy_lints/src/types.rs:957]: Thinking about it some more, I guess you meant **type variables** (as in the example in issue #6447). I will test that again later today.

Comment (camsteffen) [reply clippy_lints/src/types.rs:957]: Yes I'm hoping we can detect type variables by looking that the [`TypeFlags`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TypeFlags.html) which is readable through [`TypeFoldable`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/fold/trait.TypeFoldable.html) (that's where needs_subst is). Another method in there that might be useful is `has_projections` which means a type with `<X as Y>::Z`. I am guessing a bit here as I don't completely understand when those different flags apply.

I'm afraid this might be even more complicated - we may have to detect "does the type variable reference a type that is defined outside of the impl block?".

Comment (mdm) [reply clippy_lints/src/types.rs:957]: I think we need a different approach here. Using the example from issue #6447 I checked a __all__ type flags and they are all `false`. So we might not get any help there.
One problem might be that the original lint looks at the type of the expression passed as the argument and not at the type of the argument from the function definition.
I'll investigate this further, but if you have additional ideas I would be grateful.

Comment (camsteffen) [reply clippy_lints/src/types.rs:957]: After thinking on this again, I think we should simply not lint if `matches(arg.kind, ExprKind::Path)`. This will not lint if `arg` is a local variable.

It may be bad style to have a variable with unit as the type, but I think that should be linted upon declaration of the variable (not in this lint).

Comment (mdm) [reply clippy_lints/src/types.rs:957]: Ok, I changed my implementation to check for `ExprKind::Path`.

Comment (camsteffen) [reply clippy_lints/src/types.rs:957]: Sorry to send you for a loop there.

**Comment by camsteffen** [comment]
The fix looks good. Please add a test like the code in the bug report to give us better security for future enhancements.

**Comment by mdm** [comment]
I added the function `baz` as a simplified version of the code in the bug report. Should I add the exact test case from there instead?

**Comment by camsteffen** [comment]
The test you added is good. Another test like the one in the bug report would be help us make sure we continue to handle that case properly in the future.

**Comment by camsteffen** [comment]
Thanks! @bors r+
