### PR TITLE
correct suggestion for `manual_div_ceil` lint

### LINKED ISSUE #13843: `manual_div_ceil` lint can suggest broken code
### Summary

The `manual_div_ceil` list may suggest broken code with a method called on an integer literal of ambiguous type. Clippy should either not make the suggestion or insert the correct type suffix.

### Reproducer

I tried this code:

```rust
fn main() {
    let blocks = 3usize;
    let _ = (4096 + blocks - 1) / blocks;
}
```

Clippy suggests the following fix:
```
warning: manually reimplementing `div_ceil`
 --> src/main.rs:3:13
  |
3 |     let _ = (4096 + blocks - 1) / blocks;
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using `.div_ceil()`: `4096.div_ceil(blocks)`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_div_ceil
  = note: `#[warn(clippy::manual_div_ceil)]` on by default
```

The suggested code fails to compile because of the ambiguous integer type:
```
error[E0689]: can't call method `div_ceil` on ambiguous numeric type `{integer}`
 --> src/main.rs:3:18
  |
3 |     let _ = 4096.div_ceil(blocks);
  |                  ^^^^^^^^
  |
help: you must specify a concrete type for this numeric value, like `i32`
  |
3 |     let _ = 4096_i32.div_ceil(blocks);
  |             ~~~~~~~~
```

### Version

```text
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: x86_64-unknown-linux-gnu
release: 1.83.0
LLVM version: 19.1.1

Also affected:

rustc 1.85.0-nightly (c26db435b 2024-12-15)
binary: rustc
commit-hash: c26db435bf8aee2efc397aab50f3a21eb351d6e5
commit-date: 2024-12-15
host: x86_64-unknown-linux-gnu
release: 1.85.0-nightly
LLVM version: 19.1.5
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by lapla-cogito**
fix #13843

The `manual_div_ceil` lint makes incorrect suggestion when type suffixes need to be made explicit in the suggested code.

changelog: [`manual_div_ceil`]: suggested code now includes appropriate type suffixes where necessary

### CODE REVIEW

File: clippy_lints/src/manual_div_ceil.rs [hunk 1]
```diff
@@ -130,6 +130,22 @@ fn check_eq_expr(cx: &LateContext<'_>, lhs: &Expr<'_>, rhs: &Expr<'_>) -> bool {
...
+    let snip = snippet(cx, expr.span, "..");
+    let numeric_types = [
+        "i8", "i16", "i32", "i64", "i128", "isize", "u8", "u16", "u32", "u64", "u128", "usize",
+    ];
+
+    for ty in numeric_types {
+        if snip.ends_with(ty) {
+            return true;
+        }
+    }
```
Comment (lapla-cogito) [inline clippy_lints/src/manual_div_ceil.rs:144]: I'm not sure if there is a better way to determine if `Expr` is a literal with a type suffix...

File: clippy_lints/src/manual_div_ceil.rs [hunk 2]
```diff
@@ -138,9 +154,29 @@ fn build_suggestion(
     applicability: &mut Applicability,
 ) {
     let dividend_sugg = Sugg::hir_with_applicability(cx, lhs, "..", applicability).maybe_par();
+    let mut type_suffix = String::new();
+    if cx.typeck_results().expr_ty(lhs).is_numeric()
+        && !is_include_type_suffix(cx, lhs)
+        && matches!(lhs.kind, ExprKind::Lit(_) | ExprKind::Unary(_, _))
+    {
+        type_suffix = format!("_{}", cx.typeck_results().expr_ty(rhs));
+    }
```
Comment (lapla-cogito) [inline clippy_lints/src/manual_div_ceil.rs:163]: If it is numeric and a literal (e.g. `3`) or unary (e.g. `-3`) that needs to be type-suffixed, make the type suffix to match the type of `rhs` here.

File: clippy_lints/src/manual_div_ceil.rs [hunk 3]
```diff
@@ -138,9 +154,30 @@ fn build_suggestion(
...
 ) {
     let dividend_sugg = Sugg::hir_with_applicability(cx, lhs, "..", applicability).maybe_par();
+    let type_suffix = if cx.typeck_results().expr_ty(lhs).is_numeric()
+        && !is_include_type_suffix(cx, lhs)
+        && matches!(lhs.kind, ExprKind::Lit(_) | ExprKind::Unary(_, _))
+    {
+        format!("_{}", cx.typeck_results().expr_ty(rhs))
+    } else {
+        String::new()
+    };
```
Comment (lapla-cogito) [inline clippy_lints/src/manual_div_ceil.rs:164]: If it is a numeric and a literal (e.g. 3) or unary (e.g. -3) that needs to be type-suffixed, make the type suffix to match the type of rhs here

File: clippy_lints/src/manual_div_ceil.rs (hunk 1 above)
Comment (y21) [reply clippy_lints/src/manual_div_ceil.rs:144]: If you match on the expr and it's `ExprKind::Lit(LitKind::Int)`, you can check if the int literal type is (not) `LitIntType::Unsuffixed`

Comment (lapla-cogito) [reply clippy_lints/src/manual_div_ceil.rs]: Thank you! I changed to use `LitIntType::Unsuffixed` in https://github.com/rust-lang/rust-clippy/pull/13864/commits/de863026912d9fa86db10003825273697218a6e4.

**Review by xFrednet — APPROVED** [review]
LGTM, the implementation looks really nice, thank you for the update!

---

Roses are `_red`
Violets are `_blue`
Suffixes are `_added`
Like `_u32`
