### PR TITLE
Fix and rename `overflow_check_conditional`

### LINKED ISSUE #2457: false positive: `a - b > b` is not really an underflow check
In the original PR for `overflow_check_conditional`, I found this comment suggesting checks for subtraction: https://github.com/rust-lang-nursery/rust-clippy/pull/741#issuecomment-193456736

I agree with linting `a - b > a` -- there's no way for this to be true without underflow.  You can also look at this algebraically, where this simplifies to `0 > b`, which is nonsense for an unsigned type.

I disagree with linting `a - b > b` -- if you already know that `a - b` won't underflow (from a separate test or precondition), then this is a legitimate way of testing `a > 2 * b`, with the benefit of _avoiding_ potential overflow in `2 * b`.

One could alternately write this as `a > b.saturating_mul(2)` or `a > b.saturating_add(b)`, but I tried this in one of my Project Euler solutions, and it was measurably slower.  Even a raw `a > 2 * b` was slower than `a - b > b`!

Thoughts?

### PR DESCRIPTION
**Pull request by Jarcho**
fixes #2457

Other changes:
* Limit the lint to unsigned types.
* Actually check if the operands are the same rather than using only the first part of the path.
* Allow the repeated expression to be anything as long as there are no side effects.

changelog: Rename `overflow_check_conditional` to `panicking_overflow_check` and move to `correctness`

### CODE REVIEW

File: clippy_lints/src/panicking_overflow_checks.rs [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+                _ => return,
+            }
+            && !other.can_have_side_effects()
+            && let typeck = cx.typeck_results()
+            && let ty = typeck.expr_ty(op_lhs)
+            && matches!(ty.kind(), ty::Uint(_))
+            && ty == typeck.expr_ty(op_rhs)
+            && ty == typeck.expr_ty(other)
+            && !in_external_macro(cx.tcx.sess, expr.span)
+            && (SpanlessEq::new(cx).eq_expr(op_lhs, other)
```
Comment (y21) [inline clippy_lints/src/panicking_overflow_checks.rs:77]: Can this use `eq_expr_value`? That also uses `SpanlessEq::deny_side_effects` and would make that check on L70 redundant. Or is this intentional because rustc has different behavior that you want instead?

`Expr::can_have_side_effects` seems to ban a lot of trivial things that `SpanlessEq` allows, like binary exprs.
Not sure how common this really is, but for example `a + a + b < a + a` doesn't have a warning currently

Comment (Jarcho) [reply clippy_lints/src/panicking_overflow_checks.rs:77]: It probably could. Trivial rearrangements would still not lint so it's not really worth a lot, but it's easy so may as well.

**Review by y21 — APPROVED** [review]
Looks good, r=me with merge conflicts fixed
