### PR TITLE
fix the error-causing suggestion of 'borrowed_box'

### LINKED ISSUE #3128: borrowed_box gives syntactically invalid suggestion
It suggests `&mut Trait + 'a`, which is invalid syntax. It should be `&mut (Trait + 'a)` instead.

### PR DESCRIPTION
**Pull request by rail-rain**
Fixes #3128 

Fix the suggestion of 'borrowed_box', which causes a syntax error because it misses necessary parentheses.

---

changelog: Fix the error-causing suggestion of 'borrowed_box'

### CODE REVIEW

File: clippy_lints/src/types.rs [hunk 1]
```diff
@@ -721,6 +734,21 @@ fn is_any_trait(t: &hir::Ty<'_>) -> bool {
     false
 }
 
+fn get_bounds_if_impl_trait<'tcx>(cx: &LateContext<'tcx>, qpath: &QPath<'_>, id: HirId) -> Option<GenericBounds<'tcx>> {
```
Comment (phansch) [inline clippy_lints/src/types.rs:737]: A typo, it seems?
```suggestion
fn get_bounds_of_impl_trait<'tcx>(cx: &LateContext<'tcx>, qpath: &QPath<'_>, id: HirId) -> Option<GenericBounds<'tcx>> {
```

**Review by phansch — COMMENTED** [review]
r=me with typo fixed

File: clippy_lints/src/types.rs (hunk 1 above)
Comment (rail-rain) [reply clippy_lints/src/types.rs:737]: I'm afraid not because it returns `None` if the `qpath` is not an impl trait, and actually checking whether the `qpath` is an impl trait is one of the main role of the function. I named it so hoping it looks similar to [`get_if_local`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/hir/map/struct.Map.html#method.get_if_local). If it's confusing, something like `get_bounds_provided_impl_trait` might be more suitable?
