### PR TITLE
Fix .map(..).unwrap_or_else(..) bad suggestion

### LINKED ISSUE #4144: Clippy suggests: more directly with map_or_else(g, f) instead... recommendation does not compile
Great tool!  Thank you.

The code where clippy suggests I use a more direct approach:
```
        frequencies
            .get_mut(word)
            .map(|count| {
                *count += 1;
            })
            .unwrap_or_else(|| {
                frequencies.insert(word.to_owned(), 1);
            });
```

My interpretation of the suggestion:
```
        frequencies.get_mut(word).map_or_else(
            || {
                frequencies.insert(word.to_owned(), 1); 
                ^^^^^^^^^^^^  <<<< cannot borrow frequencies as mutable more than once at a time
            },
            |count| {
                *count += 1;
            },
        )
```

The caveat of course is that there is an easy fix to the error I'm receiving.  

Notwithstanding, my first guess is that there is an inconsistency here:
* either the recommendation is right most of the time except in the situation I have here, 
* or the `map_or_else` should work the same way as my first iteration of the code all the time.

I hope this is helpful.

\- E

### PR DESCRIPTION
**Pull request by mikerite**
Closes #4144

### CODE REVIEW

File: clippy_lints/src/methods/mod.rs [hunk 1]
```diff
@@ -1880,7 +1881,20 @@ fn lint_map_unwrap_or_else<'a, 'tcx>(
     // lint if the caller of `map()` is an `Option`
     let is_option = match_type(cx, cx.tables.expr_ty(&map_args[0]), &paths::OPTION);
     let is_result = match_type(cx, cx.tables.expr_ty(&map_args[0]), &paths::RESULT);
+
     if is_option || is_result {
+        // Don't make a suggestion that may fail to compile due to mutably borrowing
+        // they same variable twice.
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: NIT:
```suggestion
        // the same variable twice.
```
