### PR TITLE
fix version attribute for `arbitrary_source_item_ordering` lint

### LINKED ISSUE #13818: arbitrary_source_item_ordering reports warning: unknown lint with 1.83.0 (docs say this lint was enabled in 1.82.0)
### Summary

While using the 1.83.0 rust toolchain, adding the line `#![deny(clippy::arbitrary_source_item_ordering)]` to the lib.rs file, generates the following unexpected warning:
```bash
% cargo clippy
warning: unknown lint: `clippy::arbitrary_source_item_ordering`
 --> src/lib.rs:1:9
  |
1 | #![deny(clippy::arbitrary_source_item_ordering)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unknown_lints)]` on by default

warning: `replicate_arbitrary_source_item_ordering` (lib) generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
%
```

### Reproducer

I tried this code:

```rust
#![deny(clippy::arbitrary_source_item_ordering)]

pub fn add(left: u64, right: u64) -> u64 {
    left + right
}
```

I expected to see this happen:

Combpilation with no errors or warning

Instead, this happened:

A warning was emitted claiming this is an unknown lint. The Clippy documentation claims this was introduced in the previous release (1.82.0), while these examples are compiled with the 1.83.0 toolchain on Mac.

```bash
% cargo clippy
warning: unknown lint: `clippy::arbitrary_source_item_ordering`
 --> src/lib.rs:1:9
  |
1 | #![deny(clippy::arbitrary_source_item_ordering)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unknown_lints)]` on by default

warning: `replicate_arbitrary_source_item_ordering` (lib) generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
%
```

### Version

```text
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: aarch64-apple-darwin
release: 1.83.0
LLVM version: 19.1.1
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by lapla-cogito**
fix #13818 

The `arbitrary_source_item_ordering` lint does not exist in v1.82.0, so I think it needs to be fixed.

changelog: [`arbitrary_source_item_ordering`]: corrected available version information for this lint

### CODE REVIEW

**Comment by lapla-cogito** [comment]
Maybe the changelog could be none? I don't think this will affect clippy's behavior, just that the documentation will be updated.

File: clippy_lints/src/arbitrary_source_item_ordering.rs [hunk 1]
```diff
@@ -126,7 +126,7 @@ declare_clippy_lint! {
     ///
     /// [cargo-pgo]: https://github.com/Kobzol/cargo-pgo/blob/main/README.md
     ///
-    #[clippy::version = "1.82.0"]
+    #[clippy::version = "1.84.0"]
```
Comment (lapla-cogito) [inline clippy_lints/src/arbitrary_source_item_ordering.rs:129]: As I wrote in #13818 , this lint seems to be available since v1.84.0:

```
$ cargo clippy --version
clippy 0.1.84 (202008a1b8 2024-12-07)

$ cargo clippy --explain arbitrary_source_item_ordering
### What it does

Confirms that items are sorted in source files as per configuration.

### Why restrict this?

Keeping a consistent ordering throughout the codebase helps with working
as a team, and possibly improves maintainability of the codebase. The
...
```

**Review by y21 — APPROVED** [review]
Looks good to me. The author of the lint likely started working on the lint in 1.82 but only had the PR merged way later in 1.84.

For what it's worth, this isn't too uncommon but usually also not a big problem because these attributes always get "auto" fixed in the changelog PR for the version that the lint reaches stable (so they could only be wrong in the nightly docs for at most a few weeks, and stable docs are always correct), but fixing them manually early is also fine👍
