### PR TITLE
Fix `filter_map_bool_then` wrongly suggests macro definitions

### LINKED ISSUE #15047: `filter_map_bool_then` should not show the macro definition in suggestions
### Summary

`filter_map_bool_then` wrongly showed the macro definition instead of its call site in suggestions

### Reproducer

I tried this code:

```rust
    tokenize_with_text(&snippet)
        .filter_map(|(t, s, inner)| {
            matches!(t, TokenKind::Ident if s == keyword).then(|| {
                span.split_at(inner.start as u32)
                    .1
                    .split_at((inner.end - inner.start) as u32)
                    .0
            })
        })
```

I expected to see this happen:

```rust
.filter(|&(t, s, inner)| matches!(t, TokenKind::Ident if s == keyword))
.map(..)
```

Instead, this happened:

```rust
.filter(|&(t, s, inner)| match $expression {
    $pattern $(if $guard)? => true,
    _ => false
}).map(..)
```

### Version

```text

```

### Additional Labels

@rustbot label + I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by profetia**
Closes rust-lang/rust-clippy#15047 

changelog: [`filter_map_bool_then`] fix wrongly showed macro definitions in suggestions

### CODE REVIEW

**Comment by profetia** [comment]
r? samueltardieu

**Comment by samueltardieu** [comment]
r? clippy

**Comment by profetia** [comment]
r? clippy

File: clippy_lints/src/methods/filter_map_bool_then.rs [hunk 1]
```diff
@@ -45,8 +45,8 @@ pub(super) fn check<'tcx>(cx: &LateContext<'tcx>, expr: &'tcx Expr<'tcx>, arg: &
             .filter(|adj| matches!(adj.kind, Adjust::Deref(_)))
             .count()
         && let Some(param_snippet) = param.span.get_source_text(cx)
-        && let Some(filter) = recv.span.get_source_text(cx)
-        && let Some(map) = then_body.span.get_source_text(cx)
+        && let Some(filter) = recv.span.source_callsite().get_source_text(cx)
+        && let Some(map) = then_body.span.source_callsite().get_source_text(cx)
```
Comment (Alexendoo) [inline clippy_lints/src/methods/filter_map_bool_then.rs]: Since `expr` is allowed to be in a local macro for this lint you might need `hygiene::walk_chain` here rather than using the source callsite

Comment (profetia) [reply clippy_lints/src/methods/filter_map_bool_then.rs]: You are right. In this case, I believe using `snippet_with_context` would be the proper choice.

**Comment by profetia** [comment]
@Alexendoo Updated. Thank you!
