### PR TITLE
Fix match single binding when in a let stmt

### LINKED ISSUE #5267: match_single_binding suggests invalid  let x = let y = ... code
original code:
````rust
        let fn_sig = match self.normalize_associated_types_in_as_infer_ok(span, &fn_sig) {
            InferOk { value, obligations: o } => {
                obligations.extend(o);
                value
            }
        };
````

clippy suggested:
````
warning: this match could be written as a `let` statement
   --> src/librustc_typeck/check/method/mod.rs:370:22
    |
370 |           let fn_sig = match self.normalize_associated_types_in_as_infer_ok(span, &fn_sig) {
    |  ______________________^
371 | |             InferOk { value, obligations: o } => {
372 | |                 obligations.extend(o);
373 | |                 value
374 | |             }
375 | |         };
    | |_________^
    |
    = note: `#[warn(clippy::match_single_binding)]` on by default
````

````rust
        let fn_sig = let InferOk { value, obligations: o } = self.normalize_associated_types_in_as_infer_ok(span, &fn_sig);
        {
            obligations.extend(o);
            value
        };
````

which does not compile (yet?):

````
error[E0658]: `let` expressions in this position are experimental
   --> src/librustc_typeck/check/method/mod.rs:371:22
    |
371 |         let fn_sig = let InferOk { value, obligations: o } = self.normalize_associated_types_in_as_infer_ok(span, &fn_sig);
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53667
    = help: add `#![feature(let_chains)]` to the crate attributes to enable
````

### PR DESCRIPTION
**Pull request by ThibsG**
Fix bad suggestion when `match_single_binding` lints when inside a local (let) statement.

Fixes #5267

changelog: none

### CODE REVIEW

File: clippy_lints/src/matches.rs [hunk 1]
```diff
@@ -914,19 +914,36 @@ fn check_match_single_binding(cx: &LateContext<'_, '_>, ex: &Expr<'_>, arms: &[A
     let mut applicability = Applicability::MaybeIncorrect;
     match arms[0].pat.kind {
         PatKind::Binding(..) | PatKind::Tuple(_, _) | PatKind::Struct(..) => {
+            let sugg;
+            let target_span;
+            // If this match is in a local (`let`) stmt
+            if let Some(parent_let_node) = opt_parent_let(cx, ex) {
```
Comment (flip1995) [inline clippy_lints/src/matches.rs]:
```suggestion
            // If this match is in a local (`let`) stmt
            let (target_span, sugg) = if let Some(parent_let_node) = opt_parent_let(cx, ex) {
```

and then return this tuple in the `if`/`else`

**Comment by flip1995** [comment]
Thanks!

@bors r+
