### PR TITLE
Suggest `pointer::cast` when possible in `transmute_ptr_to_ref`

### LINKED ISSUE #8924: `transmute_ptr_to_ref` false positive for types containing differing lifetimes
### Summary

There's one last FP in #2906 that wasn't fixed

### Lint Name

transmute_ptr_to_ref

### Reproducer

I tried this code:

```rust
#![allow(clippy::missing_safety_doc)]

use std::mem::transmute;

pub unsafe fn ptr_to_ref<'a, 'b>(ptr: *const &'a ()) -> &&'b () {
    transmute(ptr)
}
```

I saw this happen:

```
warning: transmute from a pointer type (`*const &()`) to a reference type (`&&()`)
 --> t.rs:5:5
  |
5 |     std::mem::transmute(ptr)
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `&*ptr`
  |
```

I expected to see this happen:

It shouldn't lint, as `&*ptr` would fail to compile

### Version

_No response_

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by Jarcho**
fixes #8924

changelog: Suggest casting the pointer for any type containing lifetimes in `transmute_ptr_to_ref`.
changelog: Suggest `pointer::cast` when possible in `transmute_ptr_to_ref`.

### CODE REVIEW

**Comment by Jarcho** [comment]
Apparently casting `*const &'a T` to `*const &'b T` directly doesn't work with `as`. Not sure if double cast as a workaround is really better than transmute.

File: clippy_utils/src/msrvs.rs [hunk 1]
```diff
@@ -25,7 +25,7 @@ msrv_aliases! {
     1,40,0 { MEM_TAKE, NON_EXHAUSTIVE, OPTION_AS_DEREF }
     1,38,0 { POINTER_CAST }
     1,37,0 { TYPE_ALIAS_ENUM_VARIANTS }
-    1,36,0 { ITERATOR_COPIED }
+    1,36,0 { ITERATOR_COPIED, PTR_CAST }
```
Comment (giraffate) [inline clippy_utils/src/msrvs.rs:28]: What method is this? I thought it was [this](https://doc.rust-lang.org/std/primitive.pointer.html#method.cast), but it looks like this was added at 1.38.0.

**Review by giraffate — COMMENTED** [review]
Sorry for the late reviewing. I made comments.

File: clippy_utils/src/msrvs.rs (hunk 1 above)
Comment (Jarcho) [reply clippy_utils/src/msrvs.rs:28]: That is the right method. I don't know where I got 1.36 from.

Comment (giraffate) [reply clippy_utils/src/msrvs.rs:28]: Okay. Can `1,38,0 { POINTER_CAST }` be used for msrv?

**Review by giraffate — APPROVED** [review]

**Comment by giraffate** [comment]
@bors r+

It looks good, thanks!
