### PR TITLE
Fix or_fun_call for index operator

### LINKED ISSUE #6266: `or_fun_call` lint shouldn't ignore indexing to HashMap types
*See also the perf improvement in rustc: <https://github.com/rust-lang/rust/pull/78508>*.

Currently, `or_fun_call` lint doesn't lint on indexing to HashMap types.

I tried this code:

```rust
#![warn(clippy::or_fun_call)]
use std::collections::HashMap;
pub fn foo(opt: Option<u32>, map: HashMap<u32, u32>, idx: u32) -> u32 {
    opt.unwrap_or(map[&idx])
}
```

I expected to see this happen: A warning to `unwrap_or` method call because
`map[&idx]` maybe expensive (indexing to a hashmap).

Instead, this happened: No warning at all.

### Meta

- `cargo clippy -V`: 0.0.212 (2020-10-28 31ee872) from playground
- `rustc -Vv`: (2020-10-28 31ee872db5aae4750e3d)

Maybe a duplicate of #5821 .

### PR DESCRIPTION
**Pull request by camsteffen**
changelog: Fix or_fun_call for index operator

Fixes #6266

### CODE REVIEW

**Comment by camsteffen** [comment]
Oops. The fix for references doesn't work due to lifetimes. I'll remove that part for this PR.

**Comment by camsteffen** [comment]
Need to resolve the question of including slices at #6267.

Also, I think I should amend this to not include `opt.map_or(array[const_expr])`?

File: clippy_lints/src/methods/mod.rs [hunk 1]
```diff
@@ -1753,12 +1753,20 @@ fn lint_or_fun_call<'tcx>(
...
+        // None if lambda is required
+        fun_span: Option<Span>,
     ) {
+        // (path, fn_has_argument, methods, suffix)
+        const KNOW_TYPES: [(&[&str], bool, &[&str], &str); 4] = [
+            (&paths::BTREEMAP_ENTRY, false, &["or_insert"], "with"),
+            (&paths::HASHMAP_ENTRY, false, &["or_insert"], "with"),
+            (&paths::OPTION, false, &["map_or", "ok_or", "or", "unwrap_or"], "else"),
+            (&paths::RESULT, true, &["or", "unwrap_or"], "else"),
+        ];
```
Comment (camsteffen) [inline clippy_lints/src/methods/mod.rs:1768]: It just occurred to me - would this be better as static since otherwise this is inlining a somewhat large value?

Comment (flip1995) [reply clippy_lints/src/methods/mod.rs:1768]: I don't think this makes much of a difference. These are just a few bytes. Do as you think is best.

**Comment by flip1995** [comment]
> Need to resolve the question of including slices at #6267.

I don't think we should lint on indexing slices, arrays or vecs, since those operations are O(1), even with bounds checks, while indexing into hashmaps can be way more involved.

**Comment by camsteffen** [comment]
Okay, now it will only lint when indexing `HashMap` or `BTreeMap`.

**Comment by flip1995** [comment]
@bors r+

Thanks!
