### PR TITLE
feat: `Quick Fix` for `bare URLs`

### LINKED ISSUE #12835: `bare URLs` in `clippy::doc_markdown` lint should have a `Quick Fix`
I think there should be an auto-fix, or `Quick Fix` option for `bare URLs` in Markdown comments.

### PR DESCRIPTION
**Pull request by hamirmahal**
closes #12835.

*Please write a short comment explaining your change (or "none" for internal only changes)*

changelog: [`clippy::doc_markdown`]: `Quick Fix` for `bare URLs`

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
I wanted to try this out in an IDE with `rust-analyzer` but wasn't able to do so.

**Comment by hamirmahal** [comment]
Are there docs on how to test changes in this repository with the `rust-analyzer` extension for VSCode?

**Review by J-ZhengLi — COMMENTED** [review]
> I wanted to try this out in an IDE with rust-analyzer but wasn't able to do so.

not sure if there's a way 🤔, but you can put your test code in [`tests/ui/doc/doc-fixable.rs`](https://github.com/rust-lang/rust-clippy/blob/master/tests/ui/doc/doc-fixable.rs), then run `TESTNAME='doc-fixable' cargo uibless` to "try it out".

File: clippy_lints/src/doc/markdown.rs [hunk 1]
```diff
@@ -92,13 +92,23 @@ fn check_word(cx: &LateContext<'_>, word: &str, span: Span, code_level: isize, b
...
                 cx,
                 DOC_MARKDOWN,
                 span,
                 "you should put bare URLs between `<`/`>` or make a proper Markdown link",
+                |diag| {
+                    let mut applicability = Applicability::MachineApplicable;
+                    let snippet = snippet_with_applicability(cx, span, "..", &mut applicability);
+                    diag.span_suggestion_with_style(
+                        span,
+                        "put bare URLs between `<`/`>`",
```
Comment (y21) [inline clippy_lints/src/doc/markdown.rs:105]: I don't like that this is basically repeating the message. How about something like
```suggestion
                        "try",
```
This is a fairly common one

**Comment by y21** [comment]
I'm surprised that this didn't have to touch any tests and the checks are still passing. We should definitely have a test for this like @J-ZhengLi said :)

**Review by y21 — APPROVED** [review]
Looks good to me, can you squash your commits? :)
Then we can merge this

**Comment by hamirmahal** [comment]
> Looks good to me, can you squash your commits? :) Then we can merge this

Sure! I just squashed them after rebasing against the main branch.

**Comment by y21** [comment]
Thanks! @bors r+

**Comment by hamirmahal** [comment]
You're welcome!
