### PR TITLE
[`borrow_as_ptr`]: Ignore temporaries

### LINKED ISSUE #9884: FP borrow_as_ptr
### Summary

.

### Lint Name

borrow_as_ptr

### Reproducer

I tried this code:

```rust
enum Foo {}
impl Drop for Foo {
    fn drop(&mut self) {}
}

fn main() {
    unsafe { std::ptr::read(&1u8 as *const u8 as *const Foo) };
}
```

I saw this happen:
` cargo clippy --fix -- -Wclippy::borrow_as_ptr`
```
warning: failed to automatically apply fixes suggested by rustc to crate `a`

after fixes were automatically applied the compiler reported errors within these files:

  * src/main.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0745]: cannot take address of a temporary
 --> src/main.rs:7:48
  |
7 |     unsafe { std::ptr::read(std::ptr::addr_of!(1u8) as *const Foo) };
  |                                                ^^^ temporary value

error: aborting due to previous error

For more information about this error, try `rustc --explain E0745`.
Original diagnostics will follow.

warning: borrow as raw pointer
 --> src/main.rs:7:29
  |
7 |     unsafe { std::ptr::read(&1u8 as *const u8 as *const Foo) };
  |                             ^^^^^^^^^^^^^^^^^ help: try: `std::ptr::addr_of!(1u8)`
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#borrow_as_ptr
  = note: requested on the command line with `-W clippy::borrow-as-ptr`

warning: `a` (bin "a") generated 1 warning (run `cargo fix --bin "a"` to apply 1 suggestion)
warning: `a` (bin "a" test) generated 1 warning (1 duplicate)
```

### Version

```text
rustc 1.67.0-nightly (b833ad56f 2022-11-18)
binary: rustc
commit-hash: b833ad56f46a0bbe0e8729512812a161e7dae28a
commit-date: 2022-11-18
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by Centri3**
Fixes #9884

changelog: [`borrow_as_ptr`]: Ignore temporaries

### CODE REVIEW

File: clippy_lints/src/casts/borrow_as_ptr.rs [hunk 1]
```diff
@@ -23,6 +25,10 @@ pub(super) fn check<'tcx>(
         };
         let mut app = Applicability::MachineApplicable;
         let snip = snippet_with_context(cx, e.span, cast_expr.span.ctxt(), "..", &mut app).0;
+        // Fix #9884
+        if for_each_unconsumed_temporary(cx, expr, |_| ControlFlow::Break(true)).is_break() {
```
Comment (Alexendoo) [inline clippy_lints/src/casts/borrow_as_ptr.rs:29]: We can copy the criteria rustc uses - https://github.com/rust-lang/rust/blob/3ed2a10d173d6c2e0232776af338ca7d080b1cd4/compiler/rustc_hir_typeck/src/expr.rs#L482-L499

Comment (Centri3) [reply clippy_lints/src/casts/borrow_as_ptr.rs:29]: I was looking for that for quite a while, only finding that utils function. Thank you!

Comment (Alexendoo) [reply clippy_lints/src/casts/borrow_as_ptr.rs:29]: A good tip is to search for the error message, here "cannot take address of a temporary", and work your way up from that

Comment (Centri3) [reply clippy_lints/src/casts/borrow_as_ptr.rs:29]: I often do that after initially searching the docs, so it's a bit weird I couldn't find it then

**Review by dswij — APPROVED** [review]
LGTM, thanks!
