### PR TITLE
Do not propose to remove `async move` if variables are captured by ref

### LINKED ISSUE #10482: redundant_async_block results in broken code for `async fn f(&self)`
### Summary

auto fix of redundant_async_block can lead to broken code in some circumstances

### Lint Name

redundant_async_block

### Reproducer

I tried this code:

```rust
#[derive(Debug, Clone)]
struct F {}

impl F {

    async fn run(&self) {}
}

pub async fn run() {
    let f = F{};
    let c = f.clone();
    tokio::task::spawn(async move {c.run().await});
    let _f = f;
}
```

repro: https://github.com/mattsse/redundant-async-block-broken-code

I saw this happen:

```
after fixes were automatically applied the compiler reported errors within these files:

  * src/lib.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see 
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/rust/issues
quoting the full output of this command we'd be very appreciative!
Note that you may be able to make some more progress in the near-term
fixing code with the `--broken-code` flag

The following errors were reported:
error[E0597]: `c` does not live long enough
  --> src/lib.rs:16:24
   |
16 |     tokio::task::spawn(c.run());
   |                        ^^^^^^^
   |                        |
   |                        borrowed value does not live long enough
   |                        argument requires that `c` is borrowed for `'static`
17 |     let _f = f;
18 | }
   | - `c` dropped here while still borrowed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
Original diagnostics will follow.

warning: this async expression only awaits a single future
  --> src/lib.rs:16:24
   |
16 |     tokio::task::spawn(async move {c.run().await});
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: you can reduce it to: `c.run()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_async_block
   = note: `#[warn(clippy::redundant_async_block)]` on by default
```

I expected to see this happen:

### Version

```text
cargo 1.70.0-nightly (7d3033d2e 2023-03-08)
rustc 1.70.0-nightly (ff4b772f8 2023-03-10)
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by samueltardieu**
Fixes #10482 

changelog: FP [`redundant_async_block`] Do not propose to remove `async move` if variables are captured by ref

### CODE REVIEW

**Comment by samueltardieu** [comment]
The `captured_by_ref()` function can have false positives, which errs on the safe side. Is there a way to go from a `NodeId` to the corresponding AST in an `EarlyLintPass`? That would let us check exactly what is captured, by checking the closure built from the `Async` AST node.

**Comment by OliverNChalk** [comment]
Is there an estimated release date for this, our codebase is running into this quite a bit when we launch tasks to drive components

File: clippy_lints/src/redundant_async_block.rs [hunk 1]
```diff
@@ -42,12 +42,17 @@ impl EarlyLintPass for RedundantAsyncBlock {
...
             return;
         }
-        if let ExprKind::Async(_, _, block) = &expr.kind && block.stmts.len() == 1 &&
+        if let ExprKind::Async(capture, _, block) = &expr.kind && block.stmts.len() == 1 &&
             let Some(Stmt { kind: StmtKind::Expr(last), .. }) = block.stmts.last() &&
             let ExprKind::Await(future) = &last.kind &&
             !future.span.from_expansion() &&
             !await_in_expr(future)
         {
+            if matches!(capture, CaptureBy::Value) && captured_by_ref(last) {
```
Comment (cynecx) [inline clippy_lints/src/redundant_async_block.rs:51]: This fix is rather incomplete because `CaptureBy::Ref` can also move a value into the closure:

```rust
use std::future::Future;

async fn work(_: &str) {}

fn spawn(_: impl Future<Output = ()> + 'static) {}

fn main() {
    let val = "Hello World".to_owned();
    spawn(async { work(&{ val }).await }); // false-positive
}
```

Comment (samueltardieu) [reply clippy_lints/src/redundant_async_block.rs]: Indeed, fixed.

**Comment by samueltardieu** [comment]
I also propose to put the lint in nursery for the time being, notably because of https://github.com/rust-lang/rust-clippy/issues/10509.

**Comment by xFrednet** [comment]
Hey, thank you for the PR and comments left by others. I'll sadly be busy until the end of the week, but you'll get a review by the end of next week :)

File: clippy_lints/src/redundant_async_block.rs [hunk 2]
```diff
@@ -48,6 +48,11 @@ impl EarlyLintPass for RedundantAsyncBlock {
             !future.span.from_expansion() &&
             !await_in_expr(future)
         {
+            if captured_by_ref(last) {
```
Comment (xFrednet) [inline clippy_lints/src/redundant_async_block.rs:51]: I guess that this should also check the async capture mode:

```suggestion
            if CaptureBy::Ref = cap_kind && captured_by_ref(last) {
```

The `cap_kind` can be taken from `ExprKind::Async(cap_kind, _, block)` in line 45

---

When looking at the tests, it looks like this also detects cases with `async move`. Is this intentional? In that case, my suggestion would be wrong, but the function name would also be misleading. `captured_by_move` would then be better or if the `CaptureBy` doesn't matter at all, just something like `captures_value` :)

File: clippy_lints/src/redundant_async_block.rs [hunk 3]
```diff
@@ -82,3 +87,33 @@ impl<'ast> AstVisitor<'ast> for AwaitDetector {
...
 }
+
+/// Check whether an expression may have captured a local variable
+/// by reference. This is done by looking for paths with only one
+/// segment, except as a prefix of `.await` since this would
+/// be captured by value.
+///
+/// There will be false positives, for example when calling a local
+/// function, but at the AST level this cannot be distinguished from
+/// calling a captured closure from the local environment.
```
Comment (xFrednet) [inline clippy_lints/src/redundant_async_block.rs:98]: Could you give an example when this is a false positive? From the explanation, it sounds like detecting `function` as a ref path, would cause false negatives and not the other way around :)

File: tests/ui/redundant_async_block.rs [hunk 4]
```diff
@@ -62,3 +64,48 @@ fn main() {
...
+}
+
+fn spawn<F: Future + 'static>(_: F) {}
+
+async fn work(_: &str) {}
+
+fn capture() {
+    let val = "Hello World".to_owned();
+    // Do not lint: `val` would not live long enough
+    spawn(async { work(&{ val }).await }); // false-positive
```
Comment (xFrednet) [inline tests/ui/redundant_async_block.rs:110]:
```suggestion
    spawn(async { work(&{ val }).await }); // false-negative?
```

*false-positive* (FP) refers to triggers that shouldn't happen, while *false-negatives* (FN) are cases that should trigger a lint, but don't. Generally speaking, FNs are better than FPs :)

**Review by xFrednet — COMMENTED** [review]
Generally looks good to me, I have a few questions, regarding names and documentation, but I'd say this is ready, once they've been cleared up.

Thank you for your patience, while waiting for the review :)

File: clippy_lints/src/redundant_async_block.rs (hunk 2 above)
Comment (xFrednet) [reply clippy_lints/src/redundant_async_block.rs:51]: Woops, this suggestion has already been made above. Turns out I should have read everything before. In that case I would suggest calling the function `captures_value`

Comment (samueltardieu) [reply clippy_lints/src/redundant_async_block.rs:51]: Renamed.

File: clippy_lints/src/redundant_async_block.rs (hunk 3 above)
Comment (samueltardieu) [reply clippy_lints/src/redundant_async_block.rs]: The false positives comment concerns the function itself, I'll be clearer in the comment. Since this function is used to prevent the lint from triggering, this causes false negatives at the lint level.

I will avoid using "false …" at the function level.

File: tests/ui/redundant_async_block.rs (hunk 4 above)
Comment (samueltardieu) [reply tests/ui/redundant_async_block.rs]: I copied-pasted the code from the issue. It was indeed a false positive, that this patch is fixing. I've removed the obsolete comment.

**Review by xFrednet — APPROVED** [review]

**Comment by xFrednet** [comment]
Looks good to me, thank you!

@bors r+

I've added the `beta-nominated` label. It looks like the lint has a few FP and changing the lint group should be able to land before the next release :)

**Comment by flip1995** [comment]
This will make it into the same release as the commit that added the lint. No action required.
