### PR TITLE
fix: `manual_find` suggests wrongly when early return

### LINKED ISSUE #9521: The `manual_find` lint provides a wrong suggestion if the try operator is used
### Summary

Because the try operator cannot be used in closures, replacing a manual implementation of find with an actual function call results in changed semantics that are not simple to resolve.

### Lint Name

manual_find

### Reproducer

I tried this code:

```rust
fn assert_less_ne(x: u32, y: u32) -> Result<bool, ()> {
    if x == y {
        return Err(());
    }
    Ok(x < y)
}

fn first_less_than_10(v: Vec<u32>) -> Option<u32> {
    for x in v {
        if assert_less_ne(x, 10).ok()? {
            return Some(x)
        }
    }
    None
}
```

I saw this happen:

```
warning: manual implementation of `Iterator::find`
  --> src/main.rs:9:5
   |
9  | /     for x in v {
10 | |         if assert_less_ne(x, 10).ok()? {
11 | |             return Some(x);
12 | |         }
13 | |     }
14 | |     None
   | |________^ help: replace with an iterator: `v.into_iter().find(|&x| assert_less_ne(x, 10).ok()?)`
   |
   = note: `#[warn(clippy::manual_find)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_find
```

I expected to see this happen:

Either the help text should appear with no suggestion or a modified suggestion, or the lint should not be triggered at all.

### Version

```text
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6
```

### Additional Labels

@rustbot label +I-suggestion-causes-error

### PR DESCRIPTION
**Pull request by profetia**
Closes #9521 

changelog: [`manual_find`]: fix wrong suggestions when early return

### CODE REVIEW

File: clippy_lints/src/loops/manual_find.rs [hunk 1]
```diff
@@ -35,6 +35,7 @@ pub(super) fn check<'tcx>(
         && let ExprKind::Call(ctor, [inner_ret]) = ret_value.kind
         && is_res_lang_ctor(cx, path_res(cx, ctor), LangItem::OptionSome)
         && path_res(cx, inner_ret) == Res::Local(binding_id)
+        && !contains_return(cond)
```
Comment (samueltardieu) [inline clippy_lints/src/loops/manual_find.rs:38]: Even though this would be some strangely-designed code, we should also protect against other diverging paths in the condition, such as `break` and `continue` such as in

```rust
pub fn first_less_than_10(v: Vec<u32>) -> Option<u32> {
    for x in v {
        if if x < 3 { break; } else { x < 10 } {
            return Some(x);
        }
    }
    None
}
```

```suggestion
        && !contains_return_break_continue_macro(cond)
```

Comment (profetia) [reply clippy_lints/src/loops/manual_find.rs]: Thanks!

**Review by flip1995 — APPROVED** [review]
