### PR TITLE
Fix clippy::version of elidable_lifetime_names to 1.87

### LINKED ISSUE #14653: Getting "unknown lint: `clippy::elidable_lifetime_names`" using clippy 1.85.1
### Summary

I'm getting an "unknown lint" warning for `clippy::elidable_lifetime_names` despite using rust/clippy version 1.85.1 which is later than the version `clippy::elidable_lifetime_names` was introduced in: 1.84.0 per https://rust-lang.github.io/rust-clippy/master/index.html#/elid)

Interestingly I couldn't find the lint in the stable branch, only on master. Is that why I'm getting the lint? If so, shouldn't the docs distinguish between the version something landed on stable?

### Lint Name

 unknown lint: `clippy::elidable_lifetime_names`

### Reproducer

I tried this code:

```rust
#![allow(
    clippy::elidable_lifetime_names,
)]

fn main() {
    println!("Hello, world!");
}
```

I saw this happen:

```
cargo clippy
    Checking tmp2 v0.1.0 (/Users/cr/code/tmp2)
warning: unknown lint: `clippy::elidable_lifetime_names`
 --> src/main.rs:3:5
  |
3 |     clippy::elidable_lifetime_names,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: did you mean: `clippy::single_char_lifetime_names`
  |
  = note: `#[warn(unknown_lints)]` on by default

warning: `tmp2` (bin "tmp2") generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.06s

```

I expected to see this happen: No lint

### Version

```text
rustc 1.85.1 (4eb161250 2025-03-15)
binary: rustc
commit-hash: 4eb161250e340c8f48f66e2b929ef4a5bed7c181
commit-date: 2025-03-15
host: aarch64-apple-darwin
release: 1.85.1
LLVM version: 19.1.7
```

### Additional Labels

_No response_

### PR DESCRIPTION
**Pull request by corneliusroemer**
relates to rust-lang/rust-clippy#14653

changelog: [`elidable_lifetime_names`]: Fix clippy version that this lint was introduced in.

It might be good to have some automation to check that the version is correct.
IIUC the version should be the current nightly version at the time a PR is merged.
If a release happens while a PR is open, the version needs to be bumped - this is easy to forget.

### CODE REVIEW

File: clippy_lints/src/manual_abs_diff.rs [hunk 1]
```diff
@@ -36,7 +36,7 @@ declare_clippy_lint! {
     /// a.abs_diff(b)
     /// # ;
     /// ```
-    #[clippy::version = "1.86.0"]
+    #[clippy::version = "1.87.0"]
```
Comment (corneliusroemer) [inline clippy_lints/src/manual_abs_diff.rs:39]:
```suggestion
    #[clippy::version = "1.88.0"]
```
